### ISSUE TITLE
FEATURE request: Support for local tilestore 

### ISSUE THREAD

**Issue by mateuf** [tumic0/GPXSee#10]
It would be a nice idea to support local tile store as used by oruxmaps or mobac source:

<?xml version="1.0" encoding="UTF-8"?>
<localTileFiles>
   <name>MyMapStore</name>
   <sourceType>DIR_ZOOM_X_Y</sourceType>
   <sourceFolder>D:\maps\mymap</sourceFolder>
   
   <backgroundColor>#000000</backgroundColor>
</localTileFiles>

**Comment by shujaatak** [comment]
Yes i support this idea too!

**Comment by tumic0** [comment]
Im planing to add support for "TrekBuddy tared atlases" which can be generated by MOBAC. But it will take a while...

**Comment by tomthecat** [comment]
I would also appreciate this feature. Thank you for your effort and your great program!

**Comment by tumic0** [comment]
Version 4 has support for OziExplorer maps (image based, no ozfX support for now) and TrekBuddy tiled maps/atlases ("plain" as well as tared).
