### ISSUE TITLE
Error loading data file - Unsupported XML version

### ISSUE THREAD

**Issue by jose1711** [tumic0/GPXSee#108]
I am getting Unsupported XML version error message (line: 1) upon opening a file generated by Py3DG200 tool.  Gpxsee apparently does not like the value of version attribute in file's header which goes like this:
```<?xml version="1.1" encoding="UTF-8" standalone="no" ?>```
Changing it to 1.0 manually fixes the problem but a more systematic approach would be appreciated.

**Comment by tumic0** [comment]
GPXSee uses Qt's QXmlStreamReader for parsing XML files which does apparently  not support XML 1.1 (https://bugreports.qt.io/browse/QTBUG-15767). As XML 1.1 is a "marginal affair" (Qt self does not care) you better convince the author of Py3DG200 to use the "standard" XML version than the Qt developers to add support for it.
