### ISSUE TITLE
FEATURE request: Proxy

### ISSUE THREAD

**Issue by mateuf** [tumic0/GPXSee#11]
Does GPXSee work behind proxy on windows?  Would be nice to provide config to specify proxy if neded.

**Comment by mateuf** [comment]
I've set up a build. Managed to get through proxy by adding:

QNetworkProxyFactory::setUseSystemConfiguration(true);

**Comment by tumic0** [comment]
I will have a look at it. If it does not break the "normal" case, I will add it.

**Comment by tumic0** [comment]
Commit 19c44f56d677d6c1510066fecd5fb92837fec8b0. Please check, if it works for you.

**Comment by mateuf** [comment]
Test successful.  My mod had the change in gui.cpp but I guess it doesn't matter.  Thumbs up.
