### ISSUE TITLE
[request] Basic stats in a window

### ISSUE THREAD

**Issue by tonyrulez** [tumic0/GPXSee#111]
Hi! First of all, thank you for your amazing app! I just bought my speedometer :)
I had an idea: I like to keep my riding data in an excel sheet, and it has values of average speed (moving), maximum speed, total distance, moving time, total time, start and finish time. I believe all of this information is in the FIT file provided by my GPS speedometer. Would it be possible to show all these "raw" data in a popup window? Thanks!

**Comment by tumic0** [comment]
Well, all of the data is already available in GPXSee, but not at a single place. Some kind of a "summary window" could be useful, but the question is where to place it/how to make it accessible without changing the current simple layout. I definitely do NOT want to add another widget to the fundamental layout.

**Comment by tonyrulez** [comment]
Yes, these data are available* but scattered around. I was thinking in a windows too, I don't want a widget for this. Maybe in the toolbar: Data - Summary, and it pop up a windows with all of these data.

*start and finish time (meaning YYYY-DD-MM HH:mm:ss) are not available in-app but I believe FIT stores this too. Also, seeing total **and** moving time at the same time is not possible, you need to switch between them in the toolbar Setting - Time. So a summary window would be amazing.

**Comment by tumic0** [comment]
The start time as well as the total and moving times (as well as some more info like the track name/description) are available in a tooltip on the track. There is however not a single place where you could see this info TOGETHER with all the graph statistics (elevation, speed, ...). This is what the summary window could improve.

**Comment by tumic0** [comment]
Added in 531eb256f1cc405160f299a43135b84f0fdfcc9d
