### ISSUE TITLE
Feature request: support to exit application using ESC key

### ISSUE THREAD

**Issue by mateuf** [tumic0/GPXSee#12]
I'd like to use GPXSee as a viewer from "norton"-like filemanager - i.e. altap salamander or total commander. To do this, it would be helpful if GPXSee could be quickly existed by pressing ESC key. 
Filetypes in filemanagers can have associated viewers. The workflow is :
1\ execute viewer from commandline passing file to view as a parameter
2\ do the viewing
3\ exit by pressing escape key

I appreciate it goes against standalone GUI principles, so ESC action could be configurable by passing predefined argument via command line.

**Comment by tumic0** [comment]
The ESC key is used for leaving the fullscreen mode. For closing the app, a standard close shortcut is available (eg. CTRL+Q).

**Comment by mateuf** [comment]
What about non-fullscreen mode? Would this not be a natural extension of "exit the screen" principle?

Dual pane file managers still do a good job navigating around files. Searching, copying, renaming, using shortcuts... In my view dual pane file managers do much better job then built in open file dialogs. Integrating into this environment would allow for very smooth management of collection of GPX files.

**Comment by mateuf** [comment]
this is what I mean (maybe make it conditional to command line arg):

case Qt::Key_Escape:
			if (_fullscreenAction->isChecked()) {
				_fullscreenAction->setChecked(false);
				showFullscreen(false);
			}
                       else
                       {
                               close();
                       }

**Comment by tumic0** [comment]
Well, technically it is of course easy. The question is more "academic", if in addition to the standard shortcut, there shall be another key closing the application. Which is additionally a key already used for something else (altought similar).

I will look at some image viewers, if they behave the same (= on ESC they exit), I will add it.

**Comment by pvanek** [comment]
no ESC for quit the app, please. There is no desktop app with this shortcut. Please configure you WM if it's required behavior (my 2c)
