### ISSUE TITLE
Crashes on macOS 10.13.4 (High Sierra)

### ISSUE THREAD

**Issue by habitoti** [tumic0/GPXSee#120]
Latest version 5.12, macOS 10.13.4: On launch, there's a GPXSee menu for 2 seconds, then it's gone again. No error message, nothing. Anything I am missing?

**System log** (entries might be from 2-3 consecutive start efforts...)

May 27 21:24:15 WDFM00337320A com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000169.GPXSee[32270]): Service exited due to signal: Killed: 9 sent by CoreServicesUIAgent[32130]
May 27 21:24:23 WDFM00337320A GPXSee[32275]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
May 27 21:24:24 WDFM00337320A com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000016a.GPXSee[32275]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
May 27 21:24:34 WDFM00337320A GPXSee[32285]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
May 27 21:24:35 WDFM00337320A com.apple.xpc.launchd[1] (org.gpxsee.GPXSee.52476[32285]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
May 27 21:24:40 WDFM00337320A GPXSee[32289]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
May 27 21:24:41 WDFM00337320A com.apple.xpc.launchd[1] (org.gpxsee.GPXSee.52476[32289]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

**Crash Log**

Process:               GPXSee [32275]
Path:                  /Applications/GPXSee.app/Contents/MacOS/GPXSee
Identifier:            org.gpxsee.GPXSee
Responsible:           GPXSee [32275]
    __TEXT                 0000000107103000-00000001071d8000 [  852K] r-x/rwx SM=COW  : [/Applications/GPXSee.app/Contents/MacOS/GPXSee]
17  org.gpxsee.GPXSee             	0x0000000107150bc0 Downloader::doDownload(Download const&, QByteArray const&, Downloader::Redirect const*) + 1280
18  org.gpxsee.GPXSee             	0x0000000107152599 Downloader::get(QList<Download> const&, Authorization const&) + 73
19  org.gpxsee.GPXSee             	0x0000000107179f09 TileLoader::loadTilesAsync(QList<Tile>&) + 489
20  org.gpxsee.GPXSee             	0x000000010714fb93 OnlineMap::draw(QPainter*, QRectF const&, bool) + 723
21  org.gpxsee.GPXSee             	0x000000010714ccd2 MapView::drawBackground(QPainter*, QRectF const&) + 146
23  org.gpxsee.GPXSee             	0x000000010714ce7b MapView::paintEvent(QPaintEvent*) + 315
55  org.gpxsee.GPXSee             	0x000000010710a5fa App::run() + 26
56  org.gpxsee.GPXSee             	0x0000000107107a1a main + 42
       0x107103000 -        0x1071d7ff3 +org.gpxsee.GPXSee (5.12 - 0) <1F537487-7020-3324-819D-3A3120BB2213> /Applications/GPXSee.app/Contents/MacOS/GPXSee
       0x107220000 -        0x10724bff7 +org.qt-project.QtPrintSupport (5.8 - 5.8.0) <1FB7C62E-8FDA-3E8F-A1E4-3AC987027D3E> /Applications/GPXSee.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x107273000 -        0x1076d7fff +org.qt-project.QtWidgets (5.8 - 5.8.0) <751070F0-6091-3A9C-8B6F-31C363B69435> /Applications/GPXSee.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10784a000 -        0x107c4bfef +org.qt-project.QtGui (5.8 - 5.8.0) <D5482DD8-C913-3074-BAF5-C43A6E335247> /Applications/GPXSee.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x107d53000 -        0x108210fff +org.qt-project.QtCore (5.8 - 5.8.0) <2C2FCD3B-2BCA-3941-B85E-9F334EB73FF8> /Applications/GPXSee.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1082da000 -        0x10830efff +org.qt-project.QtOpenGL (5.8 - 5.8.0) <F88DE7C6-4F7C-31A8-AF86-ADB3EEF36539> /Applications/GPXSee.app/Contents/Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL
       0x108337000 -        0x108434fff +org.qt-project.QtNetwork (5.8 - 5.8.0) <49B9700E-E1EB-38B2-8B37-990C03510C0F> /Applications/GPXSee.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10a110000 -        0x10a25dfff +libqcocoa.dylib (0) <DA2F8E2B-AA1F-3C8A-B167-DD4C61CB284C> /Applications/GPXSee.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x10bc94000 -        0x10bc9bfff +libqgenericbearer.dylib (0) <8F182237-37C5-3D7B-AF67-4353EDB0486C> /Applications/GPXSee.app/Contents/PlugIns/bearer/libqgenericbearer.dylib
       0x10c329000 -        0x10c32fff7 +libqgif.dylib (0) <3728B87B-BBC1-3401-8CBE-10D41C5F211B> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x10c335000 -        0x10c339fff +libqmacjp2.dylib (0) <3682C928-864F-3B9C-841E-2F6AD9286ECA> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
       0x10c9aa000 -        0x10c9bdfff +libqcorewlanbearer.dylib (0) <991DF0C8-9D27-3E8F-B2FA-94AFD7D1BC2F> /Applications/GPXSee.app/Contents/PlugIns/bearer/libqcorewlanbearer.dylib
       0x10cda7000 -        0x10cdaefff +libqicns.dylib (0) <263E39CD-0337-3EBE-8A0B-57FB53655BC3> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqicns.dylib
       0x10cdb5000 -        0x10cdbafff +libqico.dylib (0) <0758E180-49D4-39BB-AAD7-00BEF311F5B6> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqico.dylib
       0x10cdc1000 -        0x10cdfbfff +libqjpeg.dylib (0) <665B03D2-613E-32E8-89FE-D71354B63C0B> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x10ce04000 -        0x10ce08ff7 +libqtga.dylib (0) <D19A7D5F-6427-371D-9DF2-CEF8C8BCD9A9> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqtga.dylib
       0x10ce0e000 -        0x10ce61fff +libqtiff.dylib (0) <F89E5455-F4A1-337E-BC3F-00327E0BEC03> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqtiff.dylib
       0x10ce6d000 -        0x10ce71fff +libqwbmp.dylib (0) <D37C1BCB-EF95-33BF-A2A4-B6A1DB193B16> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqwbmp.dylib
       0x10ce78000 -        0x10ceedff7 +libqwebp.dylib (0) <5332EC2A-28E6-3802-9407-E61AE49290B6> /Applications/GPXSee.app/Contents/PlugIns/imageformats/libqwebp.dylib

**Comment by tumic0** [comment]
Can you please provide the whole crash log file? Also the info about the map that is being used would be helpful.

**Comment by habitoti** [comment]
Crashlog attached. Since it is the initial installation, I can't tell what map would be used. Whatever the default is, I'd assume.

[GPXSee_2018-05-27-212426_Hansis-MBP.crash.zip](https://github.com/tumic0/GPXSee/files/2043736/GPXSee_2018-05-27-212426_Hansis-MBP.crash.zip)

**Comment by tumic0** [comment]
The provided file is only a MacOS Alias file, the content itself is only on your hard drive. Please post the destination file.

**Comment by habitoti** [comment]
Sorry, just pulling it from console to desktop produces only an alias.
Next try...

[GPXSee_2018-05-27-212426_Hansis-MBP.crash.zip](https://github.com/tumic0/GPXSee/files/2046192/GPXSee_2018-05-27-212426_Hansis-MBP.crash.zip)

**Comment by tumic0** [comment]
So, the problem is this QT 5.8 [bug](https://bugreports.qt.io/browse/QTBUG-58962). If you disable the  "automatic proxy" setting in your network settings, GPXSee should work. I will try to build the next version of GPXSee against QT 5.9 (when their online installer starts working again...) which should resolve the issue.

**Comment by tumic0** [comment]
GPXSee 5.13 build with Qt 5.9.5 is now available on Sourceforge.
