### ISSUE TITLE
[bug] offline maps no longer in the menu

### ISSUE THREAD

**Issue by zbooyek** [tumic0/GPXSee#121]
After upgrading to v5.12 offline maps are no longer displayed in the Maps menu, only the online ones. I have tried both the Program Files and the Users subdir; no luck. Everything worked fine up to v5.11.

**Comment by tumic0** [comment]
Automatic loading of *.map and *.jnx maps was indeed broken due to a typo. Fixed in  eeab6a399e4041adde92164b5f13a048462167fd.
