### ISSUE TITLE
5.13 not working with High Sierra

### ISSUE THREAD

**Issue by Steve1812** [tumic0/GPXSee#123]
Updated to latest version and High Sierra software wont work with it.

Any thoughts and can I download the older version?

Steve1812
![screen shot 2018-05-31 at 16 57 47](https://user-images.githubusercontent.com/39804951/40793606-c2cddc22-64f4-11e8-891a-56a465a77e7f.jpg)

**Comment by sikmir** [comment]
I can't download gpxsee 5.13 OSX bundle from SourceForge: "The page failed to include the DR_mirror_list!"

**Comment by tumic0** [comment]
Acording to https://twitter.com/sfnet_ops, Sourceforge has some outage at the moment.

**Comment by tumic0** [comment]
The Mac build was indeed somehow broken, thanks for reporting it. I have uploaded a new build/bundle that should work again. When Sourceforge starts working properly, it will be available for download.

**Comment by Steve1812** [comment]
Thank you for your quick and useful reply.
Will wait a couple of days and try again.

Steve1812

**Comment by tumic0** [comment]
Sourceforge is back, the new DMG is now available for download. Please test, if it works.

**Comment by Steve1812** [comment]
Hello,
Yes successful download using Safari - but had to turn off the Ad Blocker.
Tried Chrome without Ad Blocker and it worked first time of asking.

Thank you for your help.

Steve
