### ISSUE TITLE
Failed to open UTF8 OziExplorer files with BOM

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#124]
It happened that I got some UTF8 OziExplorer file with BOM and GPXSee failed to open it.
### Steps to reproduce
It can be easily reproduced with any file:
```bash
$ curl https://www.gpslib.ru/tracks/download/78392.plt | uconv -f utf-8 -t utf-8 --add-signature > test.plt
$ gpxsee test.plt
```
### Actual behaviour
![screenshot1](https://user-images.githubusercontent.com/688044/40873796-c67f248a-666f-11e8-9f7c-d278bdda2373.jpg)
### Configuration
GPXSee Version: 5.13

**Comment by tumic0** [comment]
Who produces such files?! Anyway, added support for them in ec247d5d1daf407df9c7fcd7954e74f6229b5b62.
