### ISSUE TITLE
[request] Ability to view Shimano Di2 gear data

### ISSUE THREAD

**Issue by redford-jones** [tumic0/GPXSee#127]
It would be really useful to be a ble to view gear shift data within GPXSee and would be a feature that no other FIT viewer has implemented - the data isn't even viewable on Strava or Garmin Connect.
Gear shift data alongside cadence, speed and elevation can help to improve a cyclist's performance and it helps to identify inefficient gear shifts.

A view similar to the shift timeline on https://di2stats.com/sample would be the ideal way visualise this data. 

The data for a gear shift is held within the .fit file structure.

**Comment by tumic0** [comment]
If implemented, the y axis could only be a one-dimensional scalar value like in all other GPXSee graphs, probably the gear ratio. But even that could be much better than nothing. Can you provide a FIT file sample with the data?

**Comment by redford-jones** [comment]
Hi

thanks for your response. Yes it makes sense to do it as a scalar graph based on gear ratio.
Attached is a FIT file from this morning's ride. The file should also contain heart rate, cadence and speed as well as gear shift data.

[2018-07-01-09-30-29.zip](https://github.com/tumic0/GPXSee/files/2152961/2018-07-01-09-30-29.zip)

**Comment by tumic0** [comment]
Added in 3424b3e2659780cb574d0941e5417976d526d0e4.

**Comment by redford-jones** [comment]
Thank you Sir. A superb addition
