### ISSUE TITLE
Installation bug xubuntu 18.04

### ISSUE THREAD

**Issue by rodin-ia** [tumic0/GPXSee#128]
After install gpxsee from repo http://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_18.04, view error:
Setting up gpxsee (5.14) ...
Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/ttf" is an invalid MIME type ("font" is an unregistered media type)
Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/otf" is an invalid MIME type ("font" is an unregistered media type)

**Comment by tumic0** [comment]
I doubt that this is an GPXSee error - GPXSee does not add such MIME entry. GPXSee runs the "update-mime-database" tool in its postinstall script (as it adds various GPS formats MIME definitions) and this is most probably where the error comes from, but the invalid entry must have been already present before GPXSee installation was started.
