### ISSUE TITLE
file format conversions/save

### ISSUE THREAD

**Issue by pvanek** [tumic0/GPXSee#13]
it would be great if there can be something what allows me to convert input file into different format. Maybe here can be implemented some easy to use frontend for gpsbabel?

**Comment by tumic0** [comment]
Well, it is the aim of the application to make GPSBabel obsolete, but in a way, that there is no conversion tool required for viewing the GPS log files, not by duplicating GPSBabel conversion functionality. If someone wants a tool for converting GPS log files, there is GPSBabel.

**Comment by j-schneid** [comment]
There is another reason to implement at least some kind of track export/write/convert feature: Export the result of smoothing. But I will open a separate request for this.
