### ISSUE TITLE
Error loading GDAL generated GPX file

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#131]
### Steps to reproduce
Well, what I'm trying to do (full story):
- Fetch OSM data:
```bash
$ wget https://download.geofabrik.de/russia/northwestern-fed-district-latest.osm.pbf
```
- Convert to .o5m format:
```bash
$ osmconvert northwestern-fed-district-latest.osm.pbf -o=northwestern-fed-district-latest.o5m
```
- Filter specific objects (rivers):
```bash
$ osmfilter northwestern-fed-district-latest.o5m --keep="waterway=river" -o=rivers.osm
```
- Open `rivers.osm` with QGIS 3.0.3 and filter some specific river: `name = 'Оредеж'`.
- Save result as GPX (with `ogr` extension, we can't save without it). Result file (gzipped) is 
[Oredezh.gpx.gz](https://github.com/tumic0/GPXSee/files/2136411/Oredezh.gpx.gz).
### Actual behaviour
- Try to open with GPXSee:
![screenshot1](https://user-images.githubusercontent.com/688044/41901394-776e2382-7939-11e8-8fee-529092c03d2c.jpg)
- What is wrong there:
```bash
$ sed -n '12p' Oredezh.gpx
    <ogr:name:en></ogr:name:en>
```
### Expected behaviour
- Remove `ogr` extensions as a workaround:
```bash
$ sed -i '/<extensions>/,/<\/extensions>/d' Oredezh.gpx
```
- Try to open with GPXSee:
![screenshot2](https://user-images.githubusercontent.com/688044/41901709-4b10aebc-793a-11e8-99cc-c15dc3a4d72a.jpg)
That's OK now.
### Configuration
GPXSee: 5.14

**Comment by tumic0** [comment]
The problem are the names with multiple colons, eg. "ogr:name:en", not the ogr extensions in general. But this is

1. IMHO invalid XML as the syntax of the (qualified) names allows only one colon of the namespace.
2. Even if this is legal, it had to be fixed in QT's QXmlSimpleReader code.

So please report it either as a GDAL bug or a QT bug.
