### ISSUE TITLE
Representation of GPX track segments

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#141]
Here are some thoughts about GPX track segments and how to represent them properly.

First of all, what is GPX track segment:
> A Track Segment holds a list of Track Points which are logically connected in order. To represent a single GPS track where GPS reception was lost, or the GPS receiver was turned off, start a new Track Segment for each continuous span of track data. ([http://www.topografix.com](http://www.topografix.com/GPX/1/1/#type_trksegType))

There are two common approaches to deal with GPX track segments:
1. Ignore it (just connect segments)
![screenshot1](https://user-images.githubusercontent.com/688044/43158296-068e08de-8f88-11e8-899b-125c3ac186f4.jpg)
![screenshot3](https://user-images.githubusercontent.com/688044/43160131-00a00eb8-8f8d-11e8-8529-ace38d2e3d14.jpg)

2. Show some gap between segments (looks like different tracks)
![screenshot4](https://user-images.githubusercontent.com/688044/43158316-14d1007c-8f88-11e8-9041-577f766eb284.jpg)

As for me, both ones are not so good. The last point of one segment and the first point of the next segment are, essentially, some kind of "route", and I would propose to show that piece of track somehow differently (e.g. as a route). That would be a killer feature of GPXSee, since I don't know any other program doing so. Moreover, it's not always so easy to distinguish what direct line actually is (recorded track or connected segments).
![screenshot2](https://user-images.githubusercontent.com/688044/43158815-547bd7a0-8f89-11e8-91be-8ae74ca8018f.jpg)
Any discussion is welcome.

**Comment by tumic0** [comment]
Well, the problem with segments is how to distinguish them from multiple tracks/routes and still show them in a non-confusing way. All proposed methods are the "right one" in different scenarios so the ideal approach would be to implement all of them and let the user select the way how segments are handled. But as I personally do not "have/create" any files with segments there is a very little motivation to start implementing such a thing...

**Comment by luznicky** [comment]
I have already sent you a few files with segments about two years ago. :-)

**Comment by sikmir** [comment]
> But as I personally do not "have/create" any files with segments...

I see) As for me, I have the opposite situation: quite often batteries in Garmin device run out and I lose some piece of track (before I notice and replace batteries).

**Comment by sikmir** [comment]
> The question here is how to connect subsequent segments. None, thin line, dotted line, ...

Exactly. Imho, some sort of dotted/dashed line is the best way.

**Comment by tumic0** [comment]
Track segment handling added in 0308dbbb09647f7cfc882ede8609d03783ba0c8c.
