### ISSUE TITLE
Statistics/Average speed is dependent on time type

### ISSUE THREAD

**Issue by tonyrulez** [tumic0/GPXSee#146]
One problem I found in the new statistics window. Looks like the average speed is dependent on the time type (toggle with hotkey T). So the statistics shows 2 different average speeds depending if the time is set to moving or total time.

I believe that - at least in the stats window - average speed should be calculated by moving time. Or if you want to keep both, make two lines for it, one "Average moving speed" and something like "Total average speed".

I don't think that the statistics should have a variable value based on other setting. Stats should show the same every time you open it. Now if I open the stats and see a very low average speed, I know it's wrongly calculated.

(or the very least, make the T hotkey work while the stat window is open)

**Comment by tumic0** [comment]
Well, the statistics window iterates the graphs and shows the data from them. The graphs change the statistics info according to the selected time type (this is desirable behavior) and so does the statistics window.

I don't think that the moving time values are the "right one". This just depends on what the user wants to see. I will have a look if changing the time type is (without to much effort) possible when the statistics window is active  but it is a modal window so it might not be possible. Another improvement could be some indication of the time type (textual? highlighting the time type row?).

**Comment by tonyrulez** [comment]
As I thought about it, I can live with this. I'll just keep the time type on moving time :)
