### ISSUE TITLE
GeoTIFF map zoom

### ISSUE THREAD

**Issue by wdklotz** [tumic0/GPXSee#147]
I have a GeoTIFF map which I want to use with GPXsee. I can load the map but can't zoom it out. Is it possible to configure GPXsee to do so?
Chhers....
Wolf-Dieter

**Comment by tumic0** [comment]
Yes, there is digital zoom in GPXSee. Its SHIFT+zoom, see the "keyboard controls" under "help" (works with mouse as well).

**Comment by wdklotz** [comment]
But it does not work on my El Capitan Mac. Zoom out with - or shift - nope!

Martin Tůma <notifications@github.com> schrieb am Mi., 22. Aug. 2018, 11:51:

**Comment by tumic0** [comment]
Do you have the latest version of GPXSee (5.17)? It works fine on my Sierra (10.12.6) as well as on all other systems I have accessible for testing...

**Comment by wdklotz** [comment]
my versions......

Wolf-Dieter Klotz



Am Mi., 22. Aug. 2018 um 22:37 Uhr schrieb Martin Tůma <
notifications@github.com>:

**Comment by wdklotz** [comment]
Guten Tag
Habe jetzt GPXSee 5.17. Das Ergebniss ist schlechter als vorher....
1) Die Schrift auf der Menuleiste ist nicht mehr lesbar (b.tiff)
2) Die GeoTiffKarte erscheint nicht mehr - nur schwarz (a.tiff)
3) zur info meine Karte (CartaBossy2018geotiff.map)
Gruss

Wolf-Dieter Klotz
wdklotz@gmail.com




Am Do., 23. Aug. 2018 um 09:13 Uhr schrieb Wolf-Dieter Klotz <
wdklotz@gmail.com>:

**Comment by tumic0** [comment]
I suppose you have enabled OpenGL, did you? When OpenGL is enabled, a lot of things get broken, especially on Mac. There are some changes in the master branch that improve support for large files when OpenGL is used, but it seems that with every workaround attempt you trigger another, new bug...

So the "solution" is - unless you really know what you are doing (like when opening several thousend kilometers of tracks) - not touching the OpenGL checkbox.

**Comment by wdklotz** [comment]
Hi again
I am now on Windows10 with GPXSee 5.17. When loading my GeoTiff-map I only
get a white background. Use OpenGL is unchecked.
Before I used GPXSee 5.15 on my MAC and had at least a map display although
I could not zoom it. But 5.17 shows nothing! Something wrong with tiff? I
have sent you before my map file to judge it. I don't understand its
content but I thought this image format is sufficiently well defined.
Cheers
Wolf-Dieter Klotz
wdklotz@gmail.com




Am Fr., 24. Aug. 2018 um 00:08 Uhr schrieb Martin Tůma <
notifications@github.com>:

**Comment by wdklotz** [comment]
Hi
I send you the map file again. It is a pure text file. The tiff file is too
large for sending (~341 MB).
Wolf-Dieter Klotz
wdklotz@gmail.com




Am Sa., 25. Aug. 2018 um 16:23 Uhr schrieb Martin Tůma <
notifications@github.com>:

**Comment by tumic0** [comment]
Sending email attachments does not work on github (this is not the first time someone have tried it). Please use the issue web page.

**Comment by wdklotz** [comment]
Ok I try it here again. I sendind the whole zip does not work - too large - refused! I send a zip of the map file.
[CartaBossy2018geotiff.map.zip](https://github.com/tumic0/GPXSee/files/2321550/CartaBossy2018geotiff.map.zip)
