### ISSUE TITLE
Suggestion: Allow to zoom in more on the map

### ISSUE THREAD

**Issue by MortenZdk** [tumic0/GPXSee#154]
The presented map has a lot of details, but zoom level is limited, so I can not zoom in to see the details, and even the street names are hard to read.

This applies to the maps "4UMaps" and "Open Topo Map", where as the "Open Street Map" allows nice zoom in.

Please allow more zoom in.

Thanks for a great program.

**Comment by sikmir** [comment]
Such limitations come from map provider, GPXSee can do nothing here. At the moment OpenTopoMap supports zoom level up to 17 (see der-stefan/OpenTopoMap#20). Moreover, it looks like OpenTopoMap server it too slow, requesting tiles for >15 zoom level in unpopular areas we get 404 or 503 response, but after a few minutes, the same requests return normal tiles (see wladich/nakarte#97).

**Comment by MortenZdk** [comment]
Hi Nikolay, OK, thanks for considering this, and I understand the limitation.  Best regards Morten
