### ISSUE TITLE
Arch Linux official repository

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#158]
Add repository, as instructed on the [download page](https://software.opensuse.org/download.html?project=home%3Atumic%3AGPXSee&package=gpxsee):

```shell
$ cat EOF >> /etc/pacman.conf
[home_tumic_GPXSee_Arch Extra]
SigLevel = Never
Server = https://download.opensuse.org/repositories/home:/tumic:/GPXSee/Arch Extra/$arch
EOF
$ pacman -Syu
:: Synchronizing package databases...
...
error: failed retrieving file 'home_tumic_GPXSee_Arch Extra.db' from download.opensuse.org : The requested URL returned error: 400
error: failed to update home_tumic_GPXSee_Arch Extra (unexpected error)
error: failed to synchronize all databases
```

Correct config:
```
[home_tumic_GPXSee_Arch%20Extra]
SigLevel = Never
Server = https://download.opensuse.org/repositories/home:/tumic:/GPXSee/Arch%20Extra/$arch
```

**Comment by tumic0** [comment]
Please open an issue in the openSUSE/open-build-service project here on GitHub. OBS is quiet broken thees days. I have already reported two issues this week (openSUSE/open-build-service#4481 and openSUSE/open-build-service#5866)

**Comment by sikmir** [comment]
OK, I just don't know details how OBS is configured for a specific project, so I wonder why there is no the same problem with other projects: there is '_' in place of space after 'Arch'.
