### ISSUE TITLE
Limited number of maps in drop-down list

### ISSUE THREAD

**Issue by JoelErin** [tumic0/GPXSee#160]
Hi,
I currently have 12 maps open in the maps -> drop-down list.
Each time I load a new map, it temporary shows-up in list, but is lost upon restart of GpxSee.
Just like if the number of visible maps (& history) is capped to the 12 oldest...

Would be nice to have this limitation to 12 extended or, even better, the last open overlapping the oldest, or an option to removed unused maps.
Thanks. Joel

**Comment by tumic0** [comment]
There is no such limit. All maps loaded from the GUI are for the current session only, they are not automatically loaded during the next start of the application. If you want a map to be "persistent", you have to put it in to the user map directory as described in the [documentation](http://www.gpxsee.org/doc.html).

Btw., you (or the system administrator for all users using the global map directory) must already have done this in the past as GPXSee comes with 5 maps by default. Technically your Linux distribution may add those additional maps to the packages, but I do not know any such distro.

**Comment by JoelErin** [comment]
Thanks Tumic0 for this clear answer.
I believe I changed my mind when I decided not to copy the maps into the maps default directory, but used another existing directory. RTFM was the answer... Joel
