### ISSUE TITLE
Map Server Definition

### ISSUE THREAD

**Issue by joch40** [tumic0/GPXSee#161]
Hello Everybody,

could we get some more hands on documentation about the maps xml format and the server compatibility. I try to create a map file for the Frauenhofer IOSB 

<url>https://tile.iosb.fraunhofer.de/#map=13/39.8873/116.3976/3]</url>

In my view this sever handles the representation of names and streets much better than the standard Openstreetmap Server. 

Background: I have some tracks from China and they are nearly not usable if you can not read the Chinese characters. 

With a rather brute force approach I tried this in a newly created xml file
```
<name>Frauenhofer Open Street Map</name>
<url>https://tile.iosb.fraunhofer.de//#map=$z//$x//$y//3</url>
```

The “3” in the end is a parameter  for OSMorg representation that ensures the addtional name information.. 

But this does not work. As I can not find any debugging information I am a bit lost. Can anybody help?

Thanks 

Janko

**Comment by sikmir** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1">
  <name>Frauenhofer Open Street Map</name>
  <url>https://tile.iosb.fraunhofer.de/tiles/osmorg/$z/$x/$y.png</url>
</map>
```

**Comment by joch40** [comment]
Works great!
Sorry that I could not solve that by myself.

Thank you

Janko
