### ISSUE TITLE
[Feature Request]: Speed heat map on tracks

### ISSUE THREAD

**Issue by ThibaultLemaire** [tumic0/GPXSee#164]
A picture is worth a thousand words (screenshot taken from [runtastic](https://www.runtastic.com/en/apps/runtastic)):

![runtastic-screenshot-cropped](https://user-images.githubusercontent.com/21345269/46662884-de612a00-cbbc-11e8-8a05-8b1e162382aa.png)

If you want more details, I have also opened [an issue in Osmand](https://github.com/osmandapp/Osmand/issues/6099) (the app I use for gps recording), but they're already flooded with issues and feature requests. It's already full of features, and I don't __need__ to have this visualization on my _phone_. In fact I feel more comfortable analyzing my tracks on my _desktop computer_, which is why I'm posting this here.

I'm really interested in this feature, and am ready to implement it myself if you think that's possible. (Qt/C++ is much more within my skill domain than Android/Java)

**Comment by tumic0** [comment]
I know that some programs/services offer such visualizations but personally I'm not a big fan of it. Path drawing in GPXSee is kept as simple (and fast) as possible to visualize stuff like this:
![bikestreda](https://user-images.githubusercontent.com/11480505/46699955-b0f79900-cc1b-11e8-9679-221141d098ce.png) (This is 5000km of tracks which - using OpenGL - is fluently moving on a 6 year old notebook)
Implementing a heatmap would make things much more complicated (even only as an option).

Also note, that you can get the same information by using the slider on the speed graph in GPXSee, so I don't think that such visualization brings some new view on the data.

**Comment by ThibaultLemaire** [comment]
I understand the performance concern, but I have to disagree on the value of such a feature. Here is my use-case: I'm recording my commutes, so that's a lot of overlapping tracks. What I want to see is where I _frequently_ have to stop (I sometimes stop to get a thing in my bag, or to answer a call. This is just noise, what I'm interested in is frequent, unavoidable stops). This way I could quickly spot which variation of my route is statistically the best.

I've tried the slider indeed, but due to unavoidable offsets in the recordings, the drops in speed I'm interested in don't exactly match and don't stand out.

**Comment by tumic0** [comment]
Definitely a valid use-case, but out of scope of GPXSee. As stated on the homepage: _GPXSee is designed as a small (no dependencies except of Qt), fast and uncomplicated GPS data/map viewer, not a full featured GIS software._

**Comment by ThibaultLemaire** [comment]
Alright, I understand. Could you point me to a project into which that could fit? (Viking maybe?)

**Comment by tumic0** [comment]
Maybe a QGIS plugin?

**Comment by eumiro** [comment]
> Alright, I understand. Could you point me to a project into which that could fit? (Viking maybe?)

I'm working on the https://github.com/eumiro/pygohome project, that is exactly the route optimizer for (bicycle/pedestrian) commuters based on your recorded GPX tracks. I'm using GPXSee to preview my GPX tracks (my spaghetti map looks similar to that Prague map of @tumic0, although currently only at 120 tracks and ~1000km) and to find “where to connect the dots”.

GPXSee is a great fast tool to visualize the files (Thanks, @tumic0!). I wish it could let me edit the waypoints (POIs and intersections where my tracks split/join), but it is probably not the purpose of the tool.

QGIS: I didn't find a way to open those 120 GPX files at once. I'm using JOSM for this (did a lot of OSM earlier), but I'd need some simple tool for the users of pygohome.
