### ISSUE TITLE
missing feature : show coordinates of the cursor position

### ISSUE THREAD

**Issue by HJarausch** [tumic0/GPXSee#167]
I'm missing the feature to display the coordinates of the current cursor position.
Or am I missing something?
Thanks for considering this,
Helmut

**Comment by sikmir** [comment]
@tumic0 black text (like scale bar) would be a better here: 
![scr1](https://user-images.githubusercontent.com/688044/52918140-dea8c900-3304-11e9-916b-fdf1014eb5ad.jpg)

**Comment by tumic0** [comment]
Good point. Fixed in 7f7d7a916a30c9810f31372a14c31b4eef3949d4.

**Comment by sikmir** [comment]
Another one issue:
1. Check on "Show cursor coordinates" -> coordinates are shown
2. Restart GPXSee -> no coordinates shown

**Comment by tumic0** [comment]
Thanks for reporting, there was a typo. Fixed in bb71cfc42681627a66dd3db5ffcfda5bc661766f together with another "Show cursor coordinates" issue.

**Comment by sikmir** [comment]
@tumic0 it doesn't work properly if GPXSee ran without tracks.

**Comment by tumic0** [comment]
I guess you have OpenGL enabled. This is yet another Qt OpenGL bug...
