### ISSUE TITLE
GPXSee does not follow the XDG Base Directory Specification

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#169]
[Environment variables](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables):

> **$XDG_DATA_HOME** defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
> 
> **$XDG_CONFIG_HOME** defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 
> 
> **$XDG_CACHE_HOME** defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used. 

[Qt standard pathes](http://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum):

Path type | Linux/FreeBSD | macOS | Windows | Haiku
--- | --- | --- | --- | ---
AppDataLocation | ~/.local/share/\<APPNAME\> | ~/Library/Application Support/\<APPNAME\> | C:/Users/\<USER\>/AppData/Roaming/\<APPNAME\> | /boot/home/config/non-packaged/data/\<APPNAME\>
AppConfigLocation | ~/.config/\<APPNAME\> | ~/Library/Preferences/\<APPNAME\> | C:/Users/\<USER\>/AppData/Local/\<APPNAME\> | /boot/home/config/settings/\<APPNAME\>
CacheLocation | ~/.cache/\<APPNAME\> | ~/Library/Caches/\<APPNAME\> | C:/Users/\<USER\>/AppData/Local/\<APPNAME\>/cache | /boot/home/config/cache/\<APPNAME\>

Just in case:
```bash
$ sed -n '94,106p' qt5/qtbase/src/corelib/io/qstandardpaths_unix.cpp 
    case AppDataLocation:
    case AppLocalDataLocation:
    case GenericDataLocation:
    {
        QString xdgDataHome = QFile::decodeName(qgetenv("XDG_DATA_HOME"));
        if (isTestModeEnabled())
            xdgDataHome = QDir::homePath() + QLatin1String("/.qttest/share");
        if (xdgDataHome.isEmpty())
            xdgDataHome = QDir::homePath() + QLatin1String("/.local/share");
        if (type == AppDataLocation || type == AppLocalDataLocation)
            appendOrganizationAndApp(xdgDataHome);
        return xdgDataHome;
    }
```

https://github.com/tumic0/GPXSee/blob/efc773d04b2dae45ca7324f6f062d095f9c768d5/src/common/programpaths.cpp#L135-L139

### Steps to reproduce
```bash
$ mkdir -p ~/test/{data/gpxsee/{maps,POI},config,cache}
$ cp -r ~/GPXSee-maps/World/Europe/RU ~/test/data/gpxsee/maps
$ cp ~/points.wpt ~/test/data/gpxsee/POI
$ export XDG_DATA_HOME=~/test/data
$ export XDG_CONFIG_HOME=~/test/config
$ export XDG_CACHE_HOME=~/test/cache
$ gpxsee
```

### Actual behaviour
* GPXSee saves **tiles** into _~/test/data/gpxsee/tiles_.
```bash
$ tree ~/test/config/
~/test/config/
└── gpxsee
    └── gpxsee.conf
$ tree -L 1 ~/test/data/gpxsee
~/test/data/gpxsee
├── maps
├── POI
└── tiles
$ tree -L 1 ~/test/cache
~/test/cache
├── fontconfig
├── mesa_shader_cache
└── qt_compose_cache_little_endian_bf36e34a4cb94756bd3498c7e20e8ed3
```

### Expected behaviour
* **tiles** is non-essential data and should be stored in _XDG_CACHE_HOME_ location.
```bash
$ tree -L 1 ~/test/data/gpxsee
~/test/data/gpxsee
├── maps
└── POI
$ tree -L 1 ~/test/cache
~/test/cache
├── fontconfig
├── gpxsee
├── mesa_shader_cache
└── qt_compose_cache_little_endian_bf36e34a4cb94756bd3498c7e20e8ed3
```

### Configuration
GPXSee Version: latest (https://github.com/tumic0/GPXSee/commit/efc773d04b2dae45ca7324f6f062d095f9c768d5)
Qt Version: 5.11.2
Operating System: Linux

**Comment by tumic0** [comment]
I have changed the tile cache directory in a299207e5d43d222c6ac77d12219174becb651f0, hope that this is what you meant. If you find some of the other "new" paths problematic, then "Speak now or forever hold your peace" ;-). After the release of 7.0 the paths will not change any more.

**Comment by sikmir** [comment]
> I have changed the tile cache directory in a299207, hope that this is what you meant.

Yes, it's kosher now.
