### ISSUE TITLE
WMS URL uppercase parameters

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#170]
There are still some WMS servers, that accept only requests having upper case url parameters.
For more details, see Leaflet/Leaflet#1751.
One more example:
`https://wms.kartes.lv/BM45/lks/15/?BBOX=492853.9711849016,287182.4383909153,516883.9093781112,311212.37658412475&WIDTH=256&HEIGHT=256&KIJS=BM45&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&LAYERS=0&SRS=EPSG%3A3059&FORMAT=image%2Fpng&TRANSPARENT=true&env=&STYLES=`

**Comment by tumic0** [comment]
My willingness to add workarounds for some other broken tools decreases every year, so this one will probably never get implemented. Let's hope that such broken WMS servers have died out during the two years and consider this issue closed...
