### ISSUE TITLE
can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer

### ISSUE THREAD

**Issue by Nahannidog** [tumic0/GPXSee#171]
and continues with: "Try reinstalling the program to fix this problem".  Reinstalling does NOT resolve.  Windows 7 PC, no apparent problems.

Suggestions???

**Comment by tumic0** [comment]
api-ms-win-crt-runtime-l1-1-0.dll is part of [Visual C++ Redistributable for Visual Studio 2015 ](https://www.microsoft.com/en-us/download/details.aspx?id=48145) (MSVC runtime). Looks like you don't have it installed which is strange as GPXSee is shipped with the runtime and the installer installs it if it isn't already installed. Another possibility is that your MSVC 2015 runtime installation is broken. Try to re-install it, if it is already installed.

**Comment by Nahannidog** [comment]
Hello...Uninstalled MSVC2015 and GPXSee 6.3, then reinstalled GPXSee 6.3 and displayed details and saw that MSVC 2015 indeed being installed.  But, starting GPXSee, immediately got the same error message Next uninstalled MSVC2015 and GPXSee 6.3 and installed GPXSee-6.3_x64 and got the same error.  Next uninstalled MSVC & GPXSee and installed GPXSee 5.18 and got the same error.  Any suggestions????

**Comment by tumic0** [comment]
Maybe you are missing [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows)?
