### ISSUE TITLE
[feature] implement support for Open Flight Maps tiles

### ISSUE THREAD

**Issue by marsark** [tumic0/GPXSee#172]
I would be great to have a support for  https://www.openflightmaps.org/lk-czech-republic/ online tiles when analyzing track log from plane trip.

**Comment by tumic0** [comment]
OpenFlightMaps are already supported. Just download the tiles and create a map definition file like this for them:

```xml
<map xmlns="http://www.gpxsee.org/map/1">
	<name>Open Flight Maps</name>
	<url>file://Users/tumic/Downloads/clip/merged/256/latest/$z/$x/$y.png</url>
	<zoom min="4" max="11"/>
	<bounds left="12.09" top="51.06" right="18.87" bottom="48.55"/>
</map>
```

When they provide online tile images, just alter the URL to the HTTP(S) URL instead of the file URL.
