### ISSUE TITLE
Not a bug but... Virustotal reports hit on win64 download image

### ISSUE THREAD

**Issue by scotttaggart** [tumic0/GPXSee#173]
This is not a bug per-se but it's nice to pass the virus detectors on downloaded executables.  The GPXSee-6.3_X64.exe reports a virus hit at virustotal: https://www.virustotal.com/#/file/05e2c6e503eacd601f0f42e5a75bb2222f1d32339ce9eb93d94409dcd50bc4d8/detection  Probably OK, but it would be nice if this could be fixed.

![image](https://user-images.githubusercontent.com/1688344/49456588-391e9880-f79e-11e8-8910-2348c7e97bbc.png)

**Comment by tumic0** [comment]
Well, all AVs have false positives and the low-quality ones like Bkav especially. There is nothing one can do about it (I have even tried to report this false positive a long time ago, but no response from Bkav as expected).

**Comment by scotttaggart** [comment]
Note sure what an AV is.  Not all apps have false positives.  Some do, 
many don't.  That said, I understand and wanted to make sure you knew 
about it.
