### ISSUE TITLE
Feature request: Display/export names, descriptions, and notes

### ISSUE THREAD

**Issue by srsoltis** [tumic0/GPXSee#177]
It would be great if you could add support for displaying and exporting names, descriptions, and notes.  Examples:

Tcx has a <Notes> attribute under <Activity>.  This is used by Garmin utilities like Training Center.

gpx has a <name> attribute that is utilized by Strava.  The gpx manual also shows <desc> which could be handy.

Excellent tool.  Thanks for your hard work.

**Comment by tumic0** [comment]
Names and descriptions are already available, you can find them in the track/route tooltip info. The name is  also part of the PDF export.

**Comment by srsoltis** [comment]
Thanks for the quick reply.  This is a fantastic tool, and I apologise if I
sound nitpicky.  

 

On GPX

- I see <name> and <desc> in the tooltip.  Sorry, I missed this.

- The <name> is printed on pdf export, but I don't see <desc> printed.

 

On TCX

- I don't see <Id> or <Notes> in the tooltips or pdf export.

 

Have you given any thought to being able to run pdf export from the
command-line?

 

 

 

  _____
