### ISSUE TITLE
Feature Request: Filter tracks by date

### ISSUE THREAD

**Issue by ksmiller99** [tumic0/GPXSee#179]
I have a lot of data and I'd like to see what happened on a certain date and I cannot see a way to do it in GPXSee. Perhaps it's an existing feature that I cannot find, or is there a work-around, like filtering the GPX data before using GPXSee. How would that be done?

**Comment by tumic0** [comment]
There is no such feature. The reason is I have never seen (original) track logs that would not have the date/time in the filename. And even then, something as simple as:

```bash
for i in *; do TIME=`grep -m 1 '<time>.*</time>' "$i" | sed 's/.*<time>\(.*\)<\/time>.*/\1/'`; mv "$i" "$TIME.gpx"; done
```

would solve the problem.
