### ISSUE TITLE
Display problem with dark theme

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#180]
### Steps to reproduce
```bash
$ sudo pacman -S qt5ct
$ mkdir -p ~/.local/share/gpxsee/{POI,maps,style}
$ cd ~/.local/share/gpxsee
$ curl -o maps/MapTiler.xml https://raw.githubusercontent.com/tumic0/GPXSee-maps/master/World/MapTiler.tpl
$ sed -i 's/insert-your-apikey-here/<my-apikey>/' maps/MapTiler.xml
$ curl -o style/dark-matter.json https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/master/style.json
$ ln -s dark-matter.json style/style.json
$ curl https://nakarte.me/geocachingSu/geocaching_su2.json | \
  gzip -d | \
  jq -r ".[]|[.[2],.[3],.[0]]|@tsv" |  \
  awk -F"\t" 'BEGIN{print "<gpx xmlns=\"http://www.topografix.com/GPX/1/1\" version=\"1.1\">"}{printf "<wpt lat=\"%s\" lon=\"%s\"><name>%s</name></wpt>\n",$1,$2,$3}END{print "</gpx>"}' | \
  sed 's/&/&amp;/g' > POI/geocaching.su.gpx
$ crudini --set ~/.config/gpxsee/gpxsee.conf Map map MapTiler
$ crudini --set ~/.config/gpxsee/gpxsee.conf POI show true
$ crudini --set ~/.config/gpxsee/gpxsee.conf Options backgroundColor '@Variant(\0\0\0\x43\x1\xff\xff\x42\x42\x42\x42\x42\x42\0\0)'
$ crudini --set ~/.config/gpxsee/gpxsee.conf Options paletteColor '@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\xff\xff\0\0)'
$ crudini --set ~/.config/gpxsee/gpxsee.conf Options poiColor '@Variant(\0\0\0\x43\x1\xff\xffUU\xff\xff\xff\xff\0\0)'
$ crudini --set ~/.config/gpxsee/gpxsee.conf Options poiSize 10
$ crudini --set ~/.config/gpxsee/gpxsee.conf Options waypointColor '@Variant(\0\0\0\x43\x1\xff\xff\0\0\xcf\xcf\0\0\0\0)'
$ crudini --set ~/.config/gpxsee/gpxsee.conf Options waypointSize 12
$ crudini --set ~/.config/qt5ct/qt5ct.conf Appearance custom_palette true
$ crudini --set ~/.config/qt5ct/qt5ct.conf Appearance color_scheme_path /usr/share/qt5ct/colors/darker.conf
$ gpxsee --platformtheme qt5ct
```
### Actual behaviour
![scr-dark](https://user-images.githubusercontent.com/688044/50690050-05ed5480-103d-11e9-9f3a-7f56842c1710.jpg)
### Expected behaviour
![scr-default](https://user-images.githubusercontent.com/688044/50690063-100f5300-103d-11e9-8ce1-b6f029dd4eee.jpg)
### Configuration
GPXSee Version: 7.1.r1312.35309ef4
OS: Arch Linux

**Comment by sikmir** [comment]
It's perfect now:
![scr3](https://user-images.githubusercontent.com/688044/50704430-6940ac00-1068-11e9-9d84-f855835f1b55.jpg)

**Comment by tumic0** [comment]
There seems to be an issue with the slider info background, but in KDE dark modes (e.g. Breeze dark) it works fine. Looks like the painter's background() is not the QWidget background in your case...

**Comment by sikmir** [comment]
Yes, and the slider is not cleared after moving:
![scr4](https://user-images.githubusercontent.com/688044/50705874-36e57d80-106d-11e9-934a-222eb95b2bc1.jpg)

**Comment by sikmir** [comment]
Looks OK now:
![scr5](https://user-images.githubusercontent.com/688044/50707076-c93b5080-1070-11e9-8417-90b2acd65141.jpg)

**Comment by tumic0** [comment]
Yes, this is how it should look like. Hopefully it has no side effects on Windows/OS X.

**Comment by sikmir** [comment]
One more unrelated issue:
![scr1](https://user-images.githubusercontent.com/688044/50709921-78305a00-107a-11e9-9cf9-7ead18e2982e.jpg)
![scr2](https://user-images.githubusercontent.com/688044/50709924-78305a00-107a-11e9-8e5a-f4260f964c95.jpg)
Why Windows shortcuts (Ctrl+F4 for Close, no shortcut for Quit) are used with `--platformtheme qt5ct`? I thought it can be changed in qt5ct settings, but all other my qt applications work OK (the same shortcuts with/without `--platformtheme qt5ct`). I think it's not GPXSee issue though.

**Comment by tumic0** [comment]
No idea, but I get the same behaviour with qt5ct (but I do run Arch Linux like you, so this is no surprise). Do the other applications use the QKeySequence::Close key sequence, or do they explicitly use "Ctrl+W"?

**Comment by sikmir** [comment]
You are right, I've checked, they use Ctrl+Q explicitly.
