### ISSUE TITLE
Using OpenSteetMap Maps Offline.

### ISSUE THREAD

**Issue by dgoadby** [tumic0/GPXSee#184]
GPXSee supports OpenStreetMap but the list of offline maps does not include OpenStreetMap. Is this because it is difficult to do or there is no interest? 

I use GPXSee on my narrow boat and Internet access is not always possible. I can download OpenStreeMap vector tiles and run my own "boat local" server. 

My question is can I use GPXSee with my own OpenStreetMap server?

**Comment by tumic0** [comment]
You can make a map definition for any raster/MVT tiles like described in #172 and don't even need a server. You may also use MBTiles, for example from [openmaptiles.org](https://openmaptiles.org/) (OpenMapTiles >= v3.7 are required). And finally you can create an offline atlas with [MOBAC](https://mobac.sourceforge.io) form any OpenStreetMap based online map.
