### ISSUE TITLE
Support for GIScience Heidelberg Maps is broken in version 7

### ISSUE THREAD

**Issue by pmo-19** [tumic0/GPXSee#185]
It was working fine in version 6 but not at all in version 7.
I am using

> `<?xml version="1.0" encoding="UTF-8"?>`
>          `<map xmlns="http://www.gpxsee.org/map/1.0">`
>          ` <name>GIScience Heidelberg</name>`
>         `<url>https://korona.geog.uni-heidelberg.de/tiles/roads/x=$x&amp;y=$y&amp;z=$z</url>`
>        ` <copyright>Map data: © OpenStreetMap contributors (ODbL) | Rendering: © GIScience Heidelberg (CC-SA)</copyright>`
>`<zoom max="20"/>`
> `</map>`

What is wrong and where are stored the downloaded tile in Linux Ubuntu ?
How to clear the downloaded tiles ?

**Comment by sikmir** [comment]
> What is wrong and where are stored the downloaded tile in Linux Ubuntu ?

That's server side problem, not a GPXSee issue.

> How to clear the downloaded tiles ?

`$ rm -fr ~/.cache/gpxsee/tiles/GIScience\ Heidelberg`

**Comment by pmo-19** [comment]
It looks like they require now an API.
However, then it would mean that downloaded tiles from version 6 are not accessed by verion 7 of GPXSee ? Why ? Where is the tiles cache stored in Linux Ubuntu ?
Another problem is that when entering the new .xml file as a patch in source code, the GPXSee program don't list at all GIScience Heidelberg as a map ... ? It was working in the previous version of the xml file.
Here is the new GIScience-Heidelberg.xml

`<?xml version="1.0" encoding="UTF-8"?>`
`<map xmlns="http://www.gpxsee.org/map/1.0">`
`<name>GIScience Heidelberg</name>`
`<url>https://api.openrouteservice.org/mapsurfer/$z/$x/$y.png?api_key=myAPIkey</url>`
`<copyright>Map data: © OpenStreetMap contributors (ODbL) | Rendering: © GIScience Heidelberg (CC-SA)</copyright>`
`<zoom max="20"/>`
`</map>`

The myAPIkey has 56 characters.

**Comment by pmo-19** [comment]
For version 6 the tiles cache was located elsewhere ? where exactly ?
Your answer is valid for GPXSee version 7.

**Comment by pmo-19** [comment]
You can register to get one free API here

[https://openrouteservice.org/dev/#/api-docs](url)

**Comment by pmo-19** [comment]
The previous GIScience-Heidelberg.xml file which is no more valid to retrieve the tiles, but was recognized by GPXSee 5 and 6 is the following

`<?xml version="1.0" encoding="UTF-8"?>`
`<map>`
`<name>GIScience Heidelberg</name>`
`<url>https://korona.geog.uni-heidelberg.de/tiles/roads/x=$x&amp;y=$y&amp;z=$z</url>`
`<copyright>Map data: © OpenStreetMap contributors (ODbL) | Rendering: © GIScience Heidelberg (CC-SA)</copyright>`
`</map>`

The new one is not recognized by GPXSee as the Map is not listed in the menu of available maps.

**Comment by sikmir** [comment]
> The new one is not recognized by GPXSee as the Map is not listed in the menu of available maps.

No, everything works for me. Check your `~/.local/share/gpxsee/maps`, the map should be placed there.

**Comment by tumic0** [comment]
The user paths have changed between version 6 and 7 like stated in the [documentation](http://www.gpxsee.org/doc.html). For both versions you can see the paths in the "Help" menu.

Downloaded tiles (for the current map) can be cleared from the "Map" menu ("Clear tile cache").

**Comment by pmo-19** [comment]
I do not agree with you.
The new xml is not recognize in version 7 and in version 6 (just tested) as suspected, as well.
In all cases the Menu Maps does not show any entry for the new xml in both versions, meaning it's not parsed properly by the program.
The old xml is recognized / parsed properly by both versions as a menu entry is shown in the Map menu, however it's not working because of a server side change as said before.
The Maps available are only those provided by default in your program, so the Openrouteservice.org xml is not parsed properly somewhere, as it doesn't show up in the Map menu.
The data locations are correct and the xml is shown in /usr/share/gpxsee/maps this is not the problem.
The tiles location is different for both versions and your first answer was correct.
If you claim you succeeded please show here a screenshot of this Openrouteservice.org Map within GPXSee.

**Comment by sikmir** [comment]
> ... meaning it's not parsed properly by the program.

Well, provide GPXSee log output with such "parsing error" if any.

**Comment by pmo-19** [comment]
I don't see any accessible log in the program itself.
However how would you explain that the old format which is close to the format used in the provided default Maps do show an entry in Menu Map and the new xml format doesn't show any entry either in version 6 or version 7 in the Menu Map for that xml ?
Where is the Map menu devised from the Map xml files ?

**Comment by sikmir** [comment]
> I don't see any accessible log in the program itself.

Run GPXSee from console and provide output.

**Comment by pmo-19** [comment]
OK. I have an error:
`/usr/share/gpxsee/maps/GIScience-Heidelberg.xml: 6: Invalid maximal zoom level`
So I will remove the zoom level and retest.

**Comment by pmo-19** [comment]
OK. That was it ! Removing the Zoom level made it work ...
Thanks

**Comment by pmo-19** [comment]
How to devise the max zoom level ? other than trial and error ?

**Comment by pmo-19** [comment]
ANother question is that I don't see any POI and DEM folder either in my /home/username or in /usr/share/gpxsee

**Comment by sikmir** [comment]
> How to devise the max zoom level ? other than trial and error ?

Get the proper value from map service provider.

> ANother question is that I don't see any POI and DEM folder either in my /home/username or in /usr/share/gpxsee

Feel free to manually create them if you need.

**Comment by tumic0** [comment]
> OK. That was it ! Removing the Zoom level made it work ...
> Thanks

You don't have to delete it, just set it to a valid value, which is <0,19>. The exact value can be either obtained from the map provider or get experimentally by the  "trial and error" method. If not set, 19 is assumed which will lead to a "suboptimal user experience" if it is not 19.
