### ISSUE TITLE
Battery percentage as graph

### ISSUE THREAD

**Issue by gri-zz-ddy** [tumic0/GPXSee#188]
Would it be possible to view the battery percentage as another tab along with the other graphs showing speed, cadence etc?

Great program by the way, really useful.

I added battery percentage to my garmin FIT files using an addon on the IQ connect store called 'FIT Battery' by the developer Stanislav.Bures, I was hoping it would show in GPXSee as another tab but I guess it would need to be added to the program

**Comment by tumic0** [comment]
It's like you guess - the graphs are not dynamic but "hardcoded". With that many file formats that GPXSee supports it is almost impossible to make them "dynamic". Also some features like units switching or (reasonable) statistics info could not be implemented in that case.

A non-standard extension of a single data file format (FIT) is not significant enough to be added as a special graph, sorry.
