### ISSUE TITLE
Not loading at desired zoom level

### ISSUE THREAD

**Issue by raretrack** [tumic0/GPXSee#189]
Hi

I've been trying to edit OpenStreetMap.xml to start at my desired zoom and lat / long.  I've amended the default of
<url>http://tile.openstreetmap.org/$z/$x/$y.png</url>
to
<url>http://tile.openstreetmap.org/13/51.9739/-0.1957.png</url>
but GPXSee still opens at the default world map level.

Please can someone let me know if I am doing something wrong.

I'm running v7.3 x86_64 on Windows 10.

Many thanks

**Comment by sikmir** [comment]
> Please can someone let me know if I am doing something wrong.

Currently it's impossible. See #73.

**Comment by raretrack** [comment]
> 
> 
> > Please can someone let me know if I am doing something wrong.
> 
> Currently it's impossible. See #73.

Ah, OK. Thanks for the quick reply

**Comment by sikmir** [comment]
As a workaround, you can add:
```xml
  <zoom min="..." max="..."/>
  <bounds left="..." right="..." bottom="..." top="..."/>
```
But generally that's not what you want.
