### ISSUE TITLE
No POI shown on map

### ISSUE THREAD

**Issue by tomthecat** [tumic0/GPXSee#19]
I refer to http://www.skitourenguru.ch/index.php/download and the files

"Hütten der Schweiz" and
"Skitouren als GPX-Version"

I was able to load these POI files in GPXsee via the POI menu entry or, as an alternative, via $home/.gpxsee/POI. Unfortunately, no POI were shown. I know that GPXSee renders only POIs reasonable near a GPX track loaded. But this is not true, even if I extend the POI radius to 100 km.

The POI files were shown correctly if loaded directly in GPXsee.

**Comment by tumic0** [comment]
Fixed in 214d7c40dc9037955a769a43f0b4a3e0eb03a01c.
