### ISSUE TITLE
Map Zoom Level

### ISSUE THREAD

**Issue by emallay** [tumic0/GPXSee#190]
Thanks for making this app available – I've been enjoying exploring it. The support for mbtiles and for multiple tracks visible at once is fantastic!

One request: please display the current zoom level of the map. I don't see any option for displaying it. Thanks!

**Comment by tumic0** [comment]
GPXSee supports hundreds of maps with different zoom level specifications (scale, projection) so there is nothing like a universal zoom level that would make sense to display. However, on every map there is the scale bar which is a much better "zoom" indicator than some "magic" number. Also note, that the GUI can not be simple and clear and at the same time display every information one can imagine.
