### ISSUE TITLE
Time step to speed

### ISSUE THREAD

**Issue by vollgray** [tumic0/GPXSee#191]
I am trying to contact the designer of this app to ask them if I can extract more data from the file itself. Namely, the speeds given are in 6 second time increments. I wanted to know if it was possible to get access to a closer time step (hopefully speed for every second or half second). It would be exceptional if there was some sort of export to Excel file for speed/time available as well. Any response or contact to help in determining if this is a possibility would be greatly appreciated. Thanks.

**Comment by tumic0** [comment]
GPXSee uses all trackpoints that are in the source data file (with exception of outliers when outlier elimination is enabled), there is no kind of interpolation. In other words - it is the data itself that was recorded with 6 seconds period. If you are sure the data have a lower period, then there must have be an error in parsing the file format, but without the data file there is nothing I can do about it.
