### ISSUE TITLE
igc track which crosses UTC midnight not handled correctly

### ISSUE THREAD

**Issue by JanBennewitz** [tumic0/GPXSee#192]
See attached example. When opened in GPXSee, the elevation and speed graphs show this three hour flight as having a duration of (24+3=) 27 hours, with a 24 hour gap where UTC midnight is crossed.

[2019-02-04-XCT-JBE-03.zip](https://github.com/tumic0/GPXSee/files/2948950/2019-02-04-XCT-JBE-03.zip)

**Comment by tumic0** [comment]
Fixed. I hope the way how the IGC file is recorded (a new date record just before the date switch) is the standard way how the loggers handle this situation. The previous implementation was AFAIK just a guess as I did not have any such IGC files or a IGC flight recorder and there is nothing in the standard about this situation.

**Comment by JanBennewitz** [comment]
I don't think it is, see attached file from a different logger. This file is however handled correctly by the released version 7.3 of GPXSee.

[51RJanB1.zip](https://github.com/tumic0/GPXSee/files/2949281/51RJanB1.zip)

[...]
B2359453821175S14417889EA0000000117
B2359503821196S14417859EA0000000121
B2359553821218S14417836EA0000000130
B0000003821238S14417820EA0000000140
B0000053821245S14417823EA0000000143
B0000103821241S14417832EA0000000142
[...]

**Comment by tumic0** [comment]
Ok, thanks for the samples. b13590450dc56c520663ec37fd834cd19cc8d3e6 changes the IGC parser in a way that both variants work.
