### ISSUE TITLE
[7.3] Hiding POI labels?

### ISSUE THREAD

**Issue by Shohreh** [tumic0/GPXSee#193]
Hello,

I'm trying 7.3 on Windows.

I found no way to 1) hide the labels on POIs and 2) display them when hovering the mouse.

Is this feature supported?

Thank you.

![F15521D8-0862-468A-8D43-B1685C027786](https://user-images.githubusercontent.com/1541861/54090258-83ea1680-4372-11e9-9cbb-85bcc400f07f.png)

**Comment by tumic0** [comment]
POIs are something different in GPXSee terminology, see the [documentation](https://www.gpxsee.org/doc.html#poi). What you are searching for is show/hide waypoint labels which you can find under "Data->Display->Waypoint labels".

**Comment by Shohreh** [comment]
Thanks. Too bad it won't display the labels when hovering the mouse over the POIs.

**Comment by tumic0** [comment]
It does. Its implemented as a tooltip, so you have to wait some time over the waypoint. The same applies to tracks and graphs.
