### ISSUE TITLE
Error loading map: 4: Expected ';', but got '=".

### ISSUE THREAD

**Issue by JuttaAnders** [tumic0/GPXSee#194]
My map.xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.3">
    <name>Test</name>
    <url>https://khms1.googleapis.com/kh?v=821&hl=en-GB&x=$x&y=$y&z=$z</url>
    <zoom max="18"/>
</map>
```
 
I would expect the following line ...
`https://khms1.googleapis.com/kh?v=821&hl=en-GB&x=$x&y=$y&z=$z`
... to be converted in something like ...
`https://khms1.googleapis.com/kh?v=821&hl=en-GB&x=0&y=0&z=0`
 
Unfortunately I get the following error while loading the xml:
 
```
Error loading map:
D:/.../test.xml
4: Expected ';', but got '=".
```

**Comment by sikmir** [comment]
Use &amp; instead of &.

**Comment by JuttaAnders** [comment]
Thanks @sikmir, it works now. Just as reference for the future, which are the chars that have to be encoded this way?

**Comment by sikmir** [comment]
> Just as reference for the future, which are the chars that have to be encoded this way?

[What characters do I need to escape in XML documents?](https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents)

**Comment by JuttaAnders** [comment]
Thanks @sikmir

**Comment by tumic0** [comment]
As this is the same "issue" you send me via email (which I have answered on 18.3.) I would be quiet interested to know whether you have received that answer. Looks like some of my emails I have send recently did not reach the recipients...

**Comment by JuttaAnders** [comment]
@tumic0 unfortunately I did not receive any email... that is why I wrote here :-)
