### ISSUE TITLE
Map zoom level resets when app window is resized

### ISSUE THREAD

**Issue by robvelez** [tumic0/GPXSee#197]
I couldn't find an existing issue on this, but when viewing a map at a certain level in the app window (not maximized), then I maximize or resize the app, the map zoom level resets to the global map view. Is there a way to preserve the map zoom level when resizing the map?

**Comment by sikmir** [comment]
See #74.

**Comment by robvelez** [comment]
Thanks @sikmir . Will close my issue as there's an existing issue pending.

**Comment by robvelez** [comment]
Closing my issue as there is an existing issue logged.
