### ISSUE TITLE
Garmin IMG maps character encoding problem

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#200]
### Steps to reproduce
```bash
$ curl -o ~/.local/share/gpxsee/maps/all_put.img http://slazav.mccme.ru/maps/hr/all_put.img
```
The same problem with other IMG maps, e.g. [MapTourist](https://maptourist.org/osm-garmin/OSM-MapTourist-szfo-RU.zip).
### Actual behaviour
![scr2](https://user-images.githubusercontent.com/688044/56580526-664bd600-65db-11e9-9166-c1602dc8601c.jpg)
### Expected behaviour
![scr1](https://user-images.githubusercontent.com/688044/56580524-664bd600-65db-11e9-99ba-d8e971e0c6fd.jpg)
### Configuration
GPXSee Version: latest imgmap branch (https://github.com/tumic0/GPXSee/commit/9ece7d59a8435c95aec68612eb12aee50bc3d7a0)

**Comment by tumic0** [comment]
I have added the missing text encodings support in 69b17cd89c993e7d199e8a29c78871ca25161da7, but note, that text support is not finished yet. The text is for example cut on tile border (when using precached image tiles that are much faster than direct rendering). And of course, street names are not handled at all (there is even not yet support for NET files).

**Comment by sikmir** [comment]
Well, it works properly now.

**Comment by sikmir** [comment]
@tumic0 One more problem with encoding of map name: 
![out](https://user-images.githubusercontent.com/688044/77150868-e1489580-6aa5-11ea-8e70-021a4567cccf.png)
[OV-Hib-Lov-20191028-1.02.zip](https://drive.google.com/uc?export=download&id=10aAOKY8U7TQvFvuWBkwTei9iP3-cUvoE).

**Comment by tumic0** [comment]
There is AFAIK no codepage field in the IMG header and the two fields that put the IMG name together must be in the latin1 encoding. The authors of mkgmap even [think](https://github.com/openstreetmap/mkgmap/blob/0b3858095e60a27870ed37afbdfc87dc49d4dc55/src/uk/me/parabola/imgfmt/sys/ImgHeader.java#L320) it must be ASCII (which is not true as there are maps from GARMIN that use latin1 characters).
