### ISSUE TITLE
Garmin IMG map: missed map features

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#201]
### Actual behaviour (no railway)
![scr2](https://user-images.githubusercontent.com/688044/56693682-c6cb3800-66ed-11e9-9b1f-4bdeaca0d7cc.jpg)
### Expected behaviour
![scr1](https://user-images.githubusercontent.com/688044/56693681-c632a180-66ed-11e9-94c3-e8883ae7cf17.jpg)

**Comment by tumic0** [comment]
This objects are part of the extended (overlay/TRE7) section. It is IMHO a very bad map design to use this sections for essential data like railways or roads, but some maps do so... I have added support for this section in 362ba88eda4ca8f302891bef0d3d11dde8501cfb, so the railway should now get displayed.
