### ISSUE TITLE
A request please

### ISSUE THREAD

**Issue by HowardFupp** [tumic0/GPXSee#202]
Is there a method for an idiot like me to use the ~15 GB of map data (osm.mca  -- file extension type) I ALREADY have stored in this old win7-pro-64-bit machine OFFLINE in your EXCELLENT GPXSee program ?  Thank you.   <rudyrudy1862hot@hotmail.com>

**Comment by sikmir** [comment]
GPXSee doesn't support _MapFactor Navigator_ map format (`.mca`).
