### ISSUE TITLE
Suppress elevation graph?

### ISSUE THREAD

**Issue by jmoellers** [tumic0/GPXSee#203]
Is it possible to suppress the elevation graph? My GPS tracker does not provide dependable elevation data and I really don't need it, so it would be nice to suppress this graph (and maybe other unwanted graphs as well).

**Comment by sikmir** [comment]
Elevation graph is suppressed, If GPS log file has no elevation data and there is no DEM data available. The same true for all other graphs. Provide your GPS log file.

**Comment by jmoellers** [comment]
The file does indeed have elevation data but it is unreliable, so I wouldn't want to clutter my window with references to it. The device in question is a "Wintec G-Rays 2"

```
<?xml version="1.0" encoding="UTF-8"?>
<gpx
version="1.0"
creator="GPSBabel - http://www.gpsbabel.org"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.topografix.com/GPX/1/0"
xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">
<time>2019-04-24T17:33:45Z</time>
<bounds minlat="51.713188300" minlon="8.541391600" maxlat="51.813706600" maxlon="8.705529900"/>
<trk>
<name>Track</name>
<cmt>Comment</cmt>
<desc>Start: 2019-04-24T17:33:45Z
End: 2019-04-24T19:29:26Z</desc>
<trkseg>
<trkpt lat="51.727448200" lon="8.684113300">
  <ele>113.000</ele>
  <time>2019-04-24T17:33:45Z</time>
  <name>TP129499</name>
</trkpt>
<trkpt lat="51.727429900" lon="8.684111600">
  <ele>113.000</ele>
  <time>2019-04-24T17:33:46Z</time>
  <name>TP129500</name>
</trkpt>
</trkseg>
</trk>
</gpx>
```
I was hoping for some check box to disable this tab/graph.

**Comment by sikmir** [comment]
If you don't need elevation data, just remove it:
```bash
$ sed -i 's#<ele>[0-9.-]*</ele>##g;/^\s*$/d' track.gpx
```

**Comment by tumic0** [comment]
You can always hide the graphs using the menu or Ctrl+g shortcut. If you want to modify the data files, you have to use some other tool (or a script), GPXSee is just a viewer.
