### ISSUE TITLE
Bing Maps Tile System Support

### ISSUE THREAD

**Issue by willdashwood** [tumic0/GPXSee#205]
Hello,

Does GPXSee support the Bing Maps Tile System (quadkeys)?

https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system

I've been trying and failing to get it to work with the following code.

```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.3">
	<name>OS Maps (Bing)</name>
	<url>http://ak.t3.tiles.virtualearth.net/tiles/r{c}.png?g=3455&lbl=l1&productSet=mmOS&key=Ai8NajASx4M8LIF33zfGRBxipDlNqj5Y9Cqvv4tQGqRrfJ9_SoZeBCKKnaeGuqrH</url>
	<copyright>Map data: © Microsoft</copyright>
</map>
```

My API key is removed from the above but of course present in the actual file. This is similar to what I use with Locus Maps on Android and I was hoping the same might work with GPXSee. 

Many thanks!

**Comment by tumic0** [comment]
There is no quadkeys support in GPXSee at the moment.

**Comment by willdashwood** [comment]
Thanks, I probably should have asked that before trying to get it to work! Is it something that might be added in the future? Or is there an alternative way of UK Ordnance Survey tiles?

**Comment by tumic0** [comment]
> Is it something that might be added in the future?

Yes. That's why I'm letting the issue open. But as the quadkeys are AFAIK used by a single service on the whole internet - the Bing maps - it won't have a very high priority.

> Or is there an alternative way of UK Ordnance Survey tiles?

Ordnance Survey apparently provides a standard [WMTS service](https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/web-services/os-ondemand/configuring-wmts.html).

**Comment by tumic0** [comment]
QadTiles support added in 5b2af9fc9cae99f726a32df7c5f4c9ce31ec87de. Use _QuadTiles_ as map type and _$quadkey_ as URL key.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4" type="QuadTiles">
	<name>OS Maps (Bing)</name>
	<url>http://ak.t3.tiles.virtualearth.net/tiles/r$quadkey.png?g=3455&lbl=l1&productSet=mmOS&key=Ai8NajASx4M8LIF33zfGRBxipDlNqj5Y9Cqvv4tQGqRrfJ9_SoZeBCKKnaeGuqrH</url>
	<copyright>Map data: © Microsoft</copyright>
</map>
```

**Comment by sikmir** [comment]
Working example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4" type="QuadTiles">
  <name>OS Maps (Bing)</name>
  <url>https://t.ssl.ak.dynamic.tiles.virtualearth.net/comp/ch/$quadkey?mkt=en-US&amp;it=A,G,RL&amp;shading=hill&amp;n=z&amp;og=420&amp;c4w=1&amp;osm=1</url>
  <copyright>Map data: © Microsoft</copyright>
</map>
```

**Comment by willdashwood** [comment]
Wow, that's quick! Thank you. I'll have to wait for the Windows builds to catch up but I look forward to giving it a try. Many thanks!

**Comment by tumic0** [comment]
You can use the automatic [ci builds](https://ci.appveyor.com/project/tumic0/gpxsee) for testing new features/bug fixes. They are missing the MVT(PBF) plugin and require the MSVC 2013 runtime (which many people have already installed) in addition to the MSVC 2015 runtime (which is part of the installer) due to appveyor/ci#1616, but otherwise  they are fully functional.

**Comment by willdashwood** [comment]
Thank you, it works a treat!

For relative noobs like me, it took me a while to find the download link. I've never visited appveyor before so took me a while to realise the builds were on the [Artifacts tab](https://ci.appveyor.com/project/tumic0/gpxsee/build/job/q8davkh92ulqef28/artifacts).

I had to wrap the URL in <![CDATA ]] but the following works perfectly.

`<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4" type="QuadTiles">
	<name>OS Maps (Bing)</name>
	<url><![CDATA[http://ak.t3.tiles.virtualearth.net/tiles/r$quadkey.png?g=3455&lbl=l1&productSet=mmOS&key=YOUR_API_KEY-HERE]]></url>
	<copyright>Map data: © Microsoft</copyright>
</map>
`

Thank you so much for implementing this so quickly!

**Comment by tumic0** [comment]
> I had to wrap the URL in <![CDATA ]] but the following works perfectly.

Well it's XML, so you have to somehow escape the special characters. CDATA is one option, the alternative are xml entities. See sikmir's example.

**Comment by tumic0** [comment]
What are you trying to achieve? Your URL does not seem to fetch map tiles which is the way how the GPXSee maps work. GPXSee does not use any proprietary (REST) API, just URLs that return tile images.

**Comment by tumic0** [comment]
> View Bing Aerial tiles. See Bing docs. Only REST seems appropriate or possible?

The example from @sikmir which still works is an (overlayed) aerial map, so I guess pure aerial maps are also possible if you fiddle with the URL parameters. But I have no idea if such requests are documented or even allowed by Bing. You have to contact Microsoft for more details - all that GPXSee provides is the ability to use quadkeys in the tile fetch URLs. Any proprietary API or usage policy of a particular map service is out of scope of GPXSee.

> I was trying to follow your docs

The REST attribute is only valid in WMTS URLs. It distinguishes between the standard WMTS REST and KVP access methods.
