### ISSUE TITLE
Translate in Italian

### ISSUE THREAD

**Issue by Denisov21** [tumic0/GPXSee#207]
Hi,
I wish it in Italian language. What do you think?

**Comment by tumic0** [comment]
The only way how to make it happen is you find someone who will translate GPXSee to Italian. If you are the volunteer yourself, simply join [Weblate](https://hosted.weblate.org/projects/gpxsee/translations/) and request the translation.

**Comment by tumic0** [comment]
Alternatively you may also create a pull request with the Italian ts file.
