### ISSUE TITLE
Open image thumbnail when clicking on waypoint

### ISSUE THREAD

**Issue by r4f** [tumic0/GPXSee#208]
I was first confused and thought my gps-tagged image did not show up when clicking on the image-label, since the hover-action does not activate immediately. I think it would be a bit more intuitive if clicking on the label would also show the tumbnail.

**Comment by tumic0** [comment]
It is a "known issue" (see #142), that the tooltip handling could be improved. I have been fiddling
with it some time ago, but it is not so easy to implement it "right".
