### ISSUE TITLE
Speed in m/s

### ISSUE THREAD

**Issue by O60PMOT** [tumic0/GPXSee#211]
Hello, why a see not correct speed on map?
I write to the file according to the specification:

```
<speed>
Optional in: <wpt> <rtept> <trkpt>
Units: meters per second
<speed>4.23</speed>
Instantaneous speed at the point.

```
In program i see momentum speed not correct, but average speed is correct!

scrrenshot:
https://habrastorage.org/webt/vi/_a/ga/vi_agauiraklgxe5brmmwdpi07g.jpeg

**Comment by tumic0** [comment]
There is data filtering/smoothing enabled by default. You can disable it in the preferences.

**Comment by O60PMOT** [comment]
i don't enable filtering/smoothing, but speed is wrong. 

https://habrastorage.org/webt/3m/qn/qf/3mqnqfohnjqntgmgiscf5copsco.jpeg
https://habrastorage.org/webt/x-/br/x0/x-brx06aaqvy_cvyfzw4py2sdks.jpeg
https://habrastorage.org/webt/-s/s9/xw/-ss9xwng_cd8djrkwrye4aqerks.jpeg

**Comment by O60PMOT** [comment]
Example GPX file: https://sites.google.com/site/dskibin555/2019-05-26_10-32-48.gpx

**Comment by tumic0** [comment]
You must also select the right source of the speed in "Data"->"Sources". The default is "Computed from distance/time", but what you want to see is "Recorded by device".

The "antialiasing" checkboxes in the "Appearance" configuration have nothing to do with the data, they only control if the graph/path lines shall be drawn antialiased.

**Comment by O60PMOT** [comment]
thanks, i select Recorded by device, restart application - speed is wrong:
https://habrastorage.org/webt/oi/sy/wn/oisywne1-zmoyop_mtn05xztwtu.jpeg

other mobile software show normal speed:
https://habrastorage.org/webt/bl/1x/ic/bl1xicia3wc-_u2vb2wu7i5nq08.jpeg

**Comment by tumic0** [comment]
After a look into the data file you have provided the situation is clear. The file is not a valid GPX file, the "speed" element can only occur inside the "extensions" element. If you look at the [GPX specification](https://www.topografix.com/gpx/1/1/#type_wptType), you can see there is no "speed" element inside a "trkpt" element. So for GPXSee there is no recorded speed in the file and in this case it uses the computed speed as fallback.

**Comment by O60PMOT** [comment]
I was guided by https://www.topografix.com/gpx_manual.asp - GPX 1.0 
and if i save in version 1.0 where this tag is provided GPXSee will read speed??

**Comment by O60PMOT** [comment]
<extensions><speed>25.00</speed></extensions> - work.

I found another mistake in myself: i recieve from NEO-7M height in meters about sea level, in GPX this is tag <geoidheight>, not <ele> tag. Is this not supported by GPXSee?

**Comment by tumic0** [comment]
I have added support for GPX 1.0 (which is 15 years obsolete...) speed entries in 301172f5e8c112cd8800a71a19a7231418cd505a. It will even work with broken GPX files likes the one provided.

**Comment by tumic0** [comment]
Regarding `geoidheight`/`ele` - I don't get what you mean. GPXSee supports both elements, but each has a different purpose, see the GPX specification for details.
