### ISSUE TITLE
Domain Network and Folder Redirection - Windows

### ISSUE THREAD

**Issue by samwhite59** [tumic0/GPXSee#212]
Hi.
Seems like I've found an issue with GPXSee running on a domain network with folder redirection.
Looking to potentially use this, as I've prior experience at home.
Issue arises on 64 bit Windows 7, 8,1 and also 10.
Event ID 1000 logged in Application Event log on Windows. Error text as follows:

Faulting application name: GPXSee.exe, version: 7.8.0.0, time stamp: 0x5ceef411
Faulting module name: Qt5Core.dll, version: 5.11.1.0, time stamp: 0x5b577d53
Exception code: 0xc0000005
Fault offset: 0x00000000001de07a
Faulting process id: 0xd14
Faulting application start time: 0x01d51d3a75a7a773
Faulting application path: C:\Program Files\GPXSee\GPXSee.exe
Faulting module path: C:\Program Files\GPXSee\Qt5Core.dll
Report Id: b49148b5-892d-11e9-88d6-00155d234401

Works fine when logged on with a local rather than Domain account.
Regards, Sam

**Comment by samwhite59** [comment]
Ok thanks. It did work in an earlier version, but I can't find any old installers to test, upgrading to the latest version broke the software. QT is now up to version 5.12, maybe that update would help?
Happy to test old versions to see when it stopped working.

**Comment by tumic0** [comment]
Well, there is usually an older version of GPXSee available on Sourceforge, but I'm pretty sure that you will get the same result with it (there are no significant changes and the Qt version is the same). I have no idea where to get older installers - I do not have them either.

You may try the automatic [Appveyor](https://ci.appveyor.com/project/tumic0/gpxsee) builds, the have a slightly different Qt version. But maybe running GPXSee in windbg on your system could help to know what is going on as the problem may be some DLL loading issue from what I have found through Google.
