### ISSUE TITLE
Windows 7: The application was unable to start correctly

### ISSUE THREAD

**Issue by fortemezzo** [tumic0/GPXSee#214]
Fresh install on Windows 7, I get an application error:

The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by tumic0** [comment]
This error usually means some problem with loading the required DLLs. But like in case of #212, there is nothing I can tell more about it unless you provide more info. Try running [Dependency walker](http://www.dependencywalker.com) on your GPXSee installation or run it in WinDbg to get more info.

**Comment by tumic0** [comment]
Another common situation that may be the root cause of your problem is that some other application also using Qt modified the PATH so, that its Qt libs are loaded before the Qt libs distributed with GPXSee and their versions/CPU type (32b versus 64bit) collide.

**Comment by fortemezzo** [comment]
I emptied my PATH and started GPXSee and it complained about missing msvcp140.dll. Copied it from somewhere and got the original error. Copied from somewhere else (Dropbox) and it was still missing vcruntime140.dll. Copied that as well and now it works. Also with the normal PATH setting. Maybe it's an option to add these dlls to the installation?

Thanks for the help. Also, the app is awesome!

**Comment by tumic0** [comment]
Those DLLs are part of the MSVC runtime which is part of the GPXSee installer. The MSVC runtime should be automatically installed during GPXSee install if not already installed. Maybe you do not have it installed and the detection fails. This may be for example due to a not-fully-successful uninstall of MSVC in the past on your system.

**Comment by fortemezzo** [comment]
Not sure. I do remember the installer taking very long to install the runtime, but it finished, so all seemed ok. But it works now, so all's good. :-)
