### ISSUE TITLE
Display problem with MVT vector tiles

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#216]
[QtPBFImagePlugin README](https://raw.githubusercontent.com/tumic0/QtPBFImagePlugin/master/README.md) claims that MVT format is supported along with PBF:
> QtPBFImagePlugin is a Qt image plugin that enables applications capable of displaying raster MBTiles maps or raster XYZ online maps to also display **PBF(MVT)** vector tiles without (almost, see usage) any application modifications.

(Well, MVT and PBF is actually the same format here.)

### Steps to reproduce
Using [tilezen/vector-datasource](https://github.com/tilezen/vector-datasource):
```sh
$ cat << EOF > ~/.local/share/gpxsee/maps/Tilezen.xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4">
  <name>Tilezen</name>
  <url>https://tile.nextzen.org/tilezen/vector/v1/512/all/$z/$x/$y.mvt?api_key=my-api-key</url>
  <tile type="vector"/>
  <zoom max="16"/>
  <copyright>© Nextzen © OpenStreetMap contributors</copyright>
</map>
EOF
$ curl -o ~/.local/share/gpxsee/style/style.json https://raw.githubusercontent.com/der-stefan/OpenTopoMap/master/vector/opentopomap.json
```

### Actual behaviour
Tilezen map:
![scr2](https://user-images.githubusercontent.com/688044/60335981-cd08b980-99a7-11e9-961e-8b72dae7cca2.jpg)

### Expected behaviour
[MapTiler](https://raw.githubusercontent.com/tumic0/GPXSee-maps/master/World/MapTiler.tpl) map:
![scr1](https://user-images.githubusercontent.com/688044/60335990-d2fe9a80-99a7-11e9-9e66-afeb15d6ccd3.jpg)

### Configuration
GPXSee: 7.9
QtPBFImagePlugin: 1.4

**Comment by tumic0** [comment]
Tilezen PBF(MVT) tiles have a different layer scheme than OpenMapTiles so you need a different style for them. There are not much such styles out there, but some do [exist](https://github.com/apollo-mapping/ap-tilezen-mapbox-styles/blob/master/src/styles/apollo-bright.json).

**Comment by sikmir** [comment]
Thanks for pointing out! That's what I need.
Using [apollo-bright-detailed](https://github.com/apollo-mapping/ap-tilezen-mapbox-styles/blob/master/src/styles/apollo-bright-detailed.json) style:
![scr3](https://user-images.githubusercontent.com/688044/60371961-a4161200-9a03-11e9-9ff3-c06b68eba7fd.jpg)
One issue is that some string labels are truncated.

**Comment by tumic0** [comment]
I guess that the PBF features do not have unique IDs, that's why you get the truncated labels. But even with unique IDs (true for OpenMapTiles >= v3.7) you will get some truncated labels due to the usage of fuzzy text bounding boxes (see [textpointitem.cpp](https://github.com/tumic0/QtPBFImagePlugin/blob/master/src/textpointitem.cpp) for details) because of performance reasons.
