### ISSUE TITLE
[request] offline vector maps

### ISSUE THREAD

**Issue by halftux** [tumic0/GPXSee#22]
Thank you very much for your offline maps support update.
Could it be also doable to have vector maps as offline maps?
It is not so important but could be a nice feature.

Maps:
http://www.openandromaps.org/en/
Library:
https://github.com/shentok/libqmapsforge

Keep up the good work. Your application is very nice.

**Comment by tumic0** [comment]
Well, there is some more map sources enhancements planned, but "yet another OpenStreet map based" maps will have the lowest priority, if any. The goal is rather to add support for map sources, that are not based on OpenStreet maps to achieve bigger map sources variety. So after adding the missing ozf2 support, GeoTIFF will most likely take a turn.
