### ISSUE TITLE
Read NMEA without checksum

### ISSUE THREAD

**Issue by Vascom** [tumic0/GPXSee#220]
Could you please add ability to load nmea files without checksum?
I want simply modify my nmea files and not compute new checksum. Now I need to convert it to gpx format with gpsbabel.

**Comment by tumic0** [comment]
GPXSee does not check the checksum value, it only checks, that there is a checksum (to verify, that the sentence is complete). So if you modify the sentences, you can simply append for example `*00` to every sentence and GPXSee will use the sentence.

**Comment by Vascom** [comment]
Thanks.
