### ISSUE TITLE
zoom in / zoom out icon

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#221]
Hello,

it will be nice to add 2 icons for zoom in / zoom out

Kind regards

**Comment by tumic0** [comment]
I really don't think that those buttons are necessary. Zooming with the mouse wheel (or two fingers on touchpads) is so natural those days that I doubt there is someone who would not be able to zoom... In addition you can use the keyboard or the mouse double clicks which should be sufficient for everyone :-).
