### ISSUE TITLE
Zoom fit

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#223]
Hello,

Following #221 (but a bit harder), a zoom fit function could be a nice feature to have.

By default clicking on zoom fit icon should zoom and pan to be able to see every opened tracks.

A contextual menu (contextual to a given track) could also be added to zoom fit a given opened track.

Kind regards

**Comment by tumic0** [comment]
Te reload button (also) does a zoom fit. If you do not have several megabytes of data loaded, the difference between a reload and a zoom fit will be hardly noticeable. So from my point of view (my use cases), there is no need to add a separate button for that.

Zoom to a particular track is something I have never missed, so my motivation for that is very low. In fact I think that "wasting" a context menu for such a task would even make the UX overcomplicated.

**Comment by scls19fr** [comment]
A contextual menu could provide several actions on a specific track (zoom fit this track... but also close this track)

**Comment by tumic0** [comment]
When there is a context menu on the objects, adding this option will definitely become a topic. I know there has to be done some work on the UI/UX of the object properties/actions, but the priority is definitely #142 (and the related links problem).
