### ISSUE TITLE
Calculate and plot ground altitude

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#224]
Hello,

it will be great to be able to calculate and plot ground altitude.
XCSoar provides .xcm files https://www.xcsoar.org/download/data.html (Terrain / Topography).

Kind regards

**Comment by scls19fr** [comment]
An other solution can be to use Google Web Services Elevation API
https://developers.google.com/maps/documentation/elevation/intro

An open alternative may be to use https://open-elevation.com/
Source : https://wiki.openstreetmap.org/wiki/Open-Elevation

**Comment by tumic0** [comment]
DEM data (SRTM HGT) is already supported by GPXSee and online elevation services are discussed in #210 . XCM files would most probably qualify as offline maps in GPXSee, but as those maps are quiet aero-specific and there is no format documentation available it is very unlikely, that I will add support to GPXSee for them...

**Comment by tumic0** [comment]
In the Options under Data->Filtering
