### ISSUE TITLE
Broken CSV files support

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#226]
### Steps to reproduce
```bash
$ curl https://nakarte.me/geocachingSu/geocaching_su2.json | gzip -d | \
  jq -r '.[]|[.[3],.[2],.[0]]|@csv' | \
  sed 's/""/"/g;s/,"/,/;s/"$//' > ~/.local/share/gpxsee/POI/geocaching.su.csv
```

### Actual behaviour
```bash
$ gpxsee
/home/sikmir/.local/share/gpxsee/POI/geocaching.su.csv:8: Parse error
$ sed '8q;d' ~/.local/share/gpxsee/POI/geocaching.su.csv 
37.0775333,55.7827333,"Голодная" пирамида
```

### Expected behaviour
It worked with GPXSee <= 7.11.

### Configuration
GPXSee Version: 7.12

**Comment by tumic0** [comment]
The CSV parser has changed in 7.12, now it uses a grammar as defined in [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt) instead of simple delimiter based field splitting. So fields with quotes must be now escaped in quoted fields:

`37.0775333,55.7827333,"""Голодная"" пирамида"`
