### ISSUE TITLE
Statistics - display time start of flight

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#228]
Hello,

Maybe statistics should display time of first record to know exactly when a flight occurred.

Kind regards

PS : related #227

**Comment by scls19fr** [comment]
Not sure however how this should work when several tracks are opened.

**Comment by tumic0** [comment]
The start time is in the tooltip of each track. In the statistics there is the long date format which would make the entry to long to display nice, especially when there are multiple tracks and a date range is displayed.
