### ISSUE TITLE
Not showing elevation of FIT file

### ISSUE THREAD

**Issue by evazzoler** [tumic0/GPXSee#231]
On GPXSee Version 7.13 (x86_64, Qt 5.5.1) I open a FIT file conaining Elevation, Temperature (from Tempe), and HR. It was produced by a Garmin Oregon 700.
The graph reports Elevation, Speed, Heart rate and Temperature, so I suppose Elevation data are found by GPXSee.

The Elevation graph is blank.

Both on the GPS Unit and on Garmin Connect I can see elevation graph.
If I export a GPX file from the GPS Unit I can see elevation graph on GPXSee.
On Settings->Options->Data->Sources I have "GPS Data" selected on the "Elevation" section.

**Comment by tumic0** [comment]
Please attach the FIT file here, otherwise there is nothing I can do about it.

**Comment by evazzoler** [comment]
> Please attach the FIT file here, otherwise there is nothing I can do about it.

Ops... Forgive me. I was sure to have forgotten someting!
Here is the zipped [sample](https://github.com/tumic0/GPXSee/files/3649432/sample.zip)!
(attaching .fit files is forbidden)

**Comment by tumic0** [comment]
I have analyzed the file and the result is, that there really is no elevation data in it. I don't know what device does the data come from, but for example Garmin's Forerunner 3x watches do not display/log the elevation (Yes, Garmin sells you a "GPS" device with only two dimensions in 2019, this is no joke...)

There is however a bug in GPXSee 7.13 that displays the elevation tab when it shouldn't be displayed. This was fixed in fa08c0dbea8f12099a75c70b3d7d886719a9293c and c4fd82e5a0ba5c256e58f1732cb18ddfda8d80f4.

**Comment by tumic0** [comment]
It is obvious but just to be sure - the elevation displayed by Garmin Connect for this file is taken from a DEM database during the "synchronization" (this is why Garmin Connect does not work without internet connection). In GPXSee you can do the same by providing the corresponding DEM HGT file (N46E012.hgt in case of the sample file).

**Comment by evazzoler** [comment]
My friend, your analysis is totally wrong.
The file comes from a Oregon 700 (as I wrote since the beginning) and it has a barometric altimeter. Activity shows elevation on the device interface, device has no DEM on board.
The final proof is that opening the fit file with myTourbook, the elevation is correctly shown (see attachment)
![mytb](https://user-images.githubusercontent.com/9479876/65823331-68822280-e254-11e9-88a1-d1f7b3c2952c.png)
.
So, please, reopen this issue.

**Comment by tumic0** [comment]
You are right, there really is altitude in the file but a new, "enhanced altitude" field is used for it. I have added support for such entries in e28e69b248f28a7ef99266f88e49c6427f6a3e99.

**Comment by evazzoler** [comment]
Great! This is a good news!
Thank you so much for the superfast support!
