### ISSUE TITLE
GPXSee Crash loading offline Garmin map

### ISSUE THREAD

**Issue by evazzoler** [tumic0/GPXSee#232]
I'm trying to load a local map, Gramin format (gmapsupp.img) downloaded from [here](https://openmtbmap.org/download/gmapsupp/) and working on a garmin device, on a Linux Ubuntu 16.04 LTS machine.
I get a segmentation error (see attached [core dump](https://github.com/tumic0/GPXSee/files/3669669/core-gpxsee.5902.thinkpad-t460.1569833058.zip)).

I also tried with a small 9MB nautical chart and the result is the same, so I suppose is not a filesize/memory problem.

Maybe the map is not a non-NT, but should I receive a message if I try to load a wrong map.

**Comment by sikmir** [comment]
To be able to analyze core dump the executable is required as well.

**Comment by evazzoler** [comment]
> https://openmtbmap.org/download/gmapsupp:
> "Sorry the downloads on this page are only for OpenMTBMap members"

In the following line you can read "`To Try Out you can download the map of Austria (and contourlines) for free! All other maps are only for members.`" 
So you can download Austrian map for free.

> > I get a segmentation error (see attached core dump).
> 
> To be able to analyze core dump the executable is required as well.

It is the current version. I attach it for better convenience.
[gpxsee.zip](https://github.com/tumic0/GPXSee/files/3670361/gpxsee.zip)


> 
> P.S.: I use free desktop version from https://openmtbmap.org/download/odbl/, and convert it into `gmapsupp.img` myself using `mkgmap`, and it works with GPXSee for me.

**Comment by sikmir** [comment]
> So you can download Austrian map for free.

Oh, I see.

> It is the current version. I attach it for better convenience.

Well, I've tried to run your binary with downloaded gmapsupp.img of Austria and everything works for me, no crash.

**Comment by evazzoler** [comment]
> > So you can download Austrian map for free.
> 
> Oh, I see.
> 
> > It is the current version. I attach it for better convenience.
> 
> Well, I've tried to run your binary with downloaded gmapsupp.img of Austria and everything works for me, no crash.

Ok, so it is definitely a Issue of my environment. Wanna know ho to fix it... :-(

I choosed the austrian free img file (but I don't really care Austria) because it is "precompiled" and I was sure it is correctly converted. Converting a free mapset with mkgmap I would introduce another variable: am I sure that I used the correct parameters with mkgmap?
Of course I initially tried to convert Germany by myself, but I'm not sure if I have to pass special parameters to mkgmap. Please can you tell me what parameters you use?

Thank you for the support, I will close the issue.

**Comment by evazzoler** [comment]
Perhaps this is a problem depending on the user environment and it was not reproduced on other's PC.
I close the issue and try to investigate the problem by myself.

**Comment by sikmir** [comment]
> Please can you tell me what parameters you use?

What I do is:
```sh
TMP=`mktemp`
wget -O $TMP https://ftp.gwdg.de/pub/misc/openstreetmap/openmtbmap/odbl/continents/mtbrussia.exe
7z e -o${TMP}_ $TMP
cd ${TMP}_
FID=`ls -x 6*.img | cut -c1-4 | head -n1`
TYPE="tradru.TYP"
mkgmap --show-profiles=1 --product-id=1 --family-id=$FID --index --gmapsupp 6*.img $TYPE
```

Adjust parameters for Germany (TYP file, img files).

**Comment by evazzoler** [comment]
Perfect, thank you!
No way: segmentation fault...
On a Windows VM all is perfect.
I'll keep investigating.

**Comment by evazzoler** [comment]
OpenGL caused the issue!
Fortunately it is possible to disable inside the app.
I don't know if it is a issue of mine or a general bug.

**Comment by sikmir** [comment]
> Fortunately it is possible to disable inside the app.

Just in case, you can disable OpenGL before starting GPXSee as well:
```sh
$ crudini --set ~/.config/gpxsee/gpxsee.conf Options useOpenGL false
```

**Comment by tumic0** [comment]
QT is full of OpenGL related bugs, [some](https://bugreports.qt.io/browse/QTBUG-39781) of them have even made it to a "feature"... This is why OpenGL is not enabled by default and should be used only when needed (rendering of "big data", i.e. hundreds kilometers of tracks). Additionally, your QT version in Ubuntu 16.04 is (as usual on Debian/Ubuntu systems...) quiet archaic, so the bug may be already fixed.
