### ISSUE TITLE
Mac Download Under Catalina

### ISSUE THREAD

**Issue by PsamatheM** [tumic0/GPXSee#234]
Download dmg for macOS from http://www.gpxsee.org, the .app wont run. OS complains as per attached screenshot.
<img width="420" alt="Screenshot 2019-10-09 at 13 32 09" src="https://user-images.githubusercontent.com/56350868/66482019-f3a3b980-ea99-11e9-9852-d2ca5fed9b5a.png">

**Comment by tumic0** [comment]
I hope the usual open with the right click and selecting "Open" from the context menu still works under Catalina and the change is only in the message which shall scary the user even more not to use SW that does not generate Apple a profit...

Technically the IMG of course can be scanned for malware. The App is also digitally signed with the certificate that is available here at Github, so everyone can check that the application comes from the same person that "owns" the source code repository. And of course the source code is publicly available so everyone can check it (although there is IMHO now way how to prove that the binary comes from the sources - here you have either to trust me or build the application yourself).

**Comment by PsamatheM** [comment]
I was not intending to question there were any issues with the .app but to alert devs to the changes in Catalina (e.g. imminent changes to Gatekeeper that will require notarisation for all apps to run on Catalina (i.e. a hard block). The warning above seems to be a 1st step, the complete "notarisation" requirement having been slipped from the original Catalina launch for a rumoured few weeks/month(s) (I'm unsure as to how long it has slipped).

I have found the same with other non-notarised apps. I'll double check the context menu open route and report back but I suspect it will be a very short term fix before notarisation becomes required.

**Comment by tumic0** [comment]
Gatekeeper (in the default configuration) did not allow the first open of GPXSee even before Catalina (as GPXSee does not use a paid developer certificate) and you had to open it from the context menu, so there is (if it still works) no change in Catalina. What has changed is the message which is now chosen to frighten the users as much as possible.

Please report if GPXSee still can be opened the first time from the context menu so I can close the issue.

**Comment by PsamatheM** [comment]
Can be opened.
But be aware hat there are major changes requiring app notarisation coming soon (within months) where I understand context menus will be no good. The change was going to happen on release of Catalina but was slipped a short time as I heard not enough devs had sent their apps through the process. e.g. [https://developer.apple.com/news/?id=09032019a](https://developer.apple.com/news/?id=09032019a)

**Comment by tumic0** [comment]
From what I read Apple did not (yet...) announced that they will ban software that does not generate them profit (= not signed with the paid developer id certificate) from their systems, so I'm closing this for now. Reopen if Apple goes completely mad and really bans such SW.
