### ISSUE TITLE
Window position and size

### ISSUE THREAD

**Issue by rcleeny** [tumic0/GPXSee#235]
I have a laptop running Windows 10. It had a second monitor where gpxsee would open. I have lost the HDMI port and now the second monitor. gpxsee still tries to open on the second monitor and is not visible. How do I reset the position/size information. I tried reinstalling gpxsee but that did not help.

**Comment by tumic0** [comment]
GPXSee uses the standard [QSettings](https://doc.qt.io/qt-5/qsettings.html) class to store the configuration. On Windows the configuration is in the Windows registry under the following path:

`HKEY_CURRENT_USER\Software\GPXSee\GPXSee`

**Comment by rcleeny** [comment]
Thank you! 
I guessed it was in the registry but could not find it. Changed the data under GPXSee/Window -- pos and size. Now I can see the window again.
