### ISSUE TITLE
Invalid time line: nnnnn

### ISSUE THREAD

**Issue by SpeedHazard** [tumic0/GPXSee#236]
when I try to open a GPX file, show me this error.

invalid time line: xxxxx

this is after the mid night.

can you check please?

I updated to 7.15and same issue.

tks.

I splited the file and the first half worked.....  not the second.

[gpx.zip](https://github.com/tumic0/GPXSee/files/3755439/gpx.zip)

**Comment by tumic0** [comment]
I can not reproduce the issue, so you have to provide some more info. What is the platform (Windows, Mac, Linux)? What is the Qt version (if the platform is Linux). What is your locale setting?
