### ISSUE TITLE
Gpxsee 7.15 doesn't show the whole gpx file (attached)

### ISSUE THREAD

**Issue by ShelleyLake** [tumic0/GPXSee#237]
Gpxsee 7.15 doesn't show the whole gpx file.

This is how the gpx file looks like in Gpxsee:
![image](https://user-images.githubusercontent.com/49189962/67396945-c3374180-f5a8-11e9-8362-4415659e6e71.png)

This is how the same gpx file looks like at [gpsvisualizer.com](https://www.gpsvisualizer.com/display/20191023062501-11036-map.html):
![image](https://user-images.githubusercontent.com/49189962/67397362-64be9300-f5a9-11e9-85b4-623b7ba8b5ba.png)

[GraphHopper.zip](https://github.com/tumic0/GPXSee/files/3762528/GraphHopper.zip)

**Comment by tumic0** [comment]
The origin of the problem are the broken timestamps in the GPX file - only a few trackpoints contain them. GPXSee works fine if all trackpoints have a timestamp or if none has a timestamp. Mixed cases fall into codepaths where GPXSee tries to workaround broken (= without timestamps) entries, but the whole process is pure shamanism... To see the whole track you can disable outlier elimination, but I would rather vote for fixing the data or their generator.

However I will have a look at the logic as the data triggers more "ugly things" , it even lets the program assert in debug mode...

**Comment by ShelleyLake** [comment]
Thank you for the explanation.
I cannot fix the source of the problem, since this data is generated from this service [https://graphhopper.com/maps/](https://graphhopper.com/maps/).

Do you know a tool to "interpolate" missing timestamps (probably GPSBABEL can do that but I don't know how to tell it...) ?

**Comment by tumic0** [comment]
> Do you know a tool to "interpolate" missing timestamps (probably GPSBABEL can do that but I don't know how to tell it...) ?

Well, maybe some of the "digital EPO" tools could support such an operation, but generally this makes not much sense. I would rather use a simple sed command and remove all the remaining time entries as they do not provide any meaningful info anyway...

(Please let the issue open so it reminds me to do a better error handling for such broken files)

**Comment by tumic0** [comment]
Fixed in 7.16
