### ISSUE TITLE
openaip airport cup file can't be opened with GPXSee

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#238]
Hello,

http://www.openaip.net/ is a nice free database but unfortunately GPXSee can't open cup file from this source.

Here is an example (just for testing purpose)
https://gist.github.com/scls19fr/cc0291efc54eef25088367f27698f123

After removing comment GPXSee can open perfectly that file...
so I think it will be nice if GPXSee could directly ignore head comments

Kind regards

**Comment by scls19fr** [comment]
According https://www.openaip.net/downloads

> Currently CUP files do not allow comments. Nevertheless openAIP *.cup files will contain the license agreement as comment. If you want to use openAIP *.cup files you will have to remove the license agreement from the file yourself. After that the files can be used in StrePla or SeeYou as usual.

but maybe GPXSee could be better than StrePla or SeeYou (at least for this use case)

**Comment by tumic0** [comment]
Sorry, but I really do not want to support someone crippling a documented format (which has no comments).
