### ISSUE TITLE
Please help me how to implement offline maps

### ISSUE THREAD

**Issue by gurpartap007** [tumic0/GPXSee#24]
Please point me in right direction what should I do or what resources should I follow to implement offline maps. I downloaded .osm files for my region.I also downloaded some .gpx files but they are for tagging.

**Comment by tumic0** [comment]
Use MOBAC (http://mobac.sourceforge.net). When creating an Atlas, select "TrekBuddy tared atlas" or "TrekBuddy untared atlas" as the format. If a small map without layers is enough, you may also choose "OziExplorer (PNG & MAP).
