### ISSUE TITLE
Incomplete trace display in some gpx file

### ISSUE THREAD

**Issue by Bombar1no** [tumic0/GPXSee#242]
Hi,
When I load some tracks instead of showing them in detail, the track displays several straight lines.
I attach one..
I'm using version 7.17 x64
Thanks for suggestions
[Rifugio_elisa.zip](https://github.com/tumic0/GPXSee/files/3800681/Rifugio_elisa.zip)

**Comment by tumic0** [comment]
I guess you have changed the default minimal speed(0.5km/h) in the "pause detection" settings. If you set it too high, the stop points will dissapear and you get a plot like you describe. With the default settings I get a plot which looks ok for me:

![Snímek obrazovky 2019-11-02 v 18 22 10](https://user-images.githubusercontent.com/11480505/68074717-7d475e00-fd9e-11e9-96c7-47202341d01d.png)

**Comment by tumic0** [comment]
Sorry for the mystification - the default "pause speed" is 0.5m/s (1.8km/h), not 0.5km/h... So you really get a "broken" plot with the default values. You have to lower the pause speed to something < 1km/h in the preferences for this particular track to get displayed correctly (like on my screenshot).

Looks like the defaults are a little bit too high for Alpine hiking...

**Comment by sikmir** [comment]
> Looks like the defaults are a little bit too high for Alpine hiking...

@tumic0 +1, I was really confused by this default (1.8 km/h) from the very beginning of using GPXSee. So, I set it to 0.5 km/h since then. IMO 1.8 km/h fits only for bike activity, almost all my hiking / backcountry skiing tracks (even not Alpine) look strange with such default, as far as it goes on mostly in difficult terrain.

**Comment by tumic0** [comment]
Well most of my data are from "faster" sports and many GPS devices can create quiet fast moves than when still standing, that's the origin of the default value. But after I saw the really broken alpine track, there is clear the default value has to be set lower. The question is only to what value...

**Comment by sikmir** [comment]
It's not a problem for me to configure that value once to proper value, but the real problem when you need to switch often between bike / hiking tracks. For bike tracks I still prefer 1.8 km/h.

**Comment by tumic0** [comment]
Added an automatic pause speed selection as the default in 258a9b0201b23f517637ace0880dfbd2ea8fd329.
