### ISSUE TITLE
Average (moving) speed is wrong

### ISSUE THREAD

**Issue by fu-hsi** [tumic0/GPXSee#243]
We can change thresholds in settings and nothing changes on the graph, even after reload file.
It seems like the application doesn't detect stops at all.

**Comment by tumic0** [comment]
Works fine for me. You have to be a little bit more specific:

1. Post the track
2. Give the EXACT parameter names/values you are changing

**Comment by fu-hsi** [comment]
Whatever I type:

- min. speed
- min. duration time

nothing changes on the graph.
I always see fixed average calculated based on total time, not moving time.

Screenshot:
https://zapodaj.net/27faaaf92fd4d.png.html

**Comment by fu-hsi** [comment]
I checked now another activity, and works... :|
Very small differences, but differs.

**Comment by tumic0** [comment]
I have improved the pause detection algorithm a little bit in 15af82ee49d8c4129e44f6b081e0c1ae035142e8. Please have a try and report, if it behaves more like you expect.

**Comment by fu-hsi** [comment]
I checked, but as I said, another activities works fine, so I guess, from only one I had problem.
Thanks for help :)
