### ISSUE TITLE
Add man file (for linux distributions) and verbose output.

### ISSUE THREAD

**Issue by Hordeking** [tumic0/GPXSee#245]
Related points.
At least as far as I can tell, there's no man files, and -h --help --version --verbose don't do anything when invoked from the command line. These would be capital (I'm requesting a man page).

The verbose option would be especially nice, since in trying to troubleshoot things, I would like to potentially be able to see details of fetches both when they're working and when they have errors, but maybe other issues. If this is output to stdout or strerr, they could also be redirected as needed. (I'm requesting verbose modes, along with some other standard command line options)

**Comment by tumic0** [comment]
Well, the command line invocation of GPXSee is quiet simple:
`gpxsee [FILES...]`
That's it. So I don't think that a manpage for that is really necessary, GPXSee is not _grep_ or _find_. There could be of course additionally some info that is available on the GPXSee [documentation page](http://www.gpxsee.org/doc.html) in the manpage, but I'm not a big fan of such duplication.

Regarding the verbose modes - for network traffic diagnostics there is Wireshark which provides much more info than a debug output would ever do. What else are you missing? GPXSee prints some additional debug stuff to stdout in case of problems and I'm fine with extending this if there is a situation where you would expect some more additional info about a problem. But I don't want to spend time on creating some "debug mode" that would print out everything one may find useful some day. For that purpose, there is the source code and the debug `<<` operators for all the interesting clases.

**Comment by sikmir** [comment]
> Regarding the verbose modes - for network traffic diagnostics there is Wireshark which provides much more info than a debug output would ever do.

Just my 2 cents, there is a much more simple way I use for it:
```sh
$ docker run --rm -it -p 9090:8080 mitmproxy/mitmproxy
$ export http_proxy http://localhost:9090/
$ export https_proxy http://localhost:9090/
$ gpxsee
```
That's all.
