### ISSUE TITLE
Wrong duration is displayed when track segments are not contiguous

### ISSUE THREAD

**Issue by alranel** [tumic0/GPXSee#246]
When a file is loaded that contains multiple track segments having a pause between them, the total duration displayed does not take those pauses into account.

For example, [this file](https://github.com/tumic0/GPXSee/files/3854607/SR_2019-09-08.145259_TEST.gpx.txt) has a ~2.5 hours pause between its two track segments, but it is rendered this way:

![Screenshot 2019-11-16 at 20 23 15](https://user-images.githubusercontent.com/594957/68998209-c1168900-08af-11ea-9ba9-4aa25a75bfb1.png)

Notice the `28:15` duration in the status bar: this is a bit awkward in terms of UX because one would expect the duration to be the total time of the loaded track.

This is probably related to #35 as the pause is also not rendered in the time graph.

(By the way, thank you for such a great software!)

**Comment by tumic0** [comment]
Well, the logic behind the graphs is based on the assumption, that only the time of the record matters. Because that's the purpose of segments - to not include moves that are not part of the activity. If you want the whole activity, do not split the record into segments.
