### ISSUE TITLE
Anonymizing route track

### ISSUE THREAD

**Issue by fu-hsi** [tumic0/GPXSee#248]
Hi.
Can you implement option for remove "+" sign from start track or add privacy zone like this:
https://support.strava.com/hc/en-us/articles/115000173384-Privacy-Zones.
After exporting track to pdf, I don't wanna show exactly my start and end point.

**Comment by tumic0** [comment]
I'm sorry, but this is really something out of scope of GPXSee. Use some other software (or do it by hand) that is designed to modify the tracks for such a task.

**Comment by fu-hsi** [comment]
Just remove the red icon from the beginning of the route (configurable option).

**Comment by tumic0** [comment]
That's already implemented (Graph->Show path markers), but that won't help you in terms of anonymization...

**Comment by fu-hsi** [comment]
Why I haven't seen it before :)
It's enough. Thanks.
