### ISSUE TITLE
Pause detection does not work since 7.18

### ISSUE THREAD

**Issue by joerg4github** [tumic0/GPXSee#250]
Hello,

it looks like the pause detection does not work in Version 7.18. I have some garmin .fit files and gpx files where are a brake from around 30 minutes is included.
Up to the version 7.17 the brake was detected.
In the version 7.18 both options of "pause detection" do not show the brake.  The "time" and "moving time" are equal.

**Comment by tumic0** [comment]
Please provide the files so I can analyze them.

**Comment by joerg4github** [comment]
Here is a .fit file, it is a unmodified file from a Garmin edge 810 Device. I attached the file as a zip-archiv, cause .fit files are not supported for upload.
GPXSee 7.15 (Fedora 29) detect a pause, also GPXSee 7.17 (Windows).
Time: 05:34:18
Moving time: 05:07:03

Version 7.18 show only a different of some seconds between "Time" and "Moving Time".

I have testet it on Debian and Windows.

[2018-11-16-10-06-38.zip](https://github.com/tumic0/GPXSee/files/3890285/2018-11-16-10-06-38.zip)
