### ISSUE TITLE
GPX track not shown

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#256]
### Steps to reproduce
The problematic track is [Chukotka 2019](https://www.gpsies.com/map.do?fileId=dinbxfdsetwbbstp):
```sh
$ curl 'https://www.gpsies.com/download.do' \
    --data 'fileId=dinbxfdsetwbbstp&dataType=1' > chukotka2019.gpx
$ gpxsee chukotka2019.gpx
```
### Actual behaviour
Nothing is shown on the map.
### Expected behaviour
Let's merge all segments in the track:
```sh
$ gpsbabel -t \
    -i gpx -f chukotka2019.gpx \
    -x track,seg2trk,pack \
    -o gpx -F chukotka2019_fixed.gpx
```
![scr1](https://user-images.githubusercontent.com/688044/69791451-a01a3600-11d5-11ea-81e3-af3e7ab42880.jpg)
### RCA
The track is a bit strange (but still valid!) - every trackpoint wrapped into segment:
```sh
$ sed -n 40,51p chukotka2019.gpx 
    <trkseg>
      <trkpt lat="69.70463530" lon="170.2846490">
        <ele>2.0000000</ele>
        <time>2019-08-01T09:34:11Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="69.70460410" lon="170.2839200">
        <ele>2.0000000</ele>
        <time>2019-08-01T09:34:55Z</time>
      </trkpt>
    </trkseg>
```

**Comment by tumic0** [comment]
Well, the minimal segment size is 2 in GPXSee. The GPX syntax may allow a single trackpoint in the segment, but semantically this makes not much sense as you can not display the segment using a path(line). Many other properties like the distance/relative time also make not much sense in a case of a single trackpoint. Also note, that the representation of consecutive one-point-segments would be a set of not interconnected points in the GPXSee segment handling logic which would be more a mess than a useful information in many cases...

An option to ignore segments, which would be a "nice to have" anyway (some people have segments in their data but would not like to display them as such, see #246 for example) would help here.

**Comment by tumic0** [comment]
Closing - one can not support all nonsense data representations that someone can imagine. For the "ignore segments" option open alternatively a new issue.
