### ISSUE TITLE
Exporting/printing PDF high resolution results in incomplete map in the output

### ISSUE THREAD

**Issue by TheOnlyMrVideo** [tumic0/GPXSee#258]
Fedora 27.
When the output is set to High-Resolution and then exporting to PDF, at 600dpi, the track is complete in the output, but the map image is not. The only maps that worked are the two USGS maps (didn't use the Antartica map). Sample uploaded.
[exportgpx.pdf](https://github.com/tumic0/GPXSee/files/3910478/exportgpx.pdf)

**Comment by TheOnlyMrVideo** [comment]
I kinda lied. I just had a USGS topo map fail to completely fill in the map. But, when I ran it again, it did.

**Comment by TheOnlyMrVideo** [comment]
Some more info. Here are some of the error messages that show up when exporting to PDF:
Error downloading file: https://a.tile.opentopomap.org/6/38/21.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/22.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/23.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/24.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/25.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/26.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/27.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/28.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/29.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/30.png: Operation canceled
Error downloading file: https://a.tile.opentopomap.org/6/38/31.png: Operation canceled
I can manually put any of the links into a browser and the image will show up.

**Comment by tumic0** [comment]
You can increase the connection timeout in the settings, but generally the global public servers won't be much willing to serve a that huge number of tiles at once. Use a local map source (MBTiles, local tiles map) if you wan't a PDF with a high resolution.
