### ISSUE TITLE
Maps update

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#261]
1. https://github.com/tumic0/GPXSee/blob/fdeb24a196edd6b8477242f65f26faae7368d730/pkg/maps/4UMaps.xml#L4

Redirect chain:
```sh
$ curl -v -L https://4umaps.com/6/39/25.png 2>&1 | egrep "^> (Host:|GET)"
> GET /6/39/25.png HTTP/1.1
> Host: 4umaps.com
> GET /6/39/25.png HTTP/1.1
> Host: www.4umaps.com
> GET /6/39/25.png HTTP/2
> Host: tileserver.4umaps.com
```
2. https://github.com/tumic0/GPXSee/blob/fdeb24a196edd6b8477242f65f26faae7368d730/pkg/maps/4UMaps.xml#L7

https://www.4umaps.com/terms-of-use-copyright.aspx:
> © 4UMaps.com
3. https://github.com/tumic0/GPXSee/blob/fdeb24a196edd6b8477242f65f26faae7368d730/pkg/maps/OpenStreetMap.xml#L4

Switch to https to take advantage of HTTP/2:
```sh
$ curl -v http://tile.openstreetmap.org/6/39/25.png 2>&1 | grep "GET\|200"
> GET /6/39/25.png HTTP/1.1
< HTTP/1.1 200 OK
$ curl -v https://tile.openstreetmap.org/6/39/25.png 2>&1 | grep "GET\|200"
> GET /6/39/25.png HTTP/2
< HTTP/2 200
```

**Comment by tumic0** [comment]
I have switched the OpenStreetMap to HTTPS, but I'm not sure about the 4umaps. They use the same URL as GPXSee uses in their web viewer (Leaflet), so this may indicate that the redirected URL may not be "permanent", i.e. it may change in the future. And I rather choose a unneeded redirect than the possibility the map will break in the future.

**Comment by sikmir** [comment]
> They use the same URL as GPXSee uses in their web viewer (Leaflet)

Yes, they are not quite consistent here, but documentation ([Add 4UMaps To Your Website](https://www.4umaps.com/embed-4umaps.aspx)) says:
>  By adding the following example code into the text editor:
> 
> [osm_map lat="45.03" lon="4.04" zoom="9" width="100%" height="600" extmap_type="OSM" extmap_name="4UMaps"
> extmap_address="**https://tileserver.4umaps.com/${z}/${x}/${y}.png**" extmap_init="numZoomLevels: 16, transitionEffect: 'resize',
> sphericalMercator: true" type="ext"
> gpx_file="../../../../wp-content/uploads/2015/03/Stage4-Chavanay-AumontAubrac-Camino.txt"
> gpx_colour="red"
> marker="45.41211,4.73756"
> marker_name="mic_blue_cycling_01.png"]

**Comment by tumic0** [comment]
Ok, I have changed it then (I could not find that info on their website).
