### ISSUE TITLE
PDF export error

### ISSUE THREAD

**Issue by Micka3lFR** [tumic0/GPXSee#263]
Hello.
When exporting to PDF, you cannot open this PDF.
Thank you

**Comment by tumic0** [comment]
Works fine for me. You have to at least attach the PDF to the issue for me to be able to do something about it...

**Comment by Micka3lFR** [comment]
Hello

Sorry

**Comment by tumic0** [comment]
This has been already discussed here several times, see #258 or #107. Short answer - use an offline/cached map when producing a PDF with several megabytes of tiles, it won't work on public online servers.

**Comment by Micka3lFR** [comment]
Okay, thank you :) 

Have a good holiday season
