### ISSUE TITLE
License: Oxygen icons not mentioned

### ISSUE THREAD

**Issue by jonasstein** [tumic0/GPXSee#264]
The repository distributes files, with other licenses as mentioned.
For example the Icons.
Are there more?
This is important for distributions.

**Comment by tumic0** [comment]
Everything that is 3rd party is marked as such (with one - grey zone - exception), either in the file header or in a separate license file. So are the Oxygen icons. The list of 3rd party stuff as for now is:

- [Oxygen icons](https://github.com/tumic0/GPXSee/blob/master/icons/GUI/licence.txt)
- [Mapbox Maki icons](https://github.com/tumic0/GPXSee/blob/master/icons/POI/licence.txt)
- [RTree implementation](https://github.com/tumic0/GPXSee/blob/master/src/common/rtree.h)
- Most projection implementations (search for libgeotrans in src/map)

A special case are the projection parameters CSV files, which are a compilation of more sources, but mostly based on the EPSG database (altough the data was not obtained directly from the database but from GDAL which did not have an license exception for it (so those were treated as BSD) at that time). Here it is quiet questionable what the license is and who is the copyright holder as even the EPSG database itself is based on work of various geographic agencies. Or more generally - can someone really own the copyright to a compilation of public geographic constants (computed by geographers that may be 100 years dead)?
