### ISSUE TITLE
dont use _B & _C identifiers

### ISSUE THREAD

**Issue by landryb** [tumic0/GPXSee#266]
(quoting @omoerbeek)
> C99 section 7.1.3 reserves all names starting with an underscore followed by an uppercase or another _

while porting gpxsee to OpenBSD (https://marc.info/?l=openbsd-ports-cvs&m=157976764732555&w=2) i got two build failures, because our ctypes.h has this section:
```
#define _U      0x01
#define _L      0x02
#define _N      0x04
#define _S      0x08
#define _P      0x10
#define _C      0x20
#define _X      0x40
#define _B      0x80
```

and _C & _B conflicts badly with the vars used in `src/map/krovak.h` & `src/map/albersequal.h`
```
../src/map/krovak.h:21:17: error: expected member name or ';' after declaration specifiers
        double _e, _A, _B, _t0, _n, _r0, _phiP;                                                                                                                                                                  
        ~~~~~~         ^      
/usr/include/ctype.h:52:12: note: expanded from macro '_B'                                                                                                                                                       
#define _B      0x80 

../src/map/albersequal.h:28:9: error: expected member name or ';' after declaration specifiers
        double _C;                              
        ~~~~~~ ^              
/usr/include/ctype.h:50:12: note: expanded from macro '_C'        
#define _C      0x20       
```

i've patched out those two in our port, replacing `_C` by `C` in the header & the corresponding cpp file, but can you use meaningful variables or avoid using _x with uppercase letters ? I can do a PR if you prefer, ofc.

Other than that gpxsee works great on OpenBSD :)

**Comment by tumic0** [comment]
Thanks for reporting, I always thought that only two underscores are prohibited...

> can you use meaningful variables

The used names are the most meaningful names as those are the characters used in the projection formulas. The most meaningful transcription of Einstein's famous formula would also be something like:
```c++
double E = m * sqr(c);
`
