### ISSUE TITLE
Question: Will routes be seachable?

### ISSUE THREAD

**Issue by Twoflower2** [tumic0/GPXSee#267]
Hi,

This looks quite nice thanks.

I want to ask a question only and will explain with a use case. Our motorcycle club want to store/catalogue gpx files. These must be searchable say with metadata/tags of Country, province, duration, difficulty etc. It is currently store in folders/directories with some meaningful names but it is a real pain to find a route as more and more routes are added.

Will it be possible to add a feature to your software to help?

Thanks.

**Comment by tumic0** [comment]
This is something completely out of scope of GPXSee, so the answer is no. Sorry.

**Comment by Twoflower2** [comment]
Understand. I guess you not mentioning a cataloguing framework/mechanism for many routes, you don't know of any?
