### ISSUE TITLE
[Request] Possibility to mark two points in graph and calculate acceleration 

### ISSUE THREAD

**Issue by ihemsen** [tumic0/GPXSee#269]
I am doing a project where I record a run and measure the average acceleration between two points in the track. 
GPXSee is almost perfect for this! Add the possibility to mark a second point and indicate speed, time (s), position (in metres) and the average acceleration in m/s2. This could be fun also for people recording the acceleration of their cars, boats etc.

<img width="885" alt="Skjermbilde 2020-02-02 kl  16 12 29" src="https://user-images.githubusercontent.com/60574738/73610740-05761300-45db-11ea-88d8-1f21382087ae.png">

**Comment by tumic0** [comment]
This a little bit too specific and would make the graph UI/UX too complicated, sorry.

**Comment by ihemsen** [comment]
Ok, would it be possible to add the position in metres to the points in addition to time? That would also help.

**Comment by tumic0** [comment]
This could be done, but I have rejected that idea in the past as it leads to a quiet confusing info (especially in case of the elevation graph) and generally it takes too much space.

**Comment by ihemsen** [comment]
I see that metres and metres can be confusing in the elevation graph. One could add a.s.l to the m to make it clear that you mean metres above sea level. https://en.wikipedia.org/wiki/Metres_above_sea_level

**Comment by migendebien** [comment]
Hi,
Thanks for your software, it is very convenient for my use. Nevertheless, for the analysis I wish to perform, I am missing the "average speed between two points" feature. I record gpx files while sailing at sea and do different speed runs marked by waypoints that appear in GPXSee. Could it be possible to add a second click or SHIFT+click in the speed graph to have the software calculete the speed between them?
Best regards,
Michaël
