### ISSUE TITLE
Norwegian Nb translation finished!

### ISSUE THREAD

**Issue by ihemsen** [tumic0/GPXSee#270]
https://hosted.weblate.org/projects/gpxsee/translations/nb_NO/

:-)

**Comment by ihemsen** [comment]
Also have a second look at #269 (reduced suggestion)

**Comment by sikmir** [comment]
> https://hosted.weblate.org/projects/gpxsee/translations/nb_NO/
> 
> :-)

Could you add one more line here as well:
https://github.com/tumic0/GPXSee/blob/06a84dcea2bc5b87ad2faf9f9a7cf7a697555918/pkg/gpxsee.desktop#L3-L11

**Comment by ihemsen** [comment]
Comment [nb]=GPS-loggfilleser og analysator
