### ISSUE TITLE
Ground elevation and height following a track

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#273]
Hello,

Here is an igc track
![Capture d’écran 2020-03-09 à 08 37 17](https://user-images.githubusercontent.com/109167/76192132-59c77080-61e1-11ea-951b-c0988ceb4d7d.png)
It's available at https://gist.github.com/scls19fr/ea74b389adff41f5e795526b70b3d692

It will be nice if altitude graph could show also ground elevation following that track.

So we could easily know both altitude (from sea level) and height (from ground level).

To process such calculation maybe you can use Google Elevation API.
An other idea could be to use some free terrain / topography data.
https://www.xcsoar.org/download/maps/
https://www.lk8000.it/download/maps.html

Shuttle Radar Topography Mission (SRTM) data https://www2.jpl.nasa.gov/srtm/
https://dwtkns.com/srtm/

I noticed in README that GPXSee supports DEM file but I haven't been able to open FRA_250.DEM (from LK8000 website) neither from File/Open nor from Map/Load a map

Kind regards

**Comment by tumic0** [comment]
DEM files must be stored (or linked) in the GPXSee's DEM directory. See the [documentation](http://www.gpxsee.org/doc.html#dem) for details.

Some better way how to show the different elevation/height sources (GPS, barometer, DEM) would be nice, especially for "pilots", but the data/graph model would have to be probably significantly redesigned as it was not created with different sources of one graph in mind...

**Comment by scls19fr** [comment]
~/Library/Application Support/GPXSee/maps

doesn't exist in my system (OS X 10.13.6)

Putting DEM file in `/Applications/GPXSee.app/Contents/Resources/maps/` doesn't help too.

I can't find a DEM directory as mentioned in doc.

**Comment by tumic0** [comment]
"maps" is a WRONG directory for DEM files. The correct paths are:
`~/Library/Application Support/GPXSee/DEM`
or the global
`/Applications/GPXSee.app/Contents/Resources/DEM`

See Help->Paths in GPXSee

**Comment by tumic0** [comment]
And yes, the directory may not exist, but that's not a problem, simply create it.

**Comment by scls19fr** [comment]
I can only see the global directory.

```
$ ls ~/Library/Application Support/GPXSee
ls: /Users/scls/Library/Application: No such file or directory

$ ls /Applications/GPXSee.app/Contents/Resources/
csv          gpxsee.icns  maps         translations
empty.lproj  icons        qt.conf
```

so I created `~/Library/Application Support/GPXSee/DEM`

```
$ mkdir ~/Library/Application\ Support/GPXSee
$ mkdir ~/Library/Application\ Support/GPXSee/DEM
$ cp FRA_250.DEM ~/Library/Application\ Support/GPXSee/DEM
$ open 2019-08-20-XCS-AAA-01.igc
```
but I still can't see ground elevation

**Comment by tumic0** [comment]
There is a radio button in the data options which selects the primary source of elevation. Most probably you have it set to GPS not to DEM.

**Comment by scls19fr** [comment]
GPXSee / Préférences / Données 
tab Sources
Altitude: Données MNT instead of GPS.
I can't find DEM despite

```
$ ls ~/Library/Application\ Support/GPXSee/DEM
FRA_250.DEM
```

**Comment by tumic0** [comment]
And I see another problem - the DEM file name must use the standard SRTM naming scheme. 
`FRA_250.DEM` won't work.

**Comment by scls19fr** [comment]
Where should I download such file (with correct naming)?
Mine was taken from https://www.lk8000.it/download/maps.html

**Comment by tumic0** [comment]
A link is in the documentation. But the naming scheme is the standard SRTM HGT naming scheme - all HGT files I have seen use it.

**Comment by scls19fr** [comment]
I downloaded 

https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N46E000.hgt.zip
https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N47E000.hgt.zip
https://dds.cr.usgs.gov/srtm/version2_1/SRTM3/Eurasia/N48E000.hgt.zip

unzip it to ~/Library/Application\ Support/GPXSee/DEM

but it's still not working

**Comment by tumic0** [comment]
Is there some error message in the console? Works for me, except you also need N46W001.hgt otherwise you will get a "combined" GPS/DEM graph:
![DEM](https://user-images.githubusercontent.com/11480505/76263811-2d9f0480-6260-11ea-9b22-555ee2ad09d6.png)

**Comment by scls19fr** [comment]
Great @tumic0 !
fallback to GPS altitude when SRTM data are missing doesn't seems to be a great idea... 
I'm wondering if it shouldn't be considered as NaN (or 0 at least for plotting purpose)
