### ISSUE TITLE
Display point on track coordinates

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#274]
Hello,

currently when moving mouse on map, point coordinates of cursor are displayed using black text.
When moving cursor on altitude or speed graph it could be nice to also see coordinates of the red cross (point on track)... maybe using a red text

Kind regards

**Comment by tumic0** [comment]
You can always move the mouse on the cross, if you are interested in a particular position. No need to overcomplicate the UI because of that.
