### ISSUE TITLE
Track create time; altitude anomaly in graph

### ISSUE THREAD

**Issue by efi99** [tumic0/GPXSee#278]
1. When the cursor is above the track, the time in tooltip bubble (tracking's start time in bottom row) is always the UTC time not the time in my timezone. Is that normal ?
2. When the unit is imperial or nautical, then in the graph the altitude's number next to slider is not in line with the scale on Y-axle.

**Comment by tumic0** [comment]
1. Yes, the time is in UTC. But adding the option to show it in the local (or custom) timezone is on my TODO list.
2. Please post a screenshot (and the data file) so can see what you mean.

**Comment by efi99** [comment]
Screenshot.
E.g at 2:28 altitude 130 m, this ok on Meter-scale (Y-Axle) too. Same graph in bottom, but with imperial units: 427 foot, but this is in Foot-scale (Y-Axle) only at 420 foot. 
![gpx1](https://user-images.githubusercontent.com/62113872/76569821-57e90000-64b4-11ea-89c4-4c59a0c6ea53.jpg)
The data file (gpx) i sent via email

**Comment by tumic0** [comment]
No file has arrived so far. Please attach it here so even others can analyze it.

**Comment by efi99** [comment]
[2020-03-12_14-59-21_-_cycling.zip](https://github.com/tumic0/GPXSee/files/4332959/2020-03-12_14-59-21_-_cycling.zip)
