### ISSUE TITLE
Cache automatically map

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#279]
Hello,

I'd like to be able to use GPXSee in offline mode.
It will be nice to have an option to download automatically some part of a map (from a given point to an other one at different zoom level).

Kind regards

**Comment by tumic0** [comment]
This can be already done using [MOBAC](https://mobac.sourceforge.io/) as mentioned in the documentation. Simply create a MBTiles or TrekBuddy atlas using MOBAC and use it in GPXSee.

**Comment by scls19fr** [comment]
My idea was to avoid installing an other software (especially a Java software)

**Comment by tumic0** [comment]
If you hate Java SW so much (I fully understand you ;-) ), you can download the tiles using e.g. curl and create a "local url map" from then like shown in #172
