### ISSUE TITLE
Optional track outline

### ISSUE THREAD

**Issue by donat-b** [tumic0/GPXSee#28]
Sometimes track merges with colors on the map and becomes really hard to see.
Can something like an outline around the track be added to make it more visible?

**Comment by tumic0** [comment]
You can increase the track width in the options (and optionally set some transparency for the used color). See https://a.fsdn.com/con/app/proj/gpxsee/screenshots/zimni.png/1 for an example.

**Comment by donat-b** [comment]
Yeah, that works, too. Thanks!
