### ISSUE TITLE
GPX convert to CSV file

### ISSUE THREAD

**Issue by jmmid** [tumic0/GPXSee#280]
Hello,
Your GPX program is perfect. But I suggest (request) to include a conversion of the statistical data into a CSV file. In fact as soon as we open a gpx file, fit, .. at the same time as the display of the route, a CSV file is created with the information contained in the statistics page. This CSV file could be overwritten each time it is opened.
Could you foresee this adaptation in a future version.
With all my best consideration.

**Comment by tumic0** [comment]
GPXSee is a viewer and format conversion is thus out of scope of GPXSee. There is [gpsbabel](https://www.gpsbabel.org/) for doing exactly what you want.
