### ISSUE TITLE
Request NMEA support

### ISSUE THREAD

**Issue by edegraaff** [tumic0/GPXSee#283]
This project seems to solve most of my problems, the only thing i would like to get into the project is also nmea support. This way external devices like, gps that support nmea, or a nmea mouse tracker can show the exact location and or tracks on all those integrated options. It would be really nice to have this. 
regards and stay healthy 

Eelco

**Comment by tumic0** [comment]
NMEA log files are already supported.

If you are talking about NMEA real time data, than there is already an open issue #34 for that (It is not exactly named NMEA, but in fact it is what you want). Most probably I will go with QtLocation when I decide to go the "real time logging" way, but at the moment I'm still not sure whether to do so.

Anyway, GPXSee is free software so you can take it and enchance it  the way you like.
