### ISSUE TITLE
Add the "Delta t" from the start of track

### ISSUE THREAD

**Issue by pascalr0410** [tumic0/GPXSee#284]
Hello

It may be cool to add on the graph view, when using the cursor, below then speed / alt and distance indication, the time elpased from the start of the track.

kind regard
Pascal.

**Comment by tumic0** [comment]
This was already discussed here in the past - the problem is the info becomes "overcrowded" and confusing with more data to display. That's why I still think the current split on time/distance graphs with the corresponding info is the way to go.
