### ISSUE TITLE
No Maps are shown

### ISSUE THREAD

**Issue by Klausenzweitausen** [tumic0/GPXSee#287]
This Software seems to be exactly what I need. Unfortunately it shows no maps. All I see is a white blank page, if I load my tracks i see them, but only on the white background. Switching the map on off button changes nothing. I also tryed to change map source or download new maps. System is Windows10 with latest patches

**Comment by tumic0** [comment]
A fast guess without any further info is, you have disabled openssl during install or you have some antivirus/firewall that blocks the connections.

Try running GPXSee from the command line with output redirection to a log file:
`gpxsee > log.txt 2>&1`
and provide the error messages, otherwise there is nothing I can do about it.

**Comment by Klausenzweitausen** [comment]
I did this, GPXSee starts, Logfile is created but stays empty. I have no active outgoing firewall and I didnt notice any OpenSSL Question durinf installation neiter can I find such a option in the menu.

**Comment by Klausenzweitausen** [comment]
I reinstalled and made sure openSSL is installed. I also added the GPXSee.exe to the Firewall exceptions and to the Windows Defender exceptions. Still no maps in the Application

**Comment by tumic0** [comment]
> I did this, GPXSee starts, Logfile is created but stays empty.

You are right, the debug output from Qt applications on Windows is by default to the system debug stream and not stderr like on Linux/Mac. So you need something like [DebugView](https://docs.microsoft.com/cs-cz/sysinternals/downloads/debugview) to view it.

Run DebugView and then GPXSee and you should get the debug output in DebugView.

**Comment by Klausenzweitausen** [comment]
[8020] Error downloading file: https://gis.ngdc.noaa.gov/arcgis/rest/services/antarctic/antarctic_basemap/MapServer/WMTS/1.0.0/WMTSCapabilities.xml: Der Zugriff auf das Netzwerk ist nicht gestattet.

**Comment by Klausenzweitausen** [comment]
I cant open that URL in my browser either, it displays a 404 error, that file is not avaiblable on the webserver...

**Comment by tumic0** [comment]
The Antarctica map server seems to be down at the moment. I will check this and eventually update/remove the map from the default maps. If you desperately need a map of Antarctica at the moment, you can use the [LIMA map](https://github.com/tumic0/GPXSee-maps/blob/master/World/Antarctica/LIMA.xml)

But the other maps are fine and you were writing about all maps...

**Comment by Klausenzweitausen** [comment]
In the options "OpenStreetMap" is choosen. Anyway, I can choose whatever map, this message appears in the log

![image](https://user-images.githubusercontent.com/64652073/80842876-0121bc00-8c03-11ea-8178-84714a637b06.png)

**Comment by tumic0** [comment]
You have disabled showing the maps in the menu ("Karte anzeigen" is not enabled). So GPXSee correctly does not show/load any maps...

**Comment by Klausenzweitausen** [comment]
![image](https://user-images.githubusercontent.com/64652073/80848702-66ca7400-8c14-11ea-91ba-e1b3a855b310.png)
I tried that before and, no, you can flip that button a thousend times. No Maps are showing...

**Comment by Klausenzweitausen** [comment]
![image](https://user-images.githubusercontent.com/64652073/80848756-a002e400-8c14-11ea-9a9e-a6dbd93d632f.png)
I tried that before and, no, you can flip that button a thousend times. No Maps are showing...

**Comment by tumic0** [comment]
Ok and what errors do you get in the debug stream when the maps are allowed?

**Comment by Klausenzweitausen** [comment]
[11856] Error downloading file: https://gis.ngdc.noaa.gov/arcgis/rest/services/antarctic/antarctic_basemap/MapServer/WMTS/1.0.0/WMTSCapabilities.xml: Der Zugriff auf das Netzwerk ist nicht gestattet.
[11856] Error downloading file: https://tile.openstreetmap.org/1/0/0.png: Der Zugriff auf das Netzwerk ist nicht gestattet.
[11856] Error downloading file: https://tile.openstreetmap.org/1/0/1.png: Der Zugriff auf das Netzwerk ist nicht gestattet.
[11856] Error downloading file: https://tile.openstreetmap.org/1/1/0.png: Der Zugriff auf das Netzwerk ist nicht gestattet.
[11856] Error downloading file: https://tile.openstreetmap.org/1/1/1.png: Der Zugriff auf das Netzwerk ist nicht gestattet.

**Comment by Klausenzweitausen** [comment]
I switched the Firewall now completely off, even though no other application ever had Problems accessing the internet on this computer.

**Comment by tumic0** [comment]
This seems to be a bug in the Qt network status detection code (probably related either to proxies or network switching). Users of the owncloud client are apparently hit by the same issue. Sadly, there is almost nothing I can do about it.

You can try fiddling with the network connections on your system (try to restart and/or disable wifi/lan interfaces) and see if you make it work/find some pattern and eventually report the bug to Qt in the [Qt bug tracker](https://bugreports.qt.io/).

**Comment by Klausenzweitausen** [comment]
I works now, no idea why.

**Comment by STEF0112** [comment]
don't work in my case.
'Network List Service' == netprofm (in German: Netzwerklistendienst) was already started and restarted additionally but same bad result

**Comment by tumic0** [comment]
See nextcloud/desktop#865 for more tips what may help. Their "fix" was to remove bearer from the distribution, but GPXSee already dos not distribute the bearer dll, so the only thing which comes to my mind is you have some other Qt app in your system that has installed bearer system-wide.

There are allegedly some changes in Qt 5.15 that may also help (the windows build uses Qt 5.14). You can try the latest [CI build](https://ci.appveyor.com/project/tumic0/gpxsee/builds/41317122/job/hycqjue4qp8cfk83/artifacts) that uses Qt 5.15.2 and see if it works on your system. There is however still appveyor/ci#1616  so the CI build requires an additional MSVC 2013 runtime (you may however already have it installed on your system).

**Comment by elig0n** [comment]
@tumic0 
I have similar issue. The debug log shows:
`[581516] QIODevice::read (QDisabledNetworkReply): device not open`
And similarly with map tiles links like:
`[576856] https://tile.openstreetmap.org/19/262141/262143.png: Network access is disabled.`

Installing from [CI build](https://ci.appveyor.com/project/tumic0/gpxsee/builds/41317122/job/hycqjue4qp8cfk83/artifacts) works for me.

Windows 10 64-bit

**Comment by tumic0** [comment]
Ok, thanks for the info. I will release the next version with Qt 5.15.2 (and the latest OpenSSL and all build with MSVC 2019). Hopefully this will solve the network access issues some people have and not bring another set of issues... Well, one is already known - the installer will be bigger as the MSVC 2019 redistributables are 24MB instead of 14MB (MSVC2017).

**Comment by tumic0** [comment]
GPXSee 9.11 which has the Windows build based on Qt 5.15.2 was released. Those who are facing the _Network access is disabled_ error, please give it a try and report here if it has solved the issue for you.

**Comment by STEF0112** [comment]
Great, now with 9.11 it works again at my WIN7 and surely also at WIN 10.
The maps (especially OSM) are loding.
Many Thx :) :) :)

**Comment by Zero3** [comment]
@tumic0 Also fixed for me on Windows 7 :). Thanks.
