### ISSUE TITLE
Dear developers! Add a feature to connect with GPS

### ISSUE THREAD

**Issue by DerekTizz** [tumic0/GPXSee#289]
Dear developers! Add a feature to connect with GPS and make moving map with GPS and record and save tracks!

**Comment by DerekTizz** [comment]
GPXSee ia a great software! Make it more greater! Add a moving map on the GPS coordinates and record and save tracks!

**Comment by sikmir** [comment]
GPXSee is a viewer. Recording/saving tracks is a job for another tool.

**Comment by luznicky** [comment]
@tumic0 They call you developers...

**Comment by tumic0** [comment]
@luznicky Better than if they would call me a "Quiche Eater"... ;-)

**Comment by DerekTizz** [comment]
Please make a moving map feature and recording and saving tracks! GPXSee can load many types of maps, so it is very useful not only to view and analyze tracks, but navigate on bary raster maps. By the way, I would like to request one more feature - create and edit waypoints.

**Comment by tumic0** [comment]
Added in fa55c6d93a0d20af9a571322dc9c9d6dc246d3a5 (using Qt positioning)
