### ISSUE TITLE
Show UTM coordinates

### ISSUE THREAD

**Issue by eumiro** [tumic0/GPXSee#290]
With so many map projections, would it be possible to customize the `Settings → Coordinates format` of the current position and add UTM coordinates as well?

**Comment by tumic0** [comment]
Well, it would be definitely possible, but the purpose of GPXSee is not to be a (overcomplicated) GIS. The only option that would still fit into the bounds of a simple map/GPS data viewer and what I'm considering to implement is to select between GPS(lat/lon) and the map projection coordinates (so for UTM maps you would get the UTM coordinates). But anything beyond this is IMHO a job for a GIS tool.
