### ISSUE TITLE
Copy the current position into clipboard

### ISSUE THREAD

**Issue by eumiro** [tumic0/GPXSee#291]
The current position is shown on the screen. Would it be possible to add the possibility to copy it in the current format into the system's clipboard? There's no context menu, and accessing the app's menu wouldn't make sense, so a keyboard shortcut would be the easiest and most interactive way.

**Comment by tumic0** [comment]
Use Shift+Left Click to copy the coordinates. Holding the shift also changes the cursor to a cross cursor.
