### ISSUE TITLE
FR: show time of day when hovering over track or graph

### ISSUE THREAD

**Issue by Gro-Tsen** [tumic0/GPXSee#292]
After I record a track of a walk or ride, I'd like to use GPXsee to learn at which time I passed by a certain point. Currently there is no easy way to do it (indeed, the best I could find is to look up the point's coordinates — and even that is not convenient — and then search for it in the GPX file).

So I'd love it if one could someone (by clicking, or maybe just hovering over the point on the track, or on one of the graphs) get some information on the closest recorded point in the GPX file: time of day, time elapsed, distance traveled, coordinates, speed, etc.

**Comment by tumic0** [comment]
You can use the slider to get the (relative) time of any point on a track. To get the absolute time you have to add it to the track start time (which can be now - starting with 5bd744a8ed4f490313c82262e28c34e325aeb856 displayed in the expected time zone). The problem of absolute times is already discussed in #35 so I'm closing this as a duplicate.
