### ISSUE TITLE
"Show Graphs" greyed out

### ISSUE THREAD

**Issue by mju253** [tumic0/GPXSee#293]
Maybe I am missing something, but for whatever reason I cannot click on "show graphs" because it is greyed out.

![Screen Shot 2020-06-07 at 2 59 48 PM](https://user-images.githubusercontent.com/66573777/83981094-afd6ad80-a8cf-11ea-825f-dcfd464ce94c.png)

**Comment by tumic0** [comment]
The graphs are disabled when there is no data to show. Please provide the GPX file so I can see whether it is a bug in GPXSee or there are really no (elevation, speed, ...) data in the file.

**Comment by mju253** [comment]
Thank you for your help. Here is the GPX file (attached).

Max

**Comment by tumic0** [comment]
No attachment has arrived. Github does allow only [some attachement formats](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests), so you have to zip/gzip the GPX file.

**Comment by tumic0** [comment]
Closing as without the data there is nothing I can do about it.

**Comment by iago-pssjd** [comment]
@tumic0 I have the same problem on Debian 9. I attach my file
[Montjuic.gpx.zip](https://github.com/tumic0/GPXSee/files/5183340/Montjuic.gpx.zip)

**Comment by sikmir** [comment]
> @tumic0 I have the same problem on Debian 9. I attach my file
> [Montjuic.gpx.zip](https://github.com/tumic0/GPXSee/files/5183340/Montjuic.gpx.zip)

Trackpoints in your file have no timestamps/elevations, so nothing to show on graphs.

**Comment by iago-pssjd** [comment]
Thank you!
