### ISSUE TITLE
Problem utc() and other is not a member of  ...

### ISSUE THREAD

**Issue by jolinux** [tumic0/GPXSee#294]
A problem to compile GPXSee 7.30.
My system Debian 8.

jo@debian:~/Downloads/GPXSee-7.30$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DAPP_VERSION=\"7.30\" -DQT_NO_DEPRECATED_WARNINGS -DQT_USE_QSTRINGBUILDER -DPREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_CONCURRENT_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o main.o src/main.cpp
In file included from src/main.cpp:3:0:
src/GUI/timezoneinfo.h: In constructor ‘TimeZoneInfo::TimeZoneInfo()’:
src/GUI/timezoneinfo.h:16:43: error: ‘systemTimeZone’ is not a member of ‘QTimeZone’
  TimeZoneInfo() : _type(UTC), _customZone(QTimeZone::systemTimeZone()) {}
                                           ^
src/GUI/timezoneinfo.h: In member function ‘QTimeZone TimeZoneInfo::zone() const’:
src/GUI/timezoneinfo.h:23:11: error: ‘utc’ is not a member of ‘QTimeZone’
    return QTimeZone::utc();
           ^
src/GUI/timezoneinfo.h:25:11: error: ‘systemTimeZone’ is not a member of ‘QTimeZone’
    return QTimeZone::systemTimeZone();
           ^
Makefile:1448: recipe for target 'main.o' failed
make: *** [main.o] Error 1

###################################
Info:

jo@debian:~/Downloads/GPXSee-7.30$ qmake -v
QMake version 3.0
Using Qt version 5.3.2 in /usr/lib/x86_64-linux-gnu

You say  in the readme

Build requirements:
* Qt 4.8 or QT 5.x (Qt >= 5.10.1 recommended for all features).

The problem is  the new function "Added time zone configuration"
       because               ENABLE_TIMEZONES is activ
I change file config.h 

From
#if QT_VERSION >= QT_VERSION_CHECK(5, 2, 0)
#define ENABLE_TIMEZONES
#endif // QT >= 5.2

TO  maximum qt-version 

#if QT_VERSION >= QT_VERSION_CHECK(5, 15, 0)
#define ENABLE_TIMEZONES
#endif // QT >= 5.2

I compile new   -> NO ERROR

So you need a new  version-check

**Comment by tumic0** [comment]
already fixed in master
