### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by spencerclrk** [tumic0/GPXSee#30]
What is the URL Scheme for Google Maps? I noticed you seem to be using them in some of your screenshots. Tried a few things to no avail.

**Comment by tumic0** [comment]
A working Google maps URL is for example:
`http://mt1.google.com/vt/lyrs=m&x=$x&y=$y&z=$z`

It is however no "official" URL and it is questionable if using it complies to some Google service rules and/or the law of your country.

**Comment by imonlyfourteen** [comment]
Here's an XML that works for me:

```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4">
	<name>Google Maps</name>
	<url>https://khms1.google.com/kh/v=979?x=$x&amp;y=$y&amp;z=$z</url>
</map>
```
