### ISSUE TITLE
Show location of elevation position on the track.

### ISSUE THREAD

**Issue by dpawlyk** [tumic0/GPXSee#302]
One can slide the position of the "cursor" in the elevation profile.

Ridewithgps has a similar feature but it also draws a dot on the corresponding position on the displayed track.

This is useful because it lets to see exactly in the track where "climbs" are.

This is a feature that should be considered for GPXSee.

**Comment by tumic0** [comment]
GPXSee also shows the position of the point in the graph on the track, when the "Graph->Show path markers" option is enabled (should be enabled by default).

If you mean something different, then please provide a better description, preferably with a screenshot.
