### ISSUE TITLE
DESTDIR not honored

### ISSUE THREAD

**Issue by Cigaes** [tumic0/GPXSee#303]
I just build from sources, saw that Makefile contains the word DESTDIR (meaning it should be supported), and used it for `make DESTDIR=/tmp/... install` as I always do, but it tried to write directly in the install directory, not taking DESTDIR into account. 
(I always use DESTDIR for safety and privilege separation: let make write in a temp directory, check that everything is clean, and then raise privileges to copy the directory.)

**Comment by tumic0** [comment]
You can use the `PREFIX` variable in qmake and then `INSTALL_ROOT` in make (eg. [Archlinux package](https://github.com/archlinux/svntogit-community/blob/packages/gpxsee/trunk/PKGBUILD), [Fedora package](https://src.fedoraproject.org/rpms/gpxsee/blob/master/f/gpxsee.spec)). It makes however not much sense to use other prefixes than `/usr` or `/usr/local` as QStandardPaths are used to locate the installed stuff at runtime.

**Comment by Cigaes** [comment]
DESTDIR and PREFIX are not the same thing at all, according to standard Makefile, like the ones produced by autotools, but also many others. PREFIX determines where the software is supposed to be installed, it governs hard-coded paths. DESTDIR only governs where the files are copied by `make install`.
I checked, INSTALL_ROOT seems to be fill that role. But it is less standard, and supporting the standard DESTDIR would be a good idea. Barring that, please make sure DESTDIR does not appear anywhere, because it is misleading.

**Comment by tumic0** [comment]
The Makefile is automatically generated by qmake and INSTALL_ROOT seems to be quiet standard in Makefiles produced by qmake as profesional packagers have used it without being documented in any GPXSee documentation... If you need/want some special qmake/Makefile tweaking, feel free to do si in your personal fork. The "official" sources will however continue to use the standard, unmodified, qmake generated Makefiles.
