### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by insanemadman** [tumic0/GPXSee#306]
I use Windows 7 64bit english version (I prefer it this way), however my native language is polish.
How am i supposed to change GPXSee GUI to polish?
I have already tried issues #38 and #39, but no success.

**Comment by tumic0** [comment]
The solution described in #38 should work on Windows 7 (works for me). If it doesn't work on your system, than you can switch to some more crazy solutions like building yourself a modified, Polish-only, version of  GPXSee. But please don't expect any help doing so - opensource means you are free to modify the program, not anyone else is obliged to do it for you...
