### ISSUE TITLE
Can't see part of South Hemisphere in map

### ISSUE THREAD

**Issue by pablohawkes** [tumic0/GPXSee#307]
In attached image is shown that part of south hemisphere is not visible on map (starting on zoom level 3):

![gpxsee](https://user-images.githubusercontent.com/47606136/92392935-6deb1c80-f0f5-11ea-93e3-3de6f9454c5e.png)

**Comment by sikmir** [comment]
It works for me, maybe some temporary problem with map server?

**Comment by pablohawkes** [comment]
Hi Sikmir, Is not a temporary problem. This happens to me every time I open the app. I use OpenStreetMap on Firefox on this without any problem.
Even changed some parameters in order to verify, but remains equal:

![gpxsee](https://user-images.githubusercontent.com/47606136/92399892-6762a200-f101-11ea-8fda-10ae81f844a7.png)

Even I tested in another notebook (app freshly install or right notebook) ant the result is the same:

![gpxsee2](https://user-images.githubusercontent.com/47606136/92400176-db04af00-f101-11ea-8422-8d3b5506b2f5.png)

Is there any specific video requirement for the app? (notebook video is Intel 5500).
Regards.

**Comment by sikmir** [comment]
Try "Maps -> Clear cache". Is there the some problem with other maps?

**Comment by pablohawkes** [comment]
Solved! I was using 4UMaps, not OSM.
Clear cache and switch to OpenStreetMap and worked.
Thanks for your help!

In fact, this seems to be an 4UMaps issue:
![gpxsee3](https://user-images.githubusercontent.com/47606136/92405445-f4125d80-f10b-11ea-972e-428d60aad582.png)

**Comment by pablohawkes** [comment]
Not an issue, but a "feature" of 4UMaps:

From his web:
4UMaps are available for
Europe
North Africa
South Canada
USA
Far East: India, China, Japan, Korea....
Australia, New Zealand

No Southamerica :(
