### ISSUE TITLE
Is it possible to support some kind of measurement for Grade adjusted pace

### ISSUE THREAD

**Issue by dnk8n** [tumic0/GPXSee#309]
Similar to what Strava offers (now only to premium members), it normalises pace across different inclines.

More here - https://support.strava.com/hc/en-us/articles/216917067-Grade-Adjusted-Pace-GAP-

Times and Grades would probably need to be calculated point to point, and summed up. I also think Strava only used a bunch of their users data to come up with the figures, and maybe different people have their own affinity towards performance at incline.

So it would also be a great feature to be able to compare a history of runs and do some kind of linear regression over multiple runs to calculate parameters that make sense to the runner (or maybe if they're cycling for example, there would be different parameters).

Is this kind of aggregated feature (taking many measurements into account) possible within this software? If not, a third party tool could run this and apply metadata to each measurement logged.

**Comment by tumic0** [comment]
I don't think that GPXSee is the right tool for such analysis. The goal of GPXSee is to be a simple and fast GPS log/map viewer. For advanced statistics there is other SW like GoldenCheatah.
