### ISSUE TITLE
Add a list of the last files opened in the File menù

### ISSUE THREAD

**Issue by mgian** [tumic0/GPXSee#311]
It would be nice to have the classic list of the last _n_ opened files in the File menù.  

I already have added it on my copy, as soon as you start accepting code contribution, I will be happy to open a pull request

**Comment by tumic0** [comment]
I don't think that this makes much sense in GPXSee. GPXSee is not "project oriented", you do not usually work with the opened files repeatedly. The typical scenario is you open some file, look at the data and forget about it...

**Comment by mgian** [comment]
Well, maybe it is just me that use it in a peculiart way. Thanks anyway
