### ISSUE TITLE
Portable version (Win-x64)

### ISSUE THREAD

**Issue by sudione** [tumic0/GPXSee#315]
Can you create and add Windows-x64 portable version (zip/7z)?
Thank you in advance for your answer.:)

**Comment by tumic0** [comment]
[GPXSee 7.33 portable](https://portable.info.pl/gpxsee-portable/)

**Comment by sudione** [comment]
It does not work.:( I prefer the official version.;)Temat: Re: [tumic0/GPXSee] Portable version (Win-x64) (#315)Data: 2020-10-22 1:21Nadawca: "Martin Tůma" Adresat: "tumic0/GPXSee" ; DW: "sudione" ; "Author" ; 
GPXSee 7.33 portable

**Comment by tumic0** [comment]
Then you have to find some other source or make the portable version yourself. I do not have the resources to maintain yet another Windows build, sorry.

**Comment by sudione** [comment]
I have a perfect idea: do not make 32-bit version for Windows in future. Taaa-daaam! 8)Temat: Re: [tumic0/GPXSee] Portable version (Win-x64) (#315)Data: 2020-10-22 1:39Nadawca: "Martin Tůma" Adresat: "tumic0/GPXSee" ; DW: "sudione" ; "Author" ; 
Then you have to find some other source or make the portable version yourself. I do not have the resources to maintain yet another Windows build, sorry.
