### ISSUE TITLE
Garmin IMG maps: max zoom limit

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#319]
There is a 100m max zoom limit now:
![scr4](https://user-images.githubusercontent.com/688044/97815512-a21b2d80-1c9f-11eb-8261-162c6025add5.jpg)
This is often not enough (map have more details that can be activated on higher zoom level), it would be great to have more, e.g. Garmin allows zoom up to 5m.

**Comment by tumic0** [comment]
![zoom](https://user-images.githubusercontent.com/11480505/97815867-71cc9280-1c91-11eb-9dec-c56dc4f62f1d.png)
The maximal zoom is definitely much higher, see the attached OpenTopo map screenshot. It shall be 28 bits (24bits is the maximal map data resolution) on every map. What map do you use?

**Comment by sikmir** [comment]
I use [OV-Hib-Lov-20201017-1.03.img](https://drive.google.com/file/d/17DUaRG_qj_qgIZ5EuHOflaDCobO0pWlv/). And I have no problem with zooming this map up to 5 m in other programs (e.g. QMapShack).

**Comment by tumic0** [comment]
The map has invalid subdiv bounds of the maximal zoom layer - the width is zero - so the maximal zoom layer gets not loaded. The validity check has changed in 7.35 - it is stricter now and does not allow such invalid tiles to be loaded (the layer gets displayed with versions <= 7.34).

How was this map produced? I have already seen exactly such a broken map, it was some older  [freemapSKtopo](http://wiki.freemap.sk/freemapSKtopo) map, but their recent maps are ok. So I suppose the map was produced by a broken mkgmap version. The question is, what to do with such broken maps. They do seem to work (as you can see in 7.34), but the subdivs gets always loaded (but not displayed, the data is dropped later) even when the view rectangle does not contain the subdiv area.

**Comment by sikmir** [comment]
> How was this map produced?

I don't know, @cornet1973 is original author.

**Comment by tumic0** [comment]
> As far as even Garmin handles such broken maps properly
The reason most probably is, they do (like QMapShack) use a different subdiv lookup algorithm than GPXSee does.
> GPXSee should not be so strict as well.
Yes, I agree, that a program shall not be unnecessary strict, but on the other hand I do want to have a single GeoRectangle `isValid()` function and not a special hack for every situation where even a broken rectangle may by chance work...
So what decides is, how common such broken maps are.

**Comment by tumic0** [comment]
Ok, after a check, that even freemapSKtopo still contains such broken subdivs (in some tiles) a have relaxed the check in 1225d350d41368ddafff8f7ac5ebc5d2992b455a.

**Comment by cornet1973** [comment]
This map created by cGPSmapper v.0100d.
It seems to me that the program for maps viewing should not be stricter than the garmin-devices.
