### ISSUE TITLE
Wishes nice to have

### ISSUE THREAD

**Issue by cyclobing** [tumic0/GPXSee#321]
First of all, your small programm is excellent and usefull !  Thank you for its simplicity and efficiency.
Nice to have : 
1) Possibility to copy the displayed statistics in the window to paste them in an Excel spreadsheet.
2) Add start and end elevations to statistics.
3) Time of the day also and not only duration or distance on X axe of graphics.
4) Preferential folder(s) to open where the GPS files are stored.

**Comment by sditn** [comment]
I just downloaded GPXSee for the first time and it's great - thanks to all devs that have supported this project. I would like to add an +1 to one element of this feature request "Time of the day also and not only duration or distance on X axe of graphics."

**_Example Scenario_**
I download and store a GPX file that contains all my movements for a given calendar month, the GPX file loads just great. I would like to be able to click on a given route point / GPS hit on the map window and see what the time and date was at that moment.

**Comment by tumic0** [comment]
Absolute time graphs are already discussed in #35. The only reason why I'm still letting this issue open is 4), which I will most likely implement (as an configurable option). But generally do not put multiple things in a single issue as they will most probably get closed unhandled in such case...

**Comment by cyclobing** [comment]
Good Morning,

 

Thank you for your answer.

There is no hurry.

 

Shal I open 3 other issues in GiHub for the other 3 wishes ?

(just by copy and paste probably and leaving only one wish)

 

Best regards.

 

Blaise Dériaz
Consulting Engineer
8, rue du Vieux-Collège
CH - 1204  Genève
+41 22 311 60 53  tél.
+41 22 320 03 17  bur.
+41 79 379 33 63  mobile

 

  _____  

De : Martin Tůma [mailto:notifications@github.com] 
Envoyé : dimanche 15 novembre 2020 17:17
À : tumic0/GPXSee
Cc : cyclobing; Author
Objet : Re: [tumic0/GPXSee] Wishes nice to have (#321)

 

Absolute time graphs are already discussed in #35 <https://github.com/tumic0/GPXSee/issues/35> . The only reason why I'm still letting this issue open is 4), which I will most likely implement (as an configurable option). But generally do not put multiple things in a single issue as they will most probably get closed unhandled in such case...

**Comment by sditn** [comment]
> 
> 
> Absolute time graphs are already discussed in #35. The only reason why I'm still letting this issue open is 4), which I will most likely implement (as an configurable option). But generally do not put multiple things in a single issue as they will most probably get closed unhandled in such case...

Thanks, yes I looked at #35 but wasn't sure it was what I was looking for, I will look at that now.

**Comment by tumic0** [comment]
No 4 implemented in 5b3b7128f62d6b20f95882cff5b324499a1e52f9. Others either discussed in other issues or "won't implement".
