### ISSUE TITLE
Error on gpx file with leading space indents.

### ISSUE THREAD

**Issue by larsnygard** [tumic0/GPXSee#322]
Fails to open gpx files with error message "declaration not at start of document" when the gpx file has leading spaces before first < bracket.

**Comment by larsnygard** [comment]
The cause of this error is of course that some of my GPX files exported from Strava has leading whitespaces like this "          <?xml version="1.0" e..."

So this is not the fault of GPXsee, but should Gpxsee should trim leading whitespaces when importing gpx files for compability reasons? 

Of course I can fix the files with sed, but that is beside the point.

**Comment by tumic0** [comment]
Well, the reason why you get this error is, that such documents are not valid XML and thus also not valid GPX.
Strava is notoriously known for producing such invalid exports - see gpsbabel/gpsbabel#371 - but evidently they are not willing to fix it... But neither am I willing to put workarounds for every broken log generator, sorry (especially when it is not a trivial task and the originator of such files does not care).
