### ISSUE TITLE
Finer control of zoom level

### ISSUE THREAD

**Issue by tamas-ferenci** [tumic0/GPXSee#323]
It sometimes happens that on a given zoom level the track occupies only a smaller part of the useful area, but if I change to the next zoom level, parts of the track are already outside the area. Thus, it'd be nice to have a zoom between the two levels.

Would it be possible to allow a finer control of the zoom level? Or it is something imposed by the map providers...?

**Comment by tumic0** [comment]
Most of the providers are raster image based, so doing some kind of "inter zoom" would make the maps look blurry/distorted. The IMG (MVT tiles are used as raster in GPXSee) vector maps could theoretically have a finer zoom scale, but it is not worth the effort. So the answer is it would be possible, but I won't do any such changes.

**Comment by tamas-ferenci** [comment]
Thank you very much!

**Comment by tamas-ferenci** [comment]
I just realized that you can achieve something very similar using an appropriate size with the 'Export to PNG' function. (Of course if you're interested in looking it as a saved image file.)
