### ISSUE TITLE
Secondary elevation (GPS/DEM) not working

### ISSUE THREAD

**Issue by tamas-ferenci** [tumic0/GPXSee#324]
Even though I tick "Show secondary elevation", the elevation plot under the map only shows a single line. If I recall correctly, it used to show the other elevation with a dashed line. Also, the elevation plot seems to be the same regardless of whether GPS or DEM is chosen under Data / Sources.

**Comment by tumic0** [comment]
Most probably you do not have the DEM data for the plot region. You must download them (and extract) manually to the corresponding DEM directory before you can use any of the DEM features.

**Comment by tamas-ferenci** [comment]
Ahh, you are completely right @tumic0 , sorry for overlooking something so trivial. To turn this into a constructive suggestion: it'd be perhaps nice, if the program gave a warning in such situation. It not just the secondary tick box: the program allows you to change to DEM even if there is no DEM file (and displays GPS with the source set to DEM -- without any notification!).

**Comment by tumic0** [comment]
There is a warning in the console (in the debug log on windows*) if the DEM file is missing. And there is deliberately no message box as most of the time it would be very annoying. But I agree, that there is a lot of space for user-friendliness improvement in the DEM data handling. Some kind of automatic DEM files downloading would probably be the ideal solution, but there are a lot of technical obstacles to do so...

* which is not very user friendly as you need a tool like DebugView to see it, but that is a problem of the whole Windows platform, not GPXSee ;-)
