### ISSUE TITLE
how to configure new tile sources

### ISSUE THREAD

**Issue by okvittem** [tumic0/GPXSee#326]
I tried to configure a new map which works  in leaflet.
However I get 
`Error downloading file: https://mapant.no/tiles/11/1081/553.png: Error transferring https://mapant.no/tiles/11/1081/553.png - server replied: 

`<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.3">
        <name>Map Ant Map</name>
        <url>https://mapant.no/tiles/$z/$x/$y.png</url>
        <zoom min="0" max="11"/>
        <copyright>Basert på FKB og laserdata (C); Statens Kartverk, Geovekst og kommunene</copyright>
</map>
`
The leaflet javascript look like this :
` templateUrl = "https://mapant.no/tiles/{z}/{y}/{x}.png";

    var mapantLayer = new L.TileLayer(templateUrl, {
	maxZoom: 11,
	maxNativeZoom: 10,
	minZoom: 0,
	tileSize: 1024,
	continuousWorld: true, 
	unloadInvisibleTiles: false,
	attribution: 'Basert p&aring; FKB og laserdata &copy; Statens Kartverk, Geovekst og kommunene'
    })`

**Comment by sikmir** [comment]
I've tried to use [WMS server](https://mapant.no/internal-wms?service=WMS&request=GetCapabilities):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4" type="WMS">
	<name>Mapant Norway</name>
	<url>https://mapant.no/internal-wms</url>
	<copyright>Basert på FKB og laserdata © Statens Kartverk, Geovekst og kommunene</copyright>
	<layer>mapant2</layer>
	<crs>EPSG:32633</crs>
</map>
```
But the server doesn't respond:
```
Error downloading file: http://hangya.spjelkavik.net:8080/geoserver/mapant/ows?SERVICE=WMS&&service=WMS&version=1.3.0&request=GetMap&bbox=-40040571.234561,-32238277.701777,34445.451018,7836738.983801&width=256&height=256&layers=mapant2&styles=&format=image/png&transparent=true&CRS=EPSG:32633
```

**Comment by tumic0** [comment]
The map is not a standard OpenStreetMap/Google tiles map, but it uses custom layers with EPSG:32633 projection. Such maps are generally supported in GPXSee, but you must define them using a standard WMTS definition. Leaflet JavaScript "mess" as definition is not (and won't be) supported.

**Comment by tumic0** [comment]
@sikmir I have tried exactly the same WMS server (as defined in the leaflet JavaScript) ;-) , but it is absolutely unusable - brutally slow and when it by chance returns an image, than it is blank...
