### ISSUE TITLE
Option to add further statistics to the header of the exported figure

### ISSUE THREAD

**Issue by tamas-ferenci** [tumic0/GPXSee#329]
Currently when the results are exported to PNG or PDF, the header includes the name, date, distance and time. I thought it'd be perhaps useful to display total ascent, total descent, maximum speed and average speed as well. This way, you'd show these basic statistics to the viewer, even if the bottom graph doesn't reveal it (i.e., if you have an elevation profile, the exported image will show no direct information on speed, or the other way around, if the speed graph is shown, there is no information on ascent and descent).

Or perhaps just add an option to the export dialog box where the user can select to add these further statistics to the header.

**Comment by tumic0** [comment]
The header line is not inflatable so it can not contain all info one can imagine. Also there are some implementation limitations - the graphs are opaque for the export layout logic at the moment and I do not want to make it more complicated than it already is.

If you want all the data, you can export all the graphs on a separate page/in a separate image.
