### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by eson57** [tumic0/GPXSee#33]
https://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_16.04/ / don't work. I get error 

> W: Failed to fetch https://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_16.04/./amd64/gpxsee_4.14_amd64.deb
>   Protocol "http" not supported or disabled in libcurl

It only works if I change _/etc/apt/sources.list.d/gpxsee.list_ to http.

**Comment by tumic0** [comment]
Hi,
Works for me now, but in the past days, they had the download infrastructure
broken, see the announcements at the main page (https://build.opensuse.org/).
Most probably they are still fiddling on the infrastructure, so occasional outages
may still happen. Anyway, there is nothing I can do about it ;-)

M.

______________________________________________________________

**Comment by eson57** [comment]
Ok, good to know you got a hang on it. Thanks!
