### ISSUE TITLE
Display timestamp of GPS hit when clicking on the route on a map.

### ISSUE THREAD

**Issue by sditn** [tumic0/GPXSee#330]
I would like to be able to click on any point on the GPS overlay (the line on the map) and then have the timestamp (e.g. 2020-10-06T10:44:07Z)  for that related GPX entry displayed on the screen in some way, e.g. hovertext or status bar.

This does not solve all the problems users have requested in issue #35 however it does help with the question I have posed (i.e. what time and date was it when I was at this place). For this reason I have separated it out to this new issue / request.

**Comment by j-schneid** [comment]
This would often be very helpful, +1!

**Comment by kaengo** [comment]
OK, on mein SLED 15SP2 is running gpxsee 8.9.
I can see, that a stamp is shown with the UTC-time. Than, there is a ,total time'  and a ,moving time'
and there is a red noted time in the graph, when I click onto a point onto the graph.
All are different, and all are different from the real (UTC-) time of the examined point, 
If I open the gpx file with an editor, I see the true UTC(=Z) times, also, if I open the file with google earth.
But I can't see the true time, if I open the file with gpxsee.
Is this a bug? I looked at the change log, and didn't find this behaviour mentioned.

Greetings,
Holger

**Comment by tumic0** [comment]
How do you define "true time"? GPXSee can show the absolute time next to the path marker and the relative (total or moving) time in the graphs. I have no idea what other type of time you could expect to be shown...

If you are trying to say, that you get the time in a different timezone than you would like, than simply set it in the preferences to the desired timezone.
