### ISSUE TITLE
GPX export

### ISSUE THREAD

**Issue by grcm0278** [tumic0/GPXSee#332]
Hi.
First of all thank You for this tool.
I would like to be able to export a .fit (or other less popular formats) to GPX.
I am aware that will mean a loss of data, but at least for my needs, this will be acceptable.

Thanks in advance.

**Comment by sikmir** [comment]
GPSBabel is what you need to convert FIT (or any other format) to GPX.

**Comment by grcm0278** [comment]
I know.
I was only asking for the ability to anayze AND convert without the need of opening another software.

**Comment by sikmir** [comment]
> Make each program do one thing well. (Unix philosophy)

GPXSee is a viewer.
GPSBabel is a converter.

**Comment by tumic0** [comment]
As already said, GPXSee is a viewer, for converting there is GPSBabel.
