### ISSUE TITLE
No maps shown and Show map grayed out

### ISSUE THREAD

**Issue by lorenzob** [tumic0/GPXSee#334]
Hi, I just built gpxsee on Linux Mint 20 and no maps are show. The gpx files are opened and shown correctly on a white background.
Both the maps button and the menu item are disabled on active position:

![Selection_747](https://user-images.githubusercontent.com/85481/103177927-cbf76780-487e-11eb-9b48-b145f5276c83.png)

I suspect a missing libary, to build it I just had to add qttools5-dev-tools 5.12.8-0ubuntu1

Here is the output running the command from the build directory:

$ ./gpxsee
qt5ct: using qt5ct plugin
No ellipsoids file found.
No GCS file found.
Maps based on a datum different from WGS84 won't work.
No PCS file found.
qt5ct: D-Bus global menu: no

$ ldd gpxsee
	linux-vdso.so.1 (0x00007fff5e7cb000)
	libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f03a0943000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f03a02a8000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f039fcbd000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f039fafc000)
	libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5 (0x00007f039faae000)
	libQt5Concurrent.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so.5 (0x00007f039faa3000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f039f55a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f039f379000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f039f22a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f039f20f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f039f01d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f039eff8000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f039ef70000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f039ef38000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f039ef1c000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f039ee17000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f039ee11000)
	libicui18n.so.66 => /usr/lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007f039eb10000)
	libicuuc.so.66 => /usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f039e92a000)
	libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007f039e8a7000)
	libdouble-conversion.so.3 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007f039e891000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f039e768000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f03a0c05000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f039e6ae000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f039e67a000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f039e5bb000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f039e58e000)
	libicudata.so.66 => /usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f039cacd000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f039ca58000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f039c91b000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f039c8f1000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f039c8eb000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f039c8e3000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f039c8c7000)

$ lrelease gpxsee.pro
Info: creating stash file /home/trz/software/GPXSee-7.38/.qmake.stash
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_en.qm'...
    Generated 1 translation(s) (1 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_cs.qm'...
    Generated 383 translation(s) (383 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_sv.qm'...
    Generated 383 translation(s) (383 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_de.qm'...
    Generated 376 translation(s) (374 finished and 2 unfinished)
    Ignored 7 untranslated source text(s)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_ru.qm'...
    Generated 383 translation(s) (383 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_fi.qm'...
    Generated 383 translation(s) (383 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_fr.qm'...
    Generated 376 translation(s) (374 finished and 2 unfinished)
    Ignored 7 untranslated source text(s)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_pl.qm'...
    Generated 371 translation(s) (368 finished and 3 unfinished)
    Ignored 12 untranslated source text(s)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_nb.qm'...
    Generated 378 translation(s) (375 finished and 3 unfinished)
    Ignored 5 untranslated source text(s)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_da.qm'...
    Generated 335 translation(s) (332 finished and 3 unfinished)
    Ignored 48 untranslated source text(s)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_tr.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 383 translation(s) (383 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_es.qm'...
    Generated 363 translation(s) (360 finished and 3 unfinished)
    Ignored 20 untranslated source text(s)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_pt_BR.qm'...
    Generated 383 translation(s) (383 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_uk.qm'...
    Generated 377 translation(s) (377 finished and 0 unfinished)
    Ignored 6 untranslated source text(s)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_hu.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 383 translation(s) (383 finished and 0 unfinished)
Updating '/home/trz/software/GPXSee-7.38/lang/gpxsee_it.qm'...
    Generated 371 translation(s) (367 finished and 4 unfinished)
    Ignored 12 untranslated source text(s)

$ make
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION=\"7.38\" -DQT_NO_DEPRECATED_WARNINGS -DQT_USE_QSTRINGBUILDER -DPREFIX=\"/usr/local\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o main.o src/main.cpp
[...]
g++ -Wl,-O1 -o gpxsee main.o axislabelitem.o mapitem.o marginswidget.o popup.o coordinates.o rectc.o range.o util.o greatcircle.o programpaths.o tifffile.o app.o gui.o axisitem.o slideritem.o markeritem.o infoitem.o elevationgraph.o speedgraph.o sliderinfoitem.o filebrowser.o scaleitem.o graphview.o waypointitem.o palette.o heartrategraph.o trackinfo.o fileselectwidget.o temperaturegraph.o trackitem.o tooltip.o routeitem.o graphitem.o pathitem.o griditem.o format.o cadencegraph.o powergraph.o gearratiograph.o optionsdialog.o colorbox.o stylecombobox.o oddspinbox.o percentslider.o elevationgraphitem.o speedgraphitem.o heartrategraphitem.o temperaturegraphitem.o cadencegraphitem.o powergraphitem.o gearratiographitem.o mapview.o areaitem.o waypoint.o bitmapline.o bitstream.o deltastream.o gmap.o huffmanbuffer.o huffmanstream.o huffmantable.o huffmantext.o nodfile.o mapdata.o rastertile.o textpathitem.o textpointitem.o bsbmap.o maplist.o onlinemap.o downloader.o emptymap.o ozimap.o polyconic.o tar.o atlas.o ozf.o matrix.o ellipsoid.o datum.o webmercator.o transversemercator.o utm.o lambertconic.o albersequal.o lambertazimuthal.o geotiff.o pcs.o transform.o mapfile.o projection.o gcs.o angularunits.o primemeridian.o linearunits.o mapsource.o tileloader.o wmtsmap.o wmts.o wmsmap.o wms.o crs.o coordinatesystem.o geocentric.o mercator.o jnxmap.o krovak.o map.o geotiffmap.o image.o mbtilesmap.o osm.o polarstereographic.o rectd.o data.o poi.o track.o route.o path.o gpxparser.o tcxparser.o csvparser.o kmlparser.o fitparser.o igcparser.o nmeaparser.o oziparsers.o locparser.o slfparser.o dem.o polygon.o obliquestereographic.o coordinatesitem.o rmap.o exifparser.o imgmap.o img.o subfile.o trefile.o rgnfile.o lblfile.o vectortile.o style.o netfile.o pathtickitem.o textitem.o csv.o cupparser.o graphicsscene.o gpiparser.o smlparser.o pdfexportdialog.o pngexportdialog.o geojsonparser.o qrc_gpxsee.o moc_mapaction.o moc_mapitem.o moc_marginswidget.o moc_app.o moc_gui.o moc_slideritem.o moc_elevationgraph.o moc_speedgraph.o moc_filebrowser.o moc_graphview.o moc_heartrategraph.o moc_trackinfo.o moc_fileselectwidget.o moc_temperaturegraph.o moc_graphtab.o moc_trackitem.o moc_routeitem.o moc_graphitem.o moc_pathitem.o moc_cadencegraph.o moc_powergraph.o moc_gearratiograph.o moc_optionsdialog.o moc_colorbox.o moc_stylecombobox.o moc_percentslider.o moc_elevationgraphitem.o moc_speedgraphitem.o moc_heartrategraphitem.o moc_temperaturegraphitem.o moc_cadencegraphitem.o moc_powergraphitem.o moc_gearratiographitem.o moc_mapview.o moc_bsbmap.o moc_invalidmap.o moc_map.o moc_onlinemap.o moc_downloader.o moc_emptymap.o moc_ozimap.o moc_atlas.o moc_tileloader.o moc_wmtsmap.o moc_wmts.o moc_wmsmap.o moc_wms.o moc_jnxmap.o moc_geotiffmap.o moc_poi.o moc_rmap.o moc_imgmap.o moc_pdfexportdialog.o moc_pngexportdialog.o   /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread

Thanks :)

**Comment by tumic0** [comment]
You are missing the maps (and other stuff like the GCS/PCS CSV files). Those get installed when you run `make install`. If you rather want to build a package, look at the various packages files at the [project's OBS page](https://build.opensuse.org/package/show/home:tumic:GPXSee/gpxsee).
