### ISSUE TITLE
Feature request: GPX Track Replay

### ISSUE THREAD

**Issue by mulka** [tumic0/GPXSee#335]
I'd like to request a feature for replaying GPX tracks. You should be able to press play and it cycles through the track points based on the time in the data.

**Comment by tumic0** [comment]
Like a 7h trip will "play" for seven hours?! I don't think that's a feature many people would use... For a fast "replay" of the track you can use the slider in the graph which is IMHO sufficient. If you desperately need an automatic replay, than you have to use a different tool that has this feature (like Google Earth). GPXSee can not bee simple and intuitive and provide any feature one can imagine at the same time, sorry.

**Comment by mulka** [comment]
Of course it would replay faster than real-time. You should be able to select how fast it replays. Totally understand if it isn't a feature you want in the software.

**Comment by mulka** [comment]
Are there any open source implementations of track replay? I think Google Earth is closed source

**Comment by tumic0** [comment]
I have seen this feature on some webs in the past, but from "offline" tools I know only about Google Earth, sorry.

**Comment by kulbhushanchand** [comment]
@mulka https://github.com/zdila/gpx-animator can output customized animations for track reply.

**Comment by MasterB0Y** [comment]
I also like to see this feature and also ability to compare two tracks and play them simultaneous.
