### ISSUE TITLE
No blank allowed for file names in HREF

### ISSUE THREAD

**Issue by freekruemel** [tumic0/GPXSee#336]
Hi
first I want to thank you for creating GPXSee - very nice and simple tool to view my recorded tracks ... :-)

There is a minor issue which you may be able to help with. Most of my tracks include waypoints which include pictures in JPG format shot during the tour. I grab recorded tracks together with the waypoint pictures from mobile phone and store them on my laptop (Win10). As pictures usually go into a different directory than GPXs I need to adapt the location manually in the GPX file.
Here is my issue - any blank within a file name causes the link to fail when playing back in GPXSee. This works:
- link href="C:\Users\Joach\GoogleDrive\Tours\SampleOne.JPG"
- "SampleOne.JPG"   (under the condition the JPG is in the same directory as the GPX file)

Such as the exmples below fail because of the blank included. The link is shown in the little waypoint window but clicking on it does nothing (instead of showing the JPG):
- "Sample Two.JPG"
- "C:\Users\Joach\Google Drive\Tours\SampleTwo.JPG"
Especially the latter is annoying as in Windows many, many directories do include blank in the name.

May be you know how to avoid this or even can adjust GPXSee.
Many thanks for your support.
Achim

**Comment by tumic0** [comment]
You must use a valid file URI scheme if you want to have properly working links to local files:

```xml
<?xml version="1.0" encoding="utf-8"?>
<gpx version="1.1">
    <wpt lat="50.0411575288" lon="14.5179645717">
        <ele>277.307000171</ele>
        <name>Link test</name>
        <link href="file:///C:/Users/Joach/Google%20Drive/Tours/SampleTwo.JPG">
            <text>Space test</text>
        </link>
    </wpt>
</gpx>
```

**Comment by freekruemel** [comment]
Thanks Martin!

Yes, that works great. Especially with the additional text for the link. 😊

This is absolutely useful in combination when you link pictures directly from Google Drive. As the link name would not give details about the picture behind.

For example:

<?xml version="1.0" encoding="utf-8"?>

<gpx version="1.1">

    <wpt lat="50.0411575288" lon="14.5179645717">

        <ele>277.307000171</ele>

        <name>Link test</name>

        <link href="https://drive.google.com/file/d/15RfyEpCFQZ1khtUptr2qVIbLQUsmMDEM/preview">

            <text>Google Drive test file</text>

        </link>

    </wpt>

</gpx>

 

By the way – the little window for the waypoint (below) details doesn’t show up when using full screen mode (F11). Any idea how the get this even in full screen?

 

Many thanks.

Achim

**Comment by freekruemel** [comment]
Thanks Martin, that did work. Meanwhile I’m using it a bit different. As mentioned my pictures are on Google Drive. I’m inserting the link to the file which I get from Google over Get Link / Copy Link functionality.

This gives me several options.

1.	Use it as it comes https://drive.google.com/file/d/1IsiWtD0aylBaY5b_O4U8tEuSTDVH8xav/view?usp=sharing  

But the view is Google Drive embedded and shows the Google Drive elements.

2.	Then I changed the suffix of the link from …/view?usp=sharing to …/preview

https://drive.google.com/file/d/1IsiWtD0aylBaY5b_O4U8tEuSTDVH8xav/preview  

Which gives you less Google Drive elements and shows the picture a bit larger.

3.	You also could change it to … https://drive.google.com/uc?id=1IsiWtD0aylBaY5b_O4U8tEuSTDVH8xav

Which gives you nothing but the picture in the browser – not a single Google Drive element. Nice to know.



 

Here is an example:

<wpt lat="48.198026" lon="12.214070">

<ele>575.894775</ele>

<time>2021-01-08T10:05:03.087Z</time>

<name>Winterwald</name>

               

               <link href="https://drive.google.com/file/d/1IsiWtD0aylBaY5b_O4U8tEuSTDVH8xav/preview">

                              <text>Biene im Winterwald</text>

               </link>

</wpt>
