### ISSUE TITLE
time tag whitespace parsing issue

### ISSUE THREAD

**Issue by zaari** [tumic0/GPXSee#338]
When a GPX file contains a whitespace inside time tag GPXSee application shows an error message, "invalid time". The following doesn't work:

```
<time>
2020-09-26T17:49:04.999+03:00
</time>
```

While the following does:

```
<time>2020-09-26T17:49:04.999+03:00</time>
```

**Comment by sikmir** [comment]
From https://www.topografix.com/GPX/1/1/:
```xml
    <time> xsd:dateTime </time> [0..1]
```
From https://www.w3.org/TR/xmlschema-2/#dateTime:
```
 The ·lexical space· of dateTime consists of finite-length sequences of characters of the form: '-'? yyyy '-' mm '-' dd 'T' hh ':' mm ':' ss ('.' s+)? (zzzzzz)?, where

    '-'? yyyy is a four-or-more digit optionally negative-signed numeral that represents the year; if more than four digits, leading zeros are prohibited, and '0000' is prohibited (see the Note above (§3.2.7); also note that a plus sign is not permitted);
    the remaining '-'s are separators between parts of the date portion;
    the first mm is a two-digit numeral that represents the month;
    dd is a two-digit numeral that represents the day;
    'T' is a separator indicating that time-of-day follows;
    hh is a two-digit numeral that represents the hour; '24' is permitted if the minutes and seconds represented are zero, and the dateTime value so represented is the first instant of the following day (the hour property of a dateTime object in the ·value space· cannot have a value greater than 23);
    ':' is a separator between parts of the time-of-day portion;
    the second mm is a two-digit numeral that represents the minute;
    ss is a two-integer-digit numeral that represents the whole seconds;
    '.' s+ (if present) represents the fractional seconds;
    zzzzzz (if present) represents the timezone (as described below).
```
So, whitespace is not allowed inside time tag.

**Comment by tumic0** [comment]
What application is the producer of such GPX files? As sikmir writes, whitespace is not allowed in xsd:dateTime, so unless it is Strava, Apple or some other "too big to fail" apps (where your application is always the broken one if it fails to read files produced by them regardless of the standards...), I won't add a spare trim() and you better report it as a bug to the producer.

**Comment by zaari** [comment]
Well, in this case the service is heiaheia.com which is a sports tracker app/service used in the Nordics. I submitted them a bug report yesterday. Let's see what their priorities are.

**Comment by tumic0** [comment]
Ok, then I'm closing the issue. This app is definitely not in a position that it can produce broken GPX files and expect others to workaround their bugs.

**Comment by zaari** [comment]
For your records, the bug was recently fixed by the service.
