### ISSUE TITLE
gpxsee crashes when loading a igc file

### ISSUE THREAD

**Issue by mhusmann** [tumic0/GPXSee#339]
When loading an igc file into gpxsee gpxsee chrases with the following:
/usr/share/gpxsee/maps/Antarctica.xml: Antarctic_Basemap: layer not provided
fish: 'gpxsee' terminated by signal SIGSEGV 

Any advice?

**Comment by tumic0** [comment]
Please provide the IGC file, without the file there is nothing I can do about the crash.

**Comment by mhusmann** [comment]
Hi Martin,

attached the file.

Thank you and best regards
Michael


Am Sa., 23. Jan. 2021 um 17:34 Uhr schrieb Martin Tůma <
notifications@github.com>:

**Comment by tumic0** [comment]
Please attach the file to a comment on the GitHub issue webpage, sending attachements using mail does not work on GitHub.
(= I did not receive any file)

**Comment by mhusmann** [comment]
OK, I do

Am Sa., 23. Jan. 2021 um 17:46 Uhr schrieb Martin Tůma <
notifications@github.com>:

**Comment by mhusmann** [comment]
I'd like to attach a file but how can I do?

**Comment by tumic0** [comment]
Click on the text _Attach files by dragging & dropping, selecting or pasting them._ and a file select dialog should appear.

**Comment by mhusmann** [comment]
That's what I tried but then the error message "We don't support that file type" comes up

**Comment by mhusmann** [comment]
Next try as a zip file
file:///home/mhusmann/Documents/fliegen/2021/2021-01-23-XCT-MHU-02.zip

**Comment by mhusmann** [comment]
[2021-01-23-XCT-MHU-02.zip](https://github.com/tumic0/GPXSee/files/5860589/2021-01-23-XCT-MHU-02.zip)

**Comment by mhusmann** [comment]
Thank you! Martin,

I just compiled the project.
It runs

Kind regards
Michael

Am Sa., 23. Jan. 2021 um 18:25 Uhr schrieb Martin Tůma <
notifications@github.com>:

**Comment by tumic0** [comment]
The bug was introduced in 8.2 where a lot of the internal path/graph logic has changed. It is not IGC related but all files that have some empty paths like your IGC file will crash GPXSee. So I will most probably release a fixed, 8.3 version soon.
