### ISSUE TITLE
No graph menu and button grayed

### ISSUE THREAD

**Issue by gitdevmod** [tumic0/GPXSee#340]
HI,

I've succcesfully build GPXSee from github source without error on Windows 10 with KDE/Craft.
I can import fit or gpx files but I can not enable graph.
There is no error on console,  with DebugV:iewer:

`
[7496] No ellipsoids file found.
[7496] No GCS file found.
[7496] Maps based on a datum different from WGS84 won't work.
[7496] No PCS file found.
`

Files installled:
C:\KDE-Craft\CraftRoot\bin\gpxsee.exe
C:\KDE-Craft\CraftRoot\share\gpxsee\maps\4UMaps.xml
C:\KDE-Craft\CraftRoot\share\gpxsee\maps\Antarctica.xml
C:\KDE-Craft\CraftRoot\share\gpxsee\maps\OpenStreetMap.xml
C:\KDE-Craft\CraftRoot\share\gpxsee\maps\OpenTopoMap.xml
C:\KDE-Craft\CraftRoot\share\gpxsee\maps\USGS-imagery.xml
C:\KDE-Craft\CraftRoot\share\gpxsee\maps\USGS-topo.xml

**Comment by gitdevmod** [comment]
Problem fixed :
Thanks to Help->Paths menu, maps must be in %appdata%/GPXSee/maps.
Now I can view my track with maps.
Is this possible to change maps path at compilation ?

**Comment by tumic0** [comment]
> Is this possible to change maps path at compilation ?

There are no defines or such thing for it as the standard QT functions are used, but you can of course modify the [programpaths.cpp](https://github.com/tumic0/GPXSee/blob/master/src/common/programpaths.cpp) source to fit your needs.

**Comment by sikmir** [comment]
> Is this possible to change maps path at compilation ?

Try to run GPXSee with proper APPDATA environment variable specified. It should work like XDG_DATA_HOME on Linux.

**Comment by gitdevmod** [comment]
$env:APPDATA contains C:\Users\user\AppData\Roaming
GPXsee should try first search in C:\KDE-Craft\CraftRoot\share\gpxsee\maps where GPXSee is installed ?
Using GPXSee official installer it finds maps without search in APPDATA directory

**Comment by gitdevmod** [comment]
Maybe AppDataLocation variable in KDE/Craft does not point to C:\KDE-Craft\CraftRoot\share\gpxsee. I need to read code :)

**Comment by tumic0** [comment]
There are two locations, where GPXSee searches for data - the "user" location and the "system" location. The "user" location takes precedence over the "system" location. For details what the "user" and "system" location is, see the documentation of [QStandardPaths](https://doc.qt.io/qt-5/qstandardpaths.html).
