### ISSUE TITLE
Option to display (download) errors on tiles

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#341]
Hello,

When error downloading a tile occurs, a blank tile is displayed.
Maybe URL (with parameters x, y, z...) should be displayed on tiles which have error (and a part of the exception should be displayed on tile also).
It should, at least, be a "debug" option for GPXSee.
MOBAC https://mobac.sourceforge.io/ provides such a feature.

Kind regards

**Comment by tumic0** [comment]
The errors are printrd to stderr. All you need to do for "debuging" download errors is to run GPXSee from the terminal (Linux, OS X) or using DebugView or a similar tool on Windows.
