### ISSUE TITLE
CLI informations

### ISSUE THREAD

**Issue by DavidHenryThoreau** [tumic0/GPXSee#344]
I suggest add a command line options in order to get gpx informations, i mean highest elevation,total distance, total elevation..
I want to get these info by script running not by opening the software, or maybe do you know tools that return these informations ?

**Comment by sikmir** [comment]
* [gpx-cmd-tools](https://github.com/tkrajina/gpx-cmd-tools) - Commandline tools for GPX
* [gpxtools](https://notabug.org/irdvo/gpxtools) - A collection of command line tools for using GPX files

**Comment by tumic0** [comment]
This is completely out of scope of GPXSee. Try one of the mentioned programs.
