### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by latot** [tumic0/GPXSee#346]
Hi hi, I'm using ver 7.29, and I have the next issue.

Seems GPXSee is not detecting the colors, I have a kml with all red polygons, but all of them show with different colors... (I made the kml with simplekml in python, I can confirm in google earth all the polygons are red and show them)

![pic](https://user-images.githubusercontent.com/10523095/107862958-3fedcf00-6e2f-11eb-87bb-1eed43d9ab5e.png)

Thx!

**Comment by tumic0** [comment]
KML styles are not supported in GPXSee. There is no styling in any other supported data format (well, GeoJSON has some unofficial extensions) and GPXSee is a general GPS data viewer, not a full featured KML viewer. It is designed to handle a common subset of all the data formats. In fact, most of the features KML can offer won't work in GPXSee. If you need a full featured KML viewer, use Google Earth as there is no other tool that supports all KML features except of Google Earth...

**Comment by latot** [comment]
D: sadly google earth can't do the job.., crash too fast if you load a big kml....

I would recommend include how is the support for KML and other formats, at least, if the app can "open" KML at least I would interpret the app support it.

Thx!

**Comment by tumic0** [comment]
It is mentioned in the [documentation](https://www.gpxsee.org/doc.html#data), that not all format features are supported for all formats, **especially KML**. GPXSee is mainly a track/route/waypoint viewer which is IMHO quiet clear from all the presentation/documentation, not a GIS tool (which is also explicitly stated on the homepage). Full KML support is clearly out of scope of GPXSee as KML is the most complicated GIS format out there...
