### ISSUE TITLE
Request: option to display distance with 2 decimal point accuracy

### ISSUE THREAD

**Issue by harrywalther** [tumic0/GPXSee#347]
Hello, 
first, thank you for maintaining this program - it's the best FIT format reader I am aware of!
I frequently use it to measure point to point distances in miles of trail runs I have done, and 1 decimal point just doesn't cut it for that purpose. I've patched the code myself to display 2 decimal points in the graph window (on Linux, very simple actually) but I wonder if you'd find it worth your while to integrate a display option to take care of this in future versions. 

Happy Trails!

**Comment by tumic0** [comment]
I don't think that increasing the precision makes any sense. Except for the shortest tracks, let's say under a few hundred meters in ideal conditions, the GPS error is much higher than 10m with any "consumer grade" device. So using two decimal points would only give the user a false feeling of a much higher accuracy than his data can ever have. And doing some auto-adjustment or even setting for the rare cases, where it may matter is simply not worth it, sorry.

There is however still good news for you - if you switch from the "Arbitrary Retarded Rollercoaster" units to SI units used in the rest of the world, you get a 60% accuracy increase for free :-)

**Comment by harrywalther** [comment]
The scenario you are describing is exactly I would want to use it for. I know that the absolute position of a GPS coordinate can't be trusted to be any more accurate than to about 20 ft (in what you refer to as "Arbitrary Retarded Rollercoaster system" - sorry, I don't have much of a choice here. It is what it is.) but the distance between points is generally much more accurate, since the direction of the position error does not change randomly every few minutes. I live in an environment with few trees, very dry air and quite a bit above sea level, so measuring reasonable distances this way make sense for me. 

But whatever. As I said, it's no big deal to do that myself - or go back to Google Earth for that purpose.

**Comment by tumic0** [comment]
> what you refer to as "Arbitrary Retarded Rollercoaster system"

That's not my invention, see Google for how much used this term is. I do of course not use the term in the program, but in informal conversation it illustrates the feelings about it of someone living the whole life in the SI units world quiet well, sorry.

> but the distance between points is generally much more accurate

Well, yes and no. For straight routes this may be true, but as long as there are curves, you get almost always some not negligible error. Sometimes corners are cut, sometimes (when the unit uses internally some kind of Kalman filter) they are extended.

Anyway, the good thing about opensource is, that you can adjust it to your needs when you need some nonstandard feature. And in this case it is pretty simple as you write - just increase the print precision on the places that you are interested. The "exact" (whatever this means) result is already there, it's just the output that needs to be adjusted.
