### ISSUE TITLE
Time skew

### ISSUE THREAD

**Issue by Tux** [tumic0/GPXSee#349]
If a track has (too) many points (very) close to eachother, the time (without microseconds) between two points willl be the same, and src/data/track.cpp#135 will throw a warning `time skew detected`
I'd appreciate this if/else to be either
```
				if (sd.at(j).timestamp() >= sd.at(j-1).timestamp())   /* >= instead of > */
					dt = sd.at(j-1).timestamp().msecsTo(
					  sd.at(j).timestamp()) / 1000.0;
				else {
					qWarning("%s: %s: time skew detected", qPrintable(
					  _data.name()), qPrintable(sd.at(j).timestamp().toString(
					  Qt::ISODate)));
					dt = 0;
				}
```
(easiest, still correct and a lot less noisy)
or that this if/else gets a new block for time stamps being equal, like
```
			if (hasTime && sd.at(j).timestamp().isValid()) {
				QDateTime cdt, pdt;
				cdt = sd.at(j  ).timestamp();
				pdt = sd.at(j-1).timestamp();
				if (cdt  > pdt)
					dt = pdt.msecsTo(cdt) / 1000.0;
				else
				if (cdt == pdt)
					dt = 0;
				else {
					qWarning("%s: %s: time skew detected", qPrintable(
					  _data.name()), qPrintable(cdt.toString(Qt::ISODate)));
					dt = 0;
				}
```
(or similar)

**Comment by tumic0** [comment]
The `>` is intentionally there. You should not have two entries with the same time in the log file. In the best case one of them is surplus, but usually they have even different coordinates which is "broken by definition" - you can not be at two places at the same time.

From what I have seen in your data, you use your own perl script to generate the GPX file. Either use a `<time>` with seconds fractions (this is allowed in xsd:dateTime/ISO 8601) or at least do not write the entry if the time is the same as in the previous entry.
