### ISSUE TITLE
Absolute time graph

### ISSUE THREAD

**Issue by UnderSampled** [tumic0/GPXSee#35]
It would be nice to be able to have graphing by absolute time, so multiple tracks can be strung together, and also compare tracks recorded at the same time but different starting times.

**Comment by tumic0** [comment]
Yes, absolute time (distance?) graphs make sense for some use cases, however after a quick research it seems that this feature would require quiet a lot of changes in the code/data structures. So it won't happen that soon...

**Comment by cyrsap** [comment]
I'd love to see this feature too

**Comment by j-schneid** [comment]
This is something I am missing, too. There is the possibility to concatenate several tracks which has a similar results, but they then have the same colour and seemingly this is not reversible.

**Comment by scls19fr** [comment]
This is probably not enough for some of us... but showing in statistics start of flight time could be an interesting feature to have https://github.com/tumic0/GPXSee/issues/228 (probably easier to implement than absolute time graph)

**Comment by alranel** [comment]
Maybe you can implement this by just adding some padding at the beginning of all the tracks until their initial points are aligned?

**Comment by alranel** [comment]
As an alternative, can't you just add an `initialTimestamp` property to the `Graph` class, that you populate when generating the `Graph` object and you use at rendering time to shift the generated segments?

**Comment by tumic0** [comment]
I'm afraid that there is no such easy solution... I was of course thinking about such hacks, but you soon realize that there is always some problem that would need another hack that would need... Also note, that the code has become much more complex during the time (there is for example outlier elimination and support for segments now) which makes things even harder. So the chance that GPXSee will get support for absolute time graphs is quite small and keeps falling...

**Comment by alranel** [comment]
I really like GPXSee and I would like it to have this feature. My use case is to collect and compare the GPS tracks created simultaneously on multiple boats during a yacht race.

The addition of track segments might help, actually. You might add a property to distinguish actual track segments from pause segments, and you might generate such pause segments automatically at load time whenever there's a significant gap between two segments. At rendering time you'd just skip the drawing part. Anything else should just work.
I don't think this is a hack. I believe this is a legit way to represent gaps in data structure. :)
What do you think?

**Comment by Peter2121** [comment]
I would like to see this feature too

**Comment by sditn** [comment]
(Moved from different issue)

I just downloaded GPXSee for the first time and it's great - thanks to all devs that have supported this project. I would like to add an +1 to this feature request. **Example Use Scenario:** I download and store a GPX file that contains all my movements for a given calendar month, the GPX file loads just great. I would like to be able to click on a given route point / GPS hit on the map window and see what the time and date was at that moment.

**Comment by sditn** [comment]
I have just posted #330 as I think my issue may be slightly less onerous.

**Comment by hieu-van** [comment]
It's sad that 3 years have passed and still there has been no progress on this… If this is a must, I suggest checking out GpsMaster. It can display absolute time as the timestamp in the GPX file itself

**Comment by tumic0** [comment]
You are right that it is time to close the issue. Absolute time graphs will simply never happen in GPXSee. You have the absolute time in the path marker since some time which is "good enough" for me.

GpsMaster can display absolute time in the graph, but this is quite easy in a program that can only show a single graph of a single track which is not the case of GPXSee.
