### ISSUE TITLE
map support

### ISSUE THREAD

**Issue by guerrierodipace** [tumic0/GPXSee#350]
no supports for maps from openandromaps https://www.openandromaps.org/en?
thanks

**Comment by tumic0** [comment]
Not yet.

**Comment by tumic0** [comment]
Added in 44a5e5de81f0c418df6155ef9759d5a2be14be82

**Comment by Tux** [comment]
Nice! I don't see it in the Maps menu to select. Should it? Or did I do something wrong on installation?

**Comment by tumic0** [comment]
It shall work like any other offline map in GPXSee. If you want the map to be permanently listed in the menu, than you have to put the map file (or a symlink) to one of the maps directories. And of course you need to compile the GIT master, it is not yet released.

**Comment by Tux** [comment]
I compile from git on every commit :) I love your project and I am thrilled to learn from GPX files and features with every change!
gpxsee is *the* reason am am into GPX. I have learned to use it to plan my hikes a lot more effecient than I used to.
If we ever meet, I owe you beer (or any drink you prefer)

**Comment by tumic0** [comment]
There is no xml for the map, it is an offline map. You have to put the downloaded `*.map` data file to the `maps` directory. You can get the maps for example here: http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/v5/
