### ISSUE TITLE
OSX Version: No actions on POI menu

### ISSUE THREAD

**Issue by pramach** [tumic0/GPXSee#353]
Version 8.7 (x86_64, Qt 5.15.2) German
OSX Big Sur

Hi

In OSX Finder, I click on a GPI (or GPX) File and select to be open with GPXSee.
In Footer Status line, the file I have opened is shown.
In the Map, the POI's from the GPI file are shown.
In the Buttons List, regardless if the Button "Show POI" is on or off, no differences. POI's are shown.
In the Menu "POI", ...
  * the first item "POI Files" has an arrow for a sub menu, but it is empty.
  * however it list files when I open them via second item "Load POI", but no POI's are shown on the map and status line says "No file loaded"
  * when click on "Close POI" then all loaded POI's via "Load POI" are closed without giving me a chance to select which file I want to close (However that might be a new feature)
  * whatever I click on or off of "Show POI Labels", "Overlap POI" or "Show POI", there is no difference on the map.

Both GPI and GPX just show some waypoints, not a route.

As I Mainly anyway use it with one GPX or GPI directly from Finder, I have not a problem with this behavior, I just noticed it. And maybe I misunderstand the means of the POI Menu.

Thanks anyway for this famous Tool.
Wolfgang

**Comment by tumic0** [comment]
The POI files in GPXSee are something a little bit different than you expect. If you want to open a file with waypoints, then simply open it as a data file and all the waypoints will be shown. POIs in GPXSee get only shown, when they are in a given range near the loaded data (tracks/points/areas).

The POI use case in GPXSee is that you can have loaded e.g. a POI file with Gas stations and using the "Show POIs" feature see all Gas stations near a loaded track.

**Comment by pramach** [comment]
Hi Martin

Thanks for explanation.

Is there somewhere a POI example file available, so I can see the 
difference ?

kr Wolfgang


Am 20.03.21 um 21:10 schrieb Martin Tůma:

**Comment by tumic0** [comment]
There is no difference in the files itself, it's the same formats as the data files (GPX, KML, CSV, ...). The difference is only in the way how the files are used. If you are looking for some samples, then for my country I use POIs from https://poi.cz/. But there are numerous services that provide POI files per category on the internet.

**Comment by pramach** [comment]
OK Thank you.
