### ISSUE TITLE
Wish: ability to play integrated sounds of TourGuide GPI

### ISSUE THREAD

**Issue by pramach** [tumic0/GPXSee#354]
Hi

When I create a GPI file with images, the images are shown.

When the GPI also contains mp3 audio files (TourGuide), it would be great to have the possibility to play the mp3 too.

Thx
Wolfgang

**Comment by tumic0** [comment]
I will definitely not add mp3 support into GPXSee, but the files could be at least played by the standard system audio player, like when you open the images from GPI files. Please provide some GPI file sample with a mp3 file so I can implement/test it.

**Comment by pramach** [comment]
First of all thanks to your incredible fast replies.
A GPI example have been send to you by mail, hope it is OK.

**Comment by tumic0** [comment]
Nothing has arrived. If the file is not "secret", than the best option is to put it here as an attachment (needs to be ZIPed for Github to accept it).

**Comment by pramach** [comment]
[TourGuide-PK-DONE.gpi.zip](https://github.com/tumic0/GPXSee/files/6177212/TourGuide-PK-DONE.gpi.zip)
Then here.

**Comment by pramach** [comment]
Hi, just noticed that you have released 8.9.
Thanks for.

**Comment by tumic0** [comment]
I have looked at the data and the sounds seems not to be a property of a single waypoint but rather a property of a waypoints group (area). Theoretically GPXSee could show an area with a the mp3 download link, but all together it is so specific, that I have decided to rather let this to some GPI-specific tool.
