### ISSUE TITLE
Using HGT elevation data - I can not get it to work

### ISSUE THREAD

**Issue by heinerolli** [tumic0/GPXSee#357]
I would like to see the elevation profile from a gpx track WITHOUT elevation data, by including DTM elevation data (from https://data.opendataportal.at/dataset/dtm-europe, which provides hgt format data).
This does not work for me:
I put that data (hgt files) in C:\Program Files\GPXSee\DEM (I am on Windows 10); I also tried putting it C:\Users\user1\AppData\Roaming\GPXSee\DEM. 
After putting the hgt files there and restarting GPXSee, GPXSee crashes. Restarting again works, but an elevation plot is still not availalble. 
Is this a bug, or am I doing something wrong?
(Also, under Settings -> Data in the Tab Datasources, I select DEM-Data)

**Comment by tumic0** [comment]
I guess the filenames are wrong. GPXSee expects the files to be named `NYYEXXX.hgt.zip` while https://data.opendataportal.at provides files named `NYYEXXX.zip`. You should see a warning message on stderr (on windows you have to use a tool like DebugView to see the messages).

Can you provide more info about the crash (a stack trace)? The program should not crash regardless what files it finds in the DEM directory.

**Comment by heinerolli** [comment]
Hi Martin;
thanks for the fast reply and the hint for DebugView.
After renaming the zip file, the app still crashed. Also, it still did not show the elevation data after reopening it.

However, after unzipping - which put the file in this path:
C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014\N51E014.hgt
and moving the file one folder up in:
C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014.hgt
it worked! Thank you!

WRT crash debug: I would be glad to help, but you need to give a bit of guidance:
I don’t know what ‘a stack trace’ is or how to retrieve it….

Best, Heiner


Von: Martin Tůma ***@***.***>
Gesendet: Samstag, 3. April 2021 15:42
An: tumic0/GPXSee ***@***.***>
Cc: heinerolli ***@***.***>; Author ***@***.***>
Betreff: Re: [tumic0/GPXSee] Using HGT elevation data - I can not get it to work (#357)


I guess the filenames are wrong. GPXSee expects the files to be named NYYEXXX.hgt.zip while https://data.opendataportal.at provides files named NYYEXXX.zip. You should see a warning message on stderr (on windows you have to use a tool like DebugView to see the messages).

Can you provide more info about the crash (a stack trace)? The program should not crash regardless what files it finds in the DEM directory.

**Comment by tumic0** [comment]
Yes, `C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014.hgt` is the correct path. Or `C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014.hgt.zip` when using the ZIPed version of the file.

Regarding the crash dump - if you are not familiar with Windows application development, than it would be quiet hard to explain as it requires to use WinDbg and maybe also to create a GPXSee build with debug symbols. And to be honest, I don't have the time to explain all the stuff to someone from scratch, especially when Windows is not my primary platform and even I may not be familiar with all the situations that may arise. So let's rather hope someone else can report that with more info.

**Comment by heinerolli** [comment]
Thats ok.
Just to clarify the crash situation, in case you want to replicate:
The 2 szenarios you quoted behave different:


„Yes, C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014.hgt is the correct path."           --> This one works

„Or C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014.hgt.zip when…“                         --> This one crashes

The different behavior might be related to how things are unzipped in Windows(?)
Because as stated earlier, a manual unzip of the above (2nd case)  results in the unzipped file being at this location (in an added new subdirectory):

C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014\N51E014.hgt




Von: Martin ***@***.***>
Gesendet: Samstag, 3. April 2021 22:37
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [tumic0/GPXSee] Using HGT elevation data - I can not get it to work (#357)


Yes, C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014.hgt is the correct path. Or C:\Users\tanja\AppData\Roaming\GPXSee\DEM\N51E014.hgt.zip when using the ZIPed version of the file.

Regarding the crash dump - if you are not familiar with Windows application development, than it would be quiet hard to explain as it requires to use WinDbg and maybe also to create a GPXSee build with debug symbols. And to be honest, I don't have the time to explain all the stuff to someone from scratch, especially when Windows is not my primary platform and even I may not be familiar with all the situations that may arise. So let's rather hope someone else can report that with more info.

**Comment by tumic0** [comment]
Can you please put here as an attachment the exact zipped DEM file, that causes the crash?

**Comment by heinerolli** [comment]
Here you go:
[N51E013.zip](https://github.com/tumic0/GPXSee/files/6254894/N51E013.zip)

**Comment by heinerolli** [comment]
Nevermind.... just updated from 8.8 to 8.9 and the issue is gone!
Putting zipped file N51E013.hgt.zip here:
C:\Users\tanja\AppData\Roaming\GPXSee\DEM
works! No crash - data is accepted & used.
Thank you & Happy Easter

**Comment by heinerolli** [comment]
P.S: Thank you for adding the DEM naming convention into your help file (http://www.gpxsee.org/doc.html)
