### ISSUE TITLE
[feature request] Support .gz for DEM/HGT

### ISSUE THREAD

**Issue by Tux** [tumic0/GPXSee#358]
Reading the other issue about not being able to use DEM data on Windows, I just had to play with it.

I was *thrilled* to see this work, and it added a lot of value to what I am doing with GPX tracks, so ++ to you for supporting it the way you do!

I however found that I had similar data already stored where the app requires .gz compression instead of .zip, so now I have the whole set double stored :(
I also asked the other app to support .zip, but no reply yet. Maybe it is easy to support .gz from gpxsee as well

Anyway, very low prio, and thanks for this wonderful tool!

**Comment by tumic0** [comment]
Although it may be quiet easy to add support for gzip compressed DEM files, it would require GPXSee to depend on gzip which I'm trying to avoid. And in this case it is really not worth to loose the nice feature that all you need is QT to build GPXSee for a quiet non-standard file type support (the DEM files are usually distributed compressed using ZIP).
