### ISSUE TITLE
Keyboard shortcuts / next-previous point 

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#359]
Hello,

when focus is on Altitude or Speed tab supporting left/right arrows as keyboard shortcuts to move to next or previous point could be a nice improvement.
Thanks again for this nice software.

Kind regards

**Comment by tumic0** [comment]
There is no "next point" in the graphs, the lines are seen as continuous functions by the display/slider logic. Moreover, the left/right keys are already taken by moving the graph view when the graph is zoomed in.

**Comment by scls19fr** [comment]
Sorry by I don't see how data can be "continuous" given that GPS receiver have a sampling period.
Even if it is continuous functions a small time increment (to be defined) could be used.
j / k could be used (j = previous / k = next)

**Comment by tumic0** [comment]
What I was trying to say is, the graphs are not designed to make steps according to the data points. There is of course some interpolation as the data is discrete, but it is the screen coordinates that is the "source of move". So the slider could probably move some fixed amount of pixels on a key press, but not to the next GPS point.

But there is still the problem with the keys, that are already taken for moving the graph view when it is zoomed in. Some other keys like "<" and ">" could of course be used, but it is questionable whether this would be intuitive for the user. Finally - I'm almost always using a mouse which is much better to move the slider, so I have little motivation fiddling with some keyboard code...
