### ISSUE TITLE
Just one more zoom level please

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#361]
These days only allowing zooming to level 17 leaves the user begging for more.
So add just one more zoom level please.
See also #154, #20. Thanks.

**Comment by tumic0** [comment]
There is nothing I can do about it. If the map only has 17 levels, then you will only get 17 levels... (you can use the digital zoom to zoom further in, but that won't of course give you more details). You can however choose some other [map](https://tumic0.github.io/GPXSee-maps/) or request the extra level at the map provider (OpenTopo maps, 4u maps, ...).

**Comment by Tux** [comment]
https://www.openstreetmap.org/#map=19/52.52326/6.48736 ← goes to level 19

**Comment by jidanni** [comment]
All I know is I was on open topo map and I looked around for a GitHub link inside the German text and ended up here.

**Comment by Tux** [comment]
![2021041014:35:15-001](https://user-images.githubusercontent.com/2492/114269978-2372ab00-9a0a-11eb-8c2f-8992234d9f3a.png)

**Comment by endolith** [comment]
Please let us zoom in more than the max zoom of the tiles, so we can see details in dense tracks and read the timestamp labels, etc. 
![image](https://github.com/user-attachments/assets/aa81d75d-d951-4015-9222-6acddf08e1b3)

**Comment by tumic0** [comment]
It's already there, it's called digital zoom.
