### ISSUE TITLE
Unable to run GPXsee on MacBook Air M1 with Big Sur 11.2.3

### ISSUE THREAD

**Issue by emulb-git** [tumic0/GPXSee#364]
Hi,
i get the following error message:
"GPXSee" cannot be opened because Apple cannot search for malware in it. 
This software needs to be updated. Contact the developer for more information. "

Tried both ways
- installed dmg package
- installed with brew

Any ideas how to solve this?
TIA
Carsten Blume

**Comment by tumic0** [comment]
You have to open the application using the right-click menu for the first time, like described on the homepage. There are also several duplicit issues like #234 here, where you can find more info.

There may be also some problem with running GPXSee on M1 as it must be run emulated as there is no OS X ARM build of GPXSee (maybe in homebrew/macports?). There is however not much I can say/do about it as I do not have access to M1 HW and as long as there is [zero user interest](https://github.com/sponsors/tumic0) for M1 support in GPXSee this won't change. In fact OS X support will be dropped from GPXSee sooner or later without the appropriate user interest as things will break one day.
