### ISSUE TITLE
Not loading POI from GPI

### ISSUE THREAD

**Issue by pschonmann** [tumic0/GPXSee#366]
Hi,
when i download file from https://osm.gpsfreemaps.net/osmcz_notes/OSMCZ_NOTES_LATEST.gpi i cant see all points. Seems little bbox is displayed, not all POIs in FILE.
Source of this file is https://api.openstreetmap.org/api/0.6/notes.gpx?bbox=12.09059002,48.55180822,18.85918143,51.05570356&closed=0&limit=10000 transformed with gpsbabel 1.70

gpsbabel -D 9 -w -i gpx -f $FILENAME.gpx -o garmin_gpi,alerts=1,category="OSMCZ_NOTES",descr=1,proximity=100,unique=0 -F $FILENAME.gpi

**Comment by tumic0** [comment]
Do all the POIs show up in some Garmin SW/unit? Because from what I know about the GPI format, the file is not a valid GPI file. But both me and GPSbabel can be wrong as there is, as usual at Garmin, no official format documentation and all that is known is based on reverse engineering.

**Comment by pschonmann** [comment]
Oh ! Probably GPI was generatd wrong on cronjob. When manually, looks fine.
You can use another file 
https://osm.gpsfreemaps.net/cpost_gpi/OSMCZ_CPOST_LATEST.gpi 
https://osm.gpsfreemaps.net/rozcestniky_gpi/OSMCZ_ROZCESTNIKY_LATEST.gpi
this is same problem, GPI generated ok. All points in units loaded ok. But i cannot see them all in gpxsee

**Comment by tumic0** [comment]
Ok then. Should be fixed in d33bcd1e5599b94925bf751391f53ec43d17ee26.
