### ISSUE TITLE
Transition between zoom levels

### ISSUE THREAD

**Issue by shujaatak** [tumic0/GPXSee#37]
I noticed that the zoom transition is very abrupt sometimes when the internet is slow and you change the zoom level the screen goes white for a long time until new tiles are downloaded. While GPXSee is the fantastic utility, it works perfectly and gets the job done! but the lack of above mentioned minor enhancement gives a bad impression/user-experience to the people who are not aware of how hard it is to code even what they have currently! Seeing the white screen they just come to wrong conclusion that GPXSee crashed or something.
User who are used to online maps like google, bing etc would expect the smooth transition (zooming the currently loaded tiles until new zoom level tiles are loaded). This would make the screen filled with something all times and engage the user.
By the way, Thanks a lot for this awesome utility! Happy coding!

**Comment by tumic0** [comment]
Sorry, but I don't like the idea of trying to hide a slow network from the user. And personally I dislike the "smooth" zoom effects that Google (and other maps) do between layer switches. But most important, this would require quiet a lot of work, that can be spend elsewhere more useful. Maybe one day when there is nothing else to do... ;-)

**Comment by scls19fr** [comment]
smooth transition is probably something difficult to implement but maybe a workaround to provide a better user experience could be to display (in title bar or status bar for example) zoom level before full download of map.
An icon in status bar could change color when downloading map to warm user that it's currently being downloaded (but it's not yet ready)... avoiding several involuntary zooming
