### ISSUE TITLE
Option to switch x Axis to Time (Single File)

### ISSUE THREAD

**Issue by ph4r** [tumic0/GPXSee#372]
I feel like the program has to already have this and I just can't find it.  I use this to review my children's fit files and it currently always displays all data against the distance covered; however, I would like to be able to switch back and forth between displaying in the current mode and displaying the collected data against time. Hopefully, this is easier than #35 or is already existing and I just need to do 'x' to switch between modes.

**Comment by tumic0** [comment]
> I just need to do 'x' to switch between modes

Have you actually tried to press the x button? Because that's the key that changes the X axis :)
You can also find this option in the `Graph` menu.
