### ISSUE TITLE
Segmentation fault when deleting file in same folder

### ISSUE THREAD

**Issue by Tux** [tumic0/GPXSee#373]
Running 9.1 (x86_64, Qt 6.0.3)

When a folder has more than one .gpx file and I open one of them with gpxsee
```
$ gpxsee file1.gpx &
```
and then delete another gpx file in the same folder
```
$ rm file2.gpx
```
gpxsee crashes with a segmentation fault:
```
Thread 1 "gpxsee" received signal SIGSEGV, Segmentation fault.
0x00007ffff524b8db in QFileInfo::QFileInfo(QFileInfo const&) () from /usr/lib64/libQt6Core.so.6
```

**Comment by tumic0** [comment]
I couldn't reproduce the crash, but there was some problematic part in the data dir changes watching code which could be the cause. It is "fixed" together with some related improvements in a53f20314f1c3545ef3e21be60de4d30dad03699. Please test and report if it fixes the issue.

**Comment by Tux** [comment]
No more crashes! Thanks for the quick fix!
