### ISSUE TITLE
Request of compiled 7.1.3 release

### ISSUE THREAD

**Issue by caspertone2003** [tumic0/GPXSee#374]
I would be interested in comparing one behaviour of version 9 and 7.1.3
I am unable to compile 7.1.3 from source.
Could you perhaps upload 7.1.3 to a cloud drive for a while and provide a public download url?
Thanks in advance,
CT

**Comment by tumic0** [comment]
There has never been a 7.1.3 version of GPXSee. And even if you mean 7.13 I really do not have the resources to prepare a personal build for every user without a very good reason (= where there is some benefit for the project), sorry.

**Comment by caspertone2003** [comment]
Thanks for the reply.
You are right, I am interested in 7.13
There is a reason behind, I am trying to tell apart "inglorious" pseudo-NTs from no-NT from real NT IMGs
Then, applying a post 7.13 and 7.13 to an img would tell pseudo-NTs from others.
While this is not directly of the project interest, I believe it would be a benefit for the community, as I have not found a tool that tells apart those three kinds.
It was not my intention to disturb you, I just thought it would be easy that you would keep a copy of each produced version, so I was only asking for an upload. or, if would be possible, to email.
Thanks anyhow.
CT

**Comment by tumic0** [comment]
> There is a reason behind, I am trying to tell apart "inglorious" pseudo-NTs from no-NT from real NT IMGs

As IMG is not a file format but rather an _exponential state space of special cases_, the only way how to handle it is to try to open the IMG file in your desired tool and see if it works.

> It was not my intention to disturb you, I just thought it would be easy that you would keep a copy of each produced version, so I was only asking for an upload. or, if would be possible, to email.

I do not keep copies of old binary versions. There is always the last but one available on Sourceforge, but that's it.

**Comment by caspertone2003** [comment]
Thanks!

**Comment by caspertone2003** [comment]
Message in a bottle / Just if someone in the future seeks something similar

While I have a overall exposition to IT, and used to program some centuries ago, I am really surprised how easy doing "something easy" of complex things can be so easy due to the tools available. So, I have been able to get runnning a windows exe of 7.13 of GPXsee (while not statically linked...). Not a single comma of the code needed a change. I really was expecting an epic failure ... but not...
Also I should say, that being the tools so advanced, I wonder why they did not went the last meters and fully integrated and authomatized the installation. So, a first automatic analisys of a .pro could set up the full needed environment, including both qt, libraries and GCC.
-------------------------------------------------------------------------
The author of GPXsee states that one needs Qt and C++ compiler, but it needs to be setup... but if you are not so fluent, here go some more detailed hints:

Download mingw compiler set up:
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download (free as in free beer)
Download Qtcreator installer - if you qualify for no money version - here https://www.qt.io/download-open-source

In what I was able to set up, after trial and errorS, I tried to have common versions between C++ and Qt creator and Qt OpenGL.
So I had to iterate until all fitted. So:

Execute  mingw installer. I settled in the following selections: 7.3.0 / x86_64 / win32 / seh

Now, it is necessary to install a version of Qtcreator that
a) is compatible with a compatible version of mingw GCC version (in this case 7.3.0)
b) contains OpenGL functions for Mingw 7.3.0
c) compiles source code without issues (current qt version does not compile 7.13 as some calls have been deprecated)
Run qt installer; an email address has to be setup. When setup arrives, you need to select custom version, then
- keep all selected boxes
- go to the end, qt developer and designer, select in qt 3D studio open GL for (your target Qt version, in my case xxx), mingw 7.3.0
- select in qt (your target Qt version, in my case xxx), mingw 7.3.0

Download source from github; unzip; click in gpxsee.pro
QT creator opens. You have to select in build, "release"; build and check no errors
Execute/Run

Voila.

Then, you will get somewere a gpxsee.exe. It needs some dll in its directory, that you must copy from mingw bin folder:
qtconcurrent, qtcore, qtgui, qtprintsupport, qtnetwork, qtsql, qtwidgets, libgcc_s_seh-1, libstdc++-6 and libwinpthread-1
Create in that folder a folder called Platforms and copy qwindows from the qt library (bin?)

In my case, this is a portable working exe (provided you keep the dlls).

I am sure there are easier and cleaner ways of doing, this is a dirty but working way.

If you are not understanding the instructions, do not ask me more, I am unable to give any more information. And if you are not understanding the instruccions, probably you have not the bare minimun baseline knowledge to do it.

CT

**Comment by tumic0** [comment]
Just for the record - if you want to fiddle with GPXSee, forget about Windows - compiling anything on Windows is a pain-in-the-ass and GPXSee is not an exception. Use linux and all you have to do are the three commands in the README.md file (ok, you need to install the Qt devel packages on most distros, but that's a single extra rpm/apt command)

**Comment by caspertone2003** [comment]
Thanks for the advice!
Unfortunately my knowledge of linux is none. I know development work is much easier... Anyhow my use case is very simple and I just needed an exe version of 7.13 and 7.14. Yes, windows for this is a PITA ... Now, it is done... I will just become a normal user, so, will try 9.1 asap...
Again, thanks for GPXSee!
CT
