### ISSUE TITLE
[Suggestion] Add wayland support

### ISSUE THREAD

**Issue by DavidHenryThoreau** [tumic0/GPXSee#375]
Add wayland support

**Comment by tumic0** [comment]
What do you mean by wayland support? The standard techniques of running a Qt application under wayland using:
`gpxsee -platform wayland` or: `export QT_QPA_PLATFORM=wayland gpxsee` should work. (Haven't tested it though as I do not have a wayland system).

**Comment by DavidHenryThoreau** [comment]
Openning gpxsee in a wayland DE or WM

You can see output for two commands :
export QT_QPA_PLATFORM=wayland && gpxsee
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

zsh: abort (core dumped)  gpxsee





gpxsee -platform wayland
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

zsh: abort (core dumped)  gpxsee -platform wayland

**Comment by sikmir** [comment]
> export QT_QPA_PLATFORM=wayland && gpxsee

Just in case, simpler:
```
$ QT_QPA_PLATFORM=wayland gpxsee
```

**Comment by tumic0** [comment]
You do not have the Qt wayland platform plugin installed. I'm pretty sure that other Qt applications do not work either on your system...

**Comment by DavidHenryThoreau** [comment]
qt6-wayland was required by gpxsee but it was not mentioned in optional dependencies in ArchLinux package.
