### ISSUE TITLE
smlparser.cpp error in handling lat and lon min/max

### ISSUE THREAD

**Issue by ebtfr** [tumic0/GPXSee#376]
Hi,
I think I just spotted two errors in smlparser.cpp
Line 26 
`if (!ok || lat < -90 || lon > 90) {`
Should be
`if (!ok || lat < -90 || lat > 90) {`

Same thing for lon Line 32
`if (!ok || lat < -180 || lon > 180) {`
Should be 
`if (!ok || lon < -180 || lon > 180) {`

Cheers

**Comment by tumic0** [comment]
Indeed, the checks are wrong, thanks for reporting. Fixed in aff4dc9408b26c8ae8b37b8069d33f3dacc5aa44.
