### ISSUE TITLE
CSV by RFC 4180 

### ISSUE THREAD

**Issue by caspertone2003** [tumic0/GPXSee#377]
This issue is about introducing flexibility or informing explicitly. So, it is not a bug but making user's life easier.

As far as I have checked, GPXSee 9.1 strickly follows RFC 4180

So, accepts this lines
-17.97936, 27.70533, C
"-17.97936", "27.70533","C"

but not
-17.97936, 27.70533, "C"

(as defined in https://www.ietf.org/rfc/rfc4180.txt , 2.5)

Thing is that https://www.gpxsee.org/doc.html states

Data files
GPXSee opens GPX, TCX, FIT, KML, NMEA, IGC, CUP, SIGMA SLF, Suunto SML, LOC, GeoJSON, OziExplorer (PLT, RTE, WPT), Garmin GPI, Garmin CSV, TomTom OV2 & ITN and geotagged JPEG files, however not all format features are supported for all formats. Generally, GPXSee supports four kinds of data objects

and Garmin CSV is linked to http://www.poi-factory.com/garmin-csv-file-format

And in the examples it states

-123.12345,34.98765,"Amy's House"
-123.12332,34.98622,"Gary's Garage"

I have not checked what input does POI loader accepts.

LibreOffice goes along with -123.12345,34.98765,"Amy's House" as input; saved CSV are "-123.12345","34.98765","Amy's House"

So, I believe that
a) either GPXSee is changed to behave like LibreOffice or
b) adding a small note about "strict compliance with RFC-4180 is added in https://www.gpxsee.org/doc.html

a) means introducing flexibility while departing from strict standard
b) means providing hints about the correct use of csv

I advocate for a) ;-)

Thanks,
CT

https://www.gpxsee.org/doc.html

**Comment by tumic0** [comment]
`-123.12345,34.98765,"Amy's House"` is not prohibited by RFC 4180 and works in GPXSee. The reason why the line `-17.97936, 27.70533, "C"` doesn't work is the space between the last coma and the quote. This does not fit into the grammar of RFC 4180.

Generaly GPXSee is RFC 4180 compliant as are the examples on the linked http://www.poi-factory.com/ page. Additionaly OpenOffice generated CSV should also work as it is RFC 4180 compliant.

**Comment by caspertone2003** [comment]
Thanks for the answer, but 9.1 is not acepting
-123.12345,34.98765,"Amy's House"

I get

![image](https://user-images.githubusercontent.com/4682903/120908528-71530a80-c66b-11eb-9a5e-48b9c87dedd5.png)

file is

[test.csv](https://github.com/tumic0/GPXSee/files/6603423/test.csv)

(perhaps I am not seeing an elephant?)

Thanks again!

**Comment by tumic0** [comment]
> In my tests, I am not sucessful if the file does not end with one and only one CRLF

That's a bug. Files not ending with CRLF are allowed (but multiple CRLFs are not). Fixed in d2913208328332e84512d97d420868bf7f20dfda.

> In my tests, I am not successful if the file does start with field_name,field_name,field_name CRLF - with or without ""field""

While RFC 4180 generally allows CSV files with headers, the semantics of Garmin CSV files does not. So you can't have a header in a Garmin CSV file (I have never seen a "real" Garmin CSV file with a header).

**Comment by caspertone2003** [comment]
Thank you very much!
