### ISSUE TITLE
Track displays incorrectly but Route is fine

### ISSUE THREAD

**Issue by Andyboy001** [tumic0/GPXSee#379]
[1London-Edinburgh-RTE2.gpx.txt](https://github.com/tumic0/GPXSee/files/6650630/1London-Edinburgh-RTE2.gpx.txt)
[1London-Edinburgh-TRK2.gpx.txt](https://github.com/tumic0/GPXSee/files/6650631/1London-Edinburgh-TRK2.gpx.txt)

I have a simple 54 point route (using rtept) that displays fine in GPXsee.

I converted it to a track (using trkpt and interpolated times) but it doesn't display correctly: the waypoints display correctly, but some lines joining the waypoints are wrong.  I initially suspected it was a problem with my data, however it displays correctly on all the other apps and sites that I tried.

I've tried both versions 9.0 and 9.1 but it's the same in both.

Attached are both RTEPT and TRKPT versions of the data (I had to add the .txt extension in order to upload)

Thanks!

**Comment by tumic0** [comment]
The "problem" is the outlier elimination algorithm that is designed to work on real track logs, not artificial data like this sample. If you disable outlier elimination in the options, you will get the same path for both the track and route files.

**Comment by Andyboy001** [comment]
Ah great, thanks for the quick response and explanation!
