### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by limex** [tumic0/GPXSee#38]
Hi,
great tool, thanks so much.
But: Any chance to change the language of gpxsee back to english on my german Win10?
Regads Günther

**Comment by tumic0** [comment]
Hi,
You can create a BAT file (e.g. GPXSee_en.bat) with the following content:

`set LANG=en_US`
`GPXSee.exe`

save it next to the original GPXSee.exe binary and use this BAT file for launching the application.
