### ISSUE TITLE
2nd cursor in the graph for displaying additional information

### ISSUE THREAD

**Issue by schortl** [tumic0/GPXSee#382]
hello tumic0,

Maybe the title of my previous post was misleading..
in #325 and other related posts the topic is about vertical speed **graphs**.
My proposal relates to adding a second cursor in the elevation diagram (maybe by displaying and setting the second cursor with mouse whilst pressing a key like cntrl or the like)
and to simply display  **a number** below the graph representing the (averaged) ascent/descend rate in m/hours or m/min (maybe selectable) by simply dividing the height difference between the two cursors by the time difference between the two cursors.
In this way also the averaged speed between the two cursors could be displayed as **a number** by  dividing the distance difference between the two cursors by the time difference between the two cursors.

regards
schortl

**Comment by tumic0** [comment]
There will definitely** not be two cursors in the elevation graph as this would be simply too much stuff in a single graph (you already have two elevation graphs per track and a cursor with quite a lot info there). Even the vertical speed graph does not fit very well into the current data model, but as this is a quite common request from pilots using GPXSee for their logs, I'm letting it open in #325 and maybe one day it will happen. One of the main goals in GPXSee development is a clean and straightforward UI/UX and you simply can not have this and at the same time implement everyone's special request.

 ** at least in the "official" version. You are of course free to implement it yourself in your own fork of GPXSee.

**Comment by schortl** [comment]
Actually I meant a second slider ...

**Comment by schortl** [comment]
Actually I meant a second slider ...
