### ISSUE TITLE
JPEG Orientation

### ISSUE THREAD

**Issue by andreas-mausch** [tumic0/GPXSee#385]
Hi, some of my pictures are displayed 90 degree rotated.
Maybe the Exif Orientation is ignored?

**Comment by andreas-mausch** [comment]
Quick research. I found this: https://github.com/tumic0/GPXSee/blob/d73627576f7ce1a89484e6b23be96bf47d2b2879/src/data/exifparser.cpp#L211
and this: https://github.com/tumic0/GPXSee/blob/a53fedf83844fb77082fa5be970bd5f6cc292479/src/GUI/tooltip.cpp#L35

So the Exif orientation is not read, but that shouldn't be a problem since Qt does the rendering.

However, it seems like the Richtext HTML Subset https://doc.qt.io/qt-5/richtext-html-subset.html used in QLabel doesn't handle the orientation.

If the rendering would be done by a QImageReader https://doc.qt.io/qt-5/qimagereader.html, there is a flag autoTransform.

**Comment by tumic0** [comment]
It's as you say - Qt's HTML engine used for displaying the popup label does not support image rotation according to the EXIF metadata. One could of course rewrite the popup widget from scratch and render it using some layout code (the current approach is the relic of the former standard tooltips used by GPXSee for the popups), but my motivation to do so is very low. Especially as I really hate this new trend not to use the image dimensions but rather "rotate" the image using some EXIF metadata...

**Comment by andreas-mausch** [comment]
Thanks for the quick response. I'd like to give it a try with the Popup widget.

**Comment by andreas-mausch** [comment]
Before:

![before](https://user-images.githubusercontent.com/1736847/126639884-cba3ade6-da47-4c37-a9a7-af7e2443f887.png)

Current version:

![wip](https://user-images.githubusercontent.com/1736847/126639925-a1c0484b-b77f-4f14-941d-e25f4dc33ff5.png)

Not perfect yet: anti-aliasing changed, border is large, too much margin and the image is not clickable yet. But I think I'm getting there. Currently it's dirty hacked. I will clean it up and create a pull request.
