### ISSUE TITLE
suggestion:  ability to change track colour

### ISSUE THREAD

**Issue by morwenna-01** [tumic0/GPXSee#388]
Maybe this is already a feature, but I couldn't find it.

It would be great to explicitly set track colours

**Comment by morwenna-01** [comment]
@tumic0   Can you tell me how to "change the base color (first track color) and the palette shift between two subsequent colors"?  That's exactly what I want to do.  I worded by question badly.

thanks.

**Comment by sikmir** [comment]
@morwenna-01 
![scr1](https://user-images.githubusercontent.com/688044/131233125-cf3a011c-0fdc-4dde-8916-73828407c97c.jpg)

**Comment by morwenna-01** [comment]
thanks so much.  It took me ages to find this!  I had to go to preferences.  All great.
