### ISSUE TITLE
OpenGL rendering draws lines wrong at max zoom

### ISSUE THREAD

**Issue by zootboy** [tumic0/GPXSee#389]
I'm running GPXSee version 9.5 on Arch Linux. The computer is a Thinkpad T470s with an Intel Skylake GT2 [HD Graphics 520] GPU, running the Mesa opengl drivers.

When OpenGL rendering is enabled, the track lines are drawn incorrectly at maximum zoom. See the following screenshots of the opengl renderer, followed by the software renderer:

![opengl](https://user-images.githubusercontent.com/4085499/131229549-8ec7baa6-fe6b-4560-af1f-fb7ff3c8df0c.jpg)

![software](https://user-images.githubusercontent.com/4085499/131229552-8c291e3e-588d-4482-b10d-c59fbb542de0.jpg)

I'm happy to help diagnose / test further, just let me know what you need.

**Comment by tumic0** [comment]
Qt is full of OpenGL bugs and this will be yet another example (All GPXSee does when you select the "Use OpenGL" checkbox is, it says Qt to render using OpenGL). There is a good reason, why OpenGL is not enabled by default in GPXSee...

You can(should) report the issue in the [Qt bugtracker](https://bugreports.qt.io), but do not expect too much from doing so...

**Comment by zootboy** [comment]
Wow, no kidding:

https://bugreports.qt.io/browse/QTBUG-10493

**Comment by tumic0** [comment]
Well, welcome in the world of Qt OpenGL bugs... My ["favourite" bug](https://bugreports.qt.io/browse/QTBUG-39781) has for example became a feature...
