### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by limex** [tumic0/GPXSee#39]
Hi,
how can I change the Language of GPXSee? On my german Win10 I want to have GPXSee in english.
Regards Günther

**Comment by tumic0** [comment]
The solution described in #38 does not work for you (works for me)? Or there any other reason for opening an identical issue?!

**Comment by limex** [comment]
Reason for identical issue: Couldn't find #38 any more, thould it was delete or not created. My fault.

Solution in #38 kindof works. But assigning the bat file as the default for extension gpx didnt work.

set LANG=en_US
c:\pathtogpxsee\GPXSee.exe %1

That sucks b/c now I open GPXSee with the bat + drag the gpx to the program. :(
Maybe you consider adding a setting for the lang in the program? 
Pleeeese. Thanks in advance

**Comment by tumic0** [comment]
Assigning the extensions works for me. If you modify the registry entry HKEY_CLASSES_ROOT/GPXSee.gpx/shell/open/command to point to the bat file, it shall work. (you need the absolute GPXSee path in the bat file and the arguments passed from the bat file arguments, which you have in your post, maybe %* is better than %1, but both should work)

Adding a language setting to GPXSee makes no sense for me, the usual way of using the system preferences should be sufficient. For special cases of e.g. testing one can fiddle with the shell variables/registry like described above.

Btw. - what is your reason for having GPXSee in english but the rest of the system in German? If there are some problems in the translations, then please report them and I will update the translation.

**Comment by limex** [comment]
Thanks you registry change did work.
Regarding english @ an german System: I install GPXSee on my company Notebook. Our sys has a policy of german language and many system settings are for admins only. This is a usual setup for anyone in a larger company. But in general using software in german language sucks b/c most translations are either misleading or wrong. Also you find less answers on the web when mentioning i.e. error messages in german.
I have no issue with the translation in GPXSee. Its just that I install all my software if possible in English.

**Comment by tumic0** [comment]
Ok, I'm closing the issue then. Setting the language is possible although not in a user-friendly way (at least on Windows), but the use-cases for doing so are rare.

**Comment by limex** [comment]
> ... but the use-cases for doing so are rare.
I agree. Thanks.

**Comment by bviktor** [comment]
I have English Windows, yet for whatever reason GPXSee displays in Hungarian. I assume that's because of my regional settings. Sorry but this makes absolutely no sense whatsoever. Why is it so hard to give us an option to select the language. Every program has an option for this, and for good reasons.

**Comment by bviktor** [comment]
So I just ended up deleting `translations/gpxsee_hu.qm`. And yes, I'll have to do this every time GPXSee updates. Or maybe I'll just never update it ever again and then I won't have this problem anymore :)
