### ISSUE TITLE
OSX 10.11 compatible build

### ISSUE THREAD

**Issue by casesolved-co-uk** [tumic0/GPXSee#392]
Hi & thanks for the app!
I have managed to build an OSX 10.11 El Capitan compatible version of v9.6 using Xcode 8.2.1 and Qt 5.11.3
Just wondering if anyone else is interested in it and if the developer would like to share it?
It works but i haven't tested it thoroughly and can't seem to get it to rebuild.
Mac dev newbie

PS A fantastic addition would be a realtime replay option. This could be used with a screen recorder. The resulting video used for inserting instrumentation into flight videos.

**Comment by tumic0** [comment]
GPXSee should normally compile/work with Qt 5.11 (and thus OS X 10.11), all one has to do is to install Qt 5.11 and compile GPXSee using it. There are however some reasons, why Qt 5.15 is used in the "official" build. For example dark mode does not work with Qt 5.11. Qt 5.15 works on OS X 10.13 which can be run on almost any Mac build after 2010. This should be more than enough, according to Apple you should buy a new machine every two years...

**Comment by casesolved-co-uk** [comment]
> according to Apple you should buy a new machine every two years

😆 according to Greta Thunberg there won't be any air to breathe if we all did that
Let me introduce you to Louis Rossmann and Right to Repair: [https://youtu.be/Npd_xDuNi9k](https://youtu.be/Npd_xDuNi9k)

**Comment by tumic0** [comment]
Well, given the amount of reverse-engineering work that was necessary to make GPXSee what it is today, I would say that me and Louis Rossmann see the world the same... But from a practical point of view, you have to draw the line somewhere in terms of supported systems. And for OS X builds, the line is OS X 10.13 (note, that there are two more operating systems to support and the resources are - as always - limited).
