### ISSUE TITLE
Cannot open NMEA files

### ISSUE THREAD

**Issue by patricktokeeffe** [tumic0/GPXSee#394]
GPXSee fails to parse GPGGA sentences. I tried first with v7.30, then with 9.6_x64 (on both Win7 & Win10). I also turned off outlier elimination. 

A plain-text file composed of "random" GPS data ([source](http://freenmea.net/decoder)) with a `.nmea` extension loads correctly:
```
$GPGGA,202642.723,3354.928,N,07802.494,W,0,00,,,M,,M,,*51
$GPGGA,202646.723,3354.927,N,07802.492,W,0,00,,,M,,M,,*5C
$GPGGA,202650.723,3354.927,N,07802.491,W,0,00,,,M,,M,,*58
$GPGGA,202654.723,3354.926,N,07802.489,W,0,00,,,M,,M,,*54
$GPGGA,202658.723,3354.926,N,07802.487,W,0,00,,,M,,M,,*56
$GPGGA,202702.723,3354.925,N,07802.486,W,0,00,,,M,,M,,*5A
```

But opening a file containing this real GPS data (still with a `.nmea` extension) ...
```
$GPGGA,172720.00,4654.4699364,N,11944.6111656,W,2,10,1.0,371.191,M,-17.542,M,6.0,0131*78
$GPGGA,172721.00,4654.4699371,N,11944.6111684,W,2,10,1.0,371.191,M,-17.542,M,7.0,0131*73
$GPGGA,172722.00,4654.4699389,N,11944.6111708,W,2,10,1.0,371.191,M,-17.542,M,7.0,0131*72
$GPGGA,172723.00,4654.4699399,N,11944.6111739,W,2,10,1.0,371.198,M,-17.542,M,7.0,0131*79
$GPGGA,172724.00,4654.4699397,N,11944.6111761,W,2,10,1.0,371.197,M,-17.542,M,4.0,0131*71
```
...produces this error message:
> Error loading data file:
> 
> [path to data file]
> 
> No usable NMEA sentence found
> Line: 11

![image](https://user-images.githubusercontent.com/1348834/133683843-4a40b703-e77f-461a-8558-8e19afd2ecf5.png)

Even though I manually verified my real GPS sentences match [the standard](http://aprs.gids.nl/nmea/#gga):

Column | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | UTC time | Latitude | N/S | Longitude | E/W | GPS fix | #sats | HDOP | Altitude | Meters | GeoSep | Meters | DiffAge | DiffID | Checksum
Real, actual GPS   data
$GPGGA | 172720.00 | 4654.4699364 | N | 11944.6111656 | W | 2 | 10 | 1 | 371.191 | M | -17.542 | M | 6 | 131 | 78
$GPGGA | 172721.00 | 4654.4699371 | N | 11944.6111684 | W | 2 | 10 | 1 | 371.191 | M | -17.542 | M | 7 | 131 | 73
$GPGGA | 172722.00 | 4654.4699389 | N | 11944.6111708 | W | 2 | 10 | 1 | 371.191 | M | -17.542 | M | 7 | 131 | 72
$GPGGA | 172723.00 | 4654.4699399 | N | 11944.6111739 | W | 2 | 10 | 1 | 371.198 | M | -17.542 | M | 7 | 131 | 79
$GPGGA | 172724.00 | 4654.4699397 | N | 11944.6111761 | W | 2 | 10 | 1 | 371.197 | M | -17.542 | M | 4 | 131 | 71
"Random"   data from freenmea.net
$GPGGA | 202642.723 | 3354.928 | N | 7802.494 | W | 0 | 0 |   |   | M |   | M |   |   | 51
$GPGGA | 202646.723 | 3354.927 | N | 7802.492 | W | 0 | 0 |   |   | M |   | M |   |   | 5C
$GPGGA | 202650.723 | 3354.927 | N | 7802.491 | W | 0 | 0 |   |   | M |   | M |   |   | 58
$GPGGA | 202654.723 | 3354.926 | N | 7802.489 | W | 0 | 0 |   |   | M |   | M |   |   | 54
$GPGGA | 202658.723 | 3354.926 | N | 7802.487 | W | 0 | 0 |   |   | M |   | M |   |   | 56
$GPGGA | 202702.723 | 3354.925 | N | 7802.486 | W | 0 | 0 |   |   | M |   | M |   |   | 5A

**Comment by tumic0** [comment]
According to the [standard](https://gpsd.gitlab.io/gpsd/NMEA.html)**, the maximum line length is 82 characters, but your data has much more. The GPXSee parser skips such invalid lines, this is why you get that error message.

** The real standard is not public, but for almost all open source SW the gpsd NMEA documentation is the defacto standard.

**Comment by patricktokeeffe** [comment]
That's too bad. I've seen the line length limit before and I also see it frequently ignored so I didn't think it was a strict rule. Thank you for clarifying.

**Comment by tumic0** [comment]
Is your data generated by a real GPS receiver? If there are real devices, that produce broken NMEA, the parser could be adjusted. If it is some generated/converted data, than the producer should be fixed to generate valid NMEA sentences (the lat/lon strings have an unrealistic precision - according to the standard there shall be two decimal digits of the minutes)
