### ISSUE TITLE
About the map xml file format

### ISSUE THREAD

**Issue by kk7mz** [tumic0/GPXSee#396]
HELLO!
I want to use an online map whose url like:
https://xx.example.com/maptile?x=$x&y=$y&z=$z
But when i create an xml file and load it , GPXSee WANRNING the message :
"Expected ';', but got '='. "
Did I make a mistake or  this type of URL is not supported? 
Thank you very much.

**Comment by tumic0** [comment]
Most probably you did not encode the `&` character to `&amp;` (the map file is a regular XML so you have to encode special XML characters either as entities or use a CDATA section), but without the actual map file it is hard to say.

**Comment by kk7mz** [comment]
Thanks for your patient reply. Sure enough , just like your reply , after I replace it with escape character , everything is OK. : )
