### ISSUE TITLE
Add Coordinate Systems

### ISSUE THREAD

**Issue by kk7mz** [tumic0/GPXSee#397]
Hi !  Is it possible to add the CRS [EPSG:4490](https://epsg.io/4490)  ?
Thanks.
__________________
So , it seems like that this CRS EPSG:4490 is special ? it can't transform to the others ?
In fact , i want to use a WMTS service via the REST access method, but when i create and load the xml , the program give me error message:
**urn:ogc:def:crs:EPSG::4490: unknown CRS** 
and the other one notice:
**urn:ogc:def:crs:EPSG::900913: unknown CRS** 
I don't know how to repair it . Although I have searched and read some documents through search engines and official websites , But  I know nothing about related information and  my English is so poor that i can't understand the complex content .
If this issues is too primary even stupid , please forgive me.

**Comment by tumic0** [comment]
>  Is it possible to add the CRS EPSG:4490?

If there is a Helmert transformation to WGS84 for EPSG:4490 than it can be added. Simply extend your `gcs.csv` file with the required info.

> urn:ogc:def:crs:EPSG::900913: unknown CRS

EPSG::900913 is an unofficial alias for EPSG:3857. Use EPSG:3857 instead (if you can't than you can extend your `pcs.csv` file with the definition).
