### ISSUE TITLE
Incorrect representation of gpx track

### ISSUE THREAD

**Issue by fabrizi-agup** [tumic0/GPXSee#399]
The attached file (.gpx), if uploaded to Garmin, is displayed correctly.
If opened with GPXSEE it shows only a broken line.
Can you fix the application so that it displays correctly?
[PNALM_F5.txt](https://github.com/tumic0/GPXSee/files/7359591/PNALM_F5.txt)

**Comment by tumic0** [comment]
Well, I wish I could turn back time, but I can't... Where do you get such weird and broken GPX files (including #398)? Looks like the files are somehow post-processed with broken scripts.

The file contains a single track that starts in the year 2015, in the middle (near the summit) it jumps to year 2020 and than it goes **backwards** in time from 9:38 to 7:15... GPXSee requires the files to comply with the laws of physics to work properly. Garmin devices maybe don't have such requirements, but I wouldn't see this as a bug in GPXSee...
