### ISSUE TITLE
Map tiles in jpeg format are not supported

### ISSUE THREAD

**Issue by luznicky** [tumic0/GPXSee#4]
Although the tiles are downloaded correctly, they are saved as *.png. Then they are incorrectly opened as png, and therefor not shown.
Can be tasted for example with maps.kompass.at.

Workaround: change file extension in src/maps.cpp

**Comment by tumic0** [comment]
Missing JPEG support (on windows) fixed in 7079e3083169bf73a0a2a0bd95effc1c9cfd9ece. The confusing  file names fixed in 4550e473de524d8c48a813eb2af550cbf869a0a8.
