### ISSUE TITLE
Toolbar got a black background when I enabled OpenGL on macOS

### ISSUE THREAD

**Issue by jollino** [tumic0/GPXSee#401]
Hello,
after updating GPXSee to the latest version available for macOS (i.e. 9.9) I enabled OpenGL in the preferences, as the map was extremely slow to scroll on a retina screen.
Now everything works smoothly, but for some reason the toolbar has gotten a black background, making the icons and text virtually impossible to read.

I already tried deleting `~/Library/Preferences/com.gpxsee.GPXSee.plist`, `~/Library/Preferences/org.gpxsee.GPXSee.plist`, `~/Saved Application State/org.gpxsee.GPXSee.savedState` and all of `~/Library/Caches/GPXSee` hoping that it would clear everything up, but for some reason the toolbar remains black.
I also completely deleted the .app bundle (to be 101% sure that the `Contents/Resources` directory within it would be clean, as indicated in https://www.gpxsee.org/doc.html) and even downloaded a different version, but it just doesn't seem to help with getting a clean slate.
Indeed, I seem to be completely missing `~/Library/Application Support/GPXSee`, despite that being suggested by Help => Paths. Where else would the config be written?

Configuration mysteries aside :), attached is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/3470104/137635311-91704140-f6c8-42ac-8e36-52e5444b6cb2.png)

I'm using GPXSee version 9.9 (x86_64, Qt 5.15.2) on macOS "Big Sur" 11.6. The machine is a 5K iMac (2017) with a Radeon Pro 580 (8 GB) graphics card.

Any suggestions on what else I can try would be most welcome!

**Comment by tumic0** [comment]
Well, the only thing you can do is to hide the toolbar when using OpenGL on Mac. This is a well known QT [bug](https://bugreports.qt.io/browse/QTBUG-39781) (it was so "popular", that it has became a feature during the time...)

But I'm a little bit surprised about the slow map scrolling without OpenGL. Normally OpenGL significantly improves the performance when there are many objects (tracks, routes, waypoints) in the scene but it should not have an effect on map drawing performance. In fact the map itself is usually a little bit slower when OpenGL is enabled...

**Comment by tumic0** [comment]
> A workaround for me is just to use GPXSee on the external screen — I just noticed that OpenGL seems to introduce odd artifacts on the track lines (at least with the files I generate from my dashcam, which have a single track with one trackpoint per second). Keeping OpenGL disabled fixes the jagged lines immediately.

OpenGL is generally quiet

**Comment by tumic0** [comment]
> A workaround for me is just to use GPXSee on the external screen — I just noticed that OpenGL seems to introduce odd artifacts on the track lines (at least with the files I generate from my dashcam, which have a single track with one trackpoint per second). Keeping OpenGL disabled fixes the jagged lines immediately.

OpenGL is generally (not only on Mac) quiet broken in Qt, you are probably facing the bug from #389. Or maybe just another one...

> Still, if you ever want me to test anything on Mac, I'll be more than happy to.

The problem is, I do not have such screen setup (GPXSee Mac "development" is done on a 2009 iMac) to test/profile the issue. All the HiDPI stuff is for example developed using SW emulation of the retina screens. Time to time I have access to a ~2015 MacBook Pro with Retina, but I had never issues with map scrolling on that machine. But it is not 5K. So I will hardly provide some "test version" of GPXSee.
