### ISSUE TITLE
Like to more zoom in

### ISSUE THREAD

**Issue by jelleruben** [tumic0/GPXSee#408]
GPXSee is a great program. My wish is to have the possibility to have more zoom in  on the map. I hope that this is possible in the future.

**Comment by sikmir** [comment]
min/max zoom depends on map.

**Comment by jelleruben** [comment]
Hello sikmir, I have found it. I have select an other map. And can now more.. thanks.  I have must look beter :-)

**Comment by tumic0** [comment]
In addition to the available map zooms, you can always use the "digital zoom" to zoom even a little bit further. But the image quality will of course decrease.

**Comment by endolith** [comment]
> you can always use the "digital zoom" to zoom even a little bit further. But the image quality will of course decrease.

Is that possible?  I don't see it anywhere in menu or options. :/

**Comment by tumic0** [comment]
Yes. There is no option or menu for that, it's just a "regular" zoom with a modifier key. See the keyboard controls in the Help menu.
