### ISSUE TITLE
Upload trace under .trk format

### ISSUE THREAD

**Issue by JoelErin** [tumic0/GPXSee#411]
Hi. 
Is there any reason why GPXSee does not support uploading .trk traces ?
This seems to be a common format and GPXSee cannot handle them.
This is honestly not a big deal as many converters exists, but it's a bit bothering.
Thanks - Joel

**Comment by tumic0** [comment]
CompeGPS files are not yet supported. If you want to speed up the process of implementing the format reader, you can provide some sample files here.

**Comment by JoelErin** [comment]
Please find attached an example of a recent .trk file (zipped)
This one is issued from CompeGPS receiver. I believe my old Garmin Etrex also used to create .trk file too.
If you need more examples (shorter or longer), please let me know.
Thanks - Joel

[MN17 - Petit Sergent - le Boutillon - Petit sergent 12km.zip](https://github.com/tumic0/GPXSee/files/7675266/MN17.-.Petit.Sergent.-.le.Boutillon.-.Petit.sergent.12km.zip)
.

**Comment by tumic0** [comment]
Please try the latest version with your data files and eventual report any issues.
