### ISSUE TITLE
Mapsforge

### ISSUE THREAD

**Issue by Gt1ult** [tumic0/GPXSee#412]
Hi,

I am trying to upload the mapsforge from the site www.openandromaps.org/. I can upload the vector maps from the site www.openandromaps.org/ but in order to see all the tracks I need to upload the mapsforge. Is it possible?

Furthermore, if I can, I would like to do some requests:
1) add profiles in order to have different tracks for for each profile
2) Add the option to hide/unhide and manage tracks 

Thank you so much!

**Comment by tumic0** [comment]
Regarding OpenAndroMaps - they work fine with GPXSee, but you need a OpenAndroMaps compatible theme for them to work/be displayed correctly. The theme must be placed in the correct directory and named correctly, see the documentation for details.

Regarding the other topics:

1. That's out of scope of GPXSee
2. There is already #222 for that
3. Never put multiple things into a single issue, things will be ignored or closed without a trace.
