### ISSUE TITLE
Supported file types not shown

### ISSUE THREAD

**Issue by David-Else** [tumic0/GPXSee#415]
Thanks for this amazing software! I am using the Centos 8 version:
```
cd /etc/yum.repos.d/
wget https://download.opensuse.org/repositories/home:tumic:GPXSee/CentOS_8/home:tumic:GPXSee.repo
yum install gpxsee
```
When I go into my Garmin Forerunner watch via USB to open .FIT files it does not see them with the default `Supported files`:

![Screenshot from 2021-12-31 13-11-26](https://user-images.githubusercontent.com/12832280/147825262-2b3a1a2f-e84c-4107-8575-dc3c1c05a644.png)

But if I switch to `All files` I can then see and open them all, and they work!

![Screenshot from 2021-12-31 13-17-15](https://user-images.githubusercontent.com/12832280/147825384-809c725a-3d8c-4888-b7d6-c3b396fc908c.png)

**Comment by tumic0** [comment]
Looks like you are using some Gk-based desktop which makes Qt to use the Gtk file select dialogue which does not filter the files in a case-insensitive way (see [QTBUG-51712](https://bugreports.qt.io/browse/QTBUG-51712) for details). As a workaround, you can run GPXSee with a different Qt style like:

`gpxsee -style=fusion`

Which should use a different open file dialogue that will filter the files case-insensitive.
