### ISSUE TITLE
MacOS version needs to be notarized

### ISSUE THREAD

**Issue by leonardpitzu** [tumic0/GPXSee#418]
On managed apple computers the app cannot pe started as non-notarized apps are blocked.
Currently the following message is presented with no way to go around it:
`“GPXSee.app” can’t be opened because Apple cannot check it for malicious software.`
Please note this is not an issue on non-managed devices where the security options are more relaxed/in the control of the user.

Documentation: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution

**Comment by tumic0** [comment]
Short answer - feel free to create a notarized build of GPXSee yourself if you need one.

Long version:
1) There is [zero user interest](https://github.com/sponsors/tumic0) for OS X builds of GPXSee.
2) There is zero GPXSee author's interest to support someone deciding what the user can and can't do on his computer (this applies to Apple as well as the organization that manages the computer)

For some more info on this topic see #300
