### ISSUE TITLE
alignement / offset when comparing gpx files.

### ISSUE THREAD

**Issue by EvilBart-PL** [tumic0/GPXSee#419]
Hi,
Is it possible to align starting position of multiple gpx files?

I mean if I have data to compare I want to start them in the same point on the map.

Some kind of offset would be great - to be able to align the starting time.
For example load file1 and load file2
set that file2 has to have an offset of +23second relative to file1. (maybe it could done via mouse just grab the line and move if left/right on the graph)

**Comment by tumic0** [comment]
There is no such thing. If you want to modify the files (although not permanently), you have to use some GPX editor like QMapShack, Viking or RouteConverter.
