### ISSUE TITLE
Error loading IGC file from XCSoar

### ISSUE THREAD

**Issue by ninelima** [tumic0/GPXSee#42]
Error loading data file ... Invalid/missing A record Line:1

[2017-12-28-XCS-AAA-01.zip](https://github.com/tumic0/GPXSee/files/1596123/2017-12-28-XCS-AAA-01.zip)

**Comment by ninelima** [comment]
Thanks. What is the recommended build procedure for Windows 7?

**Comment by tumic0** [comment]
You can use the automatic AppVeyor build. However due to appveyor/ci#1616 you have to replace the openssl lib with the one from the official GPXSee build for HTTPS to work.
