### ISSUE TITLE
GPI files

### ISSUE THREAD

**Issue by dpawlyk** [tumic0/GPXSee#421]
In GPIParser::readData, readPOIDatabase() gets called but the case falls through to issue an error.

Is that correct? 

(I have a GPI file created using GPSBabel that results in this error when the file is opened in GPXSee.)

`bool GPIParser::readData(DataStream &stream, QVector<Waypoint> &waypoints,
  QList<Area> &polygons, const QString &fileName)
{
	int imgId = 0;

	while (stream.status() == QDataStream::Ok) {
		switch (stream.nextHeaderType()) {
			case 0x09:
				readPOIDatabase(stream, waypoints, polygons, fileName,
				  imgId);
				break;
			case 0xffff: // EOF
				stream.skipRecord();
				if (stream.status() == QDataStream::Ok)
					return true;
				break;
			default:
				stream.skipRecord();
		}
	}

	_errorString = "Invalid/corrupted GPI data";

	return false;
}
`

**Comment by tumic0** [comment]
Looks like the EOF marker is missing in the file (to be sure, I would need to see the sample file). I have tried to create a GPI file using GPSBabel and the file is properly terminated by the EOF marker. So either there are some (probably old) gpsbabel versions that create broken files, or the file is corrupted.

Please attach the sample file (+ the source file) and provide more info how it was created (what GPSBabel version was used)

**Comment by tumic0** [comment]
Closing as without a sample, there is nothing more to do...
