### ISSUE TITLE
GPXSee not showing POIs when opening GPX file through the POI tab

### ISSUE THREAD

**Issue by hshagsfgd** [tumic0/GPXSee#422]
Coming from [this](https://github.com/tumic0/GPXSee/issues/420): Since Mapsforge's `.poi` format is not supported, I wanted to generate a `.gpx` file. I found [this](https://github.com/simao/osm-gpx) converter and [input](https://extract.bbbike.org/?sw_lng=14.356&sw_lat=50.023&ne_lng=14.513&ne_lat=50.139&format=osm.pbf&ref=download&lang=en&city=Prague) a [custom](https://download.bbbike.org/osm/extract/planet_14.356,50.023_14.513,50.139.osm.pbf) `.pbf` file into it to generate the GPX file[1]. It then generated the GPX file, but unfortunately, after opening the file in GPXSee->POI, no POIs are displayed. The generated file works on a web-based POI Viewer site.

[1]
```
$ cargo run -- --osm-file '~/Downloads/planet_14.356,50.023_14.513,50.139.osm.pbf' --name Water --output water.gpx --exp "amenity=drinking_water"
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/osm-gpx --osm-file ~/Downloads/planet_14.356,50.023_14.513,50.139.osm.pbf --name Water --output water.gpx --exp amenity=drinking_water`
 INFO  osm_gpx::osm > Found node named Some("Water") at Point(Coordinate { x: 14.4151449, y: 50.0725018 })
 [...]
 INFO  osm_gpx::osm > Found node named Some("Water") at Point(Coordinate { x: 14.447653299999999, y: 50.1112908 })
 INFO  osm_gpx      > finished, found 150 matching waypoints 
$
```

**Edit**
Opening the GPX file works when I drag&drop it. I also noticed that the POI hide button doesn't work.

**Comment by tumic0** [comment]
> after opening the file in GPXSee->POI, no POIs are displayed

And that is exactly what shall happen. Please see the documentation for how the POIs work in GPXSee.

**Comment by hshagsfgd** [comment]
>And that is exactly what shall happen. Please see the documentation for how the POIs work in GPXSee.

But a weird way to do it. The same file is handled differently depending on from where it's opened. User confused. The POI tab should not have a file opening menu.

>All of the supported formats with waypoints capability - GPX, KML, TCX, NMEA, CUP, WPT, LOC, GeoJSON and Garmin GPI & CSV - can be loaded either as data files or as POI files. When a file is opened as a POI file, only waypoints reasonable near the tracks/waypoints of the loaded data files are displayed.

But the menu is called `POI`, not `waypoints`, I want to see the POIs. I this how you try to handle the missing database file support (e.g. `.poi`)? That's ok, but when I load the GPX from POI menu, I don't see the POIs no matter what I do. Seems like a bug. PS: The documentation should add and say why only near the tracks and how to change that, it's a docu after all.

Again, loading the GPX from the File menu, displays the POIs, but the POI hide button doesn't work (black dots change color from 100% to like 50% transparency, but are still visible). Seems also like a bug. You closed this bug report too soon.
