### ISSUE TITLE
Document required Debian packages

### ISSUE THREAD

**Issue by jcoffland** [tumic0/GPXSee#424]
I found I needed some extra qt packages installed to build on Debian 10.  It would be nice to mention this as a build step.

    sudo apt-get install -y build-essential qtbase5-private-dev qtpositioning5-dev

**Comment by tumic0** [comment]
There are literally thousands of linux distributions wit differently split Qt packages with different naming schemes. It is unrealistic to give the exact list of required packages for every particular linux distribution (and every particular version) in a short README.md document. For some distros, you may find the list in the official [packages sources](https://build.opensuse.org/project/show/home:tumic:GPXSee), but generally if you want to compile the program, you are expected to be able to find out what packages are required on your distro by your self.

**Comment by jcoffland** [comment]
-1
