### ISSUE TITLE
Releases instead of simple tags

### ISSUE THREAD

**Issue by eoli3n** [tumic0/GPXSee#428]
Would you like to make releases for new version, to be able to be notified when a new one is out please ?
![releases](https://user-images.githubusercontent.com/14223657/160231729-09ff7664-7c28-4fbc-acac-9f5788d7e6e0.png)

**Comment by tumic0** [comment]
Due to historical reasons, releases are made on Sourceforge and at the moment I do not want to change the process or duplicate the work here on Github.
