### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ninelima** [tumic0/GPXSee#43]
Qt5.10.0/5.10.0/mingw53_32/mkspecs/win32-g++  -o debug/str2int.o ../GPXSee/src/data/str2int.cpp
'H:\Qt\Qt5.10.0\5.10.0\mingw53_32\bin\rcc.exe' -name gpxsee ../GPXSee/gpxsee.qrc -o debug/qrc_gpxsee.cpp
RCC: Error in '../GPXSee/gpxsee.qrc': Cannot find file 'lang/gpxsee_cs.qm'

Makefile.Debug:523: recipe for target 'debug/qrc_gpxsee.cpp' failed
mingw32-make[1]: Leaving directory 'H:/src/build-gpxsee-Desktop_Qt_5_10_0_MinGW_32bit-Debug'
Makefile:36: recipe for target 'debug' failed
mingw32-make[1]: *** [debug/qrc_gpxsee.cpp] Error 1
mingw32-make: *** [debug] Error 2
09:31:58: The process "H:\Qt\Qt5.10.0\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project gpxsee (kit: Desktop Qt 5.10.0 MinGW 32bit)
When executing step "Make"

**Comment by tumic0** [comment]
qm files are created from the ts files by lrelease which must be run first when building GPXsee.

**Comment by ninelima** [comment]
Ok thanks.


------ Original Message ------
