### ISSUE TITLE
GPXSee fails to render road that starts with two points at the same location

### ISSUE THREAD

**Issue by GerdP** [tumic0/GPXSee#430]
Hi,
I found a case where GPXSee stops too early in NETFile::readShape(). The road starts with a node at the tile boundary.
Basecamp shows the road "K 15"
Problem happens in this code:

		if (!stream.readNext(lonDelta, latDelta))
			break;

		if (hasAdjustBit && !stream.read(1, adjustBit))
			return false;

The method stream.readNext() returns false because both deltas are zero, but in this case this doesn't mean there is no more data.
The stream contains 5 more bits and both hasAdjustBit and useEosBit are true and the final loop adds more correct coordinates to the shape if the code doesn't stop at stream.readNext()
I've attached the missing piece as gpx, the map, the map tile is the Bielefeld tile for GARMIN  CN Europe NTU 2022.2.
Let me know if you need more info to reproduce.

**Comment by GerdP** [comment]
The gpx file was missing...
[missing.zip](https://github.com/tumic0/GPXSee/files/8499388/missing.zip)

**Comment by GerdP** [comment]
Found more such cases, the problem is not limited to roads which start at tile boundaries. I know only housenumber data as a good reason to encode two points at the same location, but there may be others.

**Comment by tumic0** [comment]
I can not reproduce it without the map. I have tried it with 2022.2 that I could get, but the given place looks ok to me and I couldn't find another place where the rendering would be broken. It also does not make any sense that there would be more points at the same location in this particular bitstream. Unless you provide the exact map tile, there is nothing I can do about it.

**Comment by GerdP** [comment]
Strange that you cannot reproduce. The corresponding tile from the gmapsupp has 11.255.808 bytes.
I found several cases so far. Not in all tiles, but maybe 10%. Sometimes a lot more bits are in the bitstream. I think GPXSee should not stop if there is a chance that further nodes are found with net.nextNode().

**Comment by GerdP** [comment]
Another case is in test map TopoD2012:
http://static.garmin.com/shared/de/custom/topod2012/testversion/TopoD2012pro_Testversion.zip
Here is the gpx file
[missing2.zip](https://github.com/tumic0/GPXSee/files/8499616/missing2.zip)

**Comment by tumic0** [comment]
Sorry, there is a typo in my post - i couldn't reproduce it with **2022.10**, not 2022.2.

**Comment by tumic0** [comment]
I can however see the issue on the other map, I will have a look at it.

**Comment by tumic0** [comment]
In 1458d6679848f3bbb98e15b4d98f6bcef3f730c6 I have made some changes that should fix the issue. Can you please confirm, that all of the known places that were broken are ok now?

**Comment by GerdP** [comment]
Sorry, I cannot test because I cannot compile GPXSee. I used my own java code when I found this problem. I think there's still the problem that GPXSee stops too early when there are further nodes. Try this gpx for the topod2012 map:
[missing3.zip](https://github.com/tumic0/GPXSee/files/8501193/missing3.zip)

The loop to read more nodes (lines 291 ..314 in netfile.cpp) is not reached.

**Comment by GerdP** [comment]
Another one in the same tile (Kelheim):
[missing4.zip](https://github.com/tumic0/GPXSee/files/8501224/missing4.zip)

**Comment by GerdP** [comment]
Not sure, but I think it should work to just set eos whenever a read from stream fails in readShape.

**Comment by GerdP** [comment]
Might work because zero deltas are probably useless without the extra bit that you call adjustBit. I think it's a flag that is used to end/start a housenumber intervall, but maybe also for something else because I found this also with unlabeled roads.

**Comment by tumic0** [comment]
Garmin (also) uses the bit to adjust the latitude of the shape points under some circumstances, that's why I call it an "adjust bit".

**Comment by GerdP** [comment]
Yes, I also saw that some lines are rendered differently in Basecamp.

**Comment by GerdP** [comment]
I tried to find again such a line but without success so far. Maybe I looked at different tiles. Happens easily when you have various older versions of a map but only the newest in Basecamp.

**Comment by tumic0** [comment]
There are many maps, where there is not even a single line of the type, that you have triggered in your samples. If you are on Windows and do not want to install all the devel stuff to build GPXSee for testing, you can always at least use the latest [CI build](https://ci.appveyor.com/project/tumic0/gpxsee). On "my" maps I couldn't find another missing line either.

**Comment by GerdP** [comment]
Thanks for the hint. I meant the lines which are rendered in a different way.

**Comment by tumic0** [comment]
The fiddling with the latitude based on the "adjust bit" is very strange. I did not fully understand the logic so i decided to simply ignore it ;-) For display purposes it does not matter, it may have some effects eg. on routing, but that is out of scope of GPXSee.

**Comment by GerdP** [comment]
Still a problem with the zero deltas in the "Winter Activity Map":
https://static.garmincdn.com/shared/de/custom/winter2013/_download/winterkarte.zip
[missing5.zip](https://github.com/tumic0/GPXSee/files/8539706/missing5.zip)
Basecamp shows an "Unpaved Track" here which is much longen than the small gpx. GPXsee 10.7 doesn't show any of this

**Comment by tumic0** [comment]
![missing5](https://user-images.githubusercontent.com/11480505/164688911-7e90d77c-c516-4c16-a41e-6e41233c59f6.png)

Works fine for me with the latest version.

**Comment by GerdP** [comment]
OK, I'll double check that the tile that causes the problem is really in that map.

**Comment by GerdP** [comment]
Or maybe I downloaded the wrong artifact? It says 10.7

**Comment by tumic0** [comment]
The latest Windows CI build as of today is here: https://ci.appveyor.com/project/tumic0/gpxsee/builds/43292395/job/vxcxvqo0wuf6m4p6/artifacts. The name of the installer won't change with further 10.7 builds, you have to know what exact version you have downloaded. My test was however on a Linux build but I doubt that it makes a difference here.

**Comment by GerdP** [comment]
I double checked. I use the right GPXSee installer and the link still points to the zip file (the gmapsupp is 884.064.256 bytes).
It's strange. When I load the whole "Winter Activity Map.img" into GPXSee the way is rendered. When I load only one tile where I found the problem it is not. I used gmaptool to split the gmapsupp and the single tile is 16768502.img with 5.828.608 bytes.
Any idea what can cause this?

**Comment by GerdP** [comment]
Anyway, the code in readShape should work OK with this special case because it's the delta for the first point and startWithStream is true, so there must be a different problem here.

**Comment by tumic0** [comment]
> When I load only one tile where I found the problem it is not. I used gmaptool to split the gmapsupp and the single tile is 16768502.img with 5.828.608 bytes.
> Any idea what can cause this?

Did you also include the TYP file? Without the exact resulting map it is hard to say, what's going on. The "Winter map" has triggered another data read error which was fixed in 959d08ba94fa5bf0db59d24f5525b8df7ec69583, but I don't think that this is the same problem you are referencing.

**Comment by GerdP** [comment]
Indeed, it seems to be the missing type file. I didn't see this problem with other maps. Sorry for the noise.
The road has type 0xd, seems there is no default for this in style.cpp?

**Comment by tumic0** [comment]
Type 0xd are county/parish borders on most maps which only "mess up" the map, but do not bring any usable info for most people, that's why there is no style for them by default. If a map redefines the type for something else, you have to provide a custom TYP file. Due to the mess GARMIN created with their missing documentation and types "reuse" it is impossible to have a default style that would work fine with all maps. It's even almost impossible to have one, that works fine with most maps...

**Comment by GerdP** [comment]
OK, I see. Is there an easy way to load a typ file? I typically use Drag&Drop with a single *.img tile, so that I can compare the results of my program with those of GPXSee. That's esp. interesting at tile boundaries.
I tried to drop a *.typ or start GPXSee with two files as arguments but that doesn't work.

**Comment by tumic0** [comment]
As described in the [documentation](https://www.gpxsee.org/doc.html#styles), you can have a global custom TYP file. Or you can extract the maps and use them in GMAP format, where you can easily fiddle with the `info.xml` file and define a custom TYP file for the map.

**Comment by tumic0** [comment]
Just a correction - line type 0xd are not county/parish borders, that's 0x1d. 0xd is something else, but the story is the same - there is no default style for stuff that is not used consistent among most maps.

**Comment by GerdP** [comment]
I already wondered because mkgmap has this method to detect types which are somehow reserved for routable lines: 

	/**
	 *  
	 * @param type the type value
	 * @return true if the type is known as routable in Garmin maps. These are 
	 * known to cause routing errors if used for non-routable lines. 
	 */
	public static boolean isSpecialRoutableLineType(int type){
		return type >= 0x01 && type <= 0x13 || type == 0x16 || type == 0x1a || type == 0x1b || type >= 0x2c && type <= 0x2f;
	}
