### ISSUE TITLE
Please add buttons for zoom

### ISSUE THREAD

**Issue by cpo-ux** [tumic0/GPXSee#431]
Hi, I am using this on a windows 10 touchscreen rugged tablet without keyboard.  When I double tap, in zooms in which is great however there is no way to zoom out.  Thanks for the great program!

**Comment by tumic0** [comment]
You can use the double right click for zoom out. On a touchscreen a two-finger tap should work as a right click.

**Comment by cpo-ux** [comment]
Thanks for the information however this doesn't work for me on this windows tablet.

**Comment by tumic0** [comment]
To be honest, I have no clue what gestures work on various touchscreens. GPXSee is a desktop application and it expects desktop input devices. The interface could be of course improved for mobile platforms, but that's not just about the zoom. Many other things will not work properly or at all on mobile devices. And as already stated in #413, I do not want to pretend that GPXSee is a mobile application and ruin it's reputation among mobile users. Either mobile platforms support will be "perfect" or not at all. But that does not mean you can not patch GPXSee yourself.

**Comment by cpo-ux** [comment]
GPXSee does have the ability to show current positioning.  So this would naturally lead to use more portable windows devices (and touch screen ones).  Unfortunately I don't code so I will not be able to patch it myself.  If anybody wants to introduce new functionality for zoom that would be great.  As far as I can see on the Windows 10 tablet I'm using the functionality is great without a physical keyboard except for the ability to zoom out.  Cheers.

**Comment by eddy-geek** [comment]
Being on my second 15" laptop with a touchscreen, I can vouch that a touchscreen is nowadays a common "desktop input device"... unless you take the word desktop literally of course ;-)

Panning the map on touchscreen is working great and in this context the lack of "pinch to zoom" functionality is surprising.

I am not sure if using the high-level [PinchGesture](https://doc.qt.io/qt-5/gestures-overview.html) or this lower-level [QTouchEvent example](https://doc.qt.io/archives/qt-5.12/qtwidgets-touch-pinchzoom-graphicsview-cpp.html) would be relevant for GPXSee?

**Comment by eddy-geek** [comment]
wrong link, maybe you meant [appveyor](https://ci.appveyor.com/project/tumic0/gpxsee/builds/43396696/job/xnlawx9ii35e7nuj/artifacts) ?

Anyway, not on windows but I'll see what I can do, thanks!

**Comment by tumic0** [comment]
Yes, I meant Appveyor, no idea how that url got there...

**Comment by tumic0** [comment]
> Anyway, not on windows but I'll see what I can do, thanks!

If you are on Ubuntu linux (I guess based on your other opened issues), then compiling your own GPXSee build from git is trivial. Just install the [devel packages](https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.dsc), do a git clone and run the three commands from the README.

**Comment by eddy-geek** [comment]
Built and tested, works great!

The sensitivity is quite high (on a 15" FHD touchscreen, Qt 5, Ubuntu 22.04, wayland), but definitely usable.

**Comment by tumic0** [comment]
You can fiddle with the [sensitivity factor](https://github.com/tumic0/GPXSee/blob/2df916eb95109964620e04d6e4dce14489630515/src/GUI/mapview.cpp#L633). On my test device (an android smartphone) I ended up with the current values (which were also used by some other guy in his patched version, so for smartphone-like devices this may be a "standard" sensitivity), but for bigger screens it may not be ideal. But until I either get some appropriate test device or there are more people suggesting a different value, I will stick with what we have now.
