### ISSUE TITLE
gpxsee does not display some gpx files

### ISSUE THREAD

**Issue by grozin** [tumic0/GPXSee#432]
I have a large collection of gpx files, most of them are displayed by gpxsee fine. But for some files, it just shows the world map, and that's all. I cannot understand what is the difference between these files and others. So, I attach an example. gpxlab and viking show this file fine. For some unknown reason, all these "bad" files are from 2011 and beginning of 2012; and the other way round, all 2011 files are "bad". Maybe, they are all taken using the same device, but I don't remember details.
[bad-wildbad-2011.04.22.gpx.gz](https://github.com/tumic0/GPXSee/files/8501999/bad-wildbad-2011.04.22.gpx.gz)

**Comment by sikmir** [comment]
That's really strange gpx file - each track point in separate track segment:
```
  <trkseg>
  <trkpt lat="48.752339999999997" lon="8.5493699999999997">
    <ele>458</ele>
    <time>2011-04-22T14:03:21Z</time>
  </trkpt>
  </trkseg>
```

**Comment by grozin** [comment]
But qmapshack, gpxlab and viking show it (though in gpxlab it looks a bit strange). OK thanks, I'll try to remove the extra <trkseg> and </trkseg> by a text editor. A little tiresome, I have a couple of dozens of such files.

**Comment by grozin** [comment]
OK, I've written a short python script removing </trkseg><trkseg> pairs. It has fixed most of broken files. In 3 of them, however, there were real trksegments, that were removed. I had to write another python script. It inserts </trkseg><trkseg> if abs of the difference of lattitudes or longitudes is > 0.01 degree. It has fixed the remaining 3 files.
I don't know why these files were broken. It seems all of them were edited by viking. However, there are many scripts edited by viking that were not broken.
Still, it is curious, why other viewers displayed these broken tracks without difficulties, while gpxsee did not.

**Comment by tumic0** [comment]
GPXSee requires a track segment to have at least two points, when segments are enabled. You can however disable segments in the preferences and the files will display like in all the other tools you have mentioned which do not support segments at all.
