### ISSUE TITLE
Can not install on MacOS Monterey

### ISSUE THREAD

**Issue by welsewool** [tumic0/GPXSee#433]
The system doesn't allow installing the app

<img width="275" alt="image" src="https://user-images.githubusercontent.com/13319725/163955481-391ab6c8-a520-480f-a740-a196d48ffb6f.png">

**Comment by tumic0** [comment]
This is just the traditional Apple [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty,_and_doubt). Apple does not allow software that does not generate them profit like GPXSee to be easily installed on macOS. You must use the "right click menu" to open the application for the first time.
