### ISSUE TITLE
Support Ubuntu 22.04

### ISSUE THREAD

**Issue by eddy-geek** [tumic0/GPXSee#434]
Can you add `repository name="xUbuntu_22.04"` to https://build.opensuse.org/projects/home:tumic:GPXSee/meta ?

From the [mailing list](https://lists.opensuse.org/archives/list/buildservice@lists.opensuse.org/thread/WOWJZMKI7H2H5X5UB26GWGYFK64AXMYV/) it seems supported:

> If you want to build for Ubuntu 22.04 you have to get to the Distributions page and "add from project". There you can enter xUbuntu22 and start building.

(Thanks for this awesome tool!)

**Comment by eddy-geek** [comment]
In the meantime here is a workaround, as the only issue (general issue with OBS + Qt + Ubuntu?) seems to be that ubuntu has no idea what qtbase-abi is.

```bash
wget https://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_21.10/amd64/gpxsee_10.7-1_amd64.deb
mkdir gpxtmp
dpkg-deb -R gpxsee_10.7-1_amd64.deb gpxtmp
sed -i 's/, qtbase-abi-5-15-2//g' gpxtmp/DEBIAN/control
dpkg-deb -b gpxtmp gpxsee-fixed_10.7-1_amd64.deb
sudo dpkg -i gpxsee-fixed_10.7-1_amd64.deb
```

**Comment by tumic0** [comment]
I will add support for Ubuntu 22.04 as soon as it is "normally" available as a distro in the OBS web interface. The OBS setup is very fragile and things have the tendency to break there (with noone to fix them when this happens), so I really do want to avoid any non-standard steps when not necessary.

**Comment by eddy-geek** [comment]
You were fast :)

Documenting how to add the ubuntu repo to remain up-to-date as that was not obvious to me ([source](https://en.opensuse.org/openSUSE:Build_Service_Debian_builds#Configuring_sources.list)):

```
echo 'deb https://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_22.04/ ./' | sudo tee /etc/apt/sources.list.d/gpxsee.list
sudo apt update
sudo apt install gpxsee
```

**Comment by tumic0** [comment]
The instructions for every distribution are part of the [download site](https://software.opensuse.org//download.html?project=home%3Atumic%3AGPXSee&package=gpxsee).
