### ISSUE TITLE
FR: Map fallback / Always focus GPX track

### ISSUE THREAD

**Issue by eddy-geek** [tumic0/GPXSee#435]
As first reported in #204, if gpx track is out of the boundary of the opened map (eg mbtiles), gpx track is invisible and impossible to navigate to.

The workaround is to select a worldwide (online) map then pan back to track.

I would prefer to keep the focus on the track (show white background, or switching to the first map which covers the area is a bonus)

More generally, I feel a "fallback" mechanism (again to white tile or alternate map) would be nice.
Related, one can also fallback to de-zooming an available level (eg from z-1 to z+2), which can also help:
* with MBTiles maps with nonconsecutive zoom levels (I didn't test https://github.com/tumic0/GPXSee/commit/22aa472dc36dc34043bef9696d926753cf047852 yet but I don't think it goes this far?) 
* to show a big GPX on a zoom-16-only MBTiles, or simply to help navigating it.

WDYT?

**Comment by tumic0** [comment]
There is no map where this would be generally possible as the map projection is often not defined outside of the map area (for example on the Antarctica map, you can not draw a track from the south pole to the northern hemisphere). Even the (web)Mercator projection that most people know will turn your tracks into garbage somewhere at 89N/S latitude. So while this is in some cases (the map does not cover the whole projection area) possible, you would have to handle every map (projection) specially and that is simply not worth it. Just use a map that fits your data.

**Comment by eddy-geek** [comment]
Ok, but you didn't argue against the "select a map that fits" approach. Known maps are in the menu, boundaries are known at least for offline maps, and when the remembered last used map is not adequate GPXSee could find another and display a "toast" to advise the user what happened. 

Right now the "gpx track focus" is a usability issue when using gpxsee as the default gpx viewer, especially for people with various local offline maps **already added to the *Map* menu** which seems to be the core functionality of the app :)

For example topographic maps tend to be per country and the alps cover 6 major countries.

Whether it's (de)zooming (so, no), allowing overlays (I think not, from your answer to other issues) or automatically fallback/switch to supported map, or other, can you say if a solution fits your vision for GPXSee?

**Comment by tumic0** [comment]
> Ok, but you didn't argue against the "select a map that fits" approach.

Well, the only argument I have here is, I do not like it :-) I prefer to chose the map myself as the first fitting map would be usually wrong anyway...

> Whether it's (de)zooming (so, no), allowing overlays (I think not, from your answer to other issues) or automatically fallback/switch to supported map, or other, can you say if a solution fits your vision for GPXSee?

I don't know what you mean by (de)zooming (GPXSee already fits the map, when a new track is loaded), so it's hard to give an answer here. The map switch was already discussed and overlays would be nice, but it is hard to do them properly with all the maps GPXSee supports (I have already tried, but it turned out that there are much more problems than expected). There may be some limited support for OSM type maps overlays like it is already implemented for the IMG maps, but it has not a high priority for me.
