### ISSUE TITLE
 No Maps are shown again

### ISSUE THREAD

**Issue by renardo-f** [tumic0/GPXSee#438]
A couple of months ago my gpxsee (Ubuntu, now 22.4) stopped displaying maps; the background of the tracks remained white. Here's what I tried so far:

* I found a similar issue (No Maps are shown #287) which is two years old and seems to have been fixed or at least closed.
* I upgraded gpxsee from 7.29 (Ubuntu repository) to 10.7 (.deb). No effect.
* I started gpxsee from a shell and checked the output. For some time nothing happeed; then I got many messages of the form "https://a.tile.opentopomap.org/12/2175/1419.png: Operation canceled." I can open these URLs in a browser but they sometimes take many seconds to respond.
* I checked the "map" menu, found that it was set to "Open topo map" and changed it to "Open street map." The same messages (with "opentopomap") appeared.
* I changed the selection to "USGS imagery" and got, almost immediately, messages of the form "Error transferring https://basemap.nationalmap.gov/ArcGIS/rest/services/USGSImageryOnly/MapServer/tile/13/2836/4348 - server replied:" In the browser these URLs result in a 404 message.
* I changed the selection to "USGS Topo", with a very similar result.
* I changed the selection to "4UMaps". Nothing happened.
* I selected "clear cache." Nothing happened.
* With every setting I toggled the "show map" button twice.

It looks like I am the only one with this problem. I would appreciate any hints.

**Comment by tumic0** [comment]
The OpenTopoMap server is very slow/unreliable in the last time and the USGS maps are valid (except of a few top levels) in the USA area only, so that may explain the errors you get. On the other hand, the OpenStreetMap server is fast and reliable so if you get no content in this case, than there is something wrong with your system/internet connection. To debug the issue, you will have to look at the network traffic in a tool like Wireshark. The "operation canceled" messages mean there was a network request timeout, but without no further info it is impossible to say anything more.

**Comment by renardo-f** [comment]
Thank you, Tumic0. Do you have an explanation why gpxsee tries to access opentopomap although I select Open Street Map in the "Maps" menu? I would like to use Open Street Map but my gpxsee insists on using opentopomap (or USGS), although it shows Open Street Map as selected (with a dot to the left) in the menu. How can I enforce my "Open Street Map" selection? (When I select "clear cache" the program prompts for clearing the "Open Street Map tile cache", so it got the setting.)

When I just now tried to reproduce the problem I got neither a map nor any error messages. A few hours ago there were at least http error messages. I have no idea what changed; I used the same GPX file.

By the way, the first message I get is always "/usr/share/gpxsee/maps/Antarctica.xml: Antarctic_Basemap: layer not provided." I have no idea if that is in any way related, though. Sometimes there is another message "QObject::disconnect: No such signal GUI::logicalDotsPerInchChanged(qreal)."

I just noticed that the settings / map / input drop-down contains far more values than I could ever hope to understand. To the best of my knowledge I have never changed anything there; it is currently set to "4326 - WGS 84 / Geographic 2D." Is there anything wrong with that?

**Comment by tumic0** [comment]
There is IMHO no other explanation for all the weird errors you get than that you have some broken GPXSee build. Looks like you have a package that was not build for your system or there is something very wrong in your system. If you build GPXSee from the sources on your machine, do you get the same errors?

**Comment by renardo-f** [comment]
Thanks again for your hints. Unfortunately I have found that in order to build gpxsee from source I need a Qt5 installation (/usr/lib/qt5), which would require getting a Qt account. Just reading and understanding the license agreement would take me a whole afternoon, without any warranty that it would lead to anything. (Yesterday I installed gpxsee freshly from gpxsee_10.7-1_amd64.deb, so I do not see what installing from a fresh build could change.)

Anyway, thanks for trying to help. As far as I am concerned this issue may be closed. I had assumed it might be a known issue.

**Comment by renardo-f** [comment]
Browsing the options dialogue I found the cause of the problem. Somehow the map opacity had been set to 4 %, which of course resulted in a virtually invisible map. Resetting it to 100% resolved my problem. (I don't remember ever having consciously changed this opacity but who knows.)
