### ISSUE TITLE
Menu on Android (dark mode)

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#439]
![Screenshot_2022-05-31-23-30-48-375_org.gpxsee.gpxsee.jpg](https://user-images.githubusercontent.com/688044/171284274-94b3c85a-6511-404d-a842-c0c3139f33b7.jpg)

**Comment by tumic0** [comment]
My "test" device has Android 8.0 which AFAIK does not have dark mode so I'm not able to test that, but the menu is a standard Qt Android menu without any styling. So it looks to me as a Qt bug (there are even more of them on Android than on macOS...)

**Comment by sikmir** [comment]
I see. As workaround Android has an option to restrict Dark mode for individual apps.

**Comment by sikmir** [comment]
Looks like localization doesn't work as well. Are translation files bundled on Android?

**Comment by tumic0** [comment]
Not yet. There are two issues with them:

1. I have to find out how/where to bundle them for the Android build.
2. Some new  - shortened - strings must be translated and all the languages have to be checked that they fit everywhere on the small screen. There were changes necessary even for English, I'd rather not imagine how German looks like...

In addition to the localization, there is one more thing missing in the Android build - QtPBFImagePlugin. Principally, it should work but it is a lot of work to make it build for all the architectures and integrate it into the build.

**Comment by tumic0** [comment]
Seems to be "fixed" in the currently used Qt 6.4.0, at least on my new Android 13 phone. The style is still bright but it is at least not  broken. A "real" dark style will come when Qt makes it work like it works on KDE and OS X.
