### ISSUE TITLE
KMZ Import showing as Unknown Format

### ISSUE THREAD

**Issue by Drakensin** [tumic0/GPXSee#442]
![Screenshot_20220613-095800](https://user-images.githubusercontent.com/26281394/173372791-55e5c8a5-c57a-4c9d-a1ca-ba14268e1672.jpg)

Using the Android version to get map data of SxS trails with a .KMZ file and it appears to be on unknown format.

**Comment by tumic0** [comment]
You must open the file as a map, not as a data file.
