### ISSUE TITLE
carico mappe lento

### ISSUE THREAD

**Issue by fabribr** [tumic0/GPXSee#444]
buon giorno,
ottimo programma per analizzare i file gpx ma è molto lento nel caricare le mappe , specialmente la Open topo map.
è possibile rimediare a questo problema?
grazie

**Comment by sikmir** [comment]
That's slow OpenTopoMap server, not GPXSee.

**Comment by fabribr** [comment]
I understand, thanks for your answer !

**Comment by tumic0** [comment]
There is nothing I can do with the speed of various map servers. Look at [maps.gpxsee.org](https://maps.gpxsee.org/), maybe you can find there a better map provider that fits your needs and is faster than the OpenTopoMap server (which is quiet slow in the last time).

**Comment by fabribr** [comment]
ok .. I will also try this, because in this way it is not possible to use it. Thank you

**Comment by fabribr** [comment]
thanks, I'll try
