### ISSUE TITLE
Feature or bug?

### ISSUE THREAD

**Issue by RealVegOs** [tumic0/GPXSee#445]
When I drop a JPG filte over GPXsee, the filename jumps to the correct location, where the photo was taken. By hover over the name, the photo is displayed by a littel popup. Is a feature or a bug?
![22-07-17-gpxsee](https://user-images.githubusercontent.com/7726676/179410860-091b78eb-bb2e-4748-898f-8748ebf644d0.jpg)

**Comment by tumic0** [comment]
That's a feature. JPEGs with GPS EXIF headers are handled like waypoints when opened by GPXSee.

**Comment by RealVegOs** [comment]
OK, that's fine! But there is no way to load photos via dialog. It also looks like, GPXsee can only load one photo at time. All of a directory or a number of them would be better for me. Gpsprune loads a set of photos, but I prefer your program to display my Garmin tracks. Does this qualify for a feature request?

**Comment by RealVegOs** [comment]
Ops, I cannot edit my last comment. So: It is possible to load a set of photos. The problem is, you do not see them in the file dialog when "all supported file types" is selected. You have to change to "all files". Supported file types only shows gpx files for me. That's a bug indeed!

**Comment by tumic0** [comment]
Opening multiple files should work fine. If the file dialogue does not show JPEG files then you are probably facing [QTBUG-51712](https://bugreports.qt.io/browse/QTBUG-51712). As a workaround you have to select all files, rename your files to have a lower case suffix or use a different desktop environment (e.g. KDE) where the QT file dialogue works fine.
