### ISSUE TITLE
android can not import mbtiles

### ISSUE THREAD

**Issue by drandgan** [tumic0/GPXSee#448]
![Screenshot_2022-08-03-15-33-24-320_org gpxsee gpxsee](https://user-images.githubusercontent.com/110545902/182626816-466d0b8c-ca80-46d3-b7d3-4a08fd22f54d.jpg)

Can not import mbtiles file on android device. Same file is working fine on the windows.

BR

**Comment by tumic0** [comment]
SQlite-based maps only work when they are read from the application map directory on android. This is the same issue as with "multiple files based maps" already described in the [documentation](https://www.gpxsee.org/doc.html#issues). I will extend the documentation, but that's all I can do about it...
