### ISSUE TITLE
Icons for waypoints

### ISSUE THREAD

**Issue by jay0pi0** [tumic0/GPXSee#454]
I use to create waypoints in "Locus Map" for Android with different symbols, representing different meanings.
For me personally, it would be desirable to be able to see at least different (if not the same) icons in GPXSee.

I attached a GPX file created by Locux Map with those 4 WPTs shown in the screenshot below.

<img width="960" alt="Unbenannt" src="https://user-images.githubusercontent.com/113432715/189888179-a6889414-104e-4d0f-8191-b8bae19196ce.png">

[Punkte,_4_Punkte.zip](https://github.com/tumic0/GPXSee/files/9556534/Punkte._4_Punkte.zip)

**Comment by tumic0** [comment]
You can use any icon you like for a given waypoint symbol, you just have to provide the image file in the `symbols` directory as described in the [documentation](https://www.gpxsee.org/doc.html#symbols). By default GPXSee comes with a set of "standard" (as used on GARMIN devices and various SW tools) [icons](https://github.com/tumic0/GPXSee/tree/master/icons/symbols), but your symbol names seem to be quite unique, so none of your waypoints matches.

**Comment by jay0pi0** [comment]
Hi Martin, thank you for the GARMIN keyword! I discovered that in Locus Map, one can also select "Garmin style" icons for the waypoints (in addition to Locus Map's own). Those GARMIN icons get tag names like "Building" - et voilà, they do indeed work with GPXSee. 🙂🙂👍
