### ISSUE TITLE
Copy text from WPT description

### ISSUE THREAD

**Issue by jay0pi0** [tumic0/GPXSee#455]
When clicking on a WPT, information is shown in a pop-up. It looks like the text that appears in that pop-up is selectable by left-click + drag or double-click on the text (a very very faint shade of gray is showing up to show the selection). But pressing CTRL-C does not copy that selected text. Right-click makes the pop-up disappear.

I would love to have that text copyable 🙂

![image](https://user-images.githubusercontent.com/113432715/189889767-6049b214-9d45-4b86-8d47-4eac42c85ced.png)

**Comment by tumic0** [comment]
Copying text from the popups should work (it works on linux), but on Windows it is broken for some (unknown) reason. I can fill a Qt bug, but that's almost all I can do about it...

**Comment by jay0pi0** [comment]
Alright, thank you for checking! I guess I'll use RouteConverter or Notepad++ for extensive work with WPT comment texts. (RouteConverter creates a nice editable list of the WPTs in a GPX file.)
