### ISSUE TITLE
Wish: display absolute time-of-day in the red data om the elevation track

### ISSUE THREAD

**Issue by Tux** [tumic0/GPXSee#456]
If I prepare a track.route, I take an original GPX file and rewrite it to reflect the expected speed on a specific date with a specified start time. I'd like to see the (expected) time of day in HH:MM next to the altitue and distance when I drag the line over the track. See https://tux.nl/Files/gpx-cursor.png for the "red" I mean. Alternatives could be the x-axis of the Speed tab instead of the distance (the distance is in the cursor already) or the bottom data line, but on the cursor data would be more intuitive.

I can also switch the Graph from Distance to Time, but I want to see both at the same time. Even if I switch to Time, it only shows the time relative to start, and not the absolute time of day

I could try to do it myself (I guess it is line 473 in src/GUI/graphview.cpp) but I am not a c++ programmer and I have no idea if this quest is sane enough to warrant options and setting.

I know I can set Data->position-info to Date/Time, but I prefer coordinates there and the date/time is not formattable (it ignores LC_TIME) so it displays as M/D/Y which is - for me being Dutch - extrememly annoying and counter-intuitive. (must add that I have EN_US.utf-8 with *modified* system settings)

**Comment by Tux** [comment]
Hmm, maybe it needs much more, like a third argument `_z` in src/GUI/sliderinfoitem.cpp - way beyond my area of expertise.
I also cannot find the locations where date and time are formatted to US instead of obeying `LC_TIME`:
```
$ locale -ck LC_TIME
LC_TIME
abday="Sun;Mon;Tue;Wed;Thu;Fri;Sat"
day="Sunday;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday"
abmon="Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec"
mon="January;February;March;April;May;June;July;August;September;October;November;December"
am_pm="AM;PM"
d_t_fmt="%a %d %b %Y %R %Z"
d_fmt="%d-%m-%Y"
t_fmt="%R"
t_fmt_ampm="%H:%M:%S"
era=
era_year=""
era_d_fmt=""
alt_digits=
era_d_t_fmt=""
era_t_fmt=""
time-era-num-entries=0
time-era-entries="S"
week-ndays=7
week-1stday=19971130
week-1stweek=1
first_weekday=1
first_workday=2
cal_direction=1
timezone=""
date_fmt="%a %d %b %Y %R %Z"
time-codeset="UTF-8"
alt_mon="January;February;March;April;May;June;July;August;September;October;November;December"
ab_alt_mon="Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec"
```

**Comment by tumic0** [comment]
You can configure GPXSee to show the absolute time on the track marker. In the graph markers there is not enough place for the info and it would be very hard to get this info into the graphs as the X axis (see #35 for some more info).

**Comment by tumic0** [comment]
Regarding the date format issue - GPXSee [uses](https://github.com/tumic0/GPXSee/blob/e8e1e98775cb6e7d3d175653daae58a43c5c3604/src/GUI/markerinfoitem.cpp#L26) Qt's QLocale class to format the date. If you think it handles your custom locale configuration wrong, you can fill an issue in the Qt bug tracker.
