### ISSUE TITLE
[support] trackpoints on track

### ISSUE THREAD

**Issue by solsticedhiver** [tumic0/GPXSee#458]
It is not really an issue but I can't find a place to ask questions about gpxsee. Is there any IRC or matrix,or discord or whatever to ask about gpxsee ?

I have a gpx with multiple tracks, but I wanted to be able to get a popup with the time when I hover my mouse over the track. To know the precise time I was at that point.

There is already those tiny rectangle with numbers. I don't what they are actually. They show a number (what is it ?) and distance and duration and time of start ?

I don't have any waypoiny on the track, that's the problem.

If not possible with gpxsee, what can I use instead? On linux.

Thank you

**Comment by tumic0** [comment]
You can get the exact time on the track by setting the position info to date/time (Data->Position info->Date/time). The popup that gets displayed when you hover over a track or click on it is just a "global" track info (it comes in handy when you have multiple tracks open).

Regarding IRC/matrix/discord - there is no such thing at the moment. I could enable the discussions here on GitHub when there is interest, but  till now the issues were sufficient. The goal is to make GPXSee (and it's documentation) so clear that there is no need to ask questions :-)

**Comment by solsticedhiver** [comment]
Yes, I can see the date/time of a track. But like I said, on a 30 minutes length duration  track, it does not help me to know at what precise moment (to the second) I was at on point in time.
For example, on a multiple tracks gpx file, click on a point and get the nearest time it was recorded. Or may be, print all the track point of the track.

**Comment by solsticedhiver** [comment]
And while I am at it, a menu with the different track with a sum up , and be able to choose to disable some or all of them. Sometimes, the gps is misbehaving, and gpsd/gpxlogger record a track when I am stationnary,because the gps does not get a good fix, which constantly changing.

**Comment by tumic0** [comment]
A time info with a seconds precision is in the graphs. The time is relative in this case, but I can not imagine a situation where I would need the absolute date/time with seconds precision.

Regarding the point list, this has already been discussed here in the past - GPXSee is explicitly designed __not__ to contain any point lists or edit the data. There are however some filters applied when displaying the data that should handle GPS errors, but this can never work 100%.

**Comment by solsticedhiver** [comment]
When I click on the graph, there is a point displayed on the map on the track with date/time. That's a start. Seconds are missing though. But it would be easier, to click on the map to get that.

**Comment by solsticedhiver** [comment]
oh and I did not meant to edit the gpx file, but to hide unrelevant track with (for example) garbage gps position.

**Comment by tumic0** [comment]
> When I click on the graph, there is a point displayed on the map on the track with date/time. That's a start. Seconds are missing though.

Yes, that's why I'm writing that the time with seconds is in the graph...

**Comment by tumic0** [comment]
> oh and I did not meant to edit the gpx file, but to hide unrelevant track with (for example) garbage gps position.

There are filters to handle such data. If they don't work in your case, than you have to edit the data manually and this is what GPXSee is not designed to do. No matter if you then save the data (back) to a file or not, any manual editing is out of scope of GPXSee.
