### ISSUE TITLE
Elevations below sea level (<0)

### ISSUE THREAD

**Issue by ninelima** [tumic0/GPXSee#46]
https://en.wikipedia.org/wiki/List_of_places_on_land_with_elevations_below_sea_level
There are valid elevations below seal level. 
static bool readAltitude(const char *data, qreal &ele)

It appears as if these altitudes are rejected?

**Comment by tumic0** [comment]
According to the specification - https://www.fai.org/sites/default/files/documents/igc_fr_spec_with_al4a_2016-4-10.pdf , page 29 - negative values are not supported for GNSS altitude entries. Do you have some file example from a real datalogger, that contains negative GNNS altitude values?

**Comment by ninelima** [comment]
[2017-11-28-XCS-AAA-03.zip](https://github.com/tumic0/GPXSee/files/1608552/2017-11-28-XCS-AAA-03.zip)

Attached is a igc file which I made in the car. It contains negative altitudes.

I believe that negative altitude is required by the specification.
From Page 29:
* Press Alt.   
* 5 bytes  
* PPPPP 
* Altitude to the ICAO ISA above the 1013.25 HPa sea level datum, valid characters
0-9 and negative sign "-".  Negative values to have negative sign instead of leading zero

**Comment by tumic0** [comment]
GPXSee uses the GNSS value for the altitude, which has - according to the document - only valid characters "0-9". It is probably a bug in the specification - I have seen a former version which did not allow negative values for the barometric altitude either.

However if "real" units do create entries with negative values there is no reason to handle them as invalid input in this case, so I will add support for it into the IGC parser.

**Comment by ninelima** [comment]
Thanks. It is more useful this way. It is entirely possible to get 
negative numbers during the takeoff from a runway close to sea level.

I am hoping that GPXSee can one day be an open source alternative to The 
commercial "SeeYou" from navITer
http://www.naviter.com/products/seeyou/

The 3D playback would be really nice to have in GPXSee.

https://youtu.be/rrB80httTO4



------ Original Message ------
