### ISSUE TITLE
Feature Request - use colors and icons from current KDE theme on Linux

### ISSUE THREAD

**Issue by peterhoeg** [tumic0/GPXSee#461]
If running under KDE on Linux, please pick up the system colors and icons to make gpxsee look like the other running applications.

**Comment by tumic0** [comment]
Unless someone provides __all__ the icons, this will not happen. You can use "platform icons" in Qt, but only for a very limited set of icons and the result - a mixture of icon styles - is much worse than a complete custom set.

The color scheme is already set to the current desktop color scheme. At least it works on my KDE desktop as well as desktops of some other people that were reporting dark scheme problems in the past. So if you think there is a specific issue, please provide more info including screenshots here.

**Comment by peterhoeg** [comment]
strawberry (a media player) supports using the system icons and it offhand uses *far* more icons than gpxsee but looks great here (with breeze). I understand of course that it'll be a mixed bag depending on which icon set is in use, so maybe having the option of the user choosing if the system icons should be used (and default to off) would work better?

As for the colors, you're right. I had the impression that it was for some reason darker than the rest of the environment when switching to a dark theme, but I was mistaken. All good on that front.

**Comment by tumic0** [comment]
I'm really not able to provide special icons for every platform where GPXSee may run. But you can adjust the icons when building a package for that platform like [Haiku](https://depot.haiku-os.org/#!/pkg/gpxsee/haikuports/haikuports_x86_64/11/4/-/-/1/x86_64?bcguid=bc145-SAEH) does.

**Comment by peterhoeg** [comment]
> I'm really not able to provide special icons for every platform where GPXSee may run

That's not actually necessary. If you guard it behind a "use system icons" option, the results will of course wary but it will not be your problem if it looks terrible.

And because this stuff isn't said often enough - thank you very much for gpxsee!! It's an awesome piece of software.
