### ISSUE TITLE
heart rate zones

### ISSUE THREAD

**Issue by shiroyagi** [tumic0/GPXSee#463]
It would be nice if the heart rate graph could show zones, at its simplest using these for the y-axis grid lines.  A bar chart of time in zone would also be useful (on the statistics window?).  Zones could either be read from the activity file (eg. .fit) or defined manually.

**Comment by tumic0** [comment]
Such visualization/analysis is out of the scope of GPXSee. Use GoldenCheetah or a similar tool for this type of data processing.
