### ISSUE TITLE
Copy the documentation into the app

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#467]
The documentation on https://www.gpxsee.org/ should also be able to be accessed offline inside the (Android) app.

**Comment by tumic0** [comment]
I don't think so. Everyone with this special need can save the doc page manually for further offline usage, no need to push it to everyone.

**Comment by jidanni** [comment]
Okay, but if you ever change your mind https://vespucci.io/ seems to do good job at twin documentation.
