### ISSUE TITLE
Website not mobile ready

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#468]
The documentation on https://www.gpxsee.org/ is very hard to read on a cell phone. Some simple changes could be made so the website would also be mobile ready.

**Comment by tumic0** [comment]
Please provide the changes (you can use a pull request to the gh-pages branch) or at least describe them somehow. The pages are definitely not mobile-friendly as this was not a goal when they were created (there was no Android version of GPXSee at time so it didn't make much sense), but I'm really not sure if some "simple changes" can fix that...

**Comment by jidanni** [comment]
All I know is pure HTML, with no side panel, would wrap around the screen without getting chopped off.,

But then there is also https://www.google.com/search?q=how+to+make+mobile-friendly+website+version .
