### ISSUE TITLE
Provide "more info about current layer" link

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#469]
Let's say we load the UNESCO layer.

We think it is a great layer, and we want to learn more about it.

Well, inside the app there is no button to get more information about it, so we have to look inside the  .XML file.

In that we infer that we should look around the https://www.unesco.org/
Website for more information. But that's rather hard. There is too much stuff there. A search turns up 500 matches.

So, next time when the team is adding new layers they should remember to jot down the introduction to layer URL.

Then, by putting that in an appropriate field, the app could turn this into a link when one puts pushes a future "more info button."

**Comment by tumic0** [comment]
The map definition files (that you call "layers") are well readable XML files so anyone who wants to see all the included info can easily do that. The map files are created by volunteers, there is no "team" behind them. Tis means when you want some more info in the map files, you have to provide it as a pull request with the appropriate XML comments.

**Comment by jidanni** [comment]
(Okay, but here's how some other apps display their XML data,)
![Screenshot_20221216-083307_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/208145463-2b164720-b5da-4e11-b394-113c542e5432.jpg)

**Comment by tumic0** [comment]
When you open the XML definition file, you get

```xml
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4">
	<name>Open Topo Map</name>
	<url>https://a.tile.opentopomap.org/$z/$x/$y.png</url>
	<zoom max="17"/>
	<copyright>Map data: © OpenStreetMap contributors (ODbL), SRTM | Rendering: © OpenTopoMap (CC-BY-SA)</copyright>
</map>
```

Which is almost the same as you can see in your example (the projection is implicitly given by the map type and the tiles path can be seen under Help -> Paths). GPXSee's philosophy is different than the philosophy of Android/Android apps where files are "bad". GPXsee paths/files are the way how to configure the app like it is usual on UNIX (Linux) where GPXSee has its origin.
