### ISSUE TITLE
Crisis when unpinching at maximum zoom level

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#470]
Here on android, we observe the app has no plus or minus zoom buttons. Therefore we must use our two fingers with the pinch and unpinch motions. So far so good.

However, when we reach the maximum zoom level, one of our fingers becomes "the chosen finger" and it starts moving the entire map up or down  the screen! (The other finger is ignored.)

(Zooming has now become panning!)

**Comment by tumic0** [comment]
What do you expect to happen? I do not see this as a bug...

**Comment by jidanni** [comment]
Here I have zoomed https://www.openstreetmap.org/ via unpinching, as far as it will go.
![Screenshot_20221216-082545_Brave - Beta.jpg](https://user-images.githubusercontent.com/1230959/208143930-a3601b29-8b99-498c-8270-5daf73135a8c.jpg)

Try it yourself: any further unpinching just snaps back. The website still knows the difference between two fingers and one. If I instead use one finger the website starts panning.

My two fingers are still recognized even though there is no more zooming possible except temporary zooming that snaps right back.

So it would be great if your app did the same as Openstreetmap here.

**Comment by tumic0** [comment]
While it would be nicer for the app to not respond at all to the pinch gesture when at the zoom limit, this is something that can be hardly changed as this is a "feature" of Qt. The touch input handling is quiet broken in Qt for Android (for example double tapping should zoom like it does on desktop on double click, but it doesn't) and until Qt fixes it, there is not much I can do about it.
