### ISSUE TITLE
FIT developer data

### ISSUE THREAD

**Issue by pbljung** [tumic0/GPXSee#476]
GPXSEE reads FIT files but does not read any developer data fields.

The Garmin FIT SDK is available at https://developer.garmin.com/fit/download/
A tiny FIT file with developer data is ~/FitSDKRelease_21.101.00/examples/DeveloperData.fit
Developer data is described at https://developer.garmin.com/fit/cookbook/developer-data/

Debugging FITParser::parseDefinitionMessage() shows it correctly identifies the number of developer fields def->numDevFields, but readdata() always leaves type=0 (invalid). As a result no developer data fields are available to view.

The online FIT viewer successfully reads the developer data fields
https://www.fitfileviewer.com/

**Comment by tumic0** [comment]
GPXSee is not designed to read any data from the files and somehow magically display them. It must "understand" the data to assign them to one of the supported data fields:

- elevation
- speed
- heart rate
- cadence
- power
- temperature
- gear ratio/shifts

any other data is ignored which is the case of all FIT developer data. If you think there is some category missing in GPXSee, then create a new request (issue) where you describe the category, why it is important to other users than you and provide some sample data.
