### ISSUE TITLE
Fractional scaling support on wayland

### ISSUE THREAD

**Issue by eddy-geek** [tumic0/GPXSee#478]
Hello,

```
gpxsee 11.12
Qt 5.15.8
Linux 5.19.0-24-generic
kwin 5.26.90
```

it seems there are issues with fractional support on Plasma/KWin/Wayland.

My system is set at 135% and what I think is happening is:
* "Standard" mode - ok, image are drawn at 135%
* "High-resolution" mode - I think they are drawn at 2x then scaled-down, so in the end 1 image pixels is drawn on 1.35/2 ≈ 0.67 screen pixels.

![Screenshot_20230129_144608](https://user-images.githubusercontent.com/2772505/215331030-1b855d57-b0b5-4b2e-9d9e-d7ee968f566b.png)

It can probably be linked to the way Qt scaling currently works on wayland (I think it's making apps draw at `ceil(ratio)` then the compositor downscales). Since work is ongoing to change this with [this recent wayland change](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/143) and [Qt 5 patch](https://invent.kde.org/qt/qt/qtwayland/-/commit/23d3fc7) (which I don't think my system has yet), if eg Linux-X11 & Windows work fine, I guess it's fine to hold off for the time it takes for the ecosystem to catch-up.

**Comment by tumic0** [comment]
The HiDPI map scaling should be fractional (but you can not get non-blurry images in other multiplications than 2^n), but I'm not sure what exactly you are referring - your image/screenshot mix is blurred as whole, not only the map. This would suggest some global scaling problem.

However, like with other exotic configurations, there is not much I can do about it until someone completely describes what is the root of the issue and how it can be solved. Without having some reference system (I don't/can't have wayland on my linux machine and I do not have a HiDPI monitor) I can hardly investigate/solve such issues.

**Comment by tumic0** [comment]
[QTBUG-123125](https://bugreports.qt.io/browse/QTBUG-123125)
