### ISSUE TITLE
Track width for PDF export not configurable

### ISSUE THREAD

**Issue by feliwir** [tumic0/GPXSee#483]
Hello,
is it possible to configure the width of tracks & routes for the PDF export? The settings don't seem to be applied (however for PNG export it is applied). When i increase the DPI the line width also doesn't change, resulting in smaller lines with higher DPI

**Comment by tumic0** [comment]
The settings are applied to the PDF export too. But if you have the "high-resolution" export enabled (which I suggest from your other issue), than small changes are hard to see as the line does not "grow" very fast due to the desired rendering scale.
