### ISSUE TITLE
High-resolution mode has large margins

### ISSUE THREAD

**Issue by feliwir** [tumic0/GPXSee#484]
Hello,

thanks a lot for this great program - exactly what i was looking for. I'm attempting to visualize multiple GPX records of my bike tours. 
I found the "High-resolution" which seems to do exactly what i want - fit the zoom to exactly to my content.
However the generated PDF has large margins in all directions. Any ideas how i can fix this behaviour? See the attached PDF
[export.pdf](https://github.com/tumic0/GPXSee/files/10840985/export.pdf)

**Comment by tumic0** [comment]
You can not fix it, this is how the "High-resolution" in principle works. The PDF is rendered in such a way, that the map images do not get scaled, so there are only discrete steps of map sizes available for resizing the paths.

**Comment by tumic0** [comment]
In WYSIWYG this is definitely possible. Just adjust the tracks in the viewport (window) so they have the desired position/margins and do an export. But the map images will of course be scaled.
