### ISSUE TITLE
FR: Persist Loaded map in Map menu

### ISSUE THREAD

**Issue by venkycz** [tumic0/GPXSee#485]
It would be very helpful, when the map loaded using "**_Load map.._**" menu item, could be persitent in **_Map_** menu for next use.

![GPXSeeMapMenu](https://user-images.githubusercontent.com/51228586/225913448-47360a42-b1ed-499f-ac33-aaf1642c5570.png)

**Comment by tumic0** [comment]
You can configure the maps in the menu by providing the corresponding file (including symlinks) structure in the configuration directory as described in the [documentation](https://www.gpxsee.org/doc.html). Adding every map permanently when loading it is not something one would like in many/most cases.

**Comment by venkycz** [comment]
Thank you for pointing out the possibility to create a symlink directly to the map file in the GPXSee map directory.
👍
