### ISSUE TITLE
Richer toolkit to deal with tile number math

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#493]
Looking at https://www.gpxsee.org/doc.html
it seems GPXSee lacks a way to, for example use {17-z}/{x}/{y}.jpg*
in case a certain site needs it. See
https://www.alpinequest.net/en/help/v2/maps/on-demand-create
for some function ideas.

In fact somebody should make some kind of module other programs could
use, so each app wouldn't need to reinvent the wheel.

(* https://skyvector.com/ seems to use something like that.)

**Comment by tumic0** [comment]
If there is some openly accessible map service that uses some kind of unsupported tile logic than provide a link to the service and I will eventually implement support for it. Some applications have support for "URL mangling" but although this mangling may be as rich as in case of AlpineQuest at the end it is almost exclusively used for the Y axis inversion (there is the TMS map type in GPXSee for that) and in some rare cases for some projection computations when accessing WMTS tiles (GPXSee has "full" WMTS support including ~4300 projected coordinates systems).

The goal of GPXSee is not to "hack" support for various commercial services that deny access to their tiles (like SkyVector). If you need access to some special private map service you can always modify the sources yourself as GPXSee is, unlike the service, free for all to fiddle with it.
