### ISSUE TITLE
click track to set crosshair cursor position

### ISSUE THREAD

**Issue by shiroyagi** [tumic0/GPXSee#494]
If you click on the graph, the crosshair is positioned at the corresponding point on the track on the map, but the reverse does not happen.

**Comment by tumic0** [comment]
That is the intended behaviour. There are some technical reasons as well as UX reasons behind it (e.g. what to do with multiple tracks). It might be probably somehow implemented but during the years of using GPXSee I have never missed it so the priority is super low for me...
