### ISSUE TITLE
elevation profile of .gpx is missing if  trkpt contains no time

### ISSUE THREAD

**Issue by Jakobs50** [tumic0/GPXSee#496]
Hi,
if a .gpx file contains trackpoints with  lan, lon and <ele> but no <time> elements no elevation profile is displayed.
Release 13.2.

**Comment by tumic0** [comment]
Works for me, but you have of course to select distance as the X axis. If you still think that it does not work, than provide the GPX file for analysis.

**Comment by Jakobs50** [comment]
You are right! I should have investigated longer :-)
