### ISSUE TITLE
MS virus scanner doesn't like the latest

### ISSUE THREAD

**Issue by dpawlyk** [tumic0/GPXSee#498]
MS virus scanner doesn't like the latest

![image](https://github.com/tumic0/GPXSee/assets/26445864/53bc74db-3f5f-4b73-b51d-9748d46180b3)

**Comment by tumic0** [comment]
[virustotal](https://www.virustotal.com/gui/file/bc55adffe0bba3759df53aa7f3b2dd3ba0e101e81e09ec1afb6ee4aad325c434) aggregated analysis does not show any detection (false positive) on the file I have re-downloaded from Sourceforge so this looks like some temporary problem with your local or Microsoft's virus database. I guess it will be gone with some update in a few hours.

**Comment by dpawlyk** [comment]
Thanks for looking at it. On Jun 2, 2023, at 10:12 PM, Martin Tůma ***@***.***> wrote:﻿
virustotal aggregated analysis does not show any detection (false positive) on the file I have re-downloaded from Sourceforge so this looks like some temporary problem with your local or Microsoft's virus database. I guess it will be gone with some update in a few hours.
