### ISSUE TITLE
Virus Detected with Windows Defender?

### ISSUE THREAD

**Issue by GW61** [tumic0/GPXSee#500]
Downloading the lasted version GPXSee-13.4_x64.exe Windows 11 Defender get a "Detected: Trojan:Win32/Spursint.F!cl" and deletes the file.
Anyone else getting this ?

**Comment by tumic0** [comment]
The aggregated  [analysis](https://www.virustotal.com/gui/file/cfe3fcf7d9d772d867355b6b3f2487dddeecbd2d3438629f247b91507be913b7) on Virustotal does not show a single detection of the installer file. But Microsoft has evidently some problems with false-positives in their recent virus databases as some people have reported the same issue with the 13.3 installer in  #498.
