### ISSUE TITLE
[Android] Stretch Graph

### ISSUE THREAD

**Issue by snooppr** [tumic0/GPXSee#501]
GPXSee on PC can stretch the plot, handy for analysis over long distances, but on Android GPXSee doesn't seem to be able to do that.  This is a problem, for example, I overlaid the GPS heights by device and DEM, the difference is not visible on the graph due to the length of the track, it is.

![ScreenshotGPXSee](https://github.com/tumic0/GPXSee/assets/61022210/38d162f0-989a-4921-b361-90b69a12907b)

Please add graph stretching to make GPXSee work on Android as well as on PC.

p.s. Good software I mentioned you in my [article](https://habr.com/ru/articles/674294/) .

**Comment by snooppr** [comment]
Great.  With the update came the ability to scale the graph.

How about optimizing this process now?  When you try to scale the chart, everything slows down, and there is also no way to reset the scale to the beginning with one button.

There are various Android applications for working with gpx, where the graph is scaled without brakes, for example, Sports Tracker or Fito Track. 

**Please optimize the chart scaling process on Android OS.**

**Comment by tumic0** [comment]
For "normal size" GPS logs the graphs move smooth for me. But when you have a big amount of track points it really can get slow. Enabling OpenGL (when it works and does not crash...) helps here, but for some universal solution some track/graph points decimation would be needed. That may come one day, but as on my logs there is no problem, the priority of such task is really low...

**Comment by snooppr** [comment]
Well, I'll write additional information just in case.  Android LOS16.  Track distance 10km, 4600 points (from the small track area).  The graph is scaled by jerks (a jerk is about a second).

**Comment by tumic0** [comment]
Version 13.26 should be much faster when rendering the graphs.

**Comment by snooppr** [comment]
version 13.26. Graphs that work quickly: tabs "height", "heart rate". Graph "speed" response is measured in seconds (slows down). Smoothing is set in the settings - 3 for all parameters. Tracks for testing 1Mb, 2.5Mb

**Comment by tumic0** [comment]
Can you please provide some real data files? While rendering the ragged speed graphs is slower than the elevation graphs, I do not see "responses in seconds" on my data, even on 2-3MB files. From your descriptions (10km, 4600 points) I'm suspecting you are mostly rendering noise as a density of ~2m per point is way beyond the precision of consumer GPS devices...

Anyway, the solution for your data might be enabling OpenGL (Settings->System->Enable OpenGL) rendering, if it works on your device. On the desktop it makes rendering of huge data sets (hundreds of tracks, thousends of km) possible/smooth, but on Android it often [crashes](https://bugreports.qt.io/browse/QTBUG-120498).
