### ISSUE TITLE
HiDPI mode broken

### ISSUE THREAD

**Issue by eddy-geek** [tumic0/GPXSee#502]
Building latest master (https://github.com/tumic0/GPXSee/commit/1dc963b133576df2aaca35e46974ba1dd874fb4a) from source, toggle in settings > Maps > HiDPI display mode is broken.

It seems stuck in Standard mode.

I have 11.4 side-by-side with the same config, so I'm sure something changed although it could be just my env of course :)

Could it be something in https://github.com/tumic0/GPXSee/commit/97e12d809f4a129c454587c98a76ca447aa59cb5 ?

**Comment by tumic0** [comment]
Works for me. Can you provide your configuration file?

**Comment by eddy-geek** [comment]
ok, I built 13.0 from source and it has the same issue... and I checked, my env builds with Qt 5 which is certainly the source of the issue as I'm using Linux Wayland, and Qt 6 has some Wayland improvements.

so, closing, sorry for the noise
