### ISSUE TITLE
Checksum failure on OBS Debian Testing repository

### ISSUE THREAD

**Issue by khumba** [tumic0/GPXSee#503]
Hello,

For a few weeks now I have been seeing the following failure when I try to upgrade GPXSee on Debian Testing.  gpxsee 13.4-1 previously installed and was fine for a while, but then it stopped working.  The Debian 12 and unstable repos are fine, I only see this error on the testing repo.  Since this happened around the time of the bookworm release, I wonder if something got mixed up in OBS because of that; rebuilds of existing version numbers not propagating to mirrors perhaps?  The error can be reproduced with `apt download` too, no need to actually install.

    # apt upgrade -V gpxsee
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Calculating upgrade... Done
    The following packages will be upgraded:
       gpxsee (13.4-1 => 13.4-1)
    1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Need to get 1,332 kB of archives.
    After this operation, 4,096 B disk space will be freed.
    Do you want to continue? [Y/n] 
    Get:1 https://download.opensuse.org/repositories/home:/tumic:/GPXSee/Debian_Testing  gpxsee 13.4-1 [1,332 kB]
    Err:1 https://download.opensuse.org/repositories/home:/tumic:/GPXSee/Debian_Testing  gpxsee 13.4-1
      File has unexpected size (1330288 != 1331560). Mirror sync in progress? [IP: 91.193.113.70 443]
      Hashes of expected file:
       - SHA256:b2da073754a48654d32308373b549cdce7acb96cbae2158887c9342499f0c9ee
       - SHA1:b20b2e71919bd064639834931187a9882e090b48 [weak]
       - MD5Sum:f736f70b65422b3a68b1da44d3909db2 [weak]
       - Filesize:1331560 [weak]
    E: Failed to fetch https://provo-mirror.opensuse.org/repositories/home%3A/tumic%3A/GPXSee/Debian_Testing/amd64/gpxsee_13.4-1_amd64.deb  File has unexpected size (1330288 != 1331560). Mirror sync in progress? [IP: 91.193.113.70 443]
       Hashes of expected file:
        - SHA256:b2da073754a48654d32308373b549cdce7acb96cbae2158887c9342499f0c9ee
        - SHA1:b20b2e71919bd064639834931187a9882e090b48 [weak]
        - MD5Sum:f736f70b65422b3a68b1da44d3909db2 [weak]
        - Filesize:1331560 [weak]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

For completeness:

    # apt policy gpxsee
    gpxsee:
      Installed: 13.4-1
      Candidate: 13.4-1
      Version table:
         13.4-1 400
            400 https://download.opensuse.org/repositories/home:/tumic:/GPXSee/Debian_Testing  Packages
     *** 13.4-1 100
            100 /var/lib/dpkg/status

Thanks very much for providing these repositories!

**Comment by tumic0** [comment]
This looks very similar to #480 where at the end everything worked fine, when I have tried it from a fresh distro install, so I guess this is the same issue with some broken package cache on your machine. It may also be some problem with OBS, but in both cases there is not much I can do, it has to be fixed either by Debian or by SUSE (OBS).

Reopen the issue when you have some info what exact could I do to fix it/make it not happen again.

**Comment by khumba** [comment]
Okay, this is a mirror issue.  `download.opensuse.org` redirects to `mirrorcache-us.opensuse.org`, which for anything under `.../GPXSee/Debian_Testing/amd64/` redirects to `provo-mirror.opensuse.org` which has the broken hashes, seemingly for all packages in the repo.  Requesting any files under `.../GPXSee/Debian_Testing/arm64/` redirects to `downloadcontent-us1.opensuse.org` which provides files with the correct hashes.  So this deb has the correct hash:

https://downloadcontent-us1.opensuse.org/repositories/home:/tumic:/GPXSee/Debian_Testing/amd64/gpxsee_13.4-1_amd64.deb

Still not sure why the rebuild (the Installed-Size changed compared to what the repo was serving earlier, otherwise apt wouldn't reinstall), but it works now.  Thanks and sorry for the noise.
