### ISSUE TITLE
FreizeitKarte causing segmentation fault

### ISSUE THREAD

**Issue by salvix** [tumic0/GPXSee#504]
Maps downloaded from https://www.freizeitkarte-osm.de/android/en/index.html used to work quite well (some glitches on custom style but nothing major) but now with Version 13.4 (x86_64, Qt 5.15.2) (debian) I load the map and I get a segmentation fault in the terminal.

How to reproduce:
- download a small map from the above site
- load map

**Comment by tumic0** [comment]
I have downloaded the [Czech Republic map](https://download.freizeitkarte-osm.de/android/latest/freizeitkarte_cze+.map.zip) and the [Freizetkarte style](https://download.freizeitkarte-osm.de/android/latest/freizeitkarte-v5.zip) but can not reproduce any crash. If this combination crashes on your system, than please provide a stack trace, if not, than provide the __exact__ map that crashes.

Also please provide which Debian version you use and whether you use some "official" package from OBS or do compile GPXSee yourself.

**Comment by salvix** [comment]
Hello @tumic0 ty for taking the time!

```
$ apt policy gpxsee
gpxsee:
  Installed: 13.4-1
  Candidate: 13.4-1
  Version table:
 *** 13.4-1 500
        500 http://download.opensuse.org/repositories/home:/tumic:/GPXSee/Debian_11  Packages
        100 /var/lib/dpkg/status
```

interestingly the same segfault happens with the map you proposed. Perhaps the debian package has a flaw of some sort?

I also deleted the `.cache/gpxsee` and `.local/share/gpxsee` to prevent a false positive but no difference.

starting from a terminal `$ gpxsee` and then clicking on Map -> Load Map and selecting the extracted archive you propose I simply get this in the terminal after gpxsee crashing.

```
$ gpxsee 
Segmentation fault
```

**Comment by tumic0** [comment]
The Debian package may be not up to date with your system (OBS did not yet updated to some recent Debian 11 changes and rebuild the package) or there may be some other problem in Debian (e.g. with OpenGL which you may have turned on). Without some more info it's hard to say anything.

I would start with you downloading the `gpxsee-dbgsym` package and run GPXSee in _gdb_ to get the stack trace. You may also eventually build GPXSee from the sources to see if you get the same crash.

**Comment by salvix** [comment]
Last question. Since the new version, the map looks squashed which makes me think I have the wrong projection selected. Do you happen to know which one is the correct one for openstreetmaps?

**Comment by salvix** [comment]
Ignore me I figured it out.
Input: 4326
Output: 3856

**Comment by tumic0** [comment]
> Do you happen to know which one is the correct one for openstreetmaps?

Generally, there is no "correct" CRS/projection for vector maps. Openstreetmaps usually use EPSG:3857 (3856), but for northern areas like Norway, Sweden, Finland or Canada there are definitely better projections with much less distortion (e.g. SWEREF99/EPSG:3006 or EPSG:3978 for Canada). However, the Mapsforge map/style format is broken by design and does not work with other CRSs than EPSG:3857 without display artefacts (you need a special style without transparency and area outlines to properly work in other projections).
