### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by bderembl** [tumic0/GPXSee#509]
Hi,
this is not a feature request but more a question to the community related to #178 (maybe @sikmir ).
I am trying to find an alternative to [quickroute](http://www.matstroeng.se/quickroute/en/features.php)  which consists in overlaying a gpx track on a scanned image (usually an orienteering map).

I guess I could convert my image to map (.img) with approximate coordinates but I don't know how to make it match the gpx track exactly (quickroute does it by adjusting the route to the image but the other way around is in principle possible)

Has anyone done this (maybe by adding an offset/scale factor to the gpx)?
Would this be possible with gpxsee?

Thank you

**Comment by tumic0** [comment]
The keyword you are looking for is `georeferencing`. Just georeference the map image (e.g. using [QGIS](https://docs.qgis.org/3.28/en/docs/training_manual/forestry/map_georeferencing.html)) and then simply use it with your GPX file. GPXSee supports various georeferenced image maps - GeoTIFF, OziExplorer and ESRI World-File. I'm pretty sure OpenOrienteering Mapper or OCAD can also export the georeference files when exporting the map as a raster image, so if you have the original map source, you do not even have to fiddle with the reference points.

**Comment by bderembl** [comment]
This is indeed in theory the proper way to proceed, thank you for the tip!

One issue though is that the scanned image are often of poor quality and the solution to adjust the gpx is sometimes simpler (as shown [here](https://youtu.be/WqdVn_6ceUU?t=234)). I guess this is clearly beyond the scope of GPXSee.

Thanks! (and feel free to close this anytime)

**Comment by tumic0** [comment]
I don't think their fiddling with the track is of any use. I took a random used "paper" map from SOW23, put it on the floor, took a photo using my mobile phone and georeferenced it in QGIS using 4 points obtained from the Swisstopo online map. It all took me roughly the same time like the guy in the video, but the result is a map, that can be used by multiple track logs. Then I took some random GPS log from the web and the result is pretty accurate as you can see, even when there are so many distortions and inaccuracies in the process.

![georeference](https://github.com/tumic0/GPXSee/assets/11480505/61f72910-21e3-4578-ab3f-852a80568557)

**Comment by bderembl** [comment]
totally makes sense!
