### ISSUE TITLE
GPXSee - Track color never change

### ISSUE THREAD

**Issue by Fritzontheway** [tumic0/GPXSee#511]
Hi, despite trying to change the color of the tracks from the "settings" menu, this doesn't happen! I'm currently using the 13.7 release of GPXSee but it happened with previous versions as well. can you suggest a solution? Thank you.

**Comment by tumic0** [comment]
Without the data (always include the "problematic" data files to bugreports!) all I can do is guessing, but most probably the data has its own style which overrides the global style from the GPXSee settings. If you unselect the "Use styles" checkbox under the "Data" menu, you will get the colors from the settings.

**Comment by Fritzontheway** [comment]
Dear Martin, many thanks for your help.

 

Your suggestion works but only temporarily, i.e. if I remove "Use styles" the track takes the color I set but closing the program and reopening it with the same file, even if "Use styles" is deselected, the track is gray again. What is the data you would like to see? Maybe the gpx file?

I am attaching some screenshots.

Best regards.

Federico

 

 

Da: Martin Tůma ***@***.*** 
Inviato: lunedì 28 agosto 2023 20:12
A: tumic0/GPXSee
Cc: Fritzontheway; Author
Oggetto: Re: [tumic0/GPXSee] GPXSee - Track color never change (Issue #511)

 

Without the data (always include the "problematic" data files to bugreports!) all I can do is guessing, but most probably the data has its own style which overrides the global style from the GPXSee settings. If you unselect the "Use styles" checkbox under the "Data" menu, you will get the colors from the settings.

**Comment by tumic0** [comment]
Yes, the GPX file. Please attach it to the issue here (you may have to zip it for GitHub to accept it).

**Comment by tumic0** [comment]
The persistent setting of "Use styles" is indeed broken, I can reproduce it on my own data, so no need to provide yours.

**Comment by Fritzontheway** [comment]
Ok Martin, thanks a lot! :)

 

Da: Martin Tůma ***@***.*** 
Inviato: martedì 29 agosto 2023 19:14
A: tumic0/GPXSee
Cc: Fritzontheway; Author
Oggetto: Re: [tumic0/GPXSee] GPXSee - Track color never change (Issue #511)

 

The persistent setting of "Use styles" is indeed broken, I can reproduce it on my own data, so no need to provide yours.

**Comment by Fritzontheway** [comment]
Thanks Martin, so have I to download a new version of the program to fix the problem?

Currently on the site I see the same version (13.7_x64) that is already installed on my pc.

All the best...

Federico

Da: Martin Tůma ***@***.*** 
Inviato: martedì 29 agosto 2023 22:08
A: tumic0/GPXSee
Cc: Fritzontheway; Author
Oggetto: Re: [tumic0/GPXSee] GPXSee - Track color never change (Issue #511)

 

Closed #511 <https://github.com/tumic0/GPXSee/issues/511>  as completed via  <https://github.com/tumic0/GPXSee/commit/490052bc6cdb3b690402e5efb63269365f8e72b5> 490052b.

**Comment by tumic0** [comment]
> so have I to download a new version of the program to fix the problem?

Yes, it will be fixed in 13.8 which is not yet released. If you want to test the fix or generally any not-yet-released-commit, you can try one of the Windows [CI builds](https://ci.appveyor.com/project/tumic0/gpxsee). The Qt5 build shall be almost identical to what is then released, the Qt6 build works from Windows 10 upwards and may be better in terms of performance or Windows integration (e.g. better dark mode support).

**Comment by Fritzontheway** [comment]
Ok Martin, I’ll wait until the new version will be released.

Thanks again.

All the best

Federico

 

Da: Martin Tůma ***@***.*** 
Inviato: mercoledì 30 agosto 2023 16:25
A: tumic0/GPXSee
Cc: Fritzontheway; Author
Oggetto: Re: [tumic0/GPXSee] GPXSee - Track color never change (Issue #511)

 

so have I to download a new version of the program to fix the problem?

Yes, it will be fixed in 13.8 which is not yet released. If you want to test the fix or generally any not-yet-released-commit, you can try one of the Windows CI builds <https://ci.appveyor.com/project/tumic0/gpxsee> . The Qt5 build shall be almost identical to what is then released, the Qt6 build works from Windows 10 upwards and may be better in terms of performance or Windows integration (e.g. better dark mode support).

**Comment by Fritzontheway** [comment]
Dear Martin, 

I just downloaded and installed version 13.8, everything works great! 

Thank you very much, all the best.

Federico

 

Da: Federico Plattner ***@***.*** 
Inviato: mercoledì 30 agosto 2023 16:30
A: 'tumic0/GPXSee'
Oggetto: R: [tumic0/GPXSee] GPXSee - Track color never change (Issue #511)

 

Ok Martin, I’ll wait until the new version will be released.

Thanks again.

All the best

Federico

 

Da: Martin Tůma ***@***.*** 
Inviato: mercoledì 30 agosto 2023 16:25
A: tumic0/GPXSee
Cc: Fritzontheway; Author
Oggetto: Re: [tumic0/GPXSee] GPXSee - Track color never change (Issue #511)

 

so have I to download a new version of the program to fix the problem?

Yes, it will be fixed in 13.8 which is not yet released. If you want to test the fix or generally any not-yet-released-commit, you can try one of the Windows CI builds <https://ci.appveyor.com/project/tumic0/gpxsee> . The Qt5 build shall be almost identical to what is then released, the Qt6 build works from Windows 10 upwards and may be better in terms of performance or Windows integration (e.g. better dark mode support).

**Comment by Fritzontheway** [comment]
Dear Martin, I’ve just installed the 13.15 release of GPXSee, is it normal that the 4Umaps button is still present?

Best regards.

Federico

-------------------------------------------------------------------

Mon Jan  1 23:25:38 CET 2024 - ***@***.***

 

- Update to version 13.14

  * Removed 4Umaps map source (map service discontinued).

  * Added mtbmap.cz map source. 

  * Multiple minor map formats fixes/improvements (TrekBuddy, IMG).

------------------------------------------------------------------

**Comment by tumic0** [comment]
If you did not uninstall the previous version of GPXSee but just replaced it, the 4Umaps map file may be still present. Or you may use user defined maps that take precedence and those are not touched during uninstall/reinstall. But the installer should contain the map set as present in [git](https://github.com/tumic0/GPXSee/tree/master/data/maps).

Please do not reuse old issues for new requests/reports, always create a new one.

**Comment by Fritzontheway** [comment]
sorry Martin, I will definitely do it.

thanks for the information, everythings works fine!

 

Da: Martin Tůma ***@***.*** 
Inviato: mercoledì 31 gennaio 2024 01:35
A: tumic0/GPXSee
Cc: Fritzontheway; Author
Oggetto: Re: [tumic0/GPXSee] GPXSee - Track color never change (Issue #511)

 

If you did not uninstall the previous version of GPXSee but just replaced it, the 4Umaps map file may be still present. Or you may use user defined maps that take precedence and those are not touched during uninstall/reinstall. But the installer should contain the map set as present in git <https://github.com/tumic0/GPXSee/tree/master/data/maps> .

Please do not reuse old issues for new requests/reports, always create a new one.
