### ISSUE TITLE
ALT keys only work one layer deep

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#513]
ALT F gives the File menu.
But then all one can do from the keyboard is use the arrow up and down buttons.
There is no way to use a second ALT key combo to choose subsequent menu entries.

**Comment by tumic0** [comment]
There are no other accelerators except the one from the main menu defined in GPXSee. If you want some more, you will have to come up with an English translation file (we need capitalization anyway) that contains accelerators for additional menu levels. The source strings can not be changed as it would break all the localization.

If you (or someone else - I won't do it as it has almost zero priority for me) is going to create the EN translation file, you have also to ensure it does not break things on any of the supported platforms (= you have to test it on Android, Windows, Linux and MacOS).

**Comment by jidanni** [comment]
All I know is when I hit ALT F in chrome, the items there have a little underline for what ALT button will activate them.
