### ISSUE TITLE
CTRL+R to refresh

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#514]
Let's say we update a file on disk.
A quick way to refresh from disk would be CTRL+R.
Saves much time over File --> Refresh in the menus.

**Comment by tumic0** [comment]
`QKeySequence::Refresh` is used as the shortcut for "reload". For example in my KDE this is `F5` and it works fine. Windows and Mac have different shortcuts but they should work as well. If you have no shortcut available, your DE probably does not define one for the "reload" action.

**Comment by jidanni** [comment]
Anyway, this is a consequence of using the Android version of the app on a Chromebook...
