### ISSUE TITLE
Allow not recentering upon reload

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#516]
Let's say we are testing a kml file,
and we need to see how it now looks often.
So via the command line, or CTRL-R for refresh,
we could get a fresh view. But we also don't necessarily
want to start out all zoomed out again.

**Comment by tumic0** [comment]
Sorry, but that is really a too special feature for GPXSee. But you can always add such special stuff yourself in your own fork if you desperately need it, that's the advantage of opensource.
