### ISSUE TITLE
Coordinates format

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#52]
Make it possible to choose coordinates format:
- Degrees
- Degrees, Minutes
- Degrees, Minutes, Seconds

Example:
![sc1](https://user-images.githubusercontent.com/688044/34801222-8e5d41fc-f678-11e7-94ff-dcf01e8467d7.png)
This is a really missed feature now.

**Comment by tumic0** [comment]
Probably a good idea. I do not use the waypoints (coordinates generally) that much, so it never came to my mind to show them in different formats, but from what I see around at least a selection between the decimal and the DMS format is quiet usual. I will add it as soon as I'm ready with the remaining 5.0 (Geotiff & related) stuff.

**Comment by sikmir** [comment]
By the way, `hddd.dddd° / hddd° mm.mm' / hddd° mm'ss.s''` is widely used Garmin options.

**Comment by tumic0** [comment]
Implemented in 7e42b57d73bfba0e8f55bcb599decd4af76878ea.
