### ISSUE TITLE
Altitude not shown

### ISSUE THREAD

**Issue by Blittr** [tumic0/GPXSee#526]
Recently I can no longer see the altitude profile of a self-written GPX file in GPXSee, even though this altitude information is in the GPX file. I only see the message Data not available. With GPX files directly from the GPS, the altitude information is provided. I can't figure out what I'm doing wrong because nothing has changed in the GPX files that I want to view, previously the height information in the same files was made visible. My apologies, but what am I overlooking?

**Comment by tumic0** [comment]
Press the 'x' key on your keyboard...

**Comment by Blittr** [comment]
Thank you, TOP :-)
