### ISSUE TITLE
Track line is hidden

### ISSUE THREAD

**Issue by agocurti** [tumic0/GPXSee#527]
Good morning,
I just downloaded/installed the last GPXsee 13.12 release. 
I'm having an issue: I load a simple gpx file but I see only the start/end points, and NOT the track line... You can see in the attached file that are present the start/end point (purple squares), the current position (see black arrow), but the track line is quite hidden (green arrow on the light gray line). IN my setting I set the track line as blue and 3 px large...
May be am I doing something wrong?

![track](https://github.com/tumic0/GPXSee/assets/153905522/830c7dd9-8fbe-4f0b-9f25-c993bcf731a3)

**Comment by tumic0** [comment]
Your data file most probably defines its own style which takes precedence over what you have defined in GPXSee preferences if "Data->Use styles" is selected (the default). But without the data file, it's just guessing...

**Comment by agocurti** [comment]
Hi,
where I must check the ‘Data->Use styles’ setting? In attach I send you my simple file.

Tino

**Comment by tumic0** [comment]
> where I must check the ‘Data->Use styles’ setting? 

In the application menu.

> I send you my simple file.

Nothing has arrived as you can see on the issue page. The attached files must be in a limited set of enabled formats for GitHub to accept them - use the web interface to attach the file to the issue to get more info. Usually you need to ZIP the GPX/KML file.

**Comment by agocurti** [comment]
Hi Martin,
I found the ‘Data->Use styles’ setting and I seen that this is set. If I unset the setting I see correctly my track!
Thanks for your great suggest!

Have a nice day (and Merry Christmas)
