### ISSUE TITLE
Open Topo Map zoom levels 15+

### ISSUE THREAD

**Issue by ro-le** [tumic0/GPXSee#530]
Recently I noticed that Open Topo Map stopped working with zoom levels 15, 16 and 17. Maximum zoom level is now 14: if I try to zoom in further, no tiles are loaded. Is there any specific reason for not showing those zoom levels anymore? Or is this an Open Topo issue where they might have stopped serving those tiles in general?

**Comment by sikmir** [comment]
Zoom 15-17 on https://opentopomap.org works fine.

**Comment by ro-le** [comment]
Huh, weird. Yesterday I tried on two different OS and with two different versions of gpxsee as well as online and it didn't work. Today it works normally. Sorry for troubles, I'm closing this.
