### ISSUE TITLE
Path not visilbe on macOS

### ISSUE THREAD

**Issue by bwalle** [tumic0/GPXSee#531]
_Version:_ 13.15 (x86_64, Qt 5.15.2)
_OS:_ macOS Sonoma 14.3 (23D56)
_Hardware:_ MacBook Air M1, 2020

I don't see any path. The GPX file is read correctly because the map shows the correct area. But no path. I even deleted my configuration (plist files), so everything should be sane. 

![Bildschirmfoto 2024-02-04 um 09 09 55](https://github.com/tumic0/GPXSee/assets/2146552/7aba4088-06c7-4405-bbfb-2fc7623447a5)

GPX: [2024-01-28_1425430538_Schlaufenweg Pappenheim.zip](https://github.com/tumic0/GPXSee/files/14156011/2024-01-28_1425430538_Schlaufenweg.Pappenheim.zip)

**Comment by tumic0** [comment]
Most probably you have just disabled the displaying of tracks in "Data->Show tracks" (cmd+T).

If not, than it might be related to your x86_64 GPXSee build running emulated on your M1 (arm) Mac. Generally this is a bad idea, use the Macports version that is build for arm instead. You may also try the latest CI Qt6 build from Github actions (if you do not use Mapbox MVT maps - QtPBFImage plugin is not included) which is a "fat" binary for both x86_64 and arm. Most probably there is also no support for non-UTF/latin1 encodings in the Qt6 build, but this may not affect you if you do not use such.

**Comment by sikmir** [comment]
No problem on macOS:
<img width="1680" alt="Näyttökuva 2024-2-4 kello 14 49 48" src="https://github.com/tumic0/GPXSee/assets/688044/aaa3538b-e335-41d4-b1dc-3d89d1acfc3a">

**Comment by tumic0** [comment]
> No problem on macOS: <img alt="Näyttökuva 2024-2-4 kello 14 49 48" width="1680" src="https://private-user-images.githubusercontent.com/688044/302097142-aaa3538b-e335-41d4-b1dc-3d89d1acfc3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDQzODQsIm5iZiI6MTcwNzA0NDA4NCwicGF0aCI6Ii82ODgwNDQvMzAyMDk3MTQyLWFhYTM1MzhiLWUzMzUtNDFkNC1iMWRjLTNkODlkMWFjZmMzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxMDU0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGNmOGFlNTVhZGRlN2JhMWY0NGZjMWNjYmQ4MzUxNjcxMTA0YzViNjdjM2NhNzEzNDk1YTQxNDAxOWZmNDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tRb3ZA2fquqwOhW9rXycEMUkjQW5KrPhjrrMsuN7Hd0">

Have you "censored" the full path in the status bar, or is it broken because of the special UTF-8 character in the name? On my old Mac the path is also broken, but in a different way affecting just the special character. On Linux/Qt5 the path displays ok, but not on Mac.

**Comment by sikmir** [comment]
> Have you "censored" the full path in the status bar, or is it broken because of the special UTF-8 character in the name?

No, I've not "censored". There is no full path.

**Comment by tumic0** [comment]
![Snímek obrazovky 2024-02-04 v 12 17 06](https://github.com/tumic0/GPXSee/assets/11480505/be65b7de-bdcc-4757-b3ff-34408050a0fd)

Well, not that I could fix that - it's definitely a Qt/OS X issue, but on my old Mac I see this.

**Comment by bwalle** [comment]
> Most probably you have just disabled the displaying of tracks in "Data->Show tracks" (cmd+T).

Indeed, that was it. Sorry and thanks.
