### ISSUE TITLE
Odd results with TraceStack tile server

### ISSUE THREAD

**Issue by wavexx** [tumic0/GPXSee#533]
I'm trying to use TraceStack's Topo map (see https://console.tracestrack.com/explorer) which is one of the layers available on OSM, although it requires an API key.

I've created the following XML file:

```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1">
        <name>TraceStack Topo</name>
        <url>https://tile.tracestrack.com/topo__/$z/$x/$y.png?key=ABC</url>
</map>
```

and while it loads the tiles, the result is a jumbled mess, with some of the tiles actually overlapping on top of each other (something which is visible both as a double-refresh while loading and by setting some transparency).

I tried to use thunderforest's cycle map, which uses a similar tile url and it works correctly, so I'm a bit at loss why this isn't working as expected.

**Comment by tumic0** [comment]
The tiles seem to be HiDPI tiles (they are 512x512px), so you need to set them up properly as HiDPI tiles:

```xml
 <?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1">
        <name>TraceStack Topo</name>
        <url>https://tile.tracestrack.com/topo__/$z/$x/$y.png?key=ABC</url>
        <tile pixelRatio="2"/>
</map>
```

**Comment by wavexx** [comment]
Could the tile size be detected automatically perhaps? I wasn't aware of this distinction of tile size, and I used this tile url in a few other programs without even knowing..

**Comment by tumic0** [comment]
No, there is no automatic way (maybe except chatGPT...) to distinguish the tiles as regular 512x512px tiles and HiDPI tiles, so you have to define the map correctly anyway.

**Comment by wavexx** [comment]
Understood. Thanks again for the help!
