### ISSUE TITLE
Temperature data display

### ISSUE THREAD

**Issue by albansuser** [tumic0/GPXSee#536]
Hello

I've recently been experimenting with the display of temperature profiles in GPXSee using data recording via an external temperature sensor connected to the mapping app OSMAnd and embedded in subsequent recorded GPX tracks. 

In the GPX file the temperature data is recorded using the "wtemp" tag. Unfortunately GPXSee currently doesn't read that tag. After some research and experimentation, I changed all occurrences of "wtemp" to "atemp". The temperature profile subsequently displayed correctly in GPXSee.

Since it seems that both "wtemp" and "atemp" are valid temperature tags I'm wondering if GPXSee could be modified so that it can read either tag as valid temperature data.

Thank you for such a useful programme.
 
Regards

**Comment by tumic0** [comment]
I have added support for the GPX water temperature (wtemp) in f814d1f5a365695a9be21a076613bbd716bf53d1, but only one temperature type can read from the GPX file. If air temperature is also present, it takes precedence.

**Comment by albansuser** [comment]
Thank you.
