### ISSUE TITLE
Wrong time zone, only with some files

### ISSUE THREAD

**Issue by feklee** [tumic0/GPXSee#537]
Applies to: Version 13.18 (x86_64, Qt 6.6.1)

Have a look at the following tracks. Both were recorded with [GPSLogger][1] on Android while in Japan.

  * [20231211.gpx.gz](https://github.com/tumic0/GPXSee/files/14846448/20231211.gpx.gz): All good, times are correctly shown in the local Japanese time zone UTC+09. According to what I see in GPXSee, I start moving around 8:00, which is plausible.

  * [20231212.gpx.gz](https://github.com/tumic0/GPXSee/files/14846464/20231212.gpx.gz): According to GPXSee, GPS tracking starts at midnight, and I head out around 1:30 in the morning. This is incorrect. Garmin BaseCamp and Google Earth Pro both report the start of the GPS tracking at 7:33.

*Is this an issue with GPXSee?*

In the files themselves I cannot see anything special. Not sure if this is even a time zone issue. It looks like GPXSee simply moves the first time in the file to midnight.

PS: Downloading this version from SourceForge took more than 2 hours. I tried from Indonesia, from the UK, and from Finland.

[1]: https://gpslogger.app/

**Comment by tumic0** [comment]
I have investigated the files and the "problem" is not in the time/timezone. Your tracks are a combination of a car ride and a walk and this does [not work very well](https://www.gpxsee.org/doc.html#filtering) with the outlier elimination algorithm. If you disable outlier elimination in the Options (Data->Filtering->Eliminate GPS outliers) then you will get a much "cleaner" path and the times will be as expected.

And by the way, thank's for the donation :-)

**Comment by feklee** [comment]
> Your tracks are a combination of a car ride and a walk and this does [not work very well](https://www.gpxsee.org/doc.html#filtering) with the outlier elimination algorithm.

Thank you for pointing that out! I will keep this option disabled as I generally use multi-mode transportation. In this case it was walking plus using train, metro, and taxi.

However, the problem with the offset did not go away. See my photo [DSC_0361.JPG.gz](https://github.com/tumic0/GPXSee/files/14860203/DSC_0361.JPG.gz). I took that with my phone at 12:05:47, stopping at a shop window when walking. Yet, according to GPXSee, I was near that location at 03:32:06:

![Screenshot of GPXSee with location where I took the photo](https://github.com/tumic0/GPXSee/assets/14994/a9d38763-c71e-492b-8eea-e1c433aa84c2)

**Comment by tumic0** [comment]
03:32:06 is the relative time from the track start. If you want the absolute time, you can enable it under Data->Position Info->Date/time (it will be shown next to the position marker on the map).

**Comment by feklee** [comment]
Thank you, that explains it all!

For most of my GPX files, the relative time is equal to the absolute time, simply because the app that I use for tracking on my phone starts a new track at midnight. Occasionally, my phone is turned off at midnight. This when I get the “offset”, which isn’t an offset after all.
