### ISSUE TITLE
Registering custom XML map in Android 

### ISSUE THREAD

**Issue by albansuser** [tumic0/GPXSee#539]
Hello 

I'm able to register a custom XML map on my Windows PC (copy to GPXSee Maps folder) however I haven't been able to find a way to register such a map within GPXSee Android.

Is there a way? If not, could a procedure be implemented?

Thanks

**Comment by tumic0** [comment]
On Android it works exactly*  the same way as on the desktop platforms - you define your map set through the content of the Maps folder. On some phones (e.g. Samsung) the folder may not be accessible from the Android file manager and you have to copy the maps using MTP from your PC. See Help->Paths for the exact folder path specific to your device.

*In fact [some maps](https://www.gpxsee.org/doc.html#issues) even do not work or are unusable slow on Android without doing so.

**Comment by albansuser** [comment]
Thanks for the explanation and solution.

Using MTP from a PC worked.

Incidentally, in my experience changing the maps folder to an accessible one using the path definitions in Setup doesn't work.

**Comment by tumic0** [comment]
> Incidentally, in my experience changing the maps folder to an accessible one using the path definitions in Setup doesn't work.

There is no such setting, you can not change the path of the maps folder in GPXSee (you can however create a symlink on your filesystem). The settings in the "System" options section define the default paths of the open dialogues.
