### ISSUE TITLE
gpxsee segfault at start

### ISSUE THREAD

**Issue by solsticedhiver** [tumic0/GPXSee#540]
```shell
$ LC_ALL=C.UTF8 gpxsee 20240417-gpxlogger-f67820ab.gpx 
/usr/share/gpxsee/maps/Antarctica.xml:
  xml: 2: Not a GMAP XML file
  xml: Antarctic_Basemap: layer not provided
Erreur de segmentation (core dumped)
```
already reported at https://gitlab.archlinux.org/archlinux/packaging/packages/gpxsee/-/issues/1 but I was told to report upstream

**Comment by tumic0** [comment]
Please provide the `20240417-gpxlogger-f67820ab.gpx` file (you have to zip it for GPXSee to accept it) which is most probably the trigger.

_xml: Antarctic_Basemap: layer not provided_ looks also strange as the [Antarctica ](https://tiles.arcgis.com/tiles/C8EMgrsFcRFL6LrL/arcgis/rest/services/Antarctic_Basemap/MapServer/WMTS/1.0.0/WMTSCapabilities.xml) WMTS service definitely has such layer. Can you also provide the content of the `$HOME/.cache/gpxsee/tiles/Antarctica/capabilities.xml` file?

**Comment by tumic0** [comment]
The Antarctica map has [moved](https://github.com/tumic0/GPXSee/commit/1990c85fd7cb382f47bd0014eb4c367f8f79c912) 4 years ago from NOAA servers to ArcGIS servers and you had the old WMTS capabilities in the cache. Deleting the file (or the whole cache) has fixed the issue and now you should have the Antarctica map available. But that is not what causes the crash.

Although I still would like to see the file you are trying to open to get sure, the cause of the crash is probably somewhere else. Can you run GPXSee in GDB and post the stack trace? This will definitely tell us more.

**Comment by solsticedhiver** [comment]
ok.
I run gdb and found out it was sefaulting in **/usr/lib/qt6/plugins/wayland-decoration-client/libqadwaitadecorations.so**
So I uninstalled qadwatita-decorations-qt6 (and qt5)

It's working now

I rebuilt the previous mentionned libraries, and it's working fine now also with them...
