### ISSUE TITLE
Debian Unstable repo: amd64 build stuck on version 13.18

### ISSUE THREAD

**Issue by chiak597** [tumic0/GPXSee#544]
Debian Unstable repo for the amd64 archicture seems to be stuck on version 13.18 for some reason (only this one; testing, stable etc. all have 13.21 available).

https://download.opensuse.org/repositories/home:/tumic:/GPXSee/Debian_Unstable/amd64/

**Comment by tumic0** [comment]
As this is evidently a OBS bug (the package builds [fine](https://build.opensuse.org/projects/home:tumic:GPXSee/packages/gpxsee/repositories/Debian_Unstable/binaries)) and there is nothing I can do about it, please report it to openSUSE. There is a "Report issue" link on the page in your link that should lead to the appropriate issue tracker.
