### ISSUE TITLE
Path color

### ISSUE THREAD

**Issue by mak-kawa** [tumic0/GPXSee#545]
Not sure what's wrong...

My GPXsee (v.13.21) always shows all paths (tracks) and graph lines by yellow color. So, they are almost invisible and indistinguishable on OpeStreetMap and graph.
![Untitled-2](https://github.com/tumic0/GPXSee/assets/139281536/0671dea0-2206-4581-8b33-3759e997dbb4)

Of course, my settings are not changed from default, path base color is "0,0,255,255" and Palette Shift is 50%.
![Untitled-1](https://github.com/tumic0/GPXSee/assets/139281536/4cd0fece-14fa-4101-be99-e5078c7c5ebd)

**Comment by tumic0** [comment]
Without the data (always include the "problematic" data files to bugreports!) all I can do is guessing, but most probably the data has its own style which overrides the global style from the GPXSee settings. If you unselect the "Use styles" checkbox under the "Data" menu, you will get the colors from the settings.

**Comment by mak-kawa** [comment]
Hi tumic0. Thank you for reply.

Your guessing is just a Bingo!! I didn't know that each GPX data has style color as...
        <gpxx:DisplayColor>Yellow</gpxx:DisplayColor>
Setting "Use Styles" option to off solved my problem.

Really appreciate for providing such great useful tool.
