### ISSUE TITLE
Some more stats for the stats window

### ISSUE THREAD

**Issue by maliayas** [tumic0/GPXSee#548]
Hi,

I think the below additional stats would contribute a lot to this already beautiful software:

- Start and end time of the track.
- Number of points and segments in the track.
- Avg distance between the points.
- Avg speed of the "moving period". I guess current avg speed is calculated using the whole duration of the track.

**Comment by tumic0** [comment]
The goal of GPXSee is to be a straightforward tool rather than an over-complex GIS tool and you can not have all info one can imagine in the GUI and at the same time have a simple and intuitive user interface.

> Start and end time of the track.

If desperately needed, it is available in the track popup info.

> Number of points and segments in the track.
> Avg distance between the points.

While that may be interesting for some people (including me), it's some technical detail out of scope of the tool.

> Avg speed of the "moving period". I guess current avg speed is calculated using the whole duration of the track.

You get what you have selected in in your "Time type" preferences.

Anyway, feel free to build yourself a version with all of the info there when you want it that way, that's the big advantage you have with opensource.

**Comment by maliayas** [comment]
> > Start and end time of the track.
> 
> If desperately needed, it is available in the track popup info.

I guess that only includes the begin time. Can I also see the end time in the current version?

> > Avg speed of the "moving period". I guess current avg speed is calculated using the whole duration of the track.
> 
> You get what you have selected in in your "Time type" preferences.

Ah I didn't know that, thanks. In this case I have a new proposal in terms of a better UX. Could you please include the active "time type" in parens next to the speed number both in stats window and the top line of the speed graph? In fact, if that setting only affects the avg speed calculation, I'd like to propose to remove the setting and display both types of speed (total and moving) next to each other instead. The less configuration, the better. And people usually would like to see the two number together, I believe, because one may be misleading.

**Comment by tumic0** [comment]
> I guess that only includes the begin time. Can I also see the end time in the current version?

There is the start time and the duration which together gives the end time. I don't think that the end time is such an important metric that it would require to spare the users from doing a simple addition.

> Ah I didn't know that, thanks. In this case I have a new proposal in terms of a better UX. Could you please include the active "time type" in parens next to the speed number both in stats window and the top line of the speed graph? In fact, if that setting only affects the avg speed calculation, I'd like to propose to remove the setting and display both types of speed (total and moving) next to each other instead. The less configuration, the better. And people usually would like to see the two number together, I believe, because one may be misleading.

You can clearly distinguish the total/moving time in the status bar (the moving time has a M attached) and on mouse over you get the second time. Moreover, when you press "T", the two times (as well as the speeds) change. For me that's enough. But as already said - if you desperately need more info on the screen at the same time, than go for it and create your own version with that change. My version will continue to prefer clarity over "any info one can imagine".
