### ISSUE TITLE
Debian package signature problem

### ISSUE THREAD

**Issue by Kiki-gh** [tumic0/GPXSee#549]
When running `apt update` in Ubuntu 22.04, the following gpg error is encountered.

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_22.04  InRelease: The following signatures were invalid: EXPKEYSIG 18D244F4B89A4627 home:tumic OBS Project <home:tumic@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_22.04/InRelease  The following signatures were invalid: EXPKEYSIG 18D244F4B89A4627 home:tumic OBS Project <home:tumic@build.opensuse.org>
```

Signing key expired?

**Comment by tumic0** [comment]
I have triggered a package rebuild on OBS, that's AFAIK all I can do about it. If it still does not work than report the issue on OBS. The non-(Open)SUSE build infrastructure on OBS is often broken.

Also note, that the packages on OBS are not meant for "regular" usage, usually you should use the package provided by your distro. The OBS packages are primary for assuring GPXSee can be build on the given distribution without any issues and for testing the latest build before it reaches the distribution repositories.
