### ISSUE TITLE
please include common files in release tarballs

### ISSUE THREAD

**Issue by jcfp** [tumic0/GPXSee#55]
While working on a debian package for gpxsee, I noticed a number of useful files present in various distribution packages aren't available in the released tarballs:

- shared mime info file (already in your own packages);
- desktop file (same), preferably with added keywords entry [(click);](https://gist.github.com/jcfp/71c9b4a1a2f928798d93bacd78b3b0a5)
- freedesktop appstream info (see official rpms);
- changelog, e.g. the gpxsee.changes file published on build.opensuse.org.

In addition, a man page would be nice to have and eliminate the sole remaining [lintian warning](https://lintian.debian.org/tags/binary-without-manpage.html). Most of the text that could go in there, such as info on adding online and offline maps, is already available on the project website (albeit under a non-free license).

**Comment by tumic0** [comment]
Moving the files to the git repo is on the road map, it has however a quiet low priority at the moment...

**Comment by jcfp** [comment]
Please do, as this does benefit more than just package maintainers. Parts of desktop files [for example](https://sources.debian.org/src/claws-mail/3.16.0-1/claws-mail.desktop/) can be translated.

**Comment by tumic0** [comment]
Added all in 5.2
