### ISSUE TITLE
FR: Keyboard shortcut for navigation

### ISSUE THREAD

**Issue by igorpupkinable** [tumic0/GPXSee#550]
May I kindly request to add some key sequence to navigate to a next/previous file please?
`Ctrl/Shift/Alt + Right/Left Arrow` or any other feasible combination would be just enough.
![image](https://github.com/tumic0/GPXSee/assets/2854230/d5cf39d3-ff6e-4839-970c-068de364c910)

**Comment by tumic0** [comment]
What's wrong with the default keys - space and backspace? Those are used by most image viewers for decades...

**Comment by igorpupkinable** [comment]
@tumic0 nothing wrong with the default keys. These were not mentioned anywhere including hover label.

```
Those are used by most image viewers for decades...
```
This is quite a bold statement given that ←→ are used pretty much everywhere.

Thanks for the hint though!

**Comment by tumic0** [comment]
> These were not mentioned anywhere including hover label.

All the keyboard controls are listed under Help->Keyboard controls.

**Comment by igorpupkinable** [comment]
Found it: `Help > Keyboard controls`.
Great, thanks!
