### ISSUE TITLE
Error Loading KMZ file with custom placemark

### ISSUE THREAD

**Issue by lonepine1995** [tumic0/GPXSee#551]
Hello
I get the following error when trying to load a very simple kmz file that has a custom placemark (only 1 placemark)...when I load the file as a kml file with a custom placemark it works...the kmz file is in the attached zip file

error loading data file: C:/Users/PC/Descktop/Bushcamp.kmz: Error extracting Zip file 
Line: 1

Thanks
[Bushcamp.zip](https://github.com/user-attachments/files/16201934/Bushcamp.zip)

**Comment by tumic0** [comment]
For some reason the Qt ZIP extractor (QZipReader) used by GPXSee does not properly extract the KMZ ZIP envelope. You may create a bug report in the [Qt bug tracker](https://bugreports.qt.io/) but from the GPXSee side there is nothing one can do about it.

**Comment by lonepine1995** [comment]
FYI 
I have discovered if I change the GE kmz file extension from kmz to zip...unzip the file...then rezip using 7-zip...change the zip extension back to kmz...the file opens both as waypoints or POIs with no errors

**Comment by tumic0** [comment]
Yes, if you "repack" the kmz file using 7-zip (or another ZIP tool not using the special flags/64bit mode, ..., whatever is not supported by QZipReader) than the same KML data works fine.
