### ISSUE TITLE
Use Styles for POI / Waypoint icon scale, icon transparency and icon label color not supported

### ISSUE THREAD

**Issue by lonepine1995** [tumic0/GPXSee#553]
Hello
Use Styles for imported POIs / Waypoints does not seem to be supported...icon scale (eg 0.7), icon transparency (eg 60%) and icon label color (eg Red) set in the GE kmz / kml files does not seem to be supported in GPXSee

However GE Path / Line width (eg 6) and transparency (eg 60%) and color is supported 

When I Import POIs / Waypoints the Icon png file full size is used (eg 32x32), transparency is 100% and icon label color is white...when I turn off Use Styles the GPXSee settings options work

Cheers

**Comment by tumic0** [comment]
The set of supported "styles" in GPXSee is limited to a subset of properties common across all the supported formats. KML is extraordinary rich on various special styling and there is AFAIK no tool that supports the whole KML format except the original Google Earth.

In GPXSee you can define the point color (with the label having the same color), an icon and the point size (which also defines the font size). For all formats except KML this is enough. For "true" KML rendering you have to use Google Earth, it is not the goal of GPXSee to implement all the stuff present in Google Earth.
