### ISSUE TITLE
FITParser: import "laps" as waypoints

### ISSUE THREAD

**Issue by fabzzap** [tumic0/GPXSee#556]
Garmin FIT files can have a "lap" section, where some points are marked.

It would be nice to have such "lap" points as waypoints in GPXSee. Gpsbabel supports the feature.

I made a patch myself to support this, but I see that pull requests will be rejected.

**Comment by tumic0** [comment]
Please provide a sample of such file.

**Comment by fabzzap** [comment]
[2024-09-03-08-33-18.fit.gz](https://github.com/user-attachments/files/16855834/2024-09-03-08-33-18.fit.gz)
Here is a sample. It has a "laps" section (global id 20) and 3 laps, roughly at 1/3, 2/3 and end of the track
