### ISSUE TITLE
Showing gaps between segments

### ISSUE THREAD

**Issue by maliayas** [tumic0/GPXSee#560]
(Related to #246, #304)

I'd like to reopen this topic for discussion. There may be valid use cases for this feature.

For example, consider an 12 hours car trip and we give ~1 hour breaks here and there on the road. And for every break, we pause GPS recording, as a best practice (saving battery and having smaller filesize). Each GPS pause/resume terminates one segment and creates a new one. After the trip, let's say we want to see at which places we gave our breaks. When we look at the gpx file with GPXSee, it's not possible to answer that question.

I created the below mockups to illustrate this:

![resim](https://github.com/user-attachments/assets/40a318b4-33ff-4a39-96ff-5d90fa8b426c)

If however GPXSee could draw the gaps between segments with a graph like below, we could easily see our breaks:

![resim](https://github.com/user-attachments/assets/4bcdd97c-dafb-41f5-83f5-53bf0309b88f)

This graph also gives a more comprehensive representation of the track. There can also be a setting for turning this on/off.

**Comment by tumic0** [comment]
You can achieve the desired graph "layout" when you disable the usage of track segments in the preferences.

**Comment by maliayas** [comment]
Thanks, I'm already aware of that setting. In fact I tried it in detail before opening this issue. However it is not any close to my proposal here. Firstly it is not easily distinguishable in the speed graph (compared to the bluish screenshot in the OP). One can't easily tell that there are segment gaps (read: trip breaks) by looking at the speed chart when track segments are disabled in the settings. The speed is not drawed as 0 km/h in that gap, instead something _low_ like 5 km/h due to some internal algorithm.

Another downside of that setting is, when I disable track segments, track line on the map becomes confusing because the gap edges are then connected with a straight line. So if there are significant distance between two segments, resulting chart becomes ugly due to the straight gap line, which is also factually incorrect.

**Comment by tumic0** [comment]
While there may be use cases where your display mode will fit better than the current one, for my data the current system is better or at least good enough and it is not worth at all to fiddle with something that fundamental and fragile to add yet another display option. But feel free to adjust the program to display the segments exactly like you want it in your own version/fork, the sources are here for exactly this reason.
