### ISSUE TITLE
In which files are the settings (in Windows) stored? How to put in file in instalaltion directory?

### ISSUE THREAD

**Issue by pstein** [tumic0/GPXSee#562]
Where does GPXsee store all its settings?

I cannot see preferences files (*.ini or *.xml) in installation directory.
or a "settings" subdirectory.

How can I tell GPXsee to save them in installation directory?

or are they stored in Windows Registry?

How can export a settings backup? (and restore it later if necessary)?

**Comment by Tux** [comment]
`$HOME/.config/gpxsee/gpxsee.conf` if you are on Linux.
Maybe change the subject line to indicate that you want to know the location on Windows

**Comment by tumic0** [comment]
GPXSee uses the [QSettings](https://doc.qt.io/qt-6/qsettings.html) class for the settings which uses the registry on Windows. If you want to use INI files, you can modify the source and create your own build that explicitly uses `QSettings::IniFormat`.
