### ISSUE TITLE
Tooltips don't work on wayland

### ISSUE THREAD

**Issue by qwerty287** [tumic0/GPXSee#564]
Hello and thanks a lot for developing gpxsee!
I changed my setup from x11 to wayland some weeks ago and noted now that the tooltips (e.g. when hovering over a track) don't work anymore. They appear, but they directly disappear again, so they're useless for me. Also, in the short time I can see them, it looks like they have a header bar.
Thanks!

**Comment by tumic0** [comment]
This is a bug in Qt 6.7.2 under Wayland, there is nothing that can be done in GPXSee with that. But there is a workaround of clicking into the map view first and then the popups display fine until the focus* ist lost again (usually on a new file load). You should also check whether this is already reported in the [Qt bugtracker](https://bugreports.qt.io/) and eventually report it, I did not do that myself yet as it is not GPXSee-specific (I can see the same bug in QtCreator as well) and chances are high someone already did it. But it's probably as usual, everyone thinks the others will do it... ;-)

\* _I do not completely understand the bug, it is probably not only the view focus playing a role in it as I have tried some workarounds using fiddling with setting the focus programatically, but nothing helped._
