### ISSUE TITLE
No hillshading

### ISSUE THREAD

**Issue by hermmd** [tumic0/GPXSee#567]
Hillshading does not seem to work (v 13.26). I've read the docs and looked for related issues but I cannot find any information.

Altitude information is there (either via map or downloaded DEM) and is correctly displayed at the cursor position. I adjusted the settings (opacity etc.) for the map and the hillshading (in the DEM settings). I also switched on / off DEM -> show hillshading. I'm currently using the OSM online map but I've also tried with other maps (some of which seem to have hillshading already built in). Any help?

**Comment by tumic0** [comment]
Hillshading only works for vector maps (Garmin IMG and Mapsforge) which have it as a separate layer. Online maps are expected to have their own hillshading.

**Comment by hermmd** [comment]
@tumic0 Thanks for clarifying. It would be great to have this information in the (online) documentation, or even better: Next to the menu / settings in the program.

**Comment by tumic0** [comment]
Hillshading info added in f41f64f37efc21ee064a290035e87fd79b0f4743.
