### ISSUE TITLE
Wrong language used for menus on Windows 10 with a second langauge pack installation

### ISSUE THREAD

**Issue by Rock2far** [tumic0/GPXSee#569]
I have a Window 10 PC with a US installation BUT a traditional Chinese language pack to allow another user of the PC to type in Chinese. Apps are meant to use the FIRST language in the Windows list. For some reason GPXSee is picking the second. See screen shot showing both the installation order of the language packs and the issue with GPXSee.
I hope this report is useful to you.
![image](https://github.com/user-attachments/assets/84c3327a-eba1-4d3c-a6ac-bb289230878c)

**Comment by tumic0** [comment]
776104a9fa9565f82473f22acf351b5939916c47 should probably fix the issue. Please test the AppVeyor CI build when it finishes and report if it has fixed the issue.
