### ISSUE TITLE
Path of GPX shown by GPXSee seems to miss data points

### ISSUE THREAD

**Issue by ramonsmits** [tumic0/GPXSee#570]
The following shows the same GPX loaded in both but in GPXSee it seems as if is skipped data points

GPXSee:

![image](https://github.com/user-attachments/assets/38b76c83-eaea-4488-81bb-816389f23b69)

VSCode Geo Data Viewer:

![image](https://github.com/user-attachments/assets/a41b51ad-2f17-4f80-8666-ef53e4f67234)

Path is also shown correctly at https://gpx.studio/

I've browsed all settings but couldn't find any that are influencing this.

Any idea what could be causing this?

**Comment by tumic0** [comment]
Most probably it is caused either by the outlier elimination algorithm or the pause detection algorithm. Both can be turned off in the preferences if you work with "artificial/nonsense data" (GPXSee is designed/tuned to work with real recorded tracks) that i suspect, but without the data file it's hard to say...

**Comment by ramonsmits** [comment]
Not sure how I missed that *Filtering* tab but after unchecking `Eliminate GPS outliers` the path is rendered correctly:

![image](https://github.com/user-attachments/assets/1e03b066-ee38-4b75-82a2-beb7e80a015e)

The GPX is a data export of lat,lon positions which are captured via the tool https://www.traccar.org/client/ where only points that have an accuracy below 15 meters are exported.

I tried truncating the start and end of the data points in a text editor. I noticed that with that file the path is shown correctly. So the start or end data sets caused the routine to plot the path differently. I can share the GPX for diagnosing it but I cannot share it publicly for private reasons.

**Comment by tumic0** [comment]
The outlier detection algorithm computes a modified Z-Score on the acceleration data. This gives good results on hiking, biking or cross-country skiing track logs but if you have some city car traffic or in general tracks that are composed of parts with very different speed profiles, it will fail.

Without the data there is no analyzing or adjusting of the algorithms possible. You are free to choose whether you will share the data or not, but if you are not sharing it, you can not expect the program to work perfectly (i.e. with the default settings) on such data.
