### ISSUE TITLE
GPXSee for Windows 7

### ISSUE THREAD

**Issue by Ocnarf54** [tumic0/GPXSee#573]
My PC works with Windows 7-x64.
Is there still a version of GPXSee working with the above in the repository?
Thanks for your attention.

Franco

**Comment by tumic0** [comment]
There is still the installer of version 13.23 available on Sourceforge, which is the last version that was build using Qt5 and works on Windows 7 (x64).

The [Qt5 CI build](https://ci.appveyor.com/project/tumic0/gpxsee/builds/50960839/job/pj1eomm906hln0of/artifacts) on Appveyor might also run on Windows 7, but if you need the [MVT plugin](https://github.com/tumic0/QtPBFImagePlugin), you have to "install" it separately.
