### ISSUE TITLE
Debian Unstable packages depend on deprecated lib

### ISSUE THREAD

**Issue by grinapo** [tumic0/GPXSee#574]
gpxsee depends on `libqt5core5a` which is obsoleted by `libqt5core5t64`, as far as I see it.
This makes it uninstallable (for a long time now).

**Comment by tumic0** [comment]
There is no such dependency in the dsc file. There is only `qtbase5-dev` defined. If the build results in a package that does not work with the current Debian unstable, than this means OBS has not (yet) updated the build image. Anyway, there is nothing I can do about it, you have to report the issue to OBS.

**Comment by grinapo** [comment]
gpxsee package depends on `qtbase-abi-5-15-10` which is turn depends on the lib.
It should depend (for unstable and testing) on `qtbase-abi-5-15-13` at least.

I am not familiar with "OBS", would you please tell me how to report the issue to them? I see no obvious way on their site. Thank you.

**Comment by tumic0** [comment]
[https://openbuildservice.org/support](https://openbuildservice.org/support/)

**Comment by grinapo** [comment]
OBS people suggested me to ask you to disable `armv7l` build on debian unstable because its missing build-deps are blocking the release. 
The other architectures (x86_64, aarch64) are told to be built successfully but can't get published when a build fails on the same repo.
Thank you!

**Comment by tumic0** [comment]
I have disabled `armv7l` and the packge/repo has indeed been rebuild. Please test if the resulting package works.

**Comment by grinapo** [comment]
Seems perfect, dependencies fixed!
Thank you very much!

(probably fixed #544 as well)
