### ISSUE TITLE
Support for openmaptiles.org (maptiler.com) OpenStreetMap .mbtiles format

### ISSUE THREAD

**Issue by bjascob** [tumic0/GPXSee#575]
I downloaded a [.mbtiles file](https://data.maptiler.com/downloads/dataset/osm/north-america/us/colorado/#5.96/39.025/-105.552) from [openmaptiles](https://openmaptiles.org/) but when loading the map in GPXSee I get "unknown file format".  It looks like GPXSee is supposed to supports this file format so I'm not certain the issue. These are listed as "vector" tiles so maybe you only support "raster" tiles in the .mbtiles container? BTW... in #184 you indicate support for this format from this specific site.

Ultimately I'm just trying to use the OpenStreetMap (OSM) data offline on my laptop when out camping/4-wheeling and don't have internet access. I've tried a few things but keep running into roadblocks. If .mbtiles won't work, maybe you can point me in the right direction.  I've looked at...
* .mbtiles download from openmaptiles.org don't load
* The are available .pbf downloads from at least 2 sites, but GPXSee doesn't load this format
* The "4U" server that Mobile Atlas Creator tries to access to create tiles usable by GPXSee is no longer online.

Just looking for a simple solution.

**Comment by tumic0** [comment]
GPXSee works fine with OpenMapTiles, but you must have [QtPBFImagePlugin](https://github.com/tumic0/QtPBFImagePlugin) installed. On Windows and Mac the plugin is part of the "official" installers, but I suppose you are on Linux where it is a separate package (qt6-qtpbfimageformat on OpenSUSE, qtpbfimageplugin-qt6 on Arch, qt5-qtpbfimageformat on Fedora, ...).

**Comment by bjascob** [comment]
Thanks. I'm using Ubuntu 22.04 and that was the issue.  Unfortunately I wasn't able to find a .deb package anywhere to install it (maybe it's named something different?) but I was able to compile it from source.

**Comment by tumic0** [comment]
Due to its basement on Debian, Ubuntu is years behind any modern distribution in terms of including new packages so you won't find QtPBFImagePlugin among it's packages like you won't find GPXSee in any Debian-based distro. If you do not wan't to compile it yourself, you can use the [OBS build](https://build.opensuse.org/package/show/home:tumic:QtPBFImagePlugin/QtPBFImagePlugin).
