### ISSUE TITLE
v13.33 Android- Elevation Profile incomplete

### ISSUE THREAD

**Issue by albansuser** [tumic0/GPXSee#577]
Hello

I've noticed with the last few releases of the Android version that the displayed elevation profiles have not been complete. This seems to occur especially on GPX tracks over say 250 km.

Other Android apps, such as Osmand and GPX Viewer Pro display the elevation profiles of the same GPX files correctly.

Android 14.

The issue also occurs on the Windows (11) platform.

Cheers

**Comment by tumic0** [comment]
Please provide at least a single GPX file with the issue.

**Comment by albansuser** [comment]
An example file as requested:

[Elevation Issue Example.zip](https://github.com/user-attachments/files/18092121/Elevation.Issue.Example.zip)

**Comment by tumic0** [comment]
Thank's for the sample file, but I do not see any problem here... Yes, there is elevation missing for the last ~100m in the graph, but if you look into the GPX file, the last few entries are missing the elevation info as well. Can you provide some more info about the issue, ideally a screenshot?

**Comment by albansuser** [comment]
When about to capture the required screenshots, and pondering the issue,  I decided to check the settings and found that the Data - Sources - Elevation setting was set to DEM. I switched to GPS and the elevation profiles are now correct, on the PC and mobile.

Obviously the DEMs for more distant areas were not downloaded.

Problem solved. Thanks for your response.
