### ISSUE TITLE
[FR] Slider for map opacity

### ISSUE THREAD

**Issue by wavexx** [tumic0/GPXSee#578]
When looking at several traces, color clash with the map is frequently an issue for me, even with muted maps.

I'm frequently adjusting the map opacity so that I can either prioritize the traces, or the map.

It would be convenient to be able to control the map opacity more easily, with a slider on the toolbar that updates instantly and/or with a shift/mouse-wheel combination.

**Comment by tumic0** [comment]
While I understand that you may need to adjust the opacity very often, for the vast majority of users this is not the case and the existing settings are sufficient. Adding some more prominent control for opacity would also most probably collide with other stuff. However, the sources are here for you so feel free to adjust the interface exactly like you wish in your personal fork of GPXSee.

**Comment by wavexx** [comment]
If I was about to try, and since maybe you have an idea, what do you think could collide in terms of settings?

Traces have their own opacity too, but that tends to make them less readable. There's a base color setting combined with a palette shift, but when I open many tracks at once (to see an overview where I was), you eventually get a rainbow effect which clashes with any possible map color. I've added a base gray OSM layout which works well enough for this, but the palette shift also doesn't yield readable colors in many cases.

I've tried both making the map brighter with a darker base color and the opposite, but without having nice reliably nice results.

Maybe having a fixed palette would work best, without having to fudge with the map opacity.

**Comment by tumic0** [comment]
> If I was about to try, and since maybe you have an idea, what do you think could collide in terms of settings?

You may have problems with other stuff using the scroll wheel and/or modifiers like zooming. On Mac modifiers can change the axis etc.

> I've tried both making the map brighter with a darker base color and the opposite, but without having nice reliably nice results.

What I'm using is a black background and 50% opacity.

![Bikestreda](https://github.com/user-attachments/assets/42ce96ed-3af0-4e15-b8c1-e52556087702)

**Comment by wavexx** [comment]
Do you keep the map darkened all the time? Overall this is what I was doing too with tracestack as a base, but from time to time I actually want to read the map around the trace (hence the idea of the slider).

**Comment by tumic0** [comment]
> Do you keep the map darkened all the time?

No, only when I need to examine a huge number of tracks at the same time. Which is very rare and therefore I do not see a need to make the settings easier accessible. But again, if you need it, than simply implement it yourself. If you do it in a fork here on GitHub, I may even look at it and eventually re-implement it in the "official" version.
