### ISSUE TITLE
Better support for more tracks in one gpx file.

### ISSUE THREAD

**Issue by luznicky** [tumic0/GPXSee#6]
Currently if there is more tracks in one gpx file then they are displayed as a one continuous track. It would be better, if they were displayed separately as if the were in multiple gpx files.

Multiple tracks in one gpx file is produced for example by Garmin devices.

**Comment by tumic0** [comment]
Can you please send me some such files so I can test it on real data? Thanks

**Comment by tumic0** [comment]
Implemented in 923a00479a047435331c6ef5d31dd11774468c4a.
