### ISSUE TITLE
Maps and copyright

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#66]
OSM: [Copyright and License](http://www.openstreetmap.org/copyright):

> You are free to copy, distribute, transmit and adapt our data, as long as you credit OpenStreetMap and its contributors.
> ...
> **How to credit OpenStreetMap**
> We require that you use the credit “© OpenStreetMap contributors”.
> You must also make it clear that the data is available under the Open Database License, and if using our map tiles, that the cartography is licensed as CC BY-SA. You may do this by linking to [this copyright page](https://www.openstreetmap.org/copyright).
> ...
> For a browsable electronic map, the credit should appear in the corner of the map.

So we should add a proper copyright item to the xml format and display it on the map:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<map>
    <name>Open Street Map</name>
    <url>http://tile.openstreetmap.org/$z/$x/$y.png</url>
    <copyright>Map data: © OpenStreetMap contributors, ODbL | Rendering: © OpenStreetMap, CC-BY-SA</copyright>
</map>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<map>
    <name>Open Topo Map</name>
    <url>https://a.tile.opentopomap.org/$z/$x/$y.png</url>
    <zoom max="17"/>
    <copyright>Map data: © OpenStreetMap contributors, ODbL | Rendering: © OpenTopoMap, CC-BY-SA</copyright>
</map>
```

**Comment by tumic0** [comment]
Yes, the switch to xml in map definitions was also to enable a copyright item there. However I really do not think that the copyright should be always displayed on the map. This kind of attribution is IMHO for online maps that are embedded into some websites where it may not be clear what the source of the data is. In GPXSee you choose the map from the map list, so the map source is quite obvious. There is really no need to display this info every time you start the application.

GPXSee is not trying to hide the map sources (they are for example linked from the homepage) but there is a lot of more useful work to do than to fiddle with displaying of some hinder stuff... I will ad the copyright tags for now, the display part will however have to wait until there is nothing else useful to do...

**Comment by tumic0** [comment]
Map source files extended in 5.2
