### ISSUE TITLE
Allow to reduce dpi when printing in HiRes mode

### ISSUE THREAD

**Issue by luznicky** [tumic0/GPXSee#69]
Printing on a shitty printer which allows setting high DPI (600 or higher), and doesn't allow to set lower DPI, has some consequences. First one is that high zoom tiles are used. The second one is that dots are so small, that almost all lines are printed invisible.

The solution would be either to limit max. zoom level or to allow user enter demanded DPI and later upscale into printers DPI.

**Comment by tumic0** [comment]
The native OS print dialog which can not be customized is used for printing. However, the demanded DPI can be set on PDF exports, so if you need a workaround for your shitty printer, simply export your data to PDF and then print the PDF.
