### ISSUE TITLE
Show time of individual points

### ISSUE THREAD

**Issue by fhimpe** [tumic0/GPXSee#7]
I cannot find a way to see the date/time of the GPX track in GPXSee. I was thinking about all individual points being marked on the map, and when hovering over them, a pop-up is shown with the date/time and other information related to that point. Another option is to somewhere have a table in the GUI which lists the individual points. When selecting a row in that table, automatically the point is selected on the map.

**Comment by tumic0** [comment]
I have added some info as a tooltip to the tracks/waypoints in dac06b9537474eb1c41e277fa90501bc73403134 that contains the date for the track. Individual track point info does not fit into the concept of the application that aims to be a simple GPX viewer/browser and not a full featured GIS. Alternatively, I may extend the waypoint info to contain eg. elevation or date, if there is some use fore it amongs the users.

**Comment by tumic0** [comment]
Track/waypoint date available since 2.17 in tooltip.
