### ISSUE TITLE
Add optional debugging info when printing/exporting 

### ISSUE THREAD

**Issue by luznicky** [tumic0/GPXSee#70]
It would be useful to know which zoom level had the tiles which were used in an exported pdf or in a printed copy.

**Comment by tumic0** [comment]
Sorry, but I really don't like the idea of printing any debug info messages except of error messages. Doing so would soon lead to an confusing log stream where the important messages would get lost.

You may however modify the sources and build yourself a version of GPXSee that logs whatever you want.
