### ISSUE TITLE
FR: Support for Garmin JNX map format

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#71]
I'm sure, currently it's the most expected feature for Garmin users, since JNX is the de facto standard for raster maps.

Links:
- [JNX Raster Maps](http://whiter.brinkster.net/en/JNX.shtml)
- [Make JNX for Garmin](http://nakarte.tk)

**Comment by tumic0** [comment]
Can you please provide some "real" JNX maps? It is not easy to get them from the Internet and I would like  to see as much as possible different maps from different sources. Particularly I'm interested in the tiles ordering as sequentially traversing 50000 tiles to find one like QMapShack is doing it looks crazy to me...

**Comment by sikmir** [comment]
If "real" means "by Garmin", then I have no such ones. As for me there are 2 primary sources: [nakarte.tk](https://nakarte.tk) and [SAS.Planet](http://sasgis.org/) (export to multi-level JNX).

**Comment by tumic0** [comment]
Implemented
