### ISSUE TITLE
Support for GIScience Heidelberg Maps

### ISSUE THREAD

**Issue by pmo-19** [tumic0/GPXSee#72]
Would it be possible to add the GIScience Heidelberg Maps ? from the University of Heidelberg I believe.
They look great and don't require an API ... And I tried to add them in GPXSee version 4.x without success.
I used the directives from [their website](https://korona.geog.uni-heidelberg.de/contact.html), adding this line to maps.txt:

GIScience Heidelberg	http://korona.geog.uni-heidelberg.de/tiles/roads/$z/$x/$y.png

I got an xml error from the web browser however the values of the variable x y z are not set: Tile coordinates were not in a correct format. RawUrl = '/tms_r.ashx?$z/$x/$y.png', UrlReferrer = '', UserIPAddress =

To open maps in a browser I type:

http://korona.geog.uni-heidelberg.de/

This line does open the maps in a web browser like the Open Topo Map line:

Open Topo Map	https://a.tile.opentopomap.org/$z/$x/$y.png

But it's not working in GPXSee ? Do you have a clue ?

**Comment by sikmir** [comment]
@pmo-19 Your URL is wrong:

> GIScience Heidelberg http://korona.geog.uni-heidelberg.de/tiles/roads/$z/$x/$y.png

From the site:
>  Web Map Tile Service Links
> - OSM Roads layer:
> URL: https://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}
> or http://129.206.66.245:8001/tms_r.ashx?x={x}&y={y}&z={z} 

This works for me:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<map>
	<name>GIScience Heidelberg</name>
	<url>https://korona.geog.uni-heidelberg.de/tiles/roads/?x=$x&amp;y=$y&amp;z=$z</url>
</map>
```

**Comment by pmo-19** [comment]
OK. Well I did place the `.xml` file you suggested in the latest version 5.2, then recompile. It's working albeit replacing the `?` by `/` in the `.xml` you wrote.
So far I have no success on the` maps.txt` of the `4.19 version` ... adding the file:
`GIScience Heidelberg	https://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}`
There is in your Debian / Ubuntu build minor packaging issues as well.

**Comment by sikmir** [comment]
> So far I have no success on the maps.txt of the 4.19 version ... adding to the file:
> GIScience Heidelberg https://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}

It works for me with 4.19 as well.

**Comment by tumic0** [comment]
https://korona.geog.uni-heidelberg.de/tiles/roads/x=1&y=1&z=1 ends with:
HTTP Error 503.2 - Service Unavailable
The serverRuntime@appConcurrentRequestLimit setting is being exceeded.

They have evidently some server/resources limit issues at the moment.

**Comment by pmo-19** [comment]
About the minor packaging issues found in the Debian / Ubuntu "official" build:
The source contains a file you called `appdata.xml` which you omit to place in the Debian package.
However it should be named `gpxsee.appdata.xml` and placed in the `/usr/share/appdata` folder.
You placed the `Qt translation files *.qm` in `/usr/share/gpxsee/translations`. This is of no use. To be handled correctly these files should be in either or both `/usr/share/qt5/translations` and / or `/usr/share/qt4/translations`...
On GPXSee 5.2 it is working well with maps from `GIScience Heidelberg`, except for 2 zoom levels centred on Southern France. This is a portion of my `Fixed Speedcams for France` gpx file. 
![radars_fixes_france gpx - gpxsee_452](https://user-images.githubusercontent.com/5914016/36459137-7fc2f0ce-1680-11e8-880a-11db5fb4a442.png)
I use it to build a Garmin set of files with natural voice alert for all kind of speed traps Autonomous LIDAR laser, Average Speed camera and Classic ones. Very helpful with the more than 3,000 in use in this country.
I will test again with the 4.19 version tomorrow.

**Comment by tumic0** [comment]
GPXSee reads translations from `/usr/share/gpxsee/translations` on Linux, so this IS the correct path where to place them even on Debian.

Tiles that could not be downloaded are not tryied to download again in the same running process. You may however restart the application to trigger a new download. Clearing the tile cache clears all the tiles from the selected map.

As the original issue is an issue of the map provider, I'm closing it. For new/other stuff please open separate issues.
