### ISSUE TITLE
Make MapView's center&zoom persistant through restart

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#73]
Actually there is no point showing the whole world map at program start, but it would be really useful and convenient to restore the last used MapView's center and zoom from ```~/.config/GPXSee/GPXSee.conf```.

**Comment by tumic0** [comment]
I don't think that this is a good idea - in my use cases I rare explore the same region after a new program start. And zooming in to the desired place is definitely much more user-friendly than moving or zooming out and than zooming in to another place.
