### ISSUE TITLE
FR: keyboard accelerators for menu items

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#75]
Could you please add shortcuts at least for main menu: `"&File"`, `"&Map"`, `"&Graph"`, `"&POI",` `"&Data"`, `"&Settings"`, `"&Help"`? That would be convenient for those (like me) who prefers to use keyboard navigation rather than mouse.

**Comment by tumic0** [comment]
Added in ccb7336e3fd5d05a0d8574530a8db704d6d68cef. (Main menu re-translation is required)
