### ISSUE TITLE
Feature request: View time when sweeping graph

### ISSUE THREAD

**Issue by Freiheiter** [tumic0/GPXSee#8]
When viewing a track and displaying a graph (elevation, speed, heart rate) below it, today I can swipe through the graph and have the respective value displayed over the distance axis, while the related position is shown in the graph as a small red cross. Cool - helpful and intuitive.
Even more helpful, I'd suggest, would be to also have the related time displayed, so you could deduce interim times from a track, for example.

It would be very kind if you could implement this - thanks in advance in that case!

Werner

P.S.: Additional suggestion: the cross is a bit small and not easily seen on my screen. Could you make it just a little larger?

**Comment by tumic0** [comment]
I'm planning/working on adding the possibility to switch between distance and time on the X-axis in the graphs, which is IMHO the best way how to handle the time information. This is however a little bit more work than it seems at the first sight, so it will take a while.

**Comment by tumic0** [comment]
Regarding the cross - It is indeed a little bit to small on most displays, so I was already considering to enlarge it a little bit. The question is, if I make it two pixels wide, won't i t bee now to big? I will have a look at it.

P.S.: Next time please fill two different tickets for different issues, so I can later close them independently.

**Comment by Freiheiter** [comment]
Thanks!! And yes, will stick to atomic issues for the future.

Kind regards;
Werner


Am 08.08.2016 um 11:06 schrieb Martin Tůma:

**Comment by tumic0** [comment]
Working time graphs since 799079392ccc5d27d00f01ea1d78a854f284d206. Will be part of version 2.19.
