### ISSUE TITLE
Kilometer markers

### ISSUE THREAD

**Issue by pschonmann** [tumic0/GPXSee#84]
Would be fine see 1km markers on track 1/5/10 km markers, like Strava . Let user choose which markers want use in settings.

**Comment by sikmir** [comment]
It would be better to have dynamic distance between markers (1/5/10km) depending on current zoom level, like nakarte.me.

**Comment by tumic0** [comment]
This could be better than the current state, the question is, how to "scale" the markers. The zoom levels are much more variable in case of GPXSee than in case of narrate.me that supports only the OSM/Google tile scheme. Moreover, the scaling should somehow take the view size into account (I don't know if nakarte.me works this way)

**Comment by sikmir** [comment]
Great, it works now in such a way! Thanks.
