### ISSUE TITLE
Wiki usage

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#87]
Is it acceptable to share online maps (TMS/WMTS) in [mapsource format](http://www.gpxsee.org/xsd/map.xsd) on [GPXSee Wiki](https://github.com/tumic0/GPXSee/wiki)? For example, grouped by country. That would be helpful for users.

**Comment by sikmir** [comment]
Either is OK, but as for me, Wiki is more convenient. If there was some sort of official "map manager" (hypothetically) in GPXSee, then another repository makes sense. But it's actually just some kind of snippets, gists, user-created documentation. It's the same thing as "git vs. weblate".

**Comment by tumic0** [comment]
[GPXSee-maps](https://github.com/tumic0/GPXSee-maps) repo is ready.
