### ISSUE TITLE
[request] Possibility to export smothened track

### ISSUE THREAD

**Issue by j-schneid** [tumic0/GPXSee#88]
First let me praise the smoothing feature! This something most programs lack although it is really necessary, particularly for imprecise elevation data that most phones (that I know) measure. Only by smoothing it is possible to get a usable result.
Now I would request as a feature: Please add a command to export the smoothed track as a new gpx file that can then be used again by other programs, smartphone apps and so on.

**Comment by sikmir** [comment]
I hope GPXSee will never be able to write a file. It's a viewer, and it does that job well.

**Comment by tumic0** [comment]
There is a plenty of GPS logs "post-processing" tools that implement various smoothing/outlier elimination (e.g. GPSBabel, GPSPrune, ...). The aim of GPXSee is to be a fast viewer with a "clean" interface. The smoothing/outlier elimination in GPXSee shall solve the most significant "display artifacts", but for a serious post-processing of the files, manual actions are required anyway. Those are however not the purpose of GPXSee - it can't be a simple viewer and a complicated all-in-one GPS tool at the same time.
