### ISSUE TITLE
[request] toggle track visibility

### ISSUE THREAD

**Issue by j-schneid** [tumic0/GPXSee#89]
It is possible to show all tracks or to cycle through them - as far as I have found out. So far it seems not to be possible to get rid of a particular track one doesn't want to see any more.
So what would be very nice is: A list of loaded tracks with the possibility to switch the visibility of each one.

**Comment by tumic0** [comment]
A list of tracks is something almost every other GPS viewer is offering, but one of the primary motivations of writing GPXSee was to get rid of stuff I'm not interested in when browsing the tracks. And the track list is the chief representative of such stuff.
