### ISSUE TITLE
Feature request: minimum of speed axis is always zero

### ISSUE THREAD

**Issue by Freiheiter** [tumic0/GPXSee#9]
GPXsee's graphs all adjust their scale (y-axis) based on the values present in the data. While this is pretty helpful for the elevation and heart rate graphs, I find it counter-intuitive for the speed graph.
My suggestion would be to draw the speed graph based on a fixed minimum of zero.

Thanks a lot for considering my request - and above all, thanks for providing GPXsee!
Werner

**Comment by tumic0** [comment]
The speed graphs are constructed starting with a [0,0] point, but the data can be then altered by the smoothing algorithm. I have however not seen any big "shifts" apart from 0. Can you please provide me some sample file, where the speed graph starts far away from zero?

**Comment by Freiheiter** [comment]
Am 22.09.2016 um 21:07 schrieb Martin Tůma:
> The speed graphs are constructed starting with a [0,0] point, but the
> data can be then altered by the smoothing algorithm. I have however not
> seen any big "shifts" apart from 0. Can you please provide me some
> sample file, where the speed graph starts far away from zero?
> 
Sure, here we go.

Werner

**Comment by tumic0** [comment]
Looks like the attachment got lost somewhere on the way... (Or I'm completely blind and can not see it here/in my mailbox)

**Comment by tumic0** [comment]
Version 3.9 has improved speed graph handling (changes related to pause detection) that could help in this case as well.
