### ISSUE TITLE
DOC: GPX extensions support

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#91]
From [documentation](http://www.gpxsee.org/doc.html):
> In addition to GPS data, data from the following sensors is supported by GPXSee:
> 
>    * Heart rate
>    * Cadence
>    * Power
>    * Temperature
> 

There are quite a few GPX extensions out there, most popular ones are:
* [Garmin v3](https://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd)
* [QLandkarte](http://www.qlandkarte.org/xmlschemas/v1.1/ql-extensions.xsd)
* [trekbuddy](http://www.trekbuddy.net/wiki/index.php?title=Howtos#GPX_File_format)
* etc.

So, could you add to documentation some more details about it (which extensions are actually supported).

**Comment by tumic0** [comment]
Well, GPXSee should support all existing HR, Cadence, Power and Temperature extensions used by major "log sources". If you have a device/service (and it is not some private extension) that generates such data that is not supported, consider this a bug.

A different story are the speed and distance extensions. (some) Speed extensions are supported (they override the computed speed if present) as they are believed to provide better data than the computed from the distance/time change. Distance extensions are not supported. I'm however toying with the idea to drop the speed extension support to unify the behavior and to simplify the code...
