### ISSUE TITLE
FR: OziExplorer track point file (*.plt) support

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#92]
Actually, I don't use OziExplorer, but as far as I see, *.plt format is really popular around us and a lot of users share their tracks with this one. So it'll help to avoid converting .plt to .gpx.

**Comment by tumic0** [comment]
1. Can you please provide some example files?
2. What about the other formats (*.rte, *.wpt, *.pnt)? Are there used in "real life"?

**Comment by sikmir** [comment]
1. Here is [20160305wz.zip (\*.plt, \*.wpt)](http://slazav.mccme.ru/gps/20160305wz.zip), or you can download any track from [GPSies](https://www.gpsies.com) or [GPSLib](https://www.gpslib.net/) as `*.plt` file.
2. Yes, `*.wpt` and `*.plt` are often used together, the 1st one for waypoints and the 2nd one for tracks.

**Comment by tumic0** [comment]
Implemented in 5.7
