### ISSUE TITLE
Display issue: square character instead of a white space

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#93]
### Steps to reproduce
1. Open "Settings -> Options -> Data -> Pause detection"
2. There are square characters in the suffix of the spin box

### Actual behaviour
![screenshot1](https://user-images.githubusercontent.com/688044/38056995-b85288aa-32e6-11e8-9ce5-9bbc67228f14.jpg)

### Expected behaviour
![screenshot2](https://user-images.githubusercontent.com/688044/38057005-bca19270-32e6-11e8-872b-57094b72223b.jpg)

### RCA
The root cause is here:
https://github.com/tumic0/GPXSee/blob/bda24d90917db9ae9dc892dfc06f35a358136203/src/GUI/units.h#L33

The following patch solves the problem:
```diff
-#define UNIT_SPACE     QString::fromUtf8("\xE2\x80\x89")
+#define UNIT_SPACE     QLatin1Char{' '}
```

### Configuration
GPXSee Version: 5.5
Operating System: Slackware Linux 14.2
Qt: 5.7.1
GCC: 5.4.0

**Comment by tumic0** [comment]
The problem is most probably in the font that you are using in your QT style. The unit space is intentionally a narrow space (\xE2\x80\x89 is a "en space"). On all my "test systems" it works fine.

If you change the space literal to "\xe2\x80\x89" ("thin space" which should be more common than the en space) do you also get a square instead of the space character?

**Comment by sikmir** [comment]
> If you change the space literal to "\xe2\x80\x89" ("thin space" which should be more common than the en space) do you also get a square instead of the space character?

Yes, the same effect with "thin space".

> The problem is most probably in the font that you are using in your QT style.

Sure, problem with fonts. As far as I see Qt5 uses `Liberation Sans` font as system default on Slackware. Switching to, for example, `Bitstream Charter` font solves the problem. But it requires additional efforts from end user:
1. Install Qt5 configuration utility ([qt5ct](https://slackbuilds.org/repository/14.2/desktop/qt5ct))
2. Set `QT_QPA_PLATFORMTHEME=qt5ct` in the environment
3. Change font using qt5ct

These steeps are a little different in case of KDE/GNOME, but anyway.
On the other hand, the same font (`Liberation Sans`) works without problems on ArchLinux.
So, I think I'll have to add that patch to [SBo package](https://slackbuilds.org/repository/14.2/gis/gpxsee) to get rid of this.

**Comment by tumic0** [comment]
Maybe a better idea would be to report the issue in some Slackware bugtracker. Btw, the special unit space is used in all graphs in GPXSee (which use the Arial font) and it apparently works fine.
