### ISSUE TITLE
Some problem with WMS map

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#94]
### Steps to reproduce
1. Create WMS mapsource file:
```xml
$ cat << EOF > ~/.gpxsee/maps/Karjalankartta.xml
<?xml version="1.0" encoding="UTF-8"?>
<map type="WMS">
  <name>Karjalankartta</name>
  <url>http://www.karjalankartat.fi/wms/8b42201cc218b9cd6c6ef9321e1d40f0</url>
  <layer>karjalankartat:topo20k</layer>
  <crs>EPSG:2394</crs>
  <style>raster</style>
</map>
EOF
```
2. Enable map:
```xml
$ crudini --set ~/.config/GPXSee/GPXSee.conf Map map Karjalankartta
```
### Actual behaviour
GPXSee generate the following request:
```
http://www.karjalankartat.fi/wms/8b42201cc218b9cd6c6ef9321e1d40f0?version=1.3.0&request=GetMap&CRS=EPSG%3A2394&bbox=4508053.285784561,6755664.294791471,4508730.618752135,6756341.627759045&width=256&height=256&layers=karjalankartat%3Atopo20k&styles=raster&format=image%2Fpng&transparent=true
```
GeoServer replies with the blank tile.

### Expected behaviour
This is just an example of a valid request:
```
http://www.karjalankartat.fi/wms/8b42201cc218b9cd6c6ef9321e1d40f0?service=WMS&version=1.1.1&request=GetMap&SRS=EPSG%3A2394&bbox=4508053.285784561,6755664.294791471,4508730.618752135,6756341.627759045&width=256&height=256&layers=karjalankartat%3Atopo20k&styles=raster&format=image%2Fpng&transparent=true
```
Result tile:
![karjalankartat-topo20k](https://user-images.githubusercontent.com/688044/38219932-9d6f329c-36e0-11e8-8e87-74269f60e2ba.jpg)

### RCA
* The 1st URL looks correct, so I have no idea why it doesn't work (whether that's server side or client side problem)
* If it's server side problem with WMS v1.3.0, how can I force GPXSee to use WMS v1.1.1
* `style` can be empty, but GPXSee doesn't allow it. For example, [`karjalankartat:topo20k_group`](http://www.karjalankartat.fi/wms/8b42201cc218b9cd6c6ef9321e1d40f0?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities) layer has no styles.

### Configuration
GPXSee Version: latest master
Operating System: ArchLinux

**Comment by tumic0** [comment]
You must define the inverted axis for the CRS (like for the WMTS set):
`<crs axis="yx">EPSG:2394</crs>`

The latest version should allow a missing style which means "default". You may also define "default" in the xml file. This is required when combining multiple layers (e.g. "default,default" for two layers with the default styles).

Please note, that WMS support is still "work in progress" so things may change/be broken/not yet implemented.

**Comment by sikmir** [comment]
> You must define the inverted axis for the CRS (like for the WMTS set):
> `<crs axis="yx">EPSG:2394</crs>`

Thanks a lot! It works now.

![screenshot1](https://user-images.githubusercontent.com/688044/38233198-61c1556c-3722-11e8-822e-981a833c83d7.jpg)

> The latest version should allow a missing style which means "default". You may also define "default" in the xml file. This is required when combining multiple layers (e.g. "default,default" for two layers with the default styles).

But `default` style doesn't work here. Compare:
* default style: `http://www.karjalankartat.fi/wms/8b42201cc218b9cd6c6ef9321e1d40f0?version=1.3.0&request=GetMap&CRS=EPSG:2394&bbox=6681494.774756,4489760.634373,6682103.882763,4490369.742962&width=256&height=256&layers=karjalankartat:topo20k_group&styles=default&format=image/png&transparent=true`
Response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://www.karjalankartat.fi:80/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
  <ServiceException code="StyleNotDefined">
      No such style: default
  </ServiceException>
</ServiceExceptionReport>
```
* empty style: `http://www.karjalankartat.fi/wms/8b42201cc218b9cd6c6ef9321e1d40f0?version=1.3.0&request=GetMap&CRS=EPSG:2394&bbox=6681494.774756,4489760.634373,6682103.882763,4490369.742962&width=256&height=256&layers=karjalankartat:topo20k_group&styles=&format=image/png&transparent=true`
Response: OK.

[GetCapabilities](http://www.karjalankartat.fi/wms/8b42201cc218b9cd6c6ef9321e1d40f0?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities):
```xml
...
<Layer queryable="1">
  <Name>karjalankartat:topo20k_group</Name>
  <Title>karjalankartat:topo20k_group</Title>
  <Abstract>Layer-Group type layer: karjalankartat:topo20k_group</Abstract>
  <CRS>EPSG:2394</CRS>
  <EX_GeographicBoundingBox>
    <westBoundLongitude>26.67861648890731</westBoundLongitude>
    <eastBoundLongitude>34.284563052038905</eastBoundLongitude>
    <southBoundLatitude>58.79817808709381</southBoundLatitude>
    <northBoundLatitude>70.33335178056033</northBoundLatitude>
  </EX_GeographicBoundingBox>
  <BoundingBox CRS="EPSG:2394" minx="6523650.0" miny="4375191.999999999" maxx="7806350.0" maxy="4661400.0"/>
</Layer>
...
```

> Please note, that WMS support is still "work in progress" so things may change/be broken/not yet implemented.

Well, I'll be early adopter:)

**Comment by tumic0** [comment]
You are right, the specification regarding the default style is different for WMS and WMTS. The latest commits should fix this and correctly handle the omitted style parameter.
