### ISSUE TITLE
Mapsforge offline map support

### ISSUE THREAD

**Issue by pschonmann** [tumic0/GPXSee#96]
Please add *.map support from mapsforge project

https://github.com/mapsforge/mapsforge

**Comment by tumic0** [comment]
I have no intention to implement any of the "yet another OSM data based format"s out there, sorry. The aim is to support 
1. the broadest range of map sources (which is not equivalent with map format)
2. universal formats or formats that have become "industry standard" in selected communities
3. formats that I'm personally interested in ;-)
