### ISSUE TITLE
Debian packages

### ISSUE THREAD

**Issue by jkufner** [tumic0/GPXSee#98]
https://packages.debian.org/search?keywords=gpxsee&searchon=names&suite=all&section=all returns no results. It would be really nice to have GPXSee in Debian.

**Comment by tumic0** [comment]
I agree, but this is definitely the wrong place to open such an issue... At the moment GPXSee is rotting in [Packages being worked on](https://www.debian.org/devel/wnpp/being_packaged_byage) and there is nothing that I'm personally willing to do to change this after all my previous negative experience with Debian.

You may however use the "official" GPXSee Debian repository at [OBS](https://software.opensuse.org//download.html?project=home%3Atumic%3AGPXSee&package=gpxsee)

**Comment by jidanni** [comment]
See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884253
