### ISSUE TITLE
Keybinding for zoom levels

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#99]
GPXSee ships out of the box with `Ctrl++`/`Ctrl+-` keybindings. Well, that's kind of standard key bindings for zooming ([QKeySequence::StandardKey](https://doc.qt.io/qt-5/qkeysequence.html#StandardKey-enum)). But... it's definitely not comfortable.
Here is why I think `+`/`-` keybindings are more convenient alternative:

1. With my keyboard layout I need to hold down the `Shift` key to enter the `+` symbol, making the shortcut effectively the same as `Ctrl+Shift+=` (too verbose). (For example, Firefox handles both `Ctrl+Shift+=` and `Ctrl+=` for Zoom In, that's agreeable.)
2. Move & Zoom are the most frequently used actions when working with a map (unlike zooming in Firefox, for example), so it's desirable to have a easier way to zoom.
3. We're used to use  `+`/`-` for zooming in QLandkarteGT, QMapShack, OOMapper and so on.

Actually I can customise GPXSee to change keybindings and I do it (sikmir/gpxsee@c9d880a87bd4e032ecccc2fe83dfab83efcfafc4).
@tumic0 What do you think?

**Comment by tumic0** [comment]
Sounds reasonable. I have already changed some shortcuts like X axis type to single keys for faster access in the past and zooming could also be changed. Its just that I'm personally using the mouse for zooming/scrolling the map so I never had the demand to make it work easier from the keyboard...

**Comment by sikmir** [comment]
So, I'm voting for `+/-` (since I prefer to use keyboard for moving and zooming).
